### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by heycmm** [travellings-link/travellings#10]
## 网站名称
殆己
## 网站链接
https://heycmm.cn
## 徽标位置
全站底部
## 推荐理由
和你们一样

**Comment by volfclub** [comment]
已收录，
能否将徽标放一个能直接看到的位置？

**Comment by proxygit** [comment]
> 已收录，
> 能否将徽标放一个能直接看到的位置？

https://heycmm.cn/s/about 暂时接力放这个页面吧，后面会尝试修改为主题悬浮徽标。

**Comment by heycmm** [comment]
已替换

**Comment by linlinzzo** [comment]
侧边栏在移动端收起时未在底部放置开往徽标。

**Comment by essesoul** [comment]
网站https://heycmm.cn/上没找到开往链接

**Comment by essesoul** [comment]
@heycmm 由于您还未在页面上添加开往的链接，您的网站将在近期被移除

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
