### ISSUE TITLE
潘深练的个人网站

### ISSUE THREAD

**Issue by senlypan** [travellings-link/travellings#1000]
### 网站名称

潘深练的个人网站

### 网站网址

https://www.panshenlian.com

### 徽标位置

顶部导航

### 内容方向

个人平台上，有技术文章、生活掠影、科技周刊、读书分享、播客推荐等。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by essesoul** [comment]
顶部导航未找到开往入口，友链扫描未检测到开往网址
![image](https://user-images.githubusercontent.com/58624474/179332508-a915b4ab-9cbb-42cd-9ee9-2ea6ee217305.png)
![image](https://user-images.githubusercontent.com/58624474/179332603-ebe07130-637d-49e3-9bed-7b4b64f56cde.png)

**Comment by senlypan** [comment]
顶部导航有【开往】入口，可访问验证。
