### ISSUE TITLE
Ykuee的博客

### ISSUE THREAD

**Issue by Ykuee** [travellings-link/travellings#1002]
### 网站名称

Ykuee的博客

### 网站网址

https://www.ykuee.link/

### 徽标位置

网站顶部 菜单栏

### 内容方向

技术分享、错误笔记、日常发病

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
