### ISSUE TITLE
申请修改繁星小站信息

### ISSUE THREAD

**Issue by s-Ruthless** [travellings-link/travellings#1003]
### 网站名称

繁星博客

### 网站网址

原信息 ：繁星小站  https://www.moeor.com/ （已无法访问）

修改为： 繁星博客 https://blog.emoao.com/

### 徽标位置

测栏

### 内容方向

分享技术教程，日常随笔

**Comment by linlinzzo** [comment]
请提供一下网站序号。

**Comment by s-Ruthless** [comment]
网站序号：313 繁星小站

**Comment by s-Ruthless** [comment]
> 请提供一下网站序号。

网站序号：313 繁星小站
