### ISSUE TITLE
Writiger

### ISSUE THREAD

**Issue by writiger** [travellings-link/travellings#1007]
### 网站名称

writiger分享站

### 网站网址

https://www.writiger.cn

### 徽标位置

右侧

### 内容方向

博客，笔记，项目

**Comment by linlinzzo** [comment]
http://hexo.writiger.cn/ 没有 https。

**Comment by writiger** [comment]
已添加

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/0e35a1d3-3149-4f43-8267-3c61a7aaf544)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
