### ISSUE TITLE
井犯博客 JF blog 申请收录

### ISSUE THREAD

**Issue by jfnice** [travellings-link/travellings#1008]
### 网站名称

井犯博客 JF blog

### 网站网址

https://nicejf.cn/

### 徽标位置

左侧栏，后续可能也会添加到网站底部

### 内容方向

个人文章，网络技术教程，生活类文章

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
