### ISSUE TITLE
[收录申请] Prk在线工具

### ISSUE THREAD

**Issue by BiliPrk** [travellings-link/travellings#1010]
### 网站名称

Prk在线工具

### 网站网址

https://tool.cprk.cc

### 徽标位置

navBar

![navBar](https://yzf.qq.com/fsnb/kf-file/kf_pic/20220526/KFPIC_kfh5a90e72eade39b9_h5396426aa0a688add07b1662b0d_WXIMAGE_78cf0c629ba04907844bd20ad4f5a19f.png)

### 内容方向

便民工具，会不停的更新~

**Comment by linlinzzo** [comment]
你这和 https://github.com/travellings-link/travellings/issues/1011 是一系列的，申请那个就行了吧。

**Comment by linlinzzo** [comment]
@HAHH9527 @qystudio0 像这种情况该怎么办？

**Comment by BiliPrk** [comment]
管理员，你好：

#1011 是博客，#1010 是在线工具，两种不同的站点。

博客专门用于经验分享、软件分享等；
在线工具用于便民工具，让任何终端设备只要有网络和浏览器就可以直接访问在线工具使用在线工具。

虽然这些站点都是同一 “系列” ，但是功能性完全不一样。

比如说B站的主站：[哔哩哔哩弹幕网](https://www.bilibili.com/) 和附属站：[哔哩哔哩漫画](https://manga.bilibili.com/) 以及附属站：[BigFun 毕方](https://www.bigfun.cn/) 等都同属于一个 “系列”，一家公司之手。再比如腾讯的 [微信](https://weixin.qq.com) 和 [QQ](https://im.qq.com) 都也是同一个 “系列” 的，总不能说这些都只收录一个就行了吧。如果功能上是一样的那么收录一个我认为可以，但是功能也好还是实际用途也好都是不一样的，那么我认为就应该都收录。

谢谢。

[Prk](https://imprk.me)
2022-05-28

**Comment by qystudio0** [comment]
相信你可以看到我们的规定，原则上我们只收录博客，按照惯例，我们最低标准需要有实质性文章内容，请等待我们组内讨论

**Comment by BiliPrk** [comment]
亲爱的管理员，你好：

首先，感谢你能够花费宝贵的时间回复。根据你们的规定【[地址](https://github.com/travellings-link/travellings/blob/master/README.md)】，Q&A中，有提及以下这句话：

> 博客，主页，**工具**，导航等都可以，只要是乐于分享的网页就可以加入开往。

根据Q&A中的内容我完全符合你们的规定。同时，我也非常期待你们的组内讨论结果！

谢谢。

[Prk](https://imprk.me)
2022-05-29

**Comment by qystudio0** [comment]
我关注到贵站https异常了，请及时处理，望网站拥有更多好用的工具

我的意见:通过

**Comment by HAHH9527** [comment]
站点失效
