### ISSUE TITLE
[收录申请] Prk博客

### ISSUE THREAD

**Issue by BiliPrk** [travellings-link/travellings#1011]
### 网站名称

Prk博客

### 网站网址

https://www.cprk.cc/

### 徽标位置

navBar

![navBar](https://yzf.qq.com/fsnb/kf-file/kf_pic/20220526/KFPIC_kfh58bea6f78fbe83c_h56705873f58cf3dde08022a9846_WXIMAGE_52fcc07011a449caa375df0647d6a4f6.png)

### 内容方向

软件分享
教程分享
经验分享
等

**Comment by qystudio0** [comment]
贵站似乎删除了开往的链接

**Comment by BiliPrk** [comment]
并没有

**Comment by qystudio0** [comment]
手机端无法查看，刚刚电脑版检查了

**Comment by BiliPrk** [comment]
抱歉，我忽略了手机版的访问。目前是只有电脑版会显示。我已经在页脚处重新补充了开往链接，因为缓存问题可能需要一段时间才能看到。

**Comment by qystudio0** [comment]
谢谢

**Comment by linlinzzo** [comment]
贵站域名解析失败，请检查。

**Comment by BiliPrk** [comment]
抱歉 换域名忘记通知了！！
https://www.prkblog.cn/
新域名已完成 ICP 备案，将稳定运行。且我的站点一直有保留开往的按钮。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
