### ISSUE TITLE
[收录申请] Go导航

### ISSUE THREAD

**Issue by BiliPrk** [travellings-link/travellings#1012]
### 网站名称

Go导航

### 网站网址

https://www.gonav.cn/

### 徽标位置

navTopBar

![navTopBar](https://yzf.qq.com/fsnb/kf-file/kf_pic/20220526/KFPIC_kfh5d180c4f9116d9f_h5725a1b2fce549ce9b0dc7b8420_WXIMAGE_c1587ef185994384bb8d7c270ebc1210.png)

### 内容方向

**便民网站** —— **导航网**，致力于做 [2345 网址导航](https://www.2345.com/?kprk) 和 [360 网址导航](https://hao.360.com/?src=lm&ls=n529d897998&classic) 的替代品。只收录企业级网站。

**Comment by qystudio0** [comment]
未能发现开往链接

**Comment by BiliPrk** [comment]
管理员你好，请根据我上方截图寻找开往的链接。

**Comment by BiliPrk** [comment]
管理员你好，开往链接目前位置只能在电脑上展示或是分辨率高的设备上。就在刚刚，我在页脚为开往再次准备了个位置，可以让手机电脑同步使用开往！（不过因为CDN缓存问题可能要15分钟~12小时的时间后才能看到）

**Comment by qystudio0** [comment]
谢谢你的理解

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
