### ISSUE TITLE
[收录申请] 速溶

### ISSUE THREAD

**Issue by fu1fan** [travellings-link/travellings#1013]
### 网站名称

速溶——记录当下 赠予未来

### 网站网址

https://zzzing.cn/

### 徽标位置

侧栏

### 内容方向

信息技术、生活日常、一些感想

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
