### ISSUE TITLE
【收录申请】zhzh博客

### ISSUE THREAD

**Issue by liuzhonghao** [travellings-link/travellings#1018]
### 网站名称

zhzh博客

### 网站网址

[https://blog.luckynumber.work/](https://blog.luckynumber.work/)

### 徽标位置

顶部
![image](https://user-images.githubusercontent.com/45680714/170865259-9b2c09bd-9b98-41c2-97a3-ca7c0fec47a5.png)

### 内容方向

- 经验分享
- 日常分享

**Comment by linlinzzo** [comment]
文章有点少，再更新一点吧。
