### ISSUE TITLE
CasecoRI 的小站

### ISSUE THREAD

**Issue by Cystee** [travellings-link/travellings#1021]
### 网站名称

CasecoRI 的小站

### 网站网址

https://www.casecori.top/

### 徽标位置

侧栏。

### 内容方向

教程，技术，心情。

**Comment by linlinzzo** [comment]
只有十二篇文章哦，写够 20 篇在这边说一下吧。

**Comment by Cystee** [comment]
这边有 20 篇文章了哦，请您复审一下。

**Comment by linlinzzo** [comment]
刚开始在首页只看到 12 篇文章，现在刚刚好 20。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Cystee** [comment]
已修改

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/6b9d09f5-d0ca-4f05-b2e6-82861100d063)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
