### ISSUE TITLE
收录申请-小小的XIAO

### ISSUE THREAD

**Issue by lz732895965** [travellings-link/travellings#1022]
### 网站名称

小小的XIAO

### 网站网址

https://www.one21.cn

### 徽标位置

主目录

### 内容方向

小小生活分享站

**Comment by HAHH9527** [comment]
证书错误，请检查证书
> 此服务器无法证明它是 www.one21.cn；它的安全证书来自 guyun2.xyz。这可能是由错误配置或者有攻击者截获你的连接而导致的。

**Comment by zhanghq1993** [comment]
>>> > 此服务器无法证明它是[www.one21.cn；其安全证书来自](http://www.one21.cn%EF%BC%9B%E5%AE%83%E7%9A%84%E5%AE%89%E5%85%A8%E8%AF%81%E4%B9%A6%E6%9D%A5%E8%87%AA)guyun2.xyz。这可能是由错误配置或有攻击者截获你的连接而导致的。
证书已修复

**Comment by lz732895965** [comment]
> 证书错误，请检查证书
> 
> > 此服务器无法证明它是 [www.one21.cn；它的安全证书来自](http://www.one21.cn%EF%BC%9B%E5%AE%83%E7%9A%84%E5%AE%89%E5%85%A8%E8%AF%81%E4%B9%A6%E6%9D%A5%E8%87%AA) guyun2.xyz。这可能是由错误配置或者有攻击者截获你的连接而导致的。

证书问题已修复

**Comment by HAHH9527** [comment]
还请再多更新一些内容
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）；

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。

**Comment by gxres042** [comment]
尊敬的站长您好，我是开往维护组成员 Restent Ou。

在巡查中，我发现了一些与您站点相关的问题：

- 根据 Issue 搜索，您似乎并未通过开往的申请，在去年的 8 月 15 日又被“移除”一次？但是，现阶段发现您仍在开往的成员列表中，故以及将您移除，如需加入开往可再次按照流程申请。
- 您的开往入口设置了延时跳转，如您后续需要再次加入开往，需要将该延时跳转取消，否则浏览器会判定为弹出式窗口并拦截、影响访客使用开往入口。

感谢您的理解与支持！
