### ISSUE TITLE
收录申请-JIWU‘S BLOG

### ISSUE THREAD

**Issue by Zhiwu-Tian** [travellings-link/travellings#1023]
### 网站名称

JIWU‘S BLOG

### 网站网址

https://blog.awu.cool

### 徽标位置

顶栏

### 内容方向

生活随笔与学习交流

**Comment by linlinzzo** [comment]
我只看到 13 篇文章，再多写一些吧。

**Comment by Zhiwu-Tian** [comment]
> 我只看到 13 篇文章，再多写一些吧。

好的！

**Comment by linlinzzo** [comment]
你写够 20 篇在这边说就行，不用 close。
