### ISSUE TITLE
收录申请-天堂里の猫

### ISSUE THREAD

**Issue by MoeCinnamo** [travellings-link/travellings#1024]
### 网站名称

天堂里の猫

### 网站网址

https://blog.mojy.xyz

### 徽标位置

顶栏

### 内容方向

生活随笔、学习交流等

**Comment by linlinzzo** [comment]
文章我看到的只有 11 篇，再写一些吧。

**Comment by MoeCinnamo** [comment]
> 文章我看到的只有 11 篇，再写一些吧。

好的

**Comment by MoeCinnamo** [comment]
目前，我的博客只有11篇文章，我相信我的工作室可以写更多的文章放到我们工作室，若有30篇，将会自动加入十年之约。开往链接和虫洞链接都在顶栏的‘开往’分类中，国内访问我们有加速，速度不用担心。
