### ISSUE TITLE
更新站点信息

### ISSUE THREAD

**Issue by Lfhsheng** [travellings-link/travellings#1025]
### 网站名称

泠风寒声の小窝

### 网站网址

将 #820 的网址更改为https://blog.lfhsheng.com

### 徽标位置

顶栏

### 内容方向

一些好玩的东西

**Comment by linlinzzo** [comment]
请提供一下网站编号，谢谢。

**Comment by qystudio0** [comment]
@Lfhsheng 请及时迁移文章并添加开往链接同时尽快回复，否则可能会下架贵站

**Comment by HowieHz** [comment]
link #737
