### ISSUE TITLE
极星网

### ISSUE THREAD

**Issue by jixingone** [travellings-link/travellings#1026]
### 网站名称

极星网

### 网站网址

https://www.jixing.one

### 徽标位置

顶栏

### 内容方向

分享生活，交流技术。

**Comment by linlinzzo** [comment]
@HAHH9527 该博客有“[违禁文章](https://www.jixing.one/airport/cheap-airport/)”。

**Comment by qystudio0** [comment]
根据相关规定，贵博客暂不收录，谢谢你的理解，请调整

**Comment by jixingone** [comment]
已调整，现在是否能收录。

**Comment by linlinzzo** [comment]
> 已调整，现在是否能收录。

https://www.jixing.one/ipv6/ipv6-vpn/
https://www.jixing.one/vps/ssr-bbr/
https://www.jixing.one/vps/get-a-vps/

**Comment by jixingone** [comment]
我放弃了。
