### ISSUE TITLE
AOHUI BLOG.

### ISSUE THREAD

**Issue by janedut** [travellings-link/travellings#1027]
### 网站名称

AOHUI BLOG.

### 网站网址

https://www.aohuiliu.fun/

### 徽标位置

顶栏

### 内容方向

学习记录，生活记录

**Comment by HAHH9527** [comment]
或许再多更新两篇文章？
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）；

**Comment by janedut** [comment]
> 或许再多更新两篇文章？
> 
> > 网页已有较多内容（建议20篇以上，已持续更新一段时间）；

好的

**Comment by janedut** [comment]
> 或许再多更新两篇文章？
> 
> > 网页已有较多内容（建议20篇以上，已持续更新一段时间）；

已更新至21篇

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by jiangmiemie** [comment]
@janedut  你好，你的网址现在无法正常打开，请问是否出于测试阶段
