### ISSUE TITLE
LYMTICS

### ISSUE THREAD

**Issue by lxymtics** [travellings-link/travellings#1028]
### 网站名称

LYMTICS

### 网站网址

https://lymtics.top

### 徽标位置

顶栏

### 内容方向

后端技术方向的文章，少量阅读笔记

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
