### ISSUE TITLE
南生余

### ISSUE THREAD

**Issue by yzzgchina** [travellings-link/travellings#1031]
### 网站名称

南生余

### 网站网址

https://www.chenii.com/

### 徽标位置

底栏

### 内容方向

个人生活日记，个人工作感悟。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
