### ISSUE TITLE
肥猪のBlog

### ISSUE THREAD

**Issue by feizhuqwq** [travellings-link/travellings#1033]
### 网站名称

肥猪のBlog

### 网站网址

https://www.feizhuqwq.com/

### 徽标位置

侧栏

### 内容方向

一些教程，实用的小工具

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by feizhuqwq** [comment]
好的，感谢

**Comment by essesoul** [comment]
https://www.feizhuqwq.com/ 页面下未找到开往的图标与链接
![image](https://user-images.githubusercontent.com/58624474/179329771-999ac43b-121d-400b-b917-57d6fda4ebb6.png)

**Comment by feizhuqwq** [comment]
homepage不包含友情链接，请检查博客:https://blog.feizhuqwq.com/

> https://www.feizhuqwq.com/页面下未找到开往的图标与链接 ![图片](https://user-images.githubusercontent.com/58624474/179329771-999ac43b-121d-400b-b917-57d6fda4ebb6.png)



> https://www.feizhuqwq.com/页面下未找到开往的图标与链接 ![图片](https://user-images.githubusercontent.com/58624474/179329771-999ac43b-121d-400b-b917-57d6fda4ebb6.png)

**Comment by feizhuqwq** [comment]
homepage不包含友情链接，请检查博客:https://blog.feizhuqwq.com/
