### ISSUE TITLE
浮云翩迁之间

### ISSUE THREAD

**Issue by huangwb8** [travellings-link/travellings#1037]
### 网站名称

浮云翩迁之间

### 网站网址

https://blognas.hwb0307.com/

### 徽标位置

顶栏

### 内容方向

Linux/Docker/R语言/人工智能/区块链/生活

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by huangwb8** [comment]
由于顶栏标签过多，我将徽标位置移至左侧菜单。忘知悉。谢谢！
希望可以尽快通过审核喔！

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by huangwb8** [comment]
@linlinzzo 已经更换，谢谢提醒！

**Comment by huangwb8** [comment]
@linlinzzo 我发现travelling很多链接已经失效。建议在重定向时进行连接检测，如果返回404之类的错误时不要显示该网站。

**Comment by linlinzzo** [comment]
> 我发现travelling很多链接已经失效。建议在重定向时进行连接检测，如果返回404之类的错误时不要显示该网站。

跳转的时间太短，来不及。对于失效的网站你可以跟我们说，我们会处理。
