### ISSUE TITLE
Tiaobug

### ISSUE THREAD

**Issue by skeetwu** [travellings-link/travellings#1039]
### 网站名称

Tiaobug

### 网站网址

https://www.tiaobug.com

### 徽标位置

顶部菜单

### 内容方向

技术分享
日常分享

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by skeetwu** [comment]
Thx！

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
