### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by Musenxi** [travellings-link/travellings#104]
## 网站名称
沐森西の小窝
## 网站链接
https://www.musenxi.com
## 徽标位置
左侧栏/底栏
## 推荐理由
沐森西的个人主页

**Comment by volfclub** [comment]
嗯，你的网站有些混乱的样子……只放在首页吗？

**Comment by Musenxi** [comment]
嗯，是的，等博客域名处理好了以后会申请放到博客上的。
麻烦你了，谢谢

**Comment by Musenxi** [comment]
> 嗯，你的网站有些混乱的样子……只放在首页吗？

嗯，是的，等博客域名处理好了以后会申请放到博客上的。
麻烦你了，谢谢

**Comment by volfclub** [comment]
看了一下，你目前的博客数似乎还不足8篇，再写些吧？

**Comment by Musenxi** [comment]
> 看了一下，你目前的博客数似乎还不足8篇，再写些吧？

更新完了，再看一下吧？

**Comment by Musenxi** [comment]
原**序号86** 名称沐森西の博客 地址https://dlizi.com 现申请收录

## 网站名称
橘夜庭
## 网站链接
https://musenxi.com/
## 徽标位置
顶部/底部
## 内容方向
日常

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
