### ISSUE TITLE
快看Kuaikan

### ISSUE THREAD

**Issue by kuailook** [travellings-link/travellings#1040]
### 网站名称

快看Kuaikan

### 网站网址

https://kuaikan.ink

### 徽标位置

顶栏

### 内容方向

生活杂记，学习交流等

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
