### ISSUE TITLE
linkkk的小屋

### ISSUE THREAD

**Issue by 2319564679** [travellings-link/travellings#1041]
### 网站名称

linkkk的小屋

### 网站网址

https://www.linkkkblog.top

### 徽标位置

侧栏

### 内容方向

一个student的技术知识与生活日常分享博客！

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by HAHH9527** [comment]
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）；

还请再努力更新一段时间的博客
