### ISSUE TITLE
CodeTime

### ISSUE THREAD

**Issue by Mcdull0921** [travellings-link/travellings#1043]
### 网站名称

CodeTime

### 网站网址

https://www.xdull.cn/

### 徽标位置

顶部菜单栏

### 内容方向

IT技术类博客，原创的算法知识分享，框架介绍，还有一些记忆类的代码指令速查。
也会在静态文章页里嵌入js代码实现互动小游戏。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Mcdull0921** [comment]
已更新，请审核
