### ISSUE TITLE
今天是晴天

### ISSUE THREAD

**Issue by luodeb** [travellings-link/travellings#1044]
### 网站名称

今天是晴天

### 网站网址

https://www.luodeb.top

### 徽标位置

顶部->友链->开往

### 内容方向

 - 技术分享
 - 生活日常
 - and so on...

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by HAHH9527** [comment]
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）

或许你可以考虑一下把老站的文章`以前的文章`迁移过来

**Comment by luodeb** [comment]
暂时想留着老站，所以没有迁移的打算。新站也在慢慢写。

**Comment by HAHH9527** [comment]
@linlinzzo 这种情况是否通过呢

**Comment by linlinzzo** [comment]
https://www.luodeb.top/12650cfc/
穿墙这个话题。。。

**Comment by linlinzzo** [comment]
> @linlinzzo 这种情况是否通过呢

你艾特我好像没收到邮件通知。。。
