### ISSUE TITLE
Izekel'Blog

### ISSUE THREAD

**Issue by jsxkl** [travellings-link/travellings#1049]
### 网站名称

Izekel'Blog

### 网站网址

https://www.izekel.cn

### 徽标位置

上方导航栏

### 内容方向

网络技术和个人感想

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by jsxkl** [comment]
麻烦问一下什么时候能通过 @linlinzzo

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/6729367b-89e7-47f3-aca1-6fcf6ea9a6c1)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
