### ISSUE TITLE
心智备份

### ISSUE THREAD

**Issue by TyrantG** [travellings-link/travellings#1050]
### 网站名称

心智备份

### 网站网址

https://www.tyrantg.com

### 徽标位置

顶部

### 内容方向

- 杂谈
- 技术分享
- 心智备份

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by TyrantG** [comment]
> 

已更新
