### ISSUE TITLE
rain的博客

### ISSUE THREAD

**Issue by youshao123** [travellings-link/travellings#1052]
### 网站名称

rain的博客

### 网站网址

https://rain123.top

### 徽标位置

页脚

### 内容方向

嵌入式开发，c语言，玩机技巧，android开发

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by HAHH9527** [comment]
未见开往徽标，或许可以检查一下CDN缓存

**Comment by HAHH9527** [comment]
以及收录要求
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）
