### ISSUE TITLE
圆周率的博客

### ISSUE THREAD

**Issue by yzl3014** [travellings-link/travellings#1053]
### 网站名称

圆周率的博客

### 网站网址

https://yuanzj.top/

### 徽标位置

顶栏和底栏

### 内容方向

概要：分享软件编程和小型网站的经验和简单的摄影。
个人自述：如今初一，涉足过C/C++,易语言,HTML,VMware,AppInventor,Python,Scratch，不能说精通，只能说但凡是语言都写过一个HelloWorld。
个人感言：我从三年级开始就在计算机领域开始探索，虽然没有引以为傲的成就，但能与他人谈上一波就已经让我觉得很不错了。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by HAHH9527** [comment]
目前收录要求
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）

**Comment by HAHH9527** [comment]
另外个人建议，编程宜精不宜杂。
编程思想和算法积累基本都是通用的，各种语法上的差距并不大。
如果你有感兴趣的方向，那么最好先朝着那个方向做上一些实际应用的探索，在自学的过程中可以培养你的资料检索和文档阅读等能力。
如果有机缘，那么你现在的这一段实际应用的探索经历将会给你以后的编程之路添上一大笔。
当然，你现在还只是一个初中生，也不用像我说的这么着急。
如果你真的对编程计算机感兴趣，那么可以关注一下诸如NOIP这样的竞赛，适合你当前的年龄阶段（具体报名规则我没有经历过，不过要提防黑心机构）。
如果你的学校有相关的指导老师和竞赛资源，那么直接向老师提出来是最好的。
如果没有，也可以和你学校的计算机老师提出来，或许老师是关注的，只是缺少一个契机。
