### ISSUE TITLE
Kobin 技术随笔

### ISSUE THREAD

**Issue by Kobin4869** [travellings-link/travellings#1059]
### 网站名称

Kobin 技术随笔

### 网站网址

https://blog.kobin.cn/

### 徽标位置

侧栏

### 内容方向

站点收录日常工作和学习中遇到的问题，主要涉及 IT 运维和网络通信技术方向。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by qystudio0** [comment]
移动端未发现开往链接

**Comment by Kobin4869** [comment]
您好，已在移动端页面底部添加链接

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
