### ISSUE TITLE
熊猫不是猫

### ISSUE THREAD

**Issue by Panda-995** [travellings-link/travellings#1060]
### 网站名称

熊猫不是猫

### 网站网址

https://panda995.xyz

### 徽标位置

导航栏

### 内容方向

一个分享日常和喜欢写点短篇故事的博主

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
