### ISSUE TITLE
CNMDSB

### ISSUE THREAD

**Issue by mlw10086** [travellings-link/travellings#1062]
### 网站名称

CNMDSB

### 网站网址

https://www.cnmdsb.cn

### 徽标位置

顶栏

### 内容方向

嗨，交个朋友，我是CNMDSB，一个有深度的自我博客。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by mlw10086** [comment]
为啥不审核我的啊？

**Comment by mlw10086** [comment]
@linlinzzo

**Comment by linlinzzo** [comment]
待项目组讨论。 @mlw10086

**Comment by qystudio0** [comment]
未查看到开往链接
