### ISSUE TITLE
思卿长安归のBlog

### ISSUE THREAD

**Issue by ShiXinBoy** [travellings-link/travellings#1063]
### 网站名称

思卿长安归のBlog

### 网站网址

https://shixin.vercel.app/

### 徽标位置

顶部一级菜单，底部社交图标区

### 内容方向

博客，网站，编程，计算机

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
只有六篇文章，再更新一点吧。

**Comment by ShiXinBoy** [comment]
此类文章更新就无法高产

**Comment by linlinzzo** [comment]
20
