### ISSUE TITLE
竹春廿柒

### ISSUE THREAD

**Issue by mojinxi** [travellings-link/travellings#1065]
### 网站名称

竹春廿柒

### 网站网址

https://mojinxi.cn

### 徽标位置

网页底部

### 内容方向

生活中的小趣事

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
