### ISSUE TITLE
汤圆的小窝

### ISSUE THREAD

**Issue by cosineU** [travellings-link/travellings#1067]
### 网站名称

汤圆的小窝

### 网站网址

https://life.8ce.org/

### 徽标位置

侧栏

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by cosineU** [comment]
出于某些原因，我打算取消加入 travelling 的申请。请删除此 issue，谢谢

**Comment by cosineU** [comment]
能否将这个 issue **删除**而不是关闭？

**Comment by HAHH9527** [comment]
github并没有提供删除issue的功能

**Comment by cosineU** [comment]
如果你有仓库的写权限的话 ![](https://p.sda1.dev/6/181c4abbd8826acbe60f9a5e9bb2d1d2/QQ截图20220707171806.png)

**Comment by cosineU** [comment]
> 我现在电脑炸了，等修好再处理。一般用不着删除啊，不会是被人……

请问您的电脑修好了没（

**Comment by cosineU** [comment]
@linlinzzo 请问您的电脑修好了没（
