### ISSUE TITLE
禾之谷

### ISSUE THREAD

**Issue by yzwsl** [travellings-link/travellings#1069]
### 网站名称

禾之谷

### 十年之约大事记网址

https://www.foreverblog.cn/blog/3086.html

### 网站网址

https://www.hezhigu.com/

### 徽标位置

顶栏

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您所提交的网站网址与大事记的链接不同？

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by yzwsl** [comment]
博客写了啊，腾讯说管局拉黑解析了，被迫换域名了

**Comment by yzwsl** [comment]
十年早就评论了，没审核而已

**Comment by linlinzzo** [comment]
> 十年早就评论了，没审核而已

没事。我现在给你添加到开往的列表中。等会十年之约审核评论后，您加入开往应该会显示在大事记中。

**Comment by yzwsl** [comment]
更换域名为blog.foxcm.com（原域名 www.hezhigu.com）
更改站点名称为晨狐戏语（原名 禾之谷）

**Comment by A7103** [comment]
@yzwsl  抱歉现在才发现，下次可以reopen issue，这样其他成员也能发现

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
