### ISSUE TITLE
WikiMimo【退出】

### ISSUE THREAD

**Issue by imgradeone** [travellings-link/travellings#1070]
> *WikiMimo 现已关闭并屏蔽中国大陆，因此申请退出“开往”，抱歉……

### 网站名称

WikiMimo

### 网站网址

https://www.wikimimo.com

### 徽标位置

网页顶栏的“开往”Tab

### 内容方向

这是一个使用 VuePress v2 驱动的、以探索兴趣领域为核心的个人势 Wiki，旨在记录互联网（和现实）上“小众”的内容，并形成一个有体系的“记事本兼资料库”。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
内容上等组里其他人判断。

**Comment by HAHH9527** [comment]
同意

**Comment by linlinzzo** [comment]
那就拉到“待添加readme”吧。

**Comment by imgradeone** [comment]
*WikiMimo 现已关闭并屏蔽中国大陆，因此申请退出“开往”，抱歉……
