### ISSUE TITLE
字节星球

### ISSUE THREAD

**Issue by csthenry** [travellings-link/travellings#1074]
### 网站名称

字节星球

### 十年之约大事记网址

https://www.foreverblog.cn/blog/636.html

### 网站网址

https://www.bytecho.net/

### 徽标位置

底部

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
移动端未能看到开往徽标。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by csthenry** [comment]
我的网站没有tag

**Comment by BLxcwg666** [comment]
> 我的网站没有tag

![image](https://github.com/travellings-link/travellings/assets/66854530/783f3261-cc23-426a-87b7-57a8510b2795)
你看吧，你想要哪些
