### ISSUE TITLE
你是人间的四月天

### ISSUE THREAD

**Issue by tosspi** [travellings-link/travellings#1076]
### 网站名称

你是人间的四月天

### 十年之约大事记网址

https://www.foreverblog.cn/blog/2687.html

### 网站网址

https://imum.me/

### 徽标位置

顶栏、网页底部

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/1cbdac73-681e-4b45-9884-e5c3891d8477)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/95a87caf-0aad-4594-aabb-9c07947ebd30)
