### ISSUE TITLE
闪闪の小窝

### ISSUE THREAD

**Issue by KnightKilito** [travellings-link/travellings#1081]
### 网站名称

闪闪の小窝

### 网站网址

https://moechun.fun/

### 徽标位置

顶栏

### 内容方向

一是技术分享，用自己一路学习、摸索、踩坑的经验帮助他人更高效快速地达到自己的目标；
二是自己喜欢的内容（二次元、生活）的分享吧，不管是否有同好来交流，我知道在这个网络世界里有我的一处栖息地。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
只有 13 篇文章哦，再多写一点吧。

**Comment by KnightKilito** [comment]
好的

**Comment by KnightKilito** [comment]
dalao，现在应该够了😭

**Comment by linlinzzo** [comment]
你用了3 天？文章都是些啥？今天连更三篇文章，都是自己写的吗？

[使用Let’s Encrypt获取免费SSL证书](https://moechun.fun/2022/07/18/%E4%BD%BF%E7%94%A8Let%E2%80%99s%20Encrypt%E8%8E%B7%E5%8F%96%E5%85%8D%E8%B4%B9SSL%E8%AF%81%E4%B9%A6/) 这篇文章的标题拿到搜索引擎上去搜搜？怎么感觉是在 [使用Let’s Encrypt获取免费证书](https://v2xtls.org/%e4%bd%bf%e7%94%a8lets-encrypt%e8%8e%b7%e5%8f%96%e5%85%8d%e8%b4%b9%e8%af%81%e4%b9%a6/) 修改来的呢？我想让你好好更博，但没必要朝着内容农场方向发展啊。

**Comment by KnightKilito** [comment]
我就那一篇想转载底下写了链接，其他我期末复习系列一篇抵人家好几篇……其他全原创，模仿的已经加入开往项目的其他人的博客，简简单单一些内容，我现在去补一篇七牛云的使用教程

**Comment by linlinzzo** [comment]
这个 issue 被关闭那还可以重新开啊。

**Comment by KnightKilito** [comment]
晓得了😭，劳烦了

**Comment by linlinzzo** [comment]
@HAHH9527 请看看符不符合标准。

**Comment by HAHH9527** [comment]
我觉得内容可以，个人意见转载转述其实也没必要做很严格的审查

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by KnightKilito** [comment]
UvmbLHYPgT
