### ISSUE TITLE
Tracert申请收录

### ISSUE THREAD

**Issue by cinwellrao** [travellings-link/travellings#1082]
### 网站名称

Tracert

### 网站网址

https://www.tracert.cn

### 徽标位置

顶栏友情链接

### 内容方向

为路由器生，为交换机死，为了Ping通奋斗一辈子！

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
你的那些生活文章能不能再详细一些？就一句话。搬砖虽忙，也要常更新博客。

**Comment by linlinzzo** [comment]
https://www.tracert.cn/h3c-speed-command.html
https://www.tracert.cn/h3c-dhcp-enable.html
https://www.tracert.cn/h3c-tracert-command.html
https://www.tracert.cn/h3c-independent-vlan.html

为什么这些文章要付费才能阅读？这不符合开往成员对开放互联网做出贡献的要求。

**Comment by cinwellrao** [comment]
> https://www.tracert.cn/h3c-speed-command.html https://www.tracert.cn/h3c-dhcp-enable.html https://www.tracert.cn/h3c-tracert-command.html https://www.tracert.cn/h3c-independent-vlan.html
> 
> 为什么这些文章要付费才能阅读？这不符合开往成员对开放互联网做出贡献的要求。

网络设备技术文档，花费大量精力整理和编写的技术型文档，知识付费才走的长远。

**Comment by linlinzzo** [comment]
经组内讨论，我们对贵站文章的原创性提出质疑，将您的加入申请驳回，并向十年之约提供有证据的建议（不干涉十年之约的审核结果）。

**Comment by linlinzzo** [comment]
如果您需要再次申请加入开往，请重提 issue。

**Comment by cinwellrao** [comment]
> 经组内讨论，我们对贵站文章的原创性提出质疑，将您的加入申请驳回，并向十年之约提供有证据的建议（不干涉十年之约的审核结果）。

好的，我撤回申请就是，但是你们团队成员（浙江宁波）没必要过来嘲讽，整理的资料和个人写的都有，整理也是辛苦的汗水。显得很没有格调。
