### ISSUE TITLE
iCooper Blog

### ISSUE THREAD

**Issue by intMojIBakE** [travellings-link/travellings#1083]
### 网站名称

iCooper Blog

### 网站网址

https://icooper.cc/

### 徽标位置

固定右侧栏

### 内容方向

计算机方面的经验心得，以及一些闲暇时的碎碎念。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
