### ISSUE TITLE
科技工坊

### ISSUE THREAD

**Issue by MyAifred** [travellings-link/travellings#1086]
### 网站名称

科技工坊

### 网站网址

https://1024war.top/

### 徽标位置

网页顶部

### 内容方向

科技作坊,征途更快更高效的科技的加工工场 个人博客，分享一些科技方面的谈天趣事！例如资源，教学，系统美化等1

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by MyAifred** [comment]
好耶

**Comment by linlinzzo** [comment]
@HAHH9527 你那边看一下，我这里网络环境有点特殊。。。

**Comment by HAHH9527** [comment]
请再多更新一些文章 我们有以下要求
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）

**Comment by MyAifred** [comment]
好嘛
&nbsp;


勿忘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月17日(星期天) 晚上10:36
收件人: ***@***.***&gt;; 
抄送: "The  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [travellings-link/travellings] 科技工坊 (Issue #1086)





 
请再多更新一些文章 我们有以下要求
  
网页已有较多内容（建议20篇以上，已持续更新一段时间）
