### ISSUE TITLE
百里飞洋の小世界

### ISSUE THREAD

**Issue by Barry-Flynn** [travellings-link/travellings#1087]
### 网站名称

百里飞洋の小世界

### 十年之约大事记网址

https://www.foreverblog.cn/blog/3241.html

### 网站网址

http://blog.meta-code.top/

### 徽标位置

右上角【更多】菜单，与十年之约放在一块，鼠标悬浮即可展开

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
开往徽标要求首屏显示（即在不进行任何鼠标操作的情况下），麻烦修改一下徽标的放置。

**Comment by Barry-Flynn** [comment]
已将徽标放置于首屏顶栏，辛苦再看一下，感谢。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by Barry-Flynn** [comment]
已更新开往链接，位置在首页顶部导航栏。
