### ISSUE TITLE
Y先生的火箭屋

### ISSUE THREAD

**Issue by pyy-Yanis** [travellings-link/travellings#1090]
### 网站名称

Y先生的火箭屋

### 网站网址

https://pyy52hz.cn

### 徽标位置

顶栏

### 内容方向

分享关于Java方面相关的知识，还有一些个人认为有趣有意思的内容

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
你的技术文章里有 mysql？要过来项目做开发吗？

**Comment by linlinzzo** [comment]
你还没有满 20 篇文章哦，再写一会吧。

**Comment by pyy-Yanis** [comment]
做开发是什么意思？ 强制要求20+？

**Comment by linlinzzo** [comment]
> 做开发是什么意思？ 强制要求20+？

开发是我个人的邀请。一般要 20+，十年之约成员申请会忽略这个要求。

**Comment by pyy-Yanis** [comment]
开发有什么要求吗

**Comment by linlinzzo** [comment]
> 开发有什么要求吗

熟悉 PHP、MySQL。
