### ISSUE TITLE
乡树

### ISSUE THREAD

**Issue by xiangshu233** [travellings-link/travellings#1099]
### 网站名称

乡树

### 网站网址

https://xiangshu233.cn

### 徽标位置

侧栏下方图标组

### 内容方向

日常，前端，开发

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
