### ISSUE TITLE
修仙大佬

### ISSUE THREAD

**Issue by XIUXIANDALao** [travellings-link/travellings#1101]
### 网站名称

修仙大佬

### 网站网址

https://heychaw.cc/

### 徽标位置

底部 右侧

### 内容方向

分享记录网络中遇到的问题

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
