### ISSUE TITLE
7gugu's Blog

### ISSUE THREAD

**Issue by 7gugu** [travellings-link/travellings#1106]
### 网站名称

7gugu's Blog

### 网站网址

https://7gugu.com

### 徽标位置

顶栏右侧

### 内容方向

博客上时常会分享一些小众的技术，好玩的经历，比如《如何设计自己的图形编码》，《日常碎碎念》等文章。后续还会持续更新图形方向与音频方向的博文。

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
