### ISSUE TITLE
计算机学习

### ISSUE THREAD

**Issue by zxqtd** [travellings-link/travellings#1111]
### 网站名称

计算机学习

### 网站网址

https://www.zxqblog.cn

### 徽标位置

顶栏 底部

### 内容方向

一下计算机专业的基础

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量有点少，再更新一点吧。

**Comment by zxqtd** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zxqtd** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
