### ISSUE TITLE
澄沨的漫游茶记

### ISSUE THREAD

**Issue by aquausora** [travellings-link/travellings#1115]
### 网站名称

澄沨的漫游茶记

### 十年之约大事记网址

https://www.foreverblog.cn/blog/3351.html

### 网站网址

https://champhoon.xyz

### 徽标位置

顶栏

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
今天过了十年之约审核，就来申请开往了。😅我看看···

**Comment by linlinzzo** [comment]
> 搞机时代大约的确是消亡了。

这句话是学鲁迅的吧。可以可以。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
加上了，等会一起合并。

**Comment by aquausora** [comment]
> > 搞机时代大约的确是消亡了。
> 
> 这句话是学鲁迅的吧。可以可以。

被发现了XD，とにかく感谢审查~

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
