### ISSUE TITLE
RK-Blog

### ISSUE THREAD

**Issue by Crazyokd** [travellings-link/travellings#1116]
### 网站名称

Rekord's Blog

### 十年之约大事记网址

https://www.foreverblog.cn/blog/3367.html

### 网站网址

https://sxrekord.com

### 徽标位置

左侧方底部

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
已添加，等会一起合并。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Crazyokd** [comment]
已更新
