### ISSUE TITLE
304号凝雀修改

### ISSUE THREAD

**Issue by Noxsk** [travellings-link/travellings#1118]
### 网站名称

Noxsk

### 网站网址

https://blog.noxsk.com

### 徽标位置

顶栏

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
已修改，等待合并。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
