### ISSUE TITLE
十月寒冬

### ISSUE THREAD

**Issue by Kagurain** [travellings-link/travellings#1121]
### 网站名称

十月寒冬

### 网站网址

https://inory.cc

### 徽标位置

顶栏

### 内容方向

我在 [这里](https://inory.cc/pages/me) 说了很多我的故事，我给站点定下了一个很明确的定位，却唯独忘了我自己。
我想分享我的生活，看那些飞鸟与鲸，看那些山川百态。
我想提高我的技术，和大家研讨技巧，为大家提出见解。
我想超越我的能力，潜移默化的进步，而不只是靠旁人。
这就是我建立站点的初衷，分享 提高和进步，和我为大家所带来的亦然。这次加入开往，望能和一众小伙伴打成一片，曾经有过三分钟热度的经历，这次不一样，决定好的事情，不能再轻易落下，望能与开往各位大大携手并进。
站点数据已恢复，离提交时站点已满636天，未来的发展方向只会与高质量文章挂钩。始欲识郎时，两心望如一。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
你 06 年出生的吗？比我大一岁。

**Comment by linlinzzo** [comment]
文章数量还没有满 20 篇，等会再来申请吧。

**Comment by Big-Cake-jpg** [comment]
> 你 06 年出生的吗？比我大一岁。

我 08 年（

**Comment by Kagurain** [comment]
> 你 06 年出生的吗？比我大一岁。

对 二月二十二

**Comment by Kagurain** [comment]
> 文章数量还没有满 20 篇，等会再来申请吧。

好的 是重新开issue还是在这里申请quq

**Comment by Kagurain** [comment]
> > 你 06 年出生的吗？比我大一岁。
> 
> 我 08 年（

我认识的10年出生的朋友也在建blog（

**Comment by linlinzzo** [comment]
ERR_HTTP2_PROTOCOL_ERROR？网站出问题了？

**Comment by linlinzzo** [comment]
> 好的 是重新开issue还是在这里申请quq

如果 14 天发不了就之后从新申请。（14 天肝这么多质量会受到影响）

**Comment by linlinzzo** [comment]
> 我认识的10年出生的朋友也在建blog（

10 后太可怕了。我在十年之约群里还见到过六年级开博客的。呼。

**Comment by Kagurain** [comment]
> ERR_HTTP2_PROTOCOL_ERROR？网站出问题了？

服务器装的宝塔面板是开心版的，想恢复原版，尝试校验+升级命令无果后在ssh内重装了，我现在在挂个通知单页

**Comment by Kagurain** [comment]
> > 好的 是重新开issue还是在这里申请quq
> 
> 如果 14 天发不了就之后从新申请。（14 天肝这么多质量会受到影响）

好的！！

**Comment by Kagurain** [comment]
> > 我认识的10年出生的朋友也在建blog（
> 
> 10 后太可怕了。我在十年之约群里还见到过六年级开博客的。呼。

我第一次认真建网站，其实是在四年级（

**Comment by linlinzzo** [comment]
> 我第一次认真建网站，其实是在四年级（

我那时候还在玩凡科呢。

**Comment by Kagurain** [comment]
> > 我第一次认真建网站，其实是在四年级（
> 
> 我那时候还在玩凡科呢。

！原来凡科大家都玩过啊

**Comment by linlinzzo** [comment]
> ！原来凡科大家都玩过啊

应该吧。我看你那个 slug，你玩《原神》吗？是不是也选空？

**Comment by linlinzzo** [comment]
我这有个项目[中文博客列表导航](https://github.com/zh-blogs)，不知道你感不感兴趣。

**Comment by Kagurain** [comment]
> > ！原来凡科大家都玩过啊
> 
> 应该吧。我看你那个 slug，你玩《原神》吗？是不是也选空？

玩过，但是接触的不多。虽然我是个小二次元，但其实我玩的最多还是phigros

**Comment by Kagurain** [comment]
> 我这有个项目[中文博客列表导航](https://github.com/zh-blogs)，不知道你感不感兴趣。

其实最早狼叔刚建立这个项目的时候我就加入了的，就是 `rua.ink` 时期，不过当时因为一些个人原因停止了博客的更新。
其他的组织暂时先放放吧，毕竟加入开往也一样会加入[中文博客列表导航](https://github.com/zh-blogs)，不被开往认可只有提高博客的质量是首要的，被认可后我才会相信自己的文章质量，其次才是加入更多的博客组织。

**Comment by linlinzzo** [comment]
> 其实最早狼叔刚建立这个项目的时候我就加入了的，就是 `rua.ink` 时期，不过当时因为一些个人原因停止了博客的更新。 其他的组织暂时先放放吧，毕竟加入开往也一样会加入[中文博客列表导航](https://github.com/zh-blogs)，不被开往认可只有提高博客的质量是首要的，被认可后我才会相信自己的文章质量，其次才是加入更多的博客组织。

其实是想让你进来干活。。。

**Comment by Kagurain** [comment]
> > 其实最早狼叔刚建立这个项目的时候我就加入了的，就是 `rua.ink` 时期，不过当时因为一些个人原因停止了博客的更新。 其他的组织暂时先放放吧，毕竟加入开往也一样会加入[中文博客列表导航](https://github.com/zh-blogs)，不被开往认可只有提高博客的质量是首要的，被认可后我才会相信自己的文章质量，其次才是加入更多的博客组织。
> 
> 其实是想让你进来干活。。。

我有空的，需要我帮什么忙都可以

**Comment by linlinzzo** [comment]
> 我有空的，需要我帮什么忙都可以

就是帮忙找一找博客网站，加到这里面去。如果可以，加我 qq

**Comment by Kagurain** [comment]
> > 我有空的，需要我帮什么忙都可以
> 
> 就是帮忙找一找博客网站，加到这里面去。如果可以，加我 qq

好的 我的QQ是70933620 我怕我会频繁 你把你的QQ也给我下

我可以被添加到组织里去吗 招收的博客面向什么类型 例如小夜这种也算吗

**Comment by linlinzzo** [comment]
我的资料里有。

**Comment by linlinzzo** [comment]
@Kagurain 812568734

**Comment by Kagurain** [comment]
> @Kagurain 812568734

我发送申请很久了 在你评论之前

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
