### ISSUE TITLE
飞刀博客

### ISSUE THREAD

**Issue by libasten** [travellings-link/travellings#1126]
### 网站名称

飞刀博客

### 网站网址

https://www.feidaoboke.com/

### 徽标位置

网站侧栏友情链接位置。

### 内容方向

包括读书笔记、随笔日志、信息技术、足球评论和新闻资讯相关的独立个人博客。

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
move to https://github.com/travellings-link/travellings/issues/303
