### ISSUE TITLE
小被被好好摸

### ISSUE THREAD

**Issue by fez7yoe** [travellings-link/travellings#1128]
### 网站名称

小被被好好摸

### 网站网址

https://fez7yoe.github.io

### 徽标位置

顶栏、侧栏、底部

### 内容方向

《 📚 收藏任何我感兴趣的东西 》
《 📝 心血来潮写一篇比参考文献更详细且目标客群是没有相关知识的教学 》
《 💣 关于某人事时地物的想法 》

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
再多写一会吧。

**Comment by fez7yoe** [comment]
> 再多写一会吧。

嗯...
你直接跟说我还要再写几篇文章吧
或给个公式，让我自己算自己还要再写多少
我是确定有达到最少数量才来申请
除非开往跟十年一样有原创文章的规定
也不想因为来这申请而有被催促写文的感觉

**Comment by fez7yoe** [comment]
请问是没收到回复通知么？
比我晚申请的博客都完成了 Issues
怎么这 Issues 就快鸽到 30 天了

**Comment by linlinzzo** [comment]
我们要求文章个数要到 20 篇，这在我们的加入条件里面有明确写出，请你重新认真阅读我们的条件。根据 https://fez7yoe.github.io/posts/dfa211a2/ ，你的博客网站上面有效的文章并不多，我个人在审核的时候会把一些无效的文章给剔除掉，不记入文章个数里面。

我们是开源项目的维护人员，做这个没有任何的“工资”，审核慢也是有理由的，没必要对我们发火。

**Comment by linlinzzo** [comment]
邮件回复通知我刚才去查了一下，还真没有。

**Comment by fez7yoe** [comment]
请教一下有效与无效文章的定义？

没有眼花看错的话
加入条件并没有明确提出那20+文章均须是原创内容
若有不适宜或其他违规内容，请明讲，问多了我的耐心自然也会下降

我并不知道维护人员的审核 "习惯"
所以看到 "在我顺序之前的issues" 跟 "在我顺序之后的issues"
标签基本都被编入 "已完成" 时，感到了不公平

你没收到回复这我也没头绪，只好再多回复一次来尝试

**Comment by linlinzzo** [comment]
我已经将 issue 转交给其他人审核，我的审核条件过于严苛。
另外，请一下横向对比的同时，做一下纵向对比，看一下这个 issue 的审核时间：https://github.com/travellings-link/travellings/issues/782 。我个人没有办法来给站长创造公平的条件，只是帮忙把这个审核时间尽量缩短。理解一下，谢谢。

**Comment by HAHH9527** [comment]
> - 禁止网站（尤其是博客网站）的文章包含如下内容：
>   * 包含色情、暴力、血腥、低俗、引战等引人不适的内容
>   * 包含辱骂、挑衅、诽谤、反动等违反法律法规的内容
>   * 包含其它维护组成员认为的不适宜内容

不知道你是否有注意到这条款项，你在这篇文章 (https://fez7yoe.github.io/posts/67c4bb57/) 中所表达的观点让我认为你以后可能会发表违反这条款项的文章。

**Comment by qystudio0** [comment]
> 你截稿期到了在催稿啊？真的是在催促大众水文唉 (笑)

我希望你可以尊重开往团队的成员，我们没有义务被你指指点点

**Comment by fez7yoe** [comment]
谢谢两位快速又明确的指出认为不适宜内容的地方
为健康风气着想，我选择放弃加入开往

最后提问劳烦各位了
请问要关闭此 issue 是我自己手动关闭还是由团队关闭？

**Comment by HAHH9527** [comment]
你可以自己关闭此 issue 或等待后续由 action 关闭

**Comment by qystudio0** [comment]
> 谢谢两位快速又明确的指出认为不适宜内容的地方
> 为健康风气着想，我选择放弃加入开往
> 
> 最后提问劳烦各位了
> 请问要关闭此 issue 是我自己手动关闭还是由团队关闭？

非常感谢您的理解
