### ISSUE TITLE
Cubik的小站

### ISSUE THREAD

**Issue by Cubik65536** [travellings-link/travellings#1129]
### 网站名称

Cubik的小站

### 十年之约大事记网址

https://www.foreverblog.cn/blog/2992.html

### 网站网址

https://www.cubik65536.top

### 徽标位置

电脑端固定侧栏（但移动端会被隐藏，也没有找到更明显的地方了，很抱歉）

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
移动端可以考虑将侧边栏的内容加到页面的底部。

**Comment by Cubik65536** [comment]
> 移动端可以考虑将侧边栏的内容加到页面的底部。

已经添加到底部了。

另外，由于一些样式设置的关系，放图片和 Font Awesome 的效果都不好，所以放在了 sitemap 的 `社交` 一栏里，希望可以通过

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Cubik65536** [comment]
已更新

> 您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：
> 
> gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif) svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)
> 
> 请您及时更换相关地址，谢谢配合。
