### ISSUE TITLE
Xlencoの小窝

### ISSUE THREAD

**Issue by xlenco** [travellings-link/travellings#1130]
### 网站名称

开往

### 网站网址

https://xlenco.eu.org/

### 徽标位置

默认收起的顶部菜单里

### 内容方向

分享互联网各种知识,建站经验..

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by xlenco** [comment]
已更换
