### ISSUE TITLE
FuBaooo 博客

### ISSUE THREAD

**Issue by FuBaooo** [travellings-link/travellings#1131]
### 网站名称

FuBaooo 博客

### 网站网址

https://baii.icu/

### 徽标位置

右上角导航栏

### 内容方向

记录自己遇到的问题、学习总结、参与的学习挑战

ps: [https://baii.icu/challenges](Fubaooo - 挑战) 内有挑战相关内容，篇数较多

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
电脑端没看到。

**Comment by FuBaooo** [comment]
> 电脑端没看到。

现在可以看到右上角出来了

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
