### ISSUE TITLE
橘夜庭|霂森西

### ISSUE THREAD

**Issue by Musenxi** [travellings-link/travellings#1134]
### 网站名称

橘夜庭|霂森西

### 十年之约大事记网址

https://www.foreverblog.cn/blog/2627.html

### 网站网址

https://musenxi.com

### 徽标位置

顶栏

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Musenxi** [comment]
原**序号86** 名称沐森西の博客 地址https://dlizi.com

**Comment by Musenxi** [comment]
member.md |符号出错了，要不把我名称的“|”删了

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
