### ISSUE TITLE
圆周率的博客

### ISSUE THREAD

**Issue by yzl3014** [travellings-link/travellings#1146]
### 网站名称

圆周率的博客

### 网站网址

https://yuanzj.top/

### 徽标位置

顶栏

### 内容方向

计算机软件、网站开发、没事写的短文短句（虽然还没发过），还有其他值得一说的经验，总之就是有什么写什么。
注：开学时可能几乎无法更新（毕竟开学就初二了），除非一开学就直接上网课。而且服务器本身可能就不太稳定。特此说明。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by yzl3014** [comment]
zMHfnJY9JC

**Comment by yzl3014** [comment]
希望将网址更改为`www.yuanzj.top`以提升访问速度，减少因重定向带来的等待。
