### ISSUE TITLE
怡然一记

### ISSUE THREAD

**Issue by Sun-Hua** [travellings-link/travellings#1158]
### 网站名称

怡然一记

### 网站网址

https://xsunhua.cn

### 徽标位置

侧栏

### 内容方向

linux基础知识和个人博客搭建及相关功能美化

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
内容不丰富。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Sun-Hua** [comment]
已更换，谢谢通知



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月5日(周四) 上午7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [travellings-link/travellings] 怡然一记 (Issue #1158)




 
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
 gif动图：https://www.travellings.cn/assets/logo.gif
 svg：https://www.travellings.cn/assets/logo.svg
 请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/77ab420a-b9a6-4e56-834c-aa8d3c7f2a68)

站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
