### ISSUE TITLE
无名博客

### ISSUE THREAD

**Issue by wumingboke** [travellings-link/travellings#1159]
### 网站名称

无名博客

### 网站网址

https://wumingboke.xyz/

### 徽标位置

侧栏

### 内容方向

折腾记录啥的 望通过QAQ

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
