### ISSUE TITLE
小明的博客

### ISSUE THREAD

**Issue by kebuAAA** [travellings-link/travellings#1162]
### 网站名称

小明的博客

### 网站网址

https://xiaoming.vercel.app/

### 徽标位置

顶部

### 内容方向

机器学习
数据科学

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by kebuAAA** [comment]
> ### 网站名称
> 小明的博客
> 
> ### 网站网址
> https://xiaoming.vercel.app/
> 
> ### 徽标位置
> 顶部
> 
> ### 内容方向
> 机器学习 数据科学
> 
> ### 请确认一下事项
> * [x]  我已确认以上事项

网站地址需要更改一下，vercel被墙.改为:https://blog.kobal.cn/

**Comment by kebuAAA** [comment]
博客地址已更改为:https://blog.kobal.cn/ @linlinzzo

**Comment by linlinzzo** [comment]
已修改，等待合并。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
