### ISSUE TITLE
WindowsRegeditのsite

### ISSUE THREAD

**Issue by WindowsRegedit** [travellings-link/travellings#1163]
### 网站名称

WindowsRegeditのsite

### 网站网址

https://wufan.fun/

### 徽标位置

侧栏

### 内容方向

分享生活中的一些感想，以及一些编程技能。

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
https://wufan.fun/index.php/archives/4/ 这个违规
请提供一下原创文章的链接

**Comment by WindowsRegedit** [comment]
违规文章已删除。原创文章是除了标签有“精选转载”的其他所有文章。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/5bf3d519-c696-47c3-8d92-ad41402a4d21)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
