### ISSUE TITLE
嘉嘉的博客

### ISSUE THREAD

**Issue by justin-jiajia** [travellings-link/travellings#1164]
### 网站名称

嘉嘉的博客

### 网站网址

https://blog.jiajia.ml/

### 徽标位置

顶部和底部

### 内容方向

C++、Python编程经验，辅以生活趣事

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
网站的评论功能没有办法用啊。

**Comment by justin-jiajia** [comment]
> 网站的评论功能没有用啊。

感谢提醒，是GitTalk的仓库地址写错了，已修复~

**Comment by justin-jiajia** [comment]
请求修改站点地址为 https://blog.hijiajia.xyz

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
