### ISSUE TITLE
Niuteの屑站

### ISSUE THREAD

**Issue by NiuFuyu855** [travellings-link/travellings#1167]
### 网站名称

Niute Fony

### 网站网址

https://blogs.niufuyu.top/

### 徽标位置

侧栏

### 内容方向

分享一些实用资源和技术教程等。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by essesoul** [comment]
![image](https://user-images.githubusercontent.com/58624474/187054888-51a73616-4c0a-41ce-ae13-e12afe5fdaec.png)
可以访问但是页面空白

**Comment by NiuFuyu855** [comment]
Vercel部署有问题，现在已经修复好了！您再看看呢

**Comment by NiuFuyu855** [comment]
Vercel部署有问题，现在已经修复好了！您再看看呢

**Comment by NiuFuyu855** [comment]
博客域名已更换：https://off.cx

**Comment by NiuFuyu855** [comment]
#1280

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
