### ISSUE TITLE
心流

### ISSUE THREAD

**Issue by flow2000** [travellings-link/travellings#1183]
### 网站名称

心流

### 网站网址

https://blog.panghai.top

### 徽标位置

默认收起的菜单里

### 内容方向

技术分享博客

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
move to #1184

**Comment by linlinzzo** [comment]
电脑首屏没有看到开往链接，建议不要收起。

**Comment by flow2000** [comment]
那我改一下

**Comment by flow2000** [comment]
已修改

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
move to #1184
