### ISSUE TITLE
心流

### ISSUE THREAD

**Issue by flow2000** [travellings-link/travellings#1184]
### 网站名称

心流

### 十年之约大事记网址

https://blog.panghai.top

### 网站网址

https://blog.panghai.top

### 徽标位置

默认收起的菜单里

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by jiangmiemie** [comment]
目前会自动跳转至https://blog.aqcoder.cn/   如确认是您个人行为，请抓紧申请更换域名：为https://blog.aqcoder.cn/
如非个人行为，请尽快修复~ @flow2000

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/93f1b8fd-4b16-4f51-b1a1-536556972891)
根据 issue 评论记录，将您站点信息更改为 https://blog.aqcoder.cn

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/0c9945ca-3aa0-4024-90ca-bee90bf2a2bd)
站点名更改为 枫叶
