### ISSUE TITLE
八荒山人的博客

### ISSUE THREAD

**Issue by BahuangShanren** [travellings-link/travellings#1190]
### 网站名称

八荒山人的博客

### 网站网址

https://www.bahuangshanren.tech/

### 徽标位置

顶栏

### 内容方向

日常技术笔记

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by BahuangShanren** [comment]
已更改为 https://www.travellings.cn/go.html
