### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by Legroft** [travellings-link/travellings#12]
## 网站名称
Legroft
## 网站链接
https://jinjis.cn
## 徽标位置
顶栏，底部
## 推荐理由
觉得这个项目很赞

**Comment by volfclub** [comment]
已收录

**Comment by Legroft** [comment]
已更新链接

**Comment by linlinzzo** [comment]
侧边栏在移动端收起时未在底部放置开往徽标。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
