### ISSUE TITLE
小忧忧のBlog

### ISSUE THREAD

**Issue by jerryyang-git** [travellings-link/travellings#1200]
### 网站名称

小忧忧のBlog

### 网站网址

https://jerryyang.link

### 徽标位置

网页底部

### 内容方向

手机刷机教程、计算机使用，自己喜欢的HIFI音源、日常工作生活 中的一些笔记

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
Please delete the following articles:       
https://jerryyang.link/index.php/archives/1/      

Problems:         
https://jerryyang.link/index.php/archives/4/ is similar to https://www.mrjeke.com/tutorials/186.html     
https://www.jerryyang.link/index.php/archives/16/ is similar to https://baike.baidu.com/item/%E5%AD%94%E4%B9%99%E5%B7%B1/2262158     
and so on

**Comment by JerryYang-git** [comment]
> 请尽量原创，认真地多写一会博客。

好的，后续我的文章合格之后再申请
