### ISSUE TITLE
安知鱼

### ISSUE THREAD

**Issue by anzhiyu-c** [travellings-link/travellings#1204]
### 网站名称

安知鱼

### 网站网址

https://anzhiy.cn

### 徽标位置

导航栏

### 内容方向

生活与前端方向技术

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
转交由其他维护人员审核。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/4aaef4ab-ee04-4bb0-ac9d-ccb8fd9e097a)

https://anzhiy.cn/ 自动重定向至 https://blog.anheyu.com/
更新链接到 https://blog.anheyu.com/
