### ISSUE TITLE
San‘qi Blog

### ISSUE THREAD

**Issue by sanqi377** [travellings-link/travellings#1206]
### 网站名称

San‘qi Blog

### 网站网址

https://www.qblog.cc/

### 徽标位置

导航右侧

### 内容方向

技术分享与生活点滴~

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量推荐满 20 篇。

**Comment by sanqi377** [comment]
差不多啦~

**Comment by sanqi377** [comment]
博客改版，徽标位置移动到了顶部右上角 ”火车“ 小图标

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
