### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by 724135753** [travellings-link/travellings#1210]
### 网站名称

树洞笔记

### 网站网址

https://www.x8xx.cn/

### 徽标位置

顶栏

### 内容方向

树洞笔记-用文字记录生活,新一代农民工的个人博客网站,IT技术分享,华为路由交换技术,无线网络,网络安全经验分享

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by HAHH9527** [comment]
审核通过，待添加

**Comment by A7103** [comment]
https://github.com/travellings-link/travellings/pull/1228 已添加，关闭此issue

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
