### ISSUE TITLE
无聊的人博客 (麻烦更改原有数据)

### ISSUE THREAD

**Issue by weiliangrong2022** [travellings-link/travellings#1211]
### 网站名称

无聊的人博客

### 网站网址

https://blog.wlr.lol

### 徽标位置

侧栏

### 内容方向

麻烦更新为
伟良荣博客
https://weiliangrong.eu.org/

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
请提供网站序号。

**Comment by weiliangrong2022** [comment]
是529

**Comment by A7103** [comment]
@weiliangrong2022  似乎你已删除开往的友链

**Comment by weiliangrong2022** [comment]
![Uploading Screenshot_2022-11-29-23-42-01-291-edit_mark.via.jpg…]()
就在这里啊

**Comment by weiliangrong2022** [comment]
侧边栏
![Screenshot_2022-11-29-23-42-01-291-edit_mark.via.jpg](https://img1.imgtp.com/2022/11/29/Bg3NFSP4.jpg)

**Comment by weiliangrong2022** [comment]
原先的链接是https://travellings.cn 现已更新未为https://travellings.link/ !

**Comment by A7103** [comment]
> 原先的链接是https://travellings.cn 现已更新为https://travellings.link/ !

@weiliangrong2022  好的

**Comment by A7103** [comment]
目前网站一切正常，关闭issue

**Comment by A7103** [comment]
@weiliangrong2022  你服务器的nginx挂啦
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/117614950/205208169-c73087f6-068b-4e01-8abf-ad3a4260f40c.png">

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by weiliangrong2022** [comment]
收到啦
