### ISSUE TITLE
大户爱の博客

### ISSUE THREAD

**Issue by ohtoaigod** [travellings-link/travellings#1217]
### 网站名称

大户爱の博客

### 网站网址

https://blog.ohtoai.com/

### 徽标位置

PC端:侧栏 , H5端：底部栏

### 内容方向

这里是大户爱的个人博客，你可以通过键入它，在互联网找到所有关于我的踪迹

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
