### ISSUE TITLE
武恩赐博客

### ISSUE THREAD

**Issue by wuenci666** [travellings-link/travellings#1222]
### 网站名称

武恩赐博客

### 网站网址

https://bolg.wuenci.wang/

### 徽标位置

网页底部

### 内容方向

武恩赐博客💻 - 记录一枚中职生的日常生活🎉

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
原创内容有点少。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
