### ISSUE TITLE
葱苓小居

### ISSUE THREAD

**Issue by ciraos** [travellings-link/travellings#1223]
### 网站名称

葱苓小居

### 网站网址

https://blog.ciraos.top

### 徽标位置

顶栏

### 内容方向

c++、c语言，html等等，博客相关。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by ciraos** [comment]
啊这，github actions出了点问题，还以为部署失败了呢。。。抱歉。。。

**Comment by ciraos** [comment]
((

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by A7103** [comment]
https://github.com/travellings-link/travellings/pull/1228 已添加，关闭issue

**Comment by HowieHz** [comment]
和博主交流后锁定，等待重新申请
