### ISSUE TITLE
浅溪

### ISSUE THREAD

**Issue by qingchenling** [travellings-link/travellings#1224]
### 网站名称

浅溪-Ling Chen's blog

### 网站网址

https://yingqing.cf/

### 徽标位置

顶栏

### 内容方向

分享一些算法与平时的心得

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
