### ISSUE TITLE
loquy

### ISSUE THREAD

**Issue by loquy** [travellings-link/travellings#1225]
### 网站名称

loquy

### 网站网址

https://www.loquy.cn/

### 徽标位置

顶栏

### 内容方向

前后端技术，文档笔记

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by loquy** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
> 
> gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg
> 
> 请您及时更换相关地址，谢谢配合。



> 

您好，已更换新的地址
