### ISSUE TITLE
linkkk的小屋

### ISSUE THREAD

**Issue by linkkk0** [travellings-link/travellings#1226]
### 网站名称

linkkk的小屋

### 网站网址

https://www.linkkk.top

### 徽标位置

侧栏

### 内容方向

一个学生的学习心得与生活感受，折腾折腾有趣的技术。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
域名解析错误？

**Comment by 2319564679** [comment]
不好意思，笔误，网址应为https://www.linkkk.top

**Comment by linlinzzo** [comment]
现在只有 15 篇“有效文章”，写到 20 篇再来吧。

**Comment by linlinzzo** [comment]
有效文章我这里把密码保护的文章和最开始的初始文章排除掉了。

**Comment by linlinzzo** [comment]
你今年初三吗？

**Comment by 2319564679** [comment]
> 现在只有 15 篇"有效文章"，写到 20 篇再来吧。

好吧，谢谢

**Comment by 2319564679** [comment]
> 你今年初三吗？

初三不至于，初二呢

**Comment by linlinzzo** [comment]
> 初三不至于，初二呢

初二就写博客？你是怎么知道博客的？为什么你要写博客呢？

**Comment by 2319564679** [comment]
> 初二就写博客？你是怎么知道博客的？为什么你要写博客呢？
是的呢
> 你是怎么知道博客的？
知道博客是几年前，然后头脑一热搞了个免费主机，走过了许许多多的数据丢失，现在买了自己的服务器稳定下来了。
> 为什么你要写博客呢？
我想，博客的初衷就是记录生活，记录自己都日常。同时也是与有共同兴趣爱好的小伙伴一起参与自己做的事。所以我的博客没有广告，且非盈利。

**Comment by essesoul** [comment]
网站无法访问

**Comment by 2319564679** [comment]
> 网站无法访问

你好，可能是cdn回源加载超时了，刷新一下就好了呢

**Comment by 2319564679** [comment]
> 网站无法访问

我的一开始网址填错了，应为https://www.linkkk.top
