### ISSUE TITLE
Mycpen

### ISSUE THREAD

**Issue by mycpen** [travellings-link/travellings#1230]
### 网站名称

Mycpen

### 网站网址

https://cpen.top

### 徽标位置

顶部导航栏

### 内容方向

分享学习笔记

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章太水。

**Comment by mycpen** [comment]
最近的1篇字数很少 仅455个字，但是过去30多篇文章的字数都大于 2k。总字数 150k，文章数 45，平均 5k/篇。
博客内容涉及的都是学习笔记，原创为主。

![image](https://user-images.githubusercontent.com/72154342/193508090-dbf69f9e-085f-4c53-97bd-3464a7d3a97f.png)

**Comment by mycpen** [comment]
> 文章太水。

@linlinzzo 最近的1篇字数很少 仅455个字，但是过去30多篇文章的字数都大于 2k。总字数 150k，文章数 45，平均 3k/篇。
博客内容涉及的都是学习笔记，原创为主。

![image](https://user-images.githubusercontent.com/72154342/193508090-dbf69f9e-085f-4c53-97bd-3464a7d3a97f.png)

**Comment by HAHH9527** [comment]
通过，待添加

**Comment by HAHH9527** [comment]
通过，待添加
