### ISSUE TITLE
熊可狸

### ISSUE THREAD

**Issue by KumaKorin** [travellings-link/travellings#1231]
### 网站名称

熊可狸

### 网站网址

https://ali-a.cn

### 徽标位置

侧边栏，顶栏

### 内容方向

博客，日常分享等

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量有点少，再写一会吧。
（另外，怎么感觉被标记失效的文章有点多）

**Comment by KumaKorin** [comment]
好的
