### ISSUE TITLE
王政乔 - Wangzhengqiao's Blog

### ISSUE THREAD

**Issue by ZhengqiaoWang** [travellings-link/travellings#1232]
### 网站名称

王政乔

### 网站网址

https://www.zhengqiao.wang/

### 徽标位置

侧栏

### 内容方向

个人技术博客，包含一些技术总结和文档翻译

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by A7103** [comment]
已添加 https://github.com/travellings-link/travellings/pull/1250

**Comment by ZhengqiaoWang** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下： gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg 请您及时更换相关地址，谢谢配合。

已变更
