### ISSUE TITLE
Heroxin

### ISSUE THREAD

**Issue by heroxin-59** [travellings-link/travellings#1238]
### 网站名称

Heroxin

### 网站网址

https://heroxin.xyz/

### 徽标位置

顶部，右侧

### 内容方向

爱好，知识，技能

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
