### ISSUE TITLE
一恒的网志

### ISSUE THREAD

**Issue by heng86** [travellings-link/travellings#1240]
### 网站名称

一恒的网志

### 网站网址

https://hu86.cc/

### 徽标位置

侧栏和底部

### 内容方向

个人博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
