### ISSUE TITLE
JaSpirit的万事屋

### ISSUE THREAD

**Issue by JohnSpirit** [travellings-link/travellings#1241]
### 网站名称

JaSpirit的万事屋

### 网站网址

https://blog.jaspirit.cc/

### 徽标位置

顶部导航栏

### 内容方向

学习笔记、知识分享（计算机、化学、物理、生物）、日常随笔

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
