### ISSUE TITLE
习物志 | Light In The Sky

### ISSUE THREAD

**Issue by songxiao1018** [travellings-link/travellings#1244]
### 网站名称

习物志 | Light In The Sky

### 网站网址

https://www.xiaoxiaosky.top/

### 徽标位置

侧栏

### 内容方向

分享学习心得

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
https://www.xiaoxiaosky.top/2022/09/19/helloworld123/
https://www.xiaoxiaosky.top/2022/10/06/hello-world/
https://www.xiaoxiaosky.top/2022/09/19/make-blog/
https://www.xiaoxiaosky.top/2022/09/15/banweixuanju/
https://www.xiaoxiaosky.top/2022/09/10/JAVA-HelloWorld/
以上文章不算作有效文章。文章数量应不少于 20 篇。
