### ISSUE TITLE
何孙涛の博客

### ISSUE THREAD

**Issue by res-256** [travellings-link/travellings#1246]
### 网站名称

何孙涛の博客

### 网站网址

https://z555.icu

### 徽标位置

顶栏

### 内容方向

<h1 align="center"> Hello! 👋  I'm <a href="https://github.com/Chocolate1999">Adam</a>!</h1>
<h1 align="center">临床医学生一枚</h1>
一个临床医学生，在这里分享知识与日常总结。个人博客网站。记录心情、学习技巧，下班之余做做美化，学习新的js等知识。
## 𝗠𝘆 𝗧𝗲𝗰𝗸 𝗦𝘁𝗮𝗰𝗸

[![OS](https://img.shields.io/badge/OS-macOS-informational?style=flat-square&logo=apple&logoColor=white)](https://en.wikipedia.org/wiki/MacOS)[![OS](https://img.shields.io/badge/OS-Linux-informational?style=flat-square&logo=linux&logoColor=white)](https://en.wikipedia.org/wiki/Linux)[![Editor](https://img.shields.io/badge/Editor-VSCode-blue?style=flat-square&logo=visual-studio-code&logoColor=white)](https://code.visualstudio.com/)
[![](https://img.shields.io/website?color=0ab9e6&style=flat-square&up_message=何孙涛の博客&url=https://z555.icu)](https://z555.icu/)![HTML5](https://img.shields.io/badge/-HTML5-%23E44D27?style=flat-square&logo=html5&logoColor=ffffff)![CSS3](https://img.shields.io/badge/-CSS3-%231572B6?style=flat-square&logo=css3)
![JavaScript](https://img.shields.io/badge/-JavaScript-%23F7DF1C?style=flat-sqare&logo=javascript&logoColor=000000&labelColor=%23F7DF1C&color=%23FFCE5A)![React](https://img.shields.io/badge/-React-%23282C34?style=flat-square&logo=react)

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by HowieHz** [comment]
巡查发现已成为菠菜网，已删除。
欢迎重新申请加入开往。
