### ISSUE TITLE
大蛋糕的烘焙坊

### ISSUE THREAD

**Issue by Big-Cake-jpg** [travellings-link/travellings#1251]
### 网站名称

大蛋糕的烘焙坊

### 网站网址

https://bigcake.cakemc.top

### 徽标位置

侧栏

### 内容方向

与世界分享自己的所见所闻、自己的成长历程以及自己觉得非常实用的小工具等
————————
初三鸽子一名，不知道十年以后的自己和小站将会是什么样子
还是希望自己能走得更远，以至于不留遗憾😄
我也会视情况更新文章，努力完成十年的契约的

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by A7103** [comment]
已添加 https://github.com/travellings-link/travellings/pull/1250

**Comment by linlinzzo** [comment]
没有看到开往链接。

**Comment by Big-Cake-jpg** [comment]
DQkkO3krbG

**Comment by linlinzzo** [comment]
已将权益申请移交给 FarCDN，等待 FarCDN 处理。
