### ISSUE TITLE
修改 SinGO博客

### ISSUE THREAD

**Issue by StarWEB890** [travellings-link/travellings#1264]
### 网站名称

SinGO博客

### 网站网址

http://blog.xsnet.eu.org/

### 徽标位置

顶栏

### 内容方向

分享教程，诉说着我的心事

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by A7103** [comment]
done. https://github.com/travellings-link/travellings/pull/1293

**Comment by HowieHz** [comment]
link #1144
