### ISSUE TITLE
釉色鸭的笔记

### ISSUE THREAD

**Issue by Yoseya2410** [travellings-link/travellings#1267]
### 网站名称

釉色鸭的知识库

### 网站网址

https://yoseya2410.github.io/

### 徽标位置

顶部导航栏

### 内容方向

主要分享数学，物理等自然科学;计算机，互联网，前端开发，程序设计；电子技术。大部分文章还在notion，正在向这个新博客转移，希望通过审核

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by HowieHz** [comment]
link #1269
