### ISSUE TITLE
姐姐的个人博客

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [travellings-link/travellings#1270]
### 网站名称

姐姐的个人博客

### 网站网址

https://jiejie.de/blog/

### 徽标位置

顶栏

### 内容方向

个人博客，泛内容分享。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
谷歌广告里有推荐非法内容，请去后台关一下。

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
> 谷歌广告里有推荐非法内容，请去后台关一下。

已关

**Comment by A7103** [comment]
https://github.com/travellings-link/travellings/pull/1291

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
