### ISSUE TITLE
懋和道人

### ISSUE THREAD

**Issue by wulintang** [travellings-link/travellings#1272]
### 网站名称

懋和道人

### 网站网址

https://www.lizhichen.cn

### 徽标位置

顶栏

### 内容方向

李懋和，俗名李栋梁。内地著名上清茅山宗道士，书法、国画爱好者，优秀的互联网安全与前端建设者。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by A7103** [comment]
done. https://github.com/travellings-link/travellings/pull/1291
