### ISSUE TITLE
MarioZZJ's blog

### ISSUE THREAD

**Issue by MarioZZJ** [travellings-link/travellings#1275]
### 网站名称

MarioZZJ's blog

### 网站网址

https://blog.mariozzj.cn/

### 徽标位置

顶栏

### 内容方向

日常，数据科学知识，技术分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by A7103** [comment]
done. https://github.com/travellings-link/travellings/pull/1291

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by MarioZZJ** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
> 
> gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg
> 
> 请您及时更换相关地址，谢谢配合。

已更换。感谢提醒
