### ISSUE TITLE
布丁の小窝

### ISSUE THREAD

**Issue by pudding233** [travellings-link/travellings#1278]
### 网站名称

布丁の小窝

### 网站网址

https://furryowo.top/

### 徽标位置

侧栏

### 内容方向

分享人生路上的坎坷(x

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by A7103** [comment]
done. https://github.com/travellings-link/travellings/pull/1291

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by gxres042** [comment]
站长您好，您的站点出现了无法访问的情况：

![图片](https://github.com/travellings-link/travellings/assets/53113178/95b93209-3f5e-42a7-9e51-e26b7f6ae225)

烦请您检查网站的运行状态。

**Comment by Big-Cake-jpg** [comment]
超时关闭。如有需要可重新提交 Issue 申请。

**Comment by HowieHz** [comment]
遗留未删除，已补删
