### ISSUE TITLE
HONG的小站

### ISSUE THREAD

**Issue by Dian-C** [travellings-link/travellings#1279]
### 网站名称

HONG的小站

### 网站网址

https://hongweblog.com

### 徽标位置

左邻右舍

### 内容方向

与世界分享我的见闻趣事

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
原批？过了。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
