### ISSUE TITLE
修改 Niuteの屑站

### ISSUE THREAD

**Issue by NiuFuyu855** [travellings-link/travellings#1280]
### 网站名称

Niute Fony

### 网站网址

https://off.cx/

### 徽标位置

侧栏

### 内容方向

分享技术以及日常生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
可以提供一下网站序号吗？

**Comment by Leon-Shaw** [comment]
网站序号：615

**Comment by NiuFuyu855** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下： gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg 请您及时更换相关地址，谢谢配合。

已修改！
