### ISSUE TITLE
L1nSn0w's Blog

### ISSUE THREAD

**Issue by lin-snow** [travellings-link/travellings#1283]
### 网站名称

L1nSn0w's Blog

### 网站网址

https://blog.linsnow.cn/

### 徽标位置

右侧边栏

### 内容方向

科技\折腾\数码\游戏\生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by HAHH9527** [comment]
审核已通过, 待添加

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
