### ISSUE TITLE
Alliot's blog

### ISSUE THREAD

**Issue by AlliotTech** [travellings-link/travellings#1285]
### 网站名称

Alliot's blog

### 网站网址

https://www.iots.vip

### 徽标位置

侧栏

### 内容方向

Maker & Developer

记录学习，记录生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by AlliotTech** [comment]
已更换。  等待CDN同步刷新

**Comment by AlliotTech** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/24980252/210954762-b0dba8b6-1fb4-4fe3-9f5a-65aab8499fef.png">
