### ISSUE TITLE
万笔记

### ISSUE THREAD

**Issue by wuyucun** [travellings-link/travellings#1286]
### 网站名称

万笔记

### 网站网址

https://wannote.com

### 徽标位置

顶栏

### 内容方向

博客板块：随笔或者水文（自我娱乐向）
微博板块：图文记录生活感悟

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by linlinzzo** [comment]
网站没有看到开往链接。
