### ISSUE TITLE
鲨鲨の小窝

### ISSUE THREAD

**Issue by KARPED1EM** [travellings-link/travellings#1287]
### 网站名称

鲨鲨の小窝

### 网站网址

https://leever.cn

### 徽标位置

顶栏

### 内容方向

初来乍到互联网，想要用博客记录点生活的各种点滴和感悟，也许不会发表学术或者专业的知识或经验

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by HAHH9527** [comment]
贵站大部分(历史)文章均为带锁文章, 请问是出于什么考虑

**Comment by KARPED1EM** [comment]
本来我的博客是在熟人之间分享的，后来看到『开往』这个项目很想加入，但在加入这种友链互访的模式后可能由于部分文章涉及隐私不方便公开。请问加入『开往』的标准是否一定是公开文章达到20篇，若是如此，非常抱歉在没有弄清要求前就来申请了，请给我一段时间创作。另外，审核辛苦了。

**Comment by HAHH9527** [comment]
这是定下的审核标准，需要文章20篇左右，欢迎更新够文章后随时恢复申请

**Comment by KARPED1EM** [comment]
好的，我明白了，辛苦啦，issue我就先close了
