### ISSUE TITLE
雪中明月の主页

### ISSUE THREAD

**Issue by lswlc33** [travellings-link/travellings#1290]
### 网站名称

雪中明月の主页

### 网站网址

https://xn--fiqz59cpva341l.ml/

### 徽标位置

电脑：右下导航栏（手机端需要手动展开）

### 内容方向

("个人信息", "成果分享", "发癫")

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
发癫？

**Comment by linlinzzo** [comment]
[博客](http://blog.xn--fiqz59cpva341l.ml/) 没有开启https。

**Comment by lswlc33** [comment]
> [博客](http://blog.xn--fiqz59cpva341l.ml/) 没有开启https。

![Screenshot_2022-11-19-09-36-47-287_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/86835895/202827972-cafa3e5c-da90-44fc-8e96-90714ddca6e5.jpg)
现在有了
