### ISSUE TITLE
P6oy的杂货铺

### ISSUE THREAD

**Issue by leopoldfitzgithub** [travellings-link/travellings#1294]
### 网站名称

P6oy的杂货铺

### 网站网址

https://www.p6oy.top

### 徽标位置

网页中第一个bash内

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
我个人不建议音乐自动播放。

**Comment by linlinzzo** [comment]
博客文章未满 20 篇。
