### ISSUE TITLE
IT同学的数字空间

### ISSUE THREAD

**Issue by ITtongxue** [travellings-link/travellings#1295]
### 网站名称

IT同学的数字空间

### 网站网址

https://www.ittongxue.cn/

### 徽标位置

网页底部

### 内容方向

WordPress，IT技术，好玩的，有趣的

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by ITtongxue** [comment]
麻烦帮忙审核一下！谢谢啦~

**Comment by Leon-Shaw** [comment]
审核通过 等待添加

**Comment by Leon-Shaw** [comment]
不好意思，复核时界面显示“建立数据库连接时出错”，请处理异常

![Image](https://user-images.githubusercontent.com/32722099/206841599-123aec9d-8b30-4e18-ae4f-6052796d02bf.png)

**Comment by ITtongxue** [comment]
可以了 麻烦看一下

**Comment by ITtongxue** [comment]
改到侧边栏了
