### ISSUE TITLE
修改懋和道人展示位置

### ISSUE THREAD

**Issue by wulintang** [travellings-link/travellings#1297]
### 网站名称

懋和道人

### 网站网址

https://www.lizhichen.cn

### 徽标位置

侧栏

### 内容方向

李懋和，俗名李栋梁。内地著名上清茅山宗道士，书法、国画爱好者，优秀的互联网安全与前端建设者。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
