### ISSUE TITLE
风铃扬音

### ISSUE THREAD

**Issue by zilinshisi** [travellings-link/travellings#1299]
### 网站名称

开往

### 网站网址

https://www.ling71.cn/

### 徽标位置

顶栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
