### ISSUE TITLE
ssstab

### ISSUE THREAD

**Issue by kongkongye** [travellings-link/travellings#1300]
### 网站名称

ssstab

### 网站网址

https://ssstab.com

### 徽标位置

右上角

### 内容方向

网络书签，在线导航。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
已交由其他人审核。

**Comment by HAHH9527** [comment]
开往更需要的是一些文字内容，或者工具集合的分享型网站，不太适合这种初始页站点
