### ISSUE TITLE
兔儿轩の小破站

### ISSUE THREAD

**Issue by rabbitxuanxuan** [travellings-link/travellings#1301]
### 网站名称

兔儿轩の小破站

### 网站网址

https://tuerxuan.com

### 徽标位置

右侧侧栏，底部

### 内容方向

建站方面
小提示：以前开往收录了，但是域名改了后缀，且之前的文章丢失，但新博客又写了20篇

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
移交其他人审核。

**Comment by HAHH9527** [comment]
#1296 无需重复提交申请
