### ISSUE TITLE
Iceの小站

### ISSUE THREAD

**Issue by Wangyuxuan08** [travellings-link/travellings#1305]
### 网站名称

Iceの小站

### 网站网址

https://081113.xyz/

### 徽标位置

首页导航栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by HAHH9527** [comment]
可以再多更新一些文章后再来申请
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）

**Comment by Wangyuxuan08** [comment]
ok啊，现在呢，写了点有意义的内容了

**Comment by Leon-Shaw** [comment]
您的网页不满足：
1、网页已有较多内容（建议20篇以上，已持续更新一段时间）；

**Comment by Wangyuxuan08** [comment]
再次申请

**Comment by linlinzzo** [comment]
文章数量没有达到 20 篇。
