### ISSUE TITLE
alpacabro

### ISSUE THREAD

**Issue by alpacabro233** [travellings-link/travellings#1306]
### 网站名称

alpacabro

### 网站网址

https://www.alpacabro.com

### 徽标位置

侧栏

### 内容方向

分享自己在生活中的点滴快乐，在折腾时的经验与教训，以及一些碎碎念。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by HAHH9527** [comment]
审核通过，等待添加

**Comment by Leon-Shaw** [comment]
复核时，无法访问，请排除故障 @alpacabro233 

![Image](https://user-images.githubusercontent.com/32722099/206841835-f9166c54-60b4-419b-a7a0-4e798fd2bc9e.png)

**Comment by alpacabro233** [comment]
不好意思，之前备案临时关闭访问，忘记重新开启了……
已经恢复访问，请重新审核，谢谢

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by alpacabro233** [comment]
已经更新，不过CDN缓存刷新可能需要一点时间，感谢理解。

**Comment by alpacabro233** [comment]
顺便一提，Readme 需要更新，并且 data.travellings.link 和 status.travellings.link 目前访问提示 Host Error

**Comment by linlinzzo** [comment]
> 顺便一提，Readme 需要更新，并且 data.travellings.link 和 status.travellings.link 目前访问提示 Host Error

已经提交PR了。
