### ISSUE TITLE
醉里

### ISSUE THREAD

**Issue by xiaohao8** [travellings-link/travellings#1307]
### 网站名称

醉里博客

### 网站网址

https://202271.xyz

### 徽标位置

顶栏，底部

### 内容方向

分享生活，并尽我自己的微薄之力帮助互联网爱好者解决一些我会的问题。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by HAHH9527** [comment]
可以再多更新一些文章后再来申请
> 网页已有较多内容（建议20篇以上，已持续更新一段时间）

**Comment by xiaohao8** [comment]
OK，谢谢了，我再丰富一下

**Comment by xiaohao8** [comment]
博客内容已经符合要求。希望及时处理，谢谢。

**Comment by linlinzzo** [comment]
https://202271.xyz/post/16107/
https://202271.xyz/post/41343/
这两个不算有效文章。

**Comment by linlinzzo** [comment]
已交由组里其他人审核。

**Comment by MYXXTS** [comment]
有效文章过于少，请认真更新内容再次申请，感谢对开往的支持

**Comment by xiaohao8** [comment]
博客已认真完善，请认真审核！

**Comment by xiaohao8** [comment]
1
