### ISSUE TITLE
小小的小

### ISSUE THREAD

**Issue by lz732895965** [travellings-link/travellings#1309]
### 网站名称

小小的小

### 网站网址

https://www.one21.cn

### 徽标位置

顶部菜单

### 内容方向

分享生活的小站

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by HAHH9527** [comment]
审核通过 等待添加

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
