### ISSUE TITLE
#349 修改标题及链接

### ISSUE THREAD

**Issue by icecliffs** [travellings-link/travellings#1315]
### 网站名称

rYu1nser's Blog

### 网站网址

https://iloli.moe

### 徽标位置

顶部

### 内容方向

编号#349 修改标题及链接，原域名已做跳转。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Leon-Shaw** [comment]
审核通过 等待修改

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
