### ISSUE TITLE
木子李

### ISSUE THREAD

**Issue by LevnLi** [travellings-link/travellings#1319]
### 网站名称

木子李

### 网站网址

https://blog.levnli.cn

### 徽标位置

顶部

### 内容方向

java开发，技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Leon-Shaw** [comment]
审核通过 等待添加

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by LevnLi** [comment]
已同步变更



木子李
 
发件人： 林林
发送时间： 2023-01-03 11:28
收件人： travellings-link/travellings
抄送： LevnLi; Author
主题： Re: [travellings-link/travellings] 木子李 (Issue #1319)
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg
请您及时更换相关地址，谢谢配合。
