### ISSUE TITLE
小朊的朋友圈

### ISSUE THREAD

**Issue by xiaoruan0** [travellings-link/travellings#1320]
### 网站名称

小朊的朋友圈

### 网站网址

https://www.xrpyq.com

### 徽标位置

侧栏 与网页底部

### 内容方向

目前希望分享一些技术类的 但是主要是分享生活的点滴

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Leon-Shaw** [comment]
审核通过 等待添加

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
