### ISSUE TITLE
Z_Tsin的小站

### ISSUE THREAD

**Issue by ztsinsun** [travellings-link/travellings#1321]
### 网站名称

Z_Tsin's Blog

### 网站网址

https://blog.ztsin.cn

### 徽标位置

底部

### 内容方向

有关我的生活以及科技方面的探讨或教程

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Leon-Shaw** [comment]
您的网页不满足：网页已有较多内容（建议20篇以上，已持续更新一段时间）；未找到开往外链，
