### ISSUE TITLE
阳光下的小宁宁

### ISSUE THREAD

**Issue by ning0818** [travellings-link/travellings#1323]
### 网站名称

阳光下的小宁宁

### 网站网址

https://www.yuanning0818.tk

### 徽标位置

侧边栏和和和和和和和和和和默认收起的菜单里

### 内容方向

各种

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by ning0818** [comment]
算了，你们太慢了，我自己加吧

**Comment by ning0818** [comment]
PR申请已提交，合并后即可生效

**Comment by ning0818** [comment]
> PR申请已提交，合并后即可生效

![image](https://user-images.githubusercontent.com/117955401/206839420-0a644431-170b-4072-a59a-0a6a6b99325e.png)

**Comment by Leon-Shaw** [comment]
审核通过 等待添加
