### ISSUE TITLE
菜鸟博客

### ISSUE THREAD

**Issue by cainiaoapi** [travellings-link/travellings#1325]
### 网站名称

菜鸟博客

### 网站网址

https://ruyun.tk/

### 徽标位置

底部

### 内容方向

一个00后站长...
期待与更多人相遇

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Leon-Shaw** [comment]
审核通过，等待添加。
还请处理下外链位置，光底部的话不是很好让游客接力下去的
> 将 开往 的外链（https://travellings.link），加入您的顶栏导航或侧栏导航中，便于访客看到并点击：

**Comment by cainiaoapi** [comment]
更换域名
https://blog.caiu.top/

**Comment by cainiaoapi** [comment]
更换域名
https://blog.caiu.top/

**Comment by cainiaoapi** [comment]
更换域名
https://blog.caiu.top/
