### ISSUE TITLE
湘铭呀！

### ISSUE THREAD

**Issue by fxm0402** [travellings-link/travellings#1330]
### 网站名称

湘铭呀！

### 网站网址

https://www.xiangming.site

### 徽标位置

侧栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by fxm0402** [comment]
阳了，有问题可能不能第一时间知道，给留个空，谢谢

**Comment by fxm0402** [comment]
我回来啦！

**Comment by linlinzzo** [comment]
文章内容太水。

**Comment by fxm0402** [comment]
这这这，博客就是记录生活啊！

**Comment by fxm0402** [comment]
有生活，有技术啊

**Comment by linlinzzo** [comment]
> 这这这，博客就是记录生活啊！

您一天发了多少篇文章？每一篇文章都是用心写的吗？

**Comment by fxm0402** [comment]
最多的时候是3篇啊，有感而发啊

**Comment by linlinzzo** [comment]
我推给别人看吧。

**Comment by fxm0402** [comment]
好的，麻烦了

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by fxm0402** [comment]
谢谢

**Comment by fxm0402** [comment]
抱歉，顶级域名出现了问题。换个二级域名，blog.xiangming.site  麻烦了，谢谢！

**Comment by fxm0402** [comment]
抱歉，顶级域名出现了问题。换个二级域名，blog.xiangming.site 麻烦了，谢谢！@linlinzzo @essesoul @imba97 麻烦了，各位大佬们
