### ISSUE TITLE
长江南北青

### ISSUE THREAD

**Issue by ymckc** [travellings-link/travellings#1332]
### 网站名称

长江南北青

### 网站网址

https://ymckc.cn

### 徽标位置

侧栏

### 内容方向

本站用于分享个人感想以及技术经验

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
一个视频？

**Comment by linlinzzo** [comment]
没有看见开往链接。

**Comment by linlinzzo** [comment]
刚刚看错了，对不起。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/80921dba-af91-404f-b680-bf011284ba51)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
