### ISSUE TITLE
星空博客（原星云馆 第30号）请求更新信息

### ISSUE THREAD

**Issue by MarikoAsian** [travellings-link/travellings#1333]
### 网站名称

星空博客

### 网站网址

https://blog.m78.co

### 徽标位置

顶栏,底部

### 内容方向

博客，IT、生活、心得的分享。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by MarikoAsian** [comment]
因为没有更新信息的issue，所以我发在这里了，如有打扰，抱歉

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
