### ISSUE TITLE
帆帆的小破站

### ISSUE THREAD

**Issue by mangofanfan** [travellings-link/travellings#1336]
### 网站名称

帆帆的小破站

### 网站网址

https://www.fancraft.top

### 徽标位置

顶栏（鼠标移动后直接显示），侧栏（需点击切换），底栏（直接显示）

### 内容方向

学校生活，学习过程，兴趣爱好，所思所想，还有一些乱写的小玩意儿（

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量未满 20 篇。（好像出事了？）

**Comment by linlinzzo** [comment]
关于最近一篇文章，建议看一看 https://www.bilibili.com/video/BV14K4y1m7hW/ 。

**Comment by mangofanfan** [comment]
雀食出事故力，本来是有十几篇的TT
然后因为服务器那边的问题（还因为我那几天没放假一直在补课）导致没来得及恢复数据，莫得了（
其实都是想到哪写到哪，我这个高中牲非常随性的▽
