### ISSUE TITLE
冬天的小窝

### ISSUE THREAD

**Issue by inwinter04** [travellings-link/travellings#1338]
### 网站名称

冬天的小窝

### 网站网址

https://www.iamdt.cn/

### 徽标位置

右固定侧栏友链第一  左侧栏    

### 内容方向

分享技术教程以及程序员各类薅羊毛教程。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by inwinter04** [comment]
由于近期域名提交到当局进行备案，目前已暂时关闭解析。预计1.3前完成备案。

**Comment by inwinter04** [comment]
备案已完成，网站已恢复访问

**Comment by linlinzzo** [comment]
你还有一些图片没搬过来吧？比如又拍云的

**Comment by linlinzzo** [comment]
到国内就要稍微注意一下版权的问题了。

**Comment by inwinter04** [comment]
> 你还有一些图片没搬过来吧？比如又拍云的

确实是这样，备案号今天才下来的。国内的对象存储以及CDN还没有配置。
关于版权问题目前博客文章内多数都是原创，剩余的是经过作者同意后才转载搬运的。
分享的程序这些大多都是Github开源程序。

**Comment by linlinzzo** [comment]
https://me.iamdt.cn/ 访问不了，导致网站页面显示异常，请修复。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by inwinter04** [comment]
> 审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

了解

**Comment by linlinzzo** [comment]
赶紧修复啊

**Comment by inwinter04** [comment]
> https://me.iamdt.cn/ 访问不了，导致网站页面显示异常，请修复。

我这边深圳访问一切正常，清除浏览器缓存也正常。正在排查问题

**Comment by linlinzzo** [comment]
> 我这边深圳访问一切正常，清除浏览器缓存也正常。正在排查问题

泉州这边访问海外网站有白名单。

**Comment by inwinter04** [comment]
> > 我这边深圳访问一切正常，清除浏览器缓存也正常。正在排查问题
> 
> 泉州这边访问海外网站有白名单。

稍后我把网站静态资源都迁移到腾讯云COS上

**Comment by inwinter04** [comment]
> > 我这边深圳访问一切正常，清除浏览器缓存也正常。正在排查问题
> 
> 泉州这边访问海外网站有白名单。

大部分静态资源已迁移到腾讯云

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by inwinter04** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
> 
> gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg
> 
> 请您及时更换相关地址，谢谢配合。

已更改。
