### ISSUE TITLE
Rainogo's Blog(原Godapex）修改信息

### ISSUE THREAD

**Issue by GodApex** [travellings-link/travellings#1339]
### 网站名称

Rainogo's Blog

### 网站网址

https://www.rainogo.com/

### 徽标位置

顶栏

### 内容方向

我的生活与技术教程

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请提供一下网站id。

**Comment by GodApex** [comment]
330 | ERROR | Godapex | https://www.godapex.com

**Comment by GodApex** [comment]
在下线列表里面

**Comment by essesoul** [comment]
文章是不是有点少了

**Comment by GodApex** [comment]
那以后我再申请吧😂上次忘记备份了
