### ISSUE TITLE
MUKAPP

### ISSUE THREAD

**Issue by MUKAPP** [travellings-link/travellings#1340]
### 网站名称

MUKAPP

### 网站网址

https://www.mukapp.top

### 徽标位置

顶栏和网页底部

### 内容方向

分享网站维护经验、一些安卓软件和好用的网站什么的

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量未满 20 篇。

**Comment by MUKAPP** [comment]
啊这，，那我之后再申请吧

**Comment by MUKAPP** [comment]
> 文章数量未满 20 篇。

可以了
