### ISSUE TITLE
工作笔记

### ISSUE THREAD

**Issue by dzsdbsdxq** [travellings-link/travellings#1346]
### 网站名称

工作笔记

### 网站网址

https://www.haoba.cc/

### 徽标位置

顶栏

### 内容方向

分享工作前端和全栈技术、行业视野、技巧总结，个人生活，养成记录和分享的习惯。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
推荐在网页的底部也添加开往链接。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by dzsdbsdxq** [comment]
已在底部添加svg的logo
