### ISSUE TITLE
InfinitySpace

### ISSUE THREAD

**Issue by SuperLangdon** [travellings-link/travellings#1348]
### 网站名称

InfinitySpace

### 网站网址

https://blog.langdon.one/

### 徽标位置

顶栏

### 内容方向

分享内容，个人的所见所闻所感、翻译、填词等。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by linlinzzo** [comment]
文章数量未满 20 篇。
