### ISSUE TITLE
YongeChanの小屋

### ISSUE THREAD

**Issue by ChanYiCYJ** [travellings-link/travellings#1353]
### 网站名称

YongeChanの小屋

### 网站网址

https://yongechan.site

### 徽标位置

网页底部（如果建议放置于菜单等通过在说）

### 内容方向

博客发展
个人喜欢写一些形形色色的文章，一些简单的动漫杂谈和生活记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量过少。
