### ISSUE TITLE
Guqing's Blog 状态有误申请恢复

### ISSUE THREAD

**Issue by guqing** [travellings-link/travellings#1355]
### 网站名称

Guqing's Blog

### 网站网址

https://guqing.xyz

### 徽标位置

网页底部

### 内容方向

27 | QUIT | Guqing's Blog | https://guqing.xyz
-- | -- | -- | --

网站状态有误，请求恢复，开往图标在站点底部，且站点状态正常并未主动申请退出。

注：站点主题属于首页可以看完全貌的风格，且顶部菜单不适合放图标，因此开往 logo 放在底部，依然可以很直观看到，如有不妥我可以添加一个文字菜单，但菜单不会放 logo。

related  https://github.com/travellings-link/travellings/issues/23

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
网站调用的travellings.js过旧，请更新或将地址换为 https://www.travellings.cn/assets/travelling.js

**Comment by linlinzzo** [comment]
https://github.com/travellings-link/travellings/commit/88982d4abe2b8b047561360727f5bd037dd069f6
当时下链的原因是找不到开往的链接。

**Comment by guqing** [comment]
> [88982d4](https://github.com/travellings-link/travellings/commit/88982d4abe2b8b047561360727f5bd037dd069f6) 当时下链的原因是找不到开往的链接。

感谢回复，已修改，或许是由于之前这个地址加载太慢我使用了同步维护的 travelling.js 导致检测不到，现已恢复，麻烦重新审核一下 🥳
