### ISSUE TITLE
六花丶紫

### ISSUE THREAD

**Issue by amber6hua** [travellings-link/travellings#1356]
### 网站名称

六花丶紫

### 网站网址

https://amber6hua.github.io/

### 徽标位置

顶部和侧栏

### 内容方向

分享个人遇到的技术问题

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
你能写一个关于页面吗？

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by amber6hua** [comment]
> 你能写一个关于页面吗？

是什么页面

**Comment by linlinzzo** [comment]
> 是什么页面

关于自己和这个博客网站的，相当于自我介绍。

**Comment by amber6hua** [comment]
> 

噢噢，可以，明天整个
