### ISSUE TITLE
浪铭的博客

### ISSUE THREAD

**Issue by weimin1992** [travellings-link/travellings#1358]
### 网站名称

浪铭的博客

### 网站网址

https://porridge.fun/blog/

### 徽标位置

顶栏

### 内容方向

技术文章，包括解决问题的方法、技术使用手册等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
能把这个弄到根目录吗？

**Comment by linlinzzo** [comment]
文章数量过少。

**Comment by weimin1992** [comment]
> 能把这个弄到根目录吗？

我设置为根目录自动跳转/blog可以吗？

**Comment by weimin1992** [comment]
> 文章数量过少。

今年会定期更新文章，将博客内容丰富起来😊

**Comment by weimin1992** [comment]
> > 能把这个弄到根目录吗？
> 
> 我设置为根目录自动跳转/blog可以吗？

目前已设置根域名自动跳转/blog子路由
