### ISSUE TITLE
echeverra

### ISSUE THREAD

**Issue by echeverra** [travellings-link/travellings#1359]
### 网站名称

echeverra

### 网站网址

https://echeverra.cn/

### 徽标位置

顶栏

### 内容方向

工作生活记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
这个开往的地址是旧的

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by echeverra** [comment]
已修改为最新的开往地址~
