### ISSUE TITLE
兔say博客

### ISSUE THREAD

**Issue by rabbitxuanxuan** [travellings-link/travellings#1361]
### 网站名称

兔say博客

### 网站网址

https://blog.rabbitwebs.cn

### 徽标位置

底部，顶部（都是文字超链接）

### 内容方向

测评各路博客源码，一些教程之类的
原来的博客：tuerxuan.com
觉得以前的博客很水，就从头开始了

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请将开往链接严格指向 https://www.travellings.cn/go.html ，谢谢。

**Comment by rabbitxuanxuan** [comment]
e，主题不能直接设置啊
我试试

**Comment by linlinzzo** [comment]
网站尚未加入开往，拨打电话无人接听。开往成员权益申请驳回。
