### ISSUE TITLE
慕雪的寒舍

### ISSUE THREAD

**Issue by Aewait** [travellings-link/travellings#1363]
### 网站名称

慕雪的寒舍

### 网站网址

https://blog.outpost54.top/

### 徽标位置

底栏的travelling  logo

### 内容方向

我的代码学习博客&工具使用教程

网站使用hexo+github+netlify部署，访问速度应该是很快的。后续若域名有变化会及时来更新~

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
已移交给组里其他人审核。

**Comment by Aewait** [comment]
图标从顶栏移动到了底栏，感谢审核！

**Comment by qystudio0** [comment]
> 图标从顶栏移动到了底栏，感谢审核！

这是不符合要求的，我们要求在导航栏或者侧边栏中加入开往的链接

**Comment by Aewait** [comment]
> > 图标从顶栏移动到了底栏，感谢审核！
> 
> 这是不符合要求的，我们要求在导航栏或者侧边栏中加入开往的链接

已修改，麻烦重新审核

**Comment by qystudio0** [comment]
审核通过待添加

**Comment by musnows** [comment]
域名更新 https://blog.musnow.top/

**Comment by baipin** [comment]
完工。
