### ISSUE TITLE
一蓑烟雨的博客

### ISSUE THREAD

**Issue by easyf12** [travellings-link/travellings#1364]
### 网站名称

一蓑烟雨的博客

### 网站网址

https://easyf12.top

### 徽标位置

网页底部菜单

### 内容方向

生活，思想。

附：本博之前加入过此项目，由于原链接一段时间内无法访问，遂在公安部的建议下去掉此功能。现看见域名更改了，便回归，希望通过，谢谢。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by easyf12** [comment]
> 审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

好的，谢谢。

**Comment by linlinzzo** [comment]
建议在更加显眼的位置放置开往链接，并推荐使用开往LOGO。
