### ISSUE TITLE
他和她的故事

### ISSUE THREAD

**Issue by wangdong618** [travellings-link/travellings#1370]
### 网站名称

他和她的故事

### 网站网址

https://taheta.ren

### 徽标位置

侧栏

### 内容方向

His and her stories

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请在更加明显的位置添加开往链接，并推荐使用开往LOGO。我一时间找不到开往在哪里。😅

**Comment by wangdong618** [comment]
你好就在首页左侧边栏啊  估计是我使用自制图标你才找不到

**Comment by wangdong618** [comment]
首页边栏 传送 图标都在那里 是贵站不接受自定图标吗？

**Comment by linlinzzo** [comment]
图标不够明显···

**Comment by linlinzzo** [comment]
在[README](https://github.com/travellings-link/travellings#%E5%BC%80%E5%BE%80%E7%90%86%E8%AE%BA%E4%B8%8A%E8%83%BD%E5%A2%9E%E5%8A%A0%E7%BD%91%E9%A1%B5%E7%9A%84%E6%B5%81%E9%87%8F)有`建议将开往的徽标放在您网页明显位置（推荐顶栏，侧栏）`一条。

**Comment by wangdong618** [comment]
https://taheta.ren/t/1.jpg 都带闪动特效的 难道不够明显？

**Comment by wangdong618** [comment]
https://taheta.ren/t/111.jpg

**Comment by linlinzzo** [comment]
建议以开往的徽标为素材设计自己的图标。

**Comment by wangdong618** [comment]
https://taheta.ren/t/kw.gif 已经用开往素材修改了

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by wangdong618** [comment]
好的谢谢https://taheta.ren/t/1111111.jpg

**Comment by HowieHz** [comment]
站长您好

您的域名根据我们的核查，已大致确定您的域名已到期并进入赎回期。

我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。

![Image](https://github.com/user-attachments/assets/1d9dda65-d4ac-4849-9b14-724378acb499)
