### ISSUE TITLE
Jack's Space

### ISSUE THREAD

**Issue by very-jack** [travellings-link/travellings#1371]
### 网站名称

Jack's Space

### 网站网址

https://veryjack.com/

### 徽标位置

顶部导航栏 侧边栏

### 内容方向

生活、摄影、折腾笔记、学习笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
