### ISSUE TITLE
Another Dayu

### ISSUE THREAD

**Issue by DayuGuo** [travellings-link/travellings#1372]
### 网站名称

Another Dayu

### 网站网址

https://anotherdayu.com/

### 徽标位置

顶部导航栏

### 内容方向

走来走去，路上观察，街头摄影。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @DayuGuo
