### ISSUE TITLE
申请友链

### ISSUE THREAD

**Issue by Rhys1024** [travellings-link/travellings#1373]
### 网站名称

Rhys Wang's Blog -知足得以常乐

### 网站网址

https://www.nuyoahbk.com/

### 徽标位置

顶栏和左侧栏

### 内容方向

分享一些软件和个人学习编程的日记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
你的开往徽标引用的是哪个地址？

**Comment by Rhys1024** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by linlinzzo** [comment]
推荐使用`https://www.travellings.cn/assets/`上的图片。

**Comment by Rhys1024** [comment]
https://www.travellings.cn/assets/链接显示403

**Comment by Rhys1024** [comment]
已经修改好了




铭焱
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 晚上9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 申请友链 (Issue #1373)





 
推荐使用https://www.travellings.cn/assets/上的图片。

**Comment by linlinzzo** [comment]
https://www.travellings.cn/assets/logo.gif
https://www.travellings.cn/assets/b.png
https://www.travellings.cn/assets/w.png
一些可以选用的LOGO

**Comment by Rhys1024** [comment]
顶部非要用长图嘛？


按照示例给出的不行嘛？


铭焱
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 申请友链 (Issue #1373)





 
https://www.travellings.cn/assets/logo.gif
 https://www.travellings.cn/assets/b.png
 https://www.travellings.cn/assets/w.png
 一些可以选用的LOGO

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
