### ISSUE TITLE
Sh1zuku的小屋

### ISSUE THREAD

**Issue by KawaiiSh1zuku** [travellings-link/travellings#1375]
### 网站名称

Sh1zuku的小屋

### 网站网址

https://9941y.top/

### 徽标位置

侧栏

### 内容方向

网络安全的工作日志和一些自己的小研究

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
已交由组里其他人审核。

**Comment by qystudio0** [comment]
请问贵站是遭受攻击了吗，如无请不要长时间开启waf截拦
贵站截拦了我的正常访问，无法加入审核

**Comment by KawaiiSh1zuku** [comment]
已关闭waf

**Comment by qystudio0** [comment]
请文章数量达到20篇时再申请
