### ISSUE TITLE
Kloudy Shape

### ISSUE THREAD

**Issue by EndersKim** [travellings-link/travellings#1378]
### 网站名称

Kloudy Shape

### 网站网址

https://shape.kloudy.cn

### 徽标位置

顶栏

### 内容方向

分享学习经验、生活经历等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
