### ISSUE TITLE
语冰

### ISSUE THREAD

**Issue by louisfiy** [travellings-link/travellings#1384]
### 网站名称

语冰

### 网站网址

https://louisfiy.com/

### 徽标位置

顶栏

### 内容方向

随心所记：宇宙、生命，以及一切。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
