### ISSUE TITLE
摸鱼屋

### ISSUE THREAD

**Issue by MutBlackTea** [travellings-link/travellings#1386]
### 网站名称

摸鱼屋

### 网站网址

https://moyu233.top/

### 徽标位置

网页顶栏

### 内容方向

有趣的好玩的
生活闲事
技术、学习笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
