### ISSUE TITLE
兔say博客

### ISSUE THREAD

**Issue by rabbitxuanxuan** [travellings-link/travellings#1388]
### 网站名称

兔say博客

### 网站网址

blog.rabbitwebs.cn

### 徽标位置

底部，顶部

### 内容方向

测评类型
然后……建站，知识？

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
已移交给组里其他人审核。

**Comment by MYXXTS** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。
