### ISSUE TITLE
Jelly27th's Blog

### ISSUE THREAD

**Issue by jelly27th** [travellings-link/travellings#1389]
### 网站名称

Jelly27th's Blog

### 网站网址

https://www.dong27th.cn/

### 徽标位置

顶栏与右侧栏

### 内容方向

分享知识与生活
学习技术和记录折腾过程

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
可以优化一下网页的加载速度吗？页面是显示出来了，但文章内容没显示出来。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by jelly27th** [comment]
我自己没感觉太大问题，不过，我会取尽力优化的。

**Comment by jelly27th** [comment]
> 可以优化一下网页的加载速度吗？页面是显示出来了，但文章内容没显示出来。

我自己使用时没啥太大感觉，不过，有时间我会去测试一下网站加载速度，尽可能优化的
