### ISSUE TITLE
Karl's Blog

### ISSUE THREAD

**Issue by karltan0328** [travellings-link/travellings#1391]
### 网站名称

Karl's Blog

### 网站网址

https://karl-blog.top/

### 徽标位置

顶栏

### 内容方向

自己的学习记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您的网站不符合以下条件：

- 网页已有较多内容（应有20篇文章或10篇原创文章，**需要已持续更新一段时间**）；

**Comment by karltan0328** [comment]
> 您的网站不符合以下条件：
> 
> 
> 
> - 网页已有较多内容（应有20篇文章或10篇原创文章，**需要已持续更新一段时间**）；

您好，请问这个一段时间具体是多久呢？

我这个博客是新搭的，之前已经在hexo上更新过一段时间了。

**Comment by qystudio0** [comment]
1.请问https://www.zhihu.com/people/san-shao-ye-de-jian-37这是您吗，如果不是那么贵站的原创的文章只有两篇，其余都是转载
2.运营一段时间指的是超过两个月，而不是两天
故我们解决了你的申请

**Comment by karltan0328** [comment]
> 1.请问https://www.zhihu.com/people/san-shao-ye-de-jian-37这是您吗，如果不是那么贵站的原创的文章只有两篇，其余都是转载
> 2.运营一段时间指的是超过两个月，而不是两天
> 故我们解决了你的申请

1.这个不是我

2.好的，感谢！
