### ISSUE TITLE
Morii

### ISSUE THREAD

**Issue by Oliyrs** [travellings-link/travellings#1392]
### 网站名称

Morii

### 网站网址

https://www.morii.club/

### 徽标位置

🚩其他：底部

### 内容方向

个人学习内容，生活分享。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
将开往放到您网页打开后就能看到的地方

**Comment by linlinzzo** [comment]
https://blog.morii.club/ 没有看到开往链接

**Comment by Oliyrs** [comment]
因为主题有点小问题，修改了一下配置文件。https://blog.morii.club/已添加开往链接，如图所示：https://i.imgtg.com/2023/01/15/QypMY.png 
https://i.imgtg.com/2023/01/15/QyJ7v.png
申请添加博客链接。

**Comment by Oliyrs** [comment]
已重新提交issue，申请通过。

**Comment by A7103** [comment]
Duplicate with https://github.com/travellings-link/travellings/issues/1394 
Close this issue, and please use the new issue, Thank you.
