### ISSUE TITLE
Morii'Blog

### ISSUE THREAD

**Issue by Oliyrs** [travellings-link/travellings#1394]
### 网站名称

Morii'Blog

### 网站网址

https://blog.morii.club

### 徽标位置

侧栏

### 内容方向

个人学习经验，记录生活。开往链接如图：https://i.imgtg.com/2023/01/15/QyJ7v.png
https://i.imgtg.com/2023/01/15/QypMY.png

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
已交由组内其他人审核。

**Comment by A7103** [comment]
https://github.com/travellings-link/travellings/issues/1392#issuecomment-1383107225

**Comment by A7103** [comment]
文章数量有点少，可以再多写一些
