### ISSUE TITLE
JacobZ的博客

### ISSUE THREAD

**Issue by cmpute** [travellings-link/travellings#1396]
### 网站名称

JacobZ的博客

### 网站网址

https://zyxin.xyz/blog/

### 徽标位置

左侧导航栏上方

### 内容方向

技术知识、技术思考

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
已交由组内其他人审核。

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by cmpute** [comment]
any updates?

**Comment by Big-Cake-jpg** [comment]
很抱歉这么久才让您知道最终的审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<

**Comment by linlinzzo** [comment]
正在将网站添加到开往，请稍后。
