### ISSUE TITLE
zd小达's blog

### ISSUE THREAD

**Issue by zdxiaoda** [travellings-link/travellings#1397]
### 网站名称

zd小达's blog

### 网站网址

https://blog.zhangda.xyz/

### 徽标位置

侧栏和底栏

### 内容方向

在博客主要发布科技类文章~

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
你是高一吗？

**Comment by zdxiaoda** [comment]
> 你是高一吗？

高二(～￣▽￣)～

**Comment by linlinzzo** [comment]
我感觉我在十年之约那看到过你。

**Comment by zdxiaoda** [comment]
> 我感觉我在十年之约那看到过你。

我博客底部还有虫洞♪(´▽｀)

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
> 我博客底部还有虫洞♪(´▽｀)

那就是朋友了，欢迎来到开往。

**Comment by zdxiaoda** [comment]
> > 我博客底部还有虫洞♪(´▽｀)
> 
> 那就是朋友了，欢迎来到开往。

好耶👏👏👏
