### ISSUE TITLE
写bug的代码人

### ISSUE THREAD

**Issue by 1stbugcoder** [travellings-link/travellings#1399]
### 网站名称

写bug的代码人

### 网站网址

https://bugcoder.gq/

### 徽标位置

顶栏与网页底部

### 内容方向

编程知识，前端开发，网站运维

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
跳转到 http://bugcoder.gq/ ？

**Comment by 1stbugcoder** [comment]
> 跳转到 http://bugcoder.gq/ ？

如果可以的话，最好跳转到https://1stbugcoder.github.io/，因为这个域名一直有效，要比bugcoder.gq这个免费域名稳定

**Comment by linlinzzo** [comment]
已移交给组里其他人审核。

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
请检查 bugcoder.gq 是否支持 HTTPS，如果支持请将 https://1stbugcoder.github.io/ 的重定向修改为 HTTPS 的版本，谢谢。

**Comment by linlinzzo** [comment]
每篇文章的内容偏少，扣除公告后文章数量也就十来篇。要加油啊。

**Comment by linlinzzo** [comment]
每篇文章的内容偏少，扣除公告后文章数量也就十来篇。要加油啊。

**Comment by 1stbugcoder** [comment]
> 请检查 bugcoder.gq 是否支持 HTTPS，如果支持请将 https://1stbugcoder.github.io/ 的重定向修改为 HTTPS 的版本，谢谢。
我这里一直是HTTPS呀，您能再看一下吗？谢谢（截图邮箱发您）

**Comment by 1stbugcoder** [comment]
> 每篇文章的内容偏少，扣除公告后文章数量也就十来篇。要加油啊。

好的，我会尽力多写一点的👌
不过扣除公告[temp.html](https://bugcoder.gq/article/temp.html)后，一共有从[001.html](https://bugcoder.gq/article/001.html)到[012.html](https://bugcoder.gq/article/012.html)十二篇文章（确实看起来没几篇）

**Comment by linlinzzo** [comment]
我们正在将您的网站添加到开往，请稍后。
