### ISSUE TITLE
栖迟於一丘-申请

### ISSUE THREAD

**Issue by linnyh** [travellings-link/travellings#1406]
### 网站名称

栖迟於一丘

### 网站网址

https://www.ccyh.xyz

### 徽标位置

顶栏，网页底部

### 内容方向

技术学习笔记，生活随笔。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
请将链接指向 https://www.travellings.cn/go.html 。

**Comment by linlinzzo** [comment]
可以在搜索引擎中搜到大量相似结果的文章：

https://www.ccyh.xyz/index.php/yhlin/%e6%b7%b1%e5%ba%a6%e5%ad%a6%e4%b9%a0/189/
https://www.ccyh.xyz/index.php/yhlin/%e6%b7%b1%e5%ba%a6%e5%ad%a6%e4%b9%a0/186/
似乎【Pytorch基础】都能搜到。

**Comment by linnyh** [comment]
因为之前是用hexo建站过，搜索引擎收录过。

**Comment by linlinzzo** [comment]
我们正在处理您的申请，请稍后。

**Comment by gxres042** [comment]
站长您好，您的站点出现了国内网络无法访问的情况：

![图片](https://github.com/travellings-link/travellings/assets/53113178/0198f4b7-7a9b-4ca9-95e5-f2823e9da28a)

烦请检查您的站点的 SSL 相关配置。

**Comment by Big-Cake-jpg** [comment]
超时关闭。如有需要可重新提交 Issue 申请。

**Comment by HowieHz** [comment]
发现遗留未删除项目，域名已过期，已补删
