### ISSUE TITLE
SKYRE NOTE

### ISSUE THREAD

**Issue by huishaojun** [travellings-link/travellings#1413]
### 网站名称

SKYRE NOTE

### 网站网址

https://www.skyre.cn/

### 徽标位置

桌面端顶栏右侧，移动端顶栏右侧展开工具栏中

### 内容方向

分享学习成果，记录美好生活，个人也为数码爱好者，博客内容主要是玩机经验、开发笔记、实用技术等方向，均为原创文章（基本与酷安同步），文章会缓更，但不会不更，博客已经有大概一年的时间，最近才发现这个项目，想加入大家，谢谢

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
达达利亚？⚪？

**Comment by linlinzzo** [comment]
**建议**开启 HSTS，并将网站添加到 Preload List。

**Comment by linlinzzo** [comment]
目前没有发现什么问题。建议发一点生活类的文章。

**Comment by huishaojun** [comment]
> 达达利亚？⚪？

鸭鸭单推人罢了🥰

**Comment by huishaojun** [comment]
> **建议**开启 HSTS，并将网站添加到 Preload List。

我看一下

**Comment by linlinzzo** [comment]
> 我看一下

Preload List 的提交链接：https://hstspreload.org/

**Comment by huishaojun** [comment]
> **建议**开启 HSTS，并将网站添加到 Preload List。

已为博客站添加对应的响应标头，但PreloadList暂缓，因子域名有需使用http协议的服务

![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b6bb1d0441fb430c9c33fdf56245e411~tplv-k3u1fbpfcp-zoom-1.image)

**Comment by Big-Cake-jpg** [comment]
3 月 12 日复核时，移动端未找到开往外链。

**Comment by huishaojun** [comment]
> 3 月 12 日复核时，移动端未找到开往外链。

一直在顶部菜单栏中
![image](https://user-images.githubusercontent.com/31238038/224525813-91828d43-44f6-427b-a56b-7191c199a60e.png)

**Comment by linlinzzo** [comment]
我让另外一位组员复查一下，请稍后。

**Comment by Big-Cake-jpg** [comment]
喔，在右侧的折叠菜单里啊，那没事了。
