### ISSUE TITLE
字节君的思想宇宙

### ISSUE THREAD

**Issue by Bytelv** [travellings-link/travellings#1414]
### 网站名称

字节君的思想宇宙

### 网站网址

https://blog.lvbyte.top/

### 徽标位置

侧栏

### 内容方向

我的生活，学习经历以及一些有意思的东西，输出有价值的信息

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
移动端没有办法发现开往链接，请安排合适位置添加，谢谢。

**Comment by linlinzzo** [comment]
另外，建议使用开往的 LOGO。

**Comment by linlinzzo** [comment]
初三？中考加油。

**Comment by linlinzzo** [comment]
请您认真阅读 README 里面的内容，谢谢。

`网页已有较多内容（应有20篇文章或10篇原创文章，需要已持续更新两个月以上，更新时间自博客第一篇内容时间开始算起）；`

**Comment by Bytelv** [comment]
> 初三？中考加油。

谢谢🙏移动端的logo应该在二级页面

**Comment by Bytelv** [comment]
> 请您认真阅读 README 里面的内容，谢谢。
> 
> `网页已有较多内容（应有20篇文章或10篇原创文章，需要已持续更新两个月以上，更新时间自博客第一篇内容时间开始算起）；`

这个博客是我去年12月新搭建的，旧博客中有文章没有迁移过来

**Comment by linlinzzo** [comment]
我们正在处理您的申请，请稍后。
