### ISSUE TITLE
平替生活

### ISSUE THREAD

**Issue by edmondsket** [travellings-link/travellings#1420]
### 网站名称

平替生活

### 网站网址

https://cheapy.top/

### 徽标位置

顶栏

### 内容方向

生活日常，技术分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
**建议**在页面底部“支持”添加开往链接。

**Comment by linlinzzo** [comment]
请尽量减少访客阅读文章的限制，

**Comment by edmondsket** [comment]
访客阅读限制已去除

**Comment by linlinzzo** [comment]
正在处理，请稍等。
