### ISSUE TITLE
Jerry Zhou的个人博客

### ISSUE THREAD

**Issue by YangguangZhou** [travellings-link/travellings#1423]
### 网站名称

Jerry Zhou的个人博客

### 网站网址

https://blog.jerryz.com.cn/

### 徽标位置

顶栏右侧倒数第三个

### 内容方向

有趣的IT、科技、信息学信息

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
https://jerry-zhou.blog.luogu.org/ 是你之前的网站吗？

**Comment by YangguangZhou** [comment]
> https://jerry-zhou.blog.luogu.org/ 是你之前的网站吗？

是的

**Comment by linlinzzo** [comment]
网站序号 732
