### ISSUE TITLE
Seraphineの小窝

### ISSUE THREAD

**Issue by L-Seraphine** [travellings-link/travellings#1424]
### 网站名称

Seraphineの小窝

### 网站网址

blog.helloseraphine.top:8090

### 徽标位置

主页一排图标栏的中间的最后一个，使用的深色图标

### 内容方向

写点什么

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by Big-Cake-jpg** [comment]
3 月 12 日复核时，网站未强制跳转 HTTPS。
