### ISSUE TITLE
Suemor's Blog

### ISSUE THREAD

**Issue by suemor233** [travellings-link/travellings#1425]
### 网站名称

Suemor's Blog

### 网站网址

https://suemor.com

### 徽标位置

顶栏最右侧

### 内容方向

前端相关

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by suemor233** [comment]
地址已修改
