### ISSUE TITLE
浅梦’s Blog

### ISSUE THREAD

**Issue by Rockytkg** [travellings-link/travellings#1426]
### 网站名称

浅梦’s Blog

### 网站网址

https://letanml.xyz/

### 徽标位置

左侧边栏第4个，页脚右侧

### 内容方向

生活，学习经历，学习笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）
