### ISSUE TITLE
悬铃木的精神世界

### ISSUE THREAD

**Issue by lorre0322** [travellings-link/travellings#1427]
### 网站名称

悬铃木的精神世界

### 网站网址

https://lorre.top/

### 徽标位置

网页底部

### 内容方向

生活日常分享，随笔，杂文，电影

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
请将开往链接改为 HTTPS，谢谢。

**Comment by lorre0322** [comment]
> 请将开往链接改为 HTTPS，谢谢。

好耶～！已修改
