### ISSUE TITLE
Echocbxの异次元

### ISSUE THREAD

**Issue by Ezgx** [travellings-link/travellings#1428]
### 网站名称

欢迎来到Echocbxの异次元

### 网站网址

https://ezgx.tk/

### 徽标位置

顶栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
标题首尾那两个字符在一些平台显示不出来。

**Comment by Ezgx** [comment]
> 标题首尾那两个字符在一些平台显示不出来。

？请问您是什么平台，我的字体在网站里有资源的

**Comment by linlinzzo** [comment]
> ？请问您是什么平台，我的字体在网站里有资源的

Edge。
![image](https://user-images.githubusercontent.com/79007796/215700314-2a385443-9dbf-4b82-9e2a-c6aef5a5d7b3.png)

**Comment by Ezgx** [comment]
> 顶栏没有看到开往链接。

我正在上传

**Comment by Ezgx** [comment]
> 顶栏没有看到开往链接。

很块就能传上去了

**Comment by linlinzzo** [comment]
建议发布一些生活记录类文章。

**Comment by Ezgx** [comment]
> 建议发布一些生活记录类文章。

好的，谢谢建议

**Comment by Ezgx** [comment]
> 建议发布一些生活记录类文章。

文章类型占比也会影响审核吗

**Comment by Ezgx** [comment]
![image](https://user-images.githubusercontent.com/110729988/215701164-47f3f3dd-3fdc-47e0-9a54-b8dd70e10c97.png)
已添加

**Comment by linlinzzo** [comment]
> 文章类型占比也会影响审核吗

不会。但技术类博客会涉及“内容农场”方面的审查。

**Comment by Ezgx** [comment]
> > 已添加
> 
> 能添加到不用展开就能看到的位置吗？

我正在尝试，技术有限

**Comment by Big-Cake-jpg** [comment]
3 月 12 日复核时，网站显示为 Netlify 默认的“未找到站点”页面。

**Comment by Ezgx** [comment]
> 3 月 12 日复核时，网站显示为 Netlify 默认的“未找到站点”页面。

修改地址了，https://ezgx.site

**Comment by Ezgx** [comment]
![image](https://user-images.githubusercontent.com/110729988/230057339-80100e8c-8186-4381-bdf9-3116b4b55571.png)
