### ISSUE TITLE
网站名称

### ISSUE THREAD

**Issue by imxww** [travellings-link/travellings#1429]
### 网站名称

Lin`Blog

### 网站网址

https://linup.me

### 徽标位置

手机左边倒数第二个，电脑右边倒数第二个

### 内容方向

万物皆可白嫖

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请将 issue 的标题修改为网站的名称，谢谢。

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by Big-Cake-jpg** [comment]
与 #1430 重复。
