### ISSUE TITLE
Lin`Blog

### ISSUE THREAD

**Issue by imxww** [travellings-link/travellings#1430]
### 网站名称

快乐的林

### 网站网址

https://linup.me

### 徽标位置

侧栏，桌面端在上面倒数第二

### 内容方向

万物皆可白嫖

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by Big-Cake-jpg** [comment]
3 月 12 日复核时，显示网站 HTTPS 证书无效。
![image](https://user-images.githubusercontent.com/76810494/224513660-163d13b0-ef57-49b4-89ae-c71746a527c8.png)

很抱歉这么久才让您知道审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<
