### ISSUE TITLE
咬一口激动的鱼

### ISSUE THREAD

**Issue by tab134suki** [travellings-link/travellings#1431]
### 网站名称

咬一口激动的鱼

### 网站网址

https://tabotef134.top/

### 徽标位置

顶栏导航+网页底部

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
风带来了种子，时间使之发芽。

原？

**Comment by tab134suki** [comment]
我是个原神玩家（原来你也玩原神）
![ ](https://uploadstatic.mihoyo.com/contentweb/20200211/2020021114221470532.jpg)

**Comment by linlinzzo** [comment]
已添加，等会同步到服务器。
