### ISSUE TITLE
新城旧梦

### ISSUE THREAD

**Issue by itxcjm** [travellings-link/travellings#1434]
### 网站名称

新城旧梦

### 网站网址

https://www.itxcjm.top

### 徽标位置

顶栏

### 内容方向

生活，技术，学习

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by Big-Cake-jpg** [comment]
3 月 12 日复核时站点显示 HTTP 504 错误。

**Comment by itxcjm** [comment]
已处理

**Comment by itxcjm** [comment]
是否需要重新提交申请
