### ISSUE TITLE
酷小呵

### ISSUE THREAD

**Issue by Kuhehe666** [travellings-link/travellings#1435]
### 网站名称

酷小呵

### 网站网址

https://www.kuhehe.top/

### 徽标位置

侧栏

### 内容方向

分享一些自己收集的各种有用的资源，分享点日常什么的，或者作为一个笔记，记录一些东西

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Cubik65536** [comment]
文章数量不足
> 网页已有较多内容（应有20篇文章或10篇原创文章，需要已持续更新两个月以上，更新时间自博客第一篇内容时间开始算起）；
