### ISSUE TITLE
网站域名更换 - 繁华是客's Blog

### ISSUE THREAD

**Issue by dzvision** [travellings-link/travellings#1436]
[网站 IssueID #828](https://github.com/travellings-link/travellings/issues/828) 
网站编号：471

新春快乐！

## 网站网址
> - 💡从 https://vlts.kract.xyz/ 更换为 https://blog.withkr.xyz
> -  网站状态： ![繁华是客 Blog](https://img.shields.io/website?url=https://blog.withkr.xyz)

## 徽标位置
> - 💡 更变为 侧栏

**Comment by linlinzzo** [comment]
收到，马上处理。

https://jinshuju.net/f/RqMPiX

**Comment by linlinzzo** [comment]
已处理，等会会更新到服务器。
