### ISSUE TITLE
阿蛮君

### ISSUE THREAD

**Issue by hausen1012** [travellings-link/travellings#1438]
### 网站名称

阿蛮君

### 网站网址

https://www.amjun.com/

### 徽标位置

网站顶栏

### 内容方向

分享开发、运维、网络等技术教程

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
源站链接超时
![image](https://user-images.githubusercontent.com/79007796/235439664-f0f58abe-fc28-4e17-a564-f0b535a2902e.png)

**Comment by hausen1012** [comment]
这几天服务器总是被打，进黑洞了，好了又打
