### ISSUE TITLE
peachRL的小站

### ISSUE THREAD

**Issue by peachrl** [travellings-link/travellings#1440]
### 网站名称

peachRL的小站

### 网站网址

https://wanyijizi.com

### 徽标位置

主页底部，以及博客的侧栏

### 内容方向

学习，生活，技术

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
已在js当中添加，等待完善合并。
