### ISSUE TITLE
HZK's Blog

### ISSUE THREAD

**Issue by PowerfulRichard** [travellings-link/travellings#1441]
### 网站名称

HZK's Blog

### 网站网址

https://blog.zekun.fun

### 徽标位置

顶栏banner

### 内容方向

`编程` `技术` `转载实用但国内难以访问的文章`

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
网页底部的谷歌广告有推送加速器，请到后台关闭一下。

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by PowerfulRichard** [comment]
> 网页底部的谷歌广告有推送加速器，请到后台关闭一下。

已经关了，感谢提醒

**Comment by linlinzzo** [comment]
已在js当中添加，等待完善合并。
