### ISSUE TITLE
博客域名更换

### ISSUE THREAD

**Issue by L-cw** [travellings-link/travellings#1443]
编号357，进击的学霸的博客，原域名：https://blog.lovem.fun
**需变更为 https://blog.jjdxb.top**

**Comment by linlinzzo** [comment]
收到，马上处理。

https://jinshuju.net/f/RqMPiX

**Comment by linlinzzo** [comment]
开往换链接了，请及时更新。

**Comment by linlinzzo** [comment]
已处理，等会会更新到服务器。
