### ISSUE TITLE
林二一的博客

### ISSUE THREAD

**Issue by mocuishlelin** [travellings-link/travellings#1444]
### 网站名称

林二一的博客

### 网站网址

https://ley.best

### 徽标位置

右上角固定导航栏和网页底部

### 内容方向

运维技术

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
已在js当中添加，等待完善合并。
