### ISSUE TITLE
七鳄学习格

### ISSUE THREAD

**Issue by hyh981006** [travellings-link/travellings#1445]
### 网站名称

七鳄学习格

### 网站网址

https://blog.gmcj0816.top/

### 徽标位置

https://blog.gmcj0816.top/img/SeriousWission_TouXiangPic.jpg 

### 内容方向

技术分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
在网站中点击开往，浏览器会阻止弹出窗口。建议改为链接。

**Comment by hyh981006** [comment]
相关问题已经修复
