### ISSUE TITLE
甜鱼/Ayu

### ISSUE THREAD

**Issue by ayuusweetfish** [travellings-link/travellings#1446]
### 网站名称

甜鱼/Ayu

### 网站网址

https://ayu.land

### 徽标位置

网页底部（注：当前的设计将外部导航集中于底部，但是首页内容会保持约一屏高度以内。如果未来首页内容加长，会调整位置，保持首屏可见。若仍有不便请告知~）

### 内容方向

创作与设计/生活日志

（算不算 blog 就交给管理员决定了x

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
已在js当中添加，等待完善合并。
