### ISSUE TITLE
Yu's Site

### ISSUE THREAD

**Issue by IdealistYu** [travellings-link/travellings#1447]
### 网站名称

Yu's Site

### 网站网址

https://idealistyu.github.io/

### 徽标位置

侧栏，顶栏(移动端)

### 内容方向

主要分享日语与修考相关内容

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

很抱歉这么久才让您知道审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<

**Comment by linlinzzo** [comment]
审核通过，等待添加。
