### ISSUE TITLE
坐井观天网

### ISSUE THREAD

**Issue by ChengduLittleA** [travellings-link/travellings#1448]
### 网站名称

坐井观天网

### 网站网址

https://www.wellobserve.com

### 徽标位置

侧栏和底栏（移动端的话菜单都是收起的这个没法）

### 内容方向

画画 写作 手工 摄影

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题，我们会继续观察一段时间。

**Comment by linlinzzo** [comment]
审核通过，等待添加。
