### ISSUE TITLE
大海看看

### ISSUE THREAD

**Issue by xiaohai921** [travellings-link/travellings#1449]
### 网站名称

大海看看

### 网站网址

https://www.dhkk.cn/

### 徽标位置

侧栏和底栏

### 内容方向

记录生活留住美好时刻 ，分享个人学习笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请阅读加入要求中的关于网站建站时间的要求，谢谢。

**Comment by xiaohai921** [comment]
好的

**Comment by xiaohai921** [comment]
好的
