### ISSUE TITLE
CHI's blog

### ISSUE THREAD

**Issue by ChaunceyCHI** [travellings-link/travellings#1451]
### 网站名称

CHI's blog

### 网站网址

https://blog.chaunceychi.fun/

### 徽标位置

侧栏

### 内容方向

生活日常、读书笔记、学习记录等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端未找到开往外链。

![image](https://user-images.githubusercontent.com/76810494/224513103-057c3bf2-c00b-4892-a4b3-98a97606aedf.png)

很抱歉这么久才让您知道审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<

**Comment by ChaunceyCHI** [comment]
> 移动端未找到开往外链。
> 
> ![image](https://user-images.githubusercontent.com/76810494/224513103-057c3bf2-c00b-4892-a4b3-98a97606aedf.png)
> 
> 很抱歉这么久才让您知道审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<

已修正

**Comment by ChaunceyCHI** [comment]
已修正，请求收录。 @Big-Cake-jpg 
![228278950-d9d640ff-745a-494c-b9a6-a19793016498](https://user-images.githubusercontent.com/58379404/232783527-b4835588-2202-4959-9994-f9880cfa885e.jpg)

**Comment by linlinzzo** [comment]
审核通过，等待添加。
