### ISSUE TITLE
bill的小站

### ISSUE THREAD

**Issue by lbnliboning** [travellings-link/travellings#1453]
### 网站名称

bill的小站

### 网站网址

https://1703.site

### 徽标位置

顶部，底部

### 内容方向

分享网络折腾记录和生活相关内容。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by lbnliboning** [comment]
改一下：blog.1703.site

**Comment by Big-Cake-jpg** [comment]
文章数量似乎不满足要求，多写一段时间吧 >_<

很抱歉这么久才让您知道审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
审核通过，等待添加。
