### ISSUE TITLE
汐语の小栈

### ISSUE THREAD

**Issue by xiyu440** [travellings-link/travellings#1454]
### 网站名称

汐语の小栈

### 网站网址

https://xyhelper.top/

### 徽标位置

固定在侧栏

### 介绍

我是一个计算机的**初学者**，作为一个刚进入互联网世界的**小白**，我需要更多志同道合的**朋友**，一切互帮互助，共同进步

### 初衷

​	进入大学以后，第一次接触以前从未遇到的事物，通过自己的探索理解和掌握，并将知识可视化分享给大家，真的很快乐~

​	**首先**是，之前遇到好多好玩、新奇或使用的东西，从来都没有记录的习惯，导致将来的某一天再次需要时，只能说是我接触过，但是并没有一个深刻的系统的掌握。由此，我萌生了用个人博客的方式去记录学习，去分享生活

​	**其次**，初入互联网的世界，感觉到很奇妙，我也有很多想法需要去实现。但奈何自己技术有限，经验不足，很多东西需要去请教志同道合的朋友或者前辈，而加入开往便是我的初衷之一，这里，我可以接触更多厉害的技术大佬，或者情投意合的朋友伙伴，去努力开创属于自己的互联网世界的一角

​	**再次**，建站加入开往的目的，是想通过互联网世界去记录自己的成长历程。何曾不想十年之后的今天，我可以告诉朋友亲人我的成长经理时，可以侃侃而谈，有迹可循。毕竟，互联网的建设有我的参与

最后，便是对中国的互联网建设贡献自己的一份力，为开源中国尽一份微不足道的力量

### 期望

​	我**希望**自己可以加入开往，结实更多互联网的伙伴，并通过记录个人的成长历程实现个人追求，以及为当下的互联网环境尽己所能。

​	我**保证**，在加入开往以后，严格遵循相关的规定，并遵守法律法规，如若违反，自动退出。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xiyu440** [comment]
虽然现在的博客数量很少，但我会尽己所能，将知识尽可能更多地分享给他人。我保证，博客内容全部原创。

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

很抱歉这么久才让您知道审核结果，由于开往管理组成员大多学业繁忙，导致审核所需时间不可控。请您谅解 >_<

**Comment by xiyu440** [comment]
您好，我已将域名更改为https://xyhelper.top 
希望后续观察期可以基于此域名（已备案）

**Comment by linlinzzo** [comment]
审核通过，等待添加。
