### ISSUE TITLE
目的地-Destination

### ISSUE THREAD

**Issue by ChrisonLeon** [travellings-link/travellings#1455]
### 网站名称

目的地-Destination

### 网站网址

https://blog.chrison.cn/

### 徽标位置

web端：顶栏；移动端：顶部折叠

### 内容方向

个人博客，技术分享，生活分享，音乐分享。
希望所有人，前程似锦、未来可期、寻得良人、共赴白头，祝你也祝我。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
审核通过，等待添加。
