### ISSUE TITLE
Pixel Fandom

### ISSUE THREAD

**Issue by MaltTheDragon** [travellings-link/travellings#1456]
### 网站名称

Pixel Fandom

### 网站网址

https://pixelfandom.com/

### 徽标位置

固定的侧栏

### 内容方向

知识以及个人的想法 >:3

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
请阅读加入规则中有关网站建立时间的要求，谢谢。
