### ISSUE TITLE
吃猫的鱼个人博客

### ISSUE THREAD

**Issue by 2911396166** [travellings-link/travellings#1457]
### 网站名称

吃猫的鱼个人博客

### 网站网址

https://www.fish9.cn

### 徽标位置

网页底部，明显展示

### 内容方向

向网络世界分享我自己的编程笔记和一些日常记录！

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
审核通过，等待添加。
