### ISSUE TITLE
Leo's blog

### ISSUE THREAD

**Issue by Tseing** [travellings-link/travellings#1459]
### 网站名称

Leo's blog

### 网站网址

https://leonis.cc

### 徽标位置

顶栏

### 内容方向

记录我的生活、心情，还有发布我的阅读感想、学习笔记。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by baipin** [comment]
已添加，欢迎加入开往大家庭！
