### ISSUE TITLE
随手记 2BA.CC

### ISSUE THREAD

**Issue by 2bacc** [travellings-link/travellings#1460]
### 网站名称

随手记 2BA.CC

### 网站网址

https://www.2ba.cc/blog

### 徽标位置

顶栏,侧栏

### 内容方向

学习笔记
技术分析
生活记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端未找到开往外链。

**Comment by Big-Cake-jpg** [comment]
由于过久没有回应，您的申请被驳回。

如果您已解决提到的所有问题，可以重新创建一个 Issue。
