### ISSUE TITLE
调皮豆干 の 博客

### ISSUE THREAD

**Issue by Dynesshely** [travellings-link/travellings#1464]
### 网站名称

调皮豆干 の 博客

### 网站网址

https://blog.catrol.cn

### 徽标位置

顶栏

### 内容方向

生活日常, 技术教程, 知识原理, 思想感悟, etc.
原创技术类文章分享为主
且坚持所有内容为原创 (除了引用, 引文)

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端未找到开往外链。

**Comment by Dynesshely** [comment]
有的，由于屏幕尺寸的原因，开往的外链在右侧导航栏底部

https://user-images.githubusercontent.com/50760269/224531485-ce1327a3-9b20-440b-bc6e-374c418d4ba0.mp4

导航栏打开按钮在页面右上角，若没有出现可以多刷新几下，相关 cdn 最近有些问题

**Comment by Dynesshely** [comment]
@Big-Cake-jpg , 是否可以通过?

**Comment by Dynesshely** [comment]
> @Dynesshely 请将链接放在显眼的位置，谢谢

您好, 针对本例博客, 请问哪些位置符合`显眼的位置`的要求?
谢谢了.

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/3489c6a1-2daa-4d3f-a452-563cfbe92684)
侧栏有了，虽然扔到第一屏的那几个图标里最好（）

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by Dynesshely** [comment]
非常感谢, 抽空会想办法在博客其他位置也附上开往的链接
