### ISSUE TITLE
kenger blog请求收录

### ISSUE THREAD

**Issue by kengerlwl** [travellings-link/travellings#1465]
### 网站名称

kenger_blog

### 网站网址

https://kenger.top/

### 徽标位置

顶栏

### 内容方向

技术教程, 知识原理, 思想感悟, 偶尔记录一下生活感悟etc.
原创技术类文章分享为主
且坚持所有内容为原创 (除了引用, 引文)

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端未找到开往外链。
![image](https://user-images.githubusercontent.com/76810494/224512652-6c53dd3d-d0f5-41dc-a32b-5139829d781c.png)

**Comment by Big-Cake-jpg** [comment]
由于太长时间没有回应，您的申请被驳回。

如果您已解决提到的所有问题，可以重新创建一个 Issue。
