### ISSUE TITLE
ImkenのBlog

### ISSUE THREAD

**Issue by immccn123** [travellings-link/travellings#1466]
### 网站名称

ImkenのBlog

### 网站网址

https://blog.immccn123.xyz

### 徽标位置

顶栏 | 左侧菜单（上）| 页脚

### 内容方向

技术（教程/分享）、日常生活、网络技术等。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by immccn123** [comment]
@travellings-link

站点网址信息有更新：

由于个人原因，原站点 blog.immccn123.xyz 转域名 blog.imken.moe 域名，但是由于~~个人生死存亡~~原因旧站点保留了部分的静态文章

现在如果可以的话麻烦更新下（原 blog.immccn123,xyz -> blog.imken.moe）

**Comment by jiangmiemie** [comment]
我帮你更新了
