### ISSUE TITLE
cicode

### ISSUE THREAD

**Issue by liuk123** [travellings-link/travellings#1472]
### 网站名称

cicode-技术内容分享与科技生活

### 网站网址

www.cicode.cn

### 徽标位置

顶部导航栏

### 内容方向

cicode集博客、导航、工具为一体，前端技术内容分享和在线开发工具

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 `6339667` 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

提示：“徽标位置”指的是开往外链的所在位置，而非网站 favicon 链接。
