### ISSUE TITLE
漫川的成长日记

### ISSUE THREAD

**Issue by Duanjyy** [travellings-link/travellings#1473]
### 网站名称

漫川的成长日记

### 网站网址

https://www.bena.cc/

### 徽标位置

导航栏

### 内容方向

分享生活中有趣的事情

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端未找到开往链接。
![image](https://user-images.githubusercontent.com/76810494/224467566-73a14ec3-dfd1-425b-942f-5a1da850691f.png)

**Comment by Duanjyy** [comment]
> 移动端未找到开往链接。 ![image](https://user-images.githubusercontent.com/76810494/224467566-73a14ec3-dfd1-425b-942f-5a1da850691f.png)

已经修改移动端显示了

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
