### ISSUE TITLE
大棉博客

### ISSUE THREAD

**Issue by muyan0709** [travellings-link/travellings#1475]
### 网站名称

大棉博客

### 网站网址

https://blog.dmxvx.cc

### 徽标位置

侧栏

### 内容方向

分享生活，也会时不时分享技术类文章

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 `6339667` 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by muyan0709** [comment]
你好，我更换了新的域名：www.dmxvx.cc并更改了博客程序，开往徽标位置改到了页脚

**Comment by muyan0709** [comment]
你好，我更换了新的域名：www.dmxvx.cc 并更改了博客程序，开往徽标位置改到了页脚
