### ISSUE TITLE
申请收录PandaX Blog

### ISSUE THREAD

**Issue by panadaxx** [travellings-link/travellings#1476]
### 网站名称

PandaX Blog

### 网站网址

https://pandax.wiki/

### 徽标位置

网页顶部，明显展示

### 内容方向

分享一些我的学习记录，笔记，可能会有日常记录
想要认识并与更多志同道合的朋友相遇

目前文章数量还没有很多，但都是原创内容

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by panadaxx** [comment]
哈喽，可以正式加入开往了嘛٩(ˊᗜˋ*)و

**Comment by Big-Cake-jpg** [comment]
> 哈喽，可以正式加入开往了嘛٩(ˊᗜˋ*)و

添加周期视情况会有所变动，由于近期开往的后端独立化造成原本的页内 JavaScript 不再起作用，添加网站不能再通过修改 travelling.js 达到目的，需要团队中的后端负责人进行处理。

请您稍等一段时间，如果后端已经可以添加网站，我们会立刻处理所有已审核通过的网站的。
