### ISSUE TITLE
卡库伊2.0

### ISSUE THREAD

**Issue by sunorz** [travellings-link/travellings#1478]
### 网站名称

卡库伊2.0

### 网站网址

https://blog.kkii.org

### 徽标位置

侧栏

### 内容方向

# IT资源和技术分享博客
Tag：Adobe,Microsoft,Office,NAS,PHP,Windows,jonathan06,jsunplace,sunplace,blog,博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
