### ISSUE TITLE
猫猫博客

### ISSUE THREAD

**Issue by Sayyiku** [travellings-link/travellings#1479]
### 网站名称

猫猫博客

### 网站网址

https://catcat.blog/

### 徽标位置

导航栏

### 内容方向

记录日常

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
似乎有堆砌内容的可能。@Big-Cake-jpg

**Comment by Sayyiku** [comment]
以前的备份xml文件提取md进行文章迁移

**Comment by Big-Cake-jpg** [comment]
> 以前的备份xml文件提取md进行文章迁移

是这样吗？那会不会需要在博客内显示一个公告用以告知呢？

---

目前看来没有什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
