### ISSUE TITLE
starmoe's site

### ISSUE THREAD

**Issue by Bro-Xun** [travellings-link/travellings#1480]
### 网站名称

starmoe's site

### 网站网址

https://hexo.hydi.xyz/

### 徽标位置

顶栏

### 内容方向

学习笔记
生活记录
技术分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/f792b684-24b1-4c9e-8808-031cc66e46ab)

![Image](https://github.com/user-attachments/assets/51d53773-8654-4eae-8480-445c134917a9)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
