### ISSUE TITLE
1nonly's blog

### ISSUE THREAD

**Issue by Inon1y** [travellings-link/travellings#1481]
### 网站名称

1nonly's blog

### 网站网址

https://blog.nonly.cn

### 徽标位置

左侧侧栏

### 内容方向

一个学习前端开发的在校生，分享自己的学习记录以及日常生活。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端无法找到开往外链。

**Comment by Inon1y** [comment]
移动端左上角打开菜单栏往下拉一丢丢就显示了。&nbsp;


yuushay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月25日(星期六) 中午1:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [travellings-link/travellings] 1nonly&#39;s blog (Issue #1481)





 
移动端无法找到开往外链。

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
