### ISSUE TITLE
缘生笔记

### ISSUE THREAD

**Issue by ysicing** [travellings-link/travellings#1484]
### 网站名称

缘生笔记

### 网站网址

https://ysicing.me

### 徽标位置

首页和内页导航

### 内容方向

运维&开发笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端无法找到开往外链。

**Comment by ysicing** [comment]
移动端和PC端一样啊，首页有啊 开往
![image](https://user-images.githubusercontent.com/8605565/227772697-bb29107d-8530-4af2-81e7-c2c1463882ad.png)

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
