### ISSUE TITLE
mtxh'blog

### ISSUE THREAD

**Issue by XIJL123** [travellings-link/travellings#1486]
### 网站名称

mtxh'blog

### 网站网址

blogs.mtxh.fun

### 徽标位置

侧栏

### 内容方向

分享技术和生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
未找到开往外链。
![image](https://github.com/travellings-link/travellings/assets/76810494/b15f88f4-3fe9-41d3-a096-b377be1013ff)
