### ISSUE TITLE
山水流年

### ISSUE THREAD

**Issue by iuiurun** [travellings-link/travellings#1491]
### 网站名称

山水流年

### 网站网址

https://liufw.cn

### 徽标位置

导航栏+网页底部

### 内容方向

记录生活，愿你在山水之间度过自己美好的年华，感受生活中的各种各样的幸福。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）
