### ISSUE TITLE
Daoker小站

### ISSUE THREAD

**Issue by Daoker01** [travellings-link/travellings#1492]
### 网站名称

Daoker小站

### 网站网址

https://daoker.cc

### 徽标位置

顶部导航栏

### 内容方向

分享见闻，记录心情。分享一些日常折腾遇到的技术难题，同时也是一个笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请修改开往链接为 README 当中推荐的链接，谢谢。

**Comment by Daoker01** [comment]
检查确实已经是README中推荐的链接https://www.travellings.cn

**Comment by Big-Cake-jpg** [comment]
请将开往外链修改为 `https://www.travellings.cn/go.html`。

**Comment by Daoker01** [comment]
> https://www.travellings.cn/go.html

已修改

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by linlinzzo** [comment]
已添加到数据库，index=828。
