### ISSUE TITLE
空灵的二月

### ISSUE THREAD

**Issue by Jesseais** [travellings-link/travellings#1494]
### 网站名称

空灵的二月

### 网站网址

https://blog.ethereal.run/

### 徽标位置

ex.侧栏

### 内容方向

“世界不再贩卖焦虑，开始流行快乐。”

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/9e5a8db9-0738-4e80-8fd7-ee953ef766b5)

**Comment by Big-Cake-jpg** [comment]
由于 14 天内未得到您的回复，团队将拒绝您的申请。

如果您已将上述所提到的问题处理完毕，可以重新创建一个 Issue。
