### ISSUE TITLE
HUGEH4rD-技术苑

### ISSUE THREAD

**Issue by zelas2xerath** [travellings-link/travellings#1499]
### 网站名称

HUGEH4rD-技术苑

### 网站网址

https://blog.806006.xyz

### 徽标位置

顶部导航

### 内容方向

CTF、运维技术、个人博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
移动端没有看到开往链接？

**Comment by zelas2xerath** [comment]
之前是由于您的移动端设备宽度过小所以没有显示，现在已经完全修复了该问题，在多个浏览器上均已测试成功

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/70723f73-4c96-4ceb-b5c1-d2cabd1819b1)
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
