### ISSUE TITLE
SinzMise的小屋

### ISSUE THREAD

**Issue by SinzMise** [travellings-link/travellings#1503]
### 网站名称

SinzMise的小屋

### 网站网址

https://blog.sinzmise.top/

### 徽标位置

顶栏

### 内容方向

分享教程、讲述心事等等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by SinzMise** [comment]
本站正在备案，大约一个多星期完成，期间站点无法访问，请见谅!

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by baipin** [comment]
已添加，欢迎加入开往大家庭！
