### ISSUE TITLE
Echocbxの异次元-—已修复

### ISSUE THREAD

**Issue by Ezgx** [travellings-link/travellings#1505]
### 网站名称

Echocbxの异次元

### 网站网址

https://ezgx.site/

### 徽标位置

导航栏

### 内容方向

技术，前后端，linux

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
能给一下网站序号吗？

**Comment by Ezgx** [comment]
> 能给一下网站序号吗？

issue的序号吗

**Comment by Ezgx** [comment]
> 能给一下网站序号吗？

issue序号1428

**Comment by linlinzzo** [comment]
> issue序号1428

不是，是成员列表前面的序号哦。

**Comment by baipin** [comment]
已添加，欢迎加入开往大家庭！

**Comment by jiangmiemie** [comment]
已更改地址为 https://uu.sssu.us/
