### ISSUE TITLE
BLxcwg666 's Blog

### ISSUE THREAD

**Issue by BLxcwg666** [travellings-link/travellings#1507]
### 网站名称

BLxcwg666 's Blog

### 网站网址

https://blog.xcnya.cn

### 徽标位置

左侧边栏

### 内容方向

主要更技术性教程类文章，偶尔闲谈几句，望收录喵~

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
样式掉了？

**Comment by BLxcwg666** [comment]
> 样式掉了？

没有啊，我这正常

**Comment by Big-Cake-jpg** [comment]
emmmmm，这个 Bot 是怎么回事......？

目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by Big-Cake-jpg** [comment]
duplicate of #1553
