### ISSUE TITLE
腕能新趣 - 资源交流社区

### ISSUE THREAD

**Issue by sai875** [travellings-link/travellings#1508]
### 网站名称

腕能新趣 - 资源交流社区

### 网站网址

https://bbs.wsfq.top/

### 徽标位置

顶栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by sai875** [comment]
> ### 网站名称
> 腕能新趣 - 资源交流社区
> 
> ### 网站网址
> https://www.8uid.com/
> 
> ### 徽标位置
> 顶栏
> 
> ### 内容方向
> _No response_
> 
> ### 请确认一下事项
> * [x]  我已确认以上事项

**Comment by linlinzzo** [comment]
移动端没有看到开往链接。
