### ISSUE TITLE
木木困玉光的博客

### ISSUE THREAD

**Issue by l739217783** [travellings-link/travellings#1511]
### 网站名称

木木困玉光的博客

### 网站网址

https://linguoguang.com

### 徽标位置

顶栏选项卡、底部微标

### 内容方向

- 技术分享（软件应用、软件配置、Python、JavaScript等）
- 生活分享（生活点滴、思考、感悟等）

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by l739217783** [comment]
近期因备案需要，目前网站暂停解析一段时间，请谅解😉

**Comment by l739217783** [comment]
备案完毕，未在成员列表，申请重新收录
