### ISSUE TITLE
Devzhi's Blog

### ISSUE THREAD

**Issue by devzhi** [travellings-link/travellings#1515]
### 网站名称

Devzhi's Blog

### 网站网址

https://www.devzhi.com/

### 徽标位置

顶栏

### 内容方向

后端开发、Java 生态系统相关技术和框架等方面

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by Big-Cake-jpg** [comment]
另：不建议使用 jsDelivr 主服务域名 `cdn.jsdelivr.net`。

**Comment by devzhi** [comment]
> 

感谢提醒，已经切换至国内CDN
