### ISSUE TITLE
寒夏Rainiar

### ISSUE THREAD

**Issue by SamuNatsu** [travellings-link/travellings#1519]
### 网站名称

寒夏Rainiar

### 网站网址

https://rainiar.top/

### 徽标位置

顶部导航栏

### 内容方向

网站网址链接向主站 <https://rainiar.top>，为个人介绍页

在顶部导航栏有博客站链接向二级域名 <https://blog.rainiar.top>

内容展示以博客站方面为主，即技术文章和杂谈 log

如果被中文博客列表导航项目收录，希望记录的 URL 是博客站的二级域名

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
