### ISSUE TITLE
mepic丢帧的影像

### ISSUE THREAD

**Issue by Moweihu** [travellings-link/travellings#1521]
### 网站名称

丢帧的影像

### 网站网址

https://www.mepic.cn

### 徽标位置

网站介绍栏

### 内容方向

不是每个人都能成为摄影家，但是，好的摄影作品可以出自任何人。丢帧，即是一个分享小伙伴们优秀摄影作品的网站。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
未找到开往外链。

**Comment by Moweihu** [comment]
![Uploading BF1A3737-6805-46F2-999F-E347F0C759B0.jpeg…]()

**Comment by Moweihu** [comment]
![Uploading 9FFE3E1B-70B3-4F0A-9BC2-6D915B31D416.jpeg…]()

**Comment by Big-Cake-jpg** [comment]
找到了，多少有些不明显 = =

![image](https://user-images.githubusercontent.com/76810494/235552932-44f604e9-5040-47f4-a530-88eb48877306.png)

目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by Moweihu** [comment]
这地方是我网站最醒目的地方了 哈哈
