### ISSUE TITLE
極東晝寢愛好家

### ISSUE THREAD

**Issue by LittleNyima** [travellings-link/travellings#1523]
### 网站名称

極東晝寢愛好家

### 网站网址

https://littlenyima.github.io/

### 徽标位置

顶栏右侧

### 内容方向

技术向博客和杂谈

p.s. 目前没有达到20篇文章的要求，不过已经有10篇原创内容。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by LittleNyima** [comment]
\*移动端浏览时顶栏被收起，需要手动展开才能看到图标

**Comment by Big-Cake-jpg** [comment]
文章数量有点少，记得多写一点哦。

目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
