### ISSUE TITLE
Siax's Blog

### ISSUE THREAD

**Issue by L-20021213** [travellings-link/travellings#1526]
### 网站名称

Siax's Blog

### 网站网址

https://siax.cn/

### 徽标位置

侧栏和底部

### 内容方向

个人博客，学习笔记和生活琐事

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请在侧栏中也放置开往图标，谢谢。

**Comment by Big-Cake-jpg** [comment]
> 请在侧栏中也放置开往图标，谢谢。

PC 端上侧边栏是有开往图标的。
