### ISSUE TITLE
HOMIE笔记

### ISSUE THREAD

**Issue by HOMIEFF** [travellings-link/travellings#1527]
### 网站名称

HOMIE笔记

### 网站网址

https://ffnb.top/

### 徽标位置

侧栏

### 内容方向

记录我的日常，我的摄影故事，分享我想分享给大家的故事。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
无法访问。

**Comment by linlinzzo** [comment]
![Screenshot_20230502_075111_mark.via.jpg](https://user-images.githubusercontent.com/79007796/235550954-7254d3a8-285a-44b5-9cb8-c5446d326ad1.jpg)

**Comment by Big-Cake-jpg** [comment]
2023 / 05 / 02 复核，站点可以正常访问。

![image](https://user-images.githubusercontent.com/76810494/235553620-2c03367a-1cd4-4a6b-9b7b-9e3561bd4fa9.png)

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by HOMIEFF** [comment]
访问失败可以刷新一下 可能是当时网络环境异常或者是有问题才触发了安全保护 那个500提示是我改的 那个情况刷新一下就好了🙏
