### ISSUE TITLE
收录申请_下一页 · NextPage

### ISSUE THREAD

**Issue by JIWU-HelloWorld** [travellings-link/travellings#1530]
### 网站名称

下一页 · NextPage

### 网站网址

https://www.next-page.cn

### 徽标位置

顶部

### 内容方向

这里的种类会非常的繁杂,有技能的教程干货、有生活上的吐槽和妙招、有话题上的思考和想法。一般我研究什么、发现了什么都会分享在这里。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
