### ISSUE TITLE
泠风寒声の小窝

### ISSUE THREAD

**Issue by Lfhsheng** [travellings-link/travellings#1531]
### 网站名称

泠风寒声の小窝

### 网站网址

https://blog.lfhsheng.com

### 徽标位置

顶部、底栏

### 内容方向

分享有趣的东西

抱歉之前没有及时看Github，同时重置了blog导致开往链接消失

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
请提供网站序号。

**Comment by Lfhsheng** [comment]
#737

**Comment by Lfhsheng** [comment]
az貌似我站一直都是通过的（

**Comment by Lfhsheng** [comment]
但貌似成员列表里没我啊（

**Comment by HowieHz** [comment]
link #737
