### ISSUE TITLE
Shimoko

### ISSUE THREAD

**Issue by wzh4869** [travellings-link/travellings#1539]
### 网站名称

Shimoko

### 网站网址

https://www.shimoko.com/

### 徽标位置

固定侧栏，移动端侧栏在上面折叠

### 内容方向

轨迹改变角度交错，寂寞城市又在探戈

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by wzh4869** [comment]
更正：内容方向为生活/Linux/技术

**Comment by linlinzzo** [comment]
{"msg":"connection reset by peer","code":"50303005","id":"c7ede94f12d61566eb811fb65361336e"}

**Comment by linlinzzo** [comment]
出现错误？

**Comment by wzh4869** [comment]
> 出现错误？

CDN问题，现在应该ok了

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
