### ISSUE TITLE
宇生の后花园

### ISSUE THREAD

**Issue by flyu0** [travellings-link/travellings#1540]
### 网站名称

宇生の后花园

### 网站网址

https://blog.yudragon.cn

### 徽标位置

顶栏/侧栏

### 内容方向

生活类博客，记录生活日常。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
请将开往外链更改为 `https://www.travellings.cn/go.html`。

**Comment by yulikegirl** [comment]
> 请将打开外链更改为`https://www.travellings.cn/go.html`。

好的，已对链接进行更新

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
