### ISSUE TITLE
孟夏十二の天空

### ISSUE THREAD

**Issue by q1263868407** [travellings-link/travellings#1544]
### 网站名称

孟夏十二の天空

### 网站网址

https://aprdec.top

### 徽标位置

顶栏，移动端侧栏

### 内容方向

个人学习的互联网内容，编程记录，平时折腾的分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by q1263868407** [comment]
![image-20230604122452448](https://luchetuchuang.oss-cn-beijing.aliyuncs.com/aprimg/image-20230604122452448.png)
因为主机服务商迁移问题 博客暂时不能访问

**Comment by Big-Cake-jpg** [comment]
2023 / 07 / 02 复查，网站无法访问。
![image](https://github.com/travellings-link/travellings/assets/76810494/4bce0639-13e2-4a12-b6d9-5b9ad0e58d86)

**Comment by q1263868407** [comment]
> 2023 / 07 / 02 复查，网站无法访问。
> ![image](https://github.com/travellings-link/travellings/assets/76810494/4bce0639-13e2-4a12-b6d9-5b9ad0e58d86)
> 

十分抱歉，服务器厂商一拖再拖，最终确定在7月10号恢复香港服务器的运行。😓
请问是否可以7.10日之后再次观察

**Comment by Big-Cake-jpg** [comment]
2023 / 07 / 11 复查，网站仍然无法访问。
![image](https://github.com/travellings-link/travellings/assets/76810494/22ab01f7-7879-4c38-8df3-d6a37d0cabfc)
![image](https://github.com/travellings-link/travellings/assets/76810494/ac970ab8-e6df-455c-b525-b594c4a5a8dd)

**Comment by linlinzzo** [comment]
ERR_CONNECTION_REFUSED

**Comment by q1263868407** [comment]
> 2023 / 07 / 11 复查，网站仍然无法访问。
> ![image](https://github.com/travellings-link/travellings/assets/76810494/22ab01f7-7879-4c38-8df3-d6a37d0cabfc)
> ![image](https://github.com/travellings-link/travellings/assets/76810494/ac970ab8-e6df-455c-b525-b594c4a5a8dd)

十分抱歉，因为服务器厂商没有按照规定恢复，本来想等回复备份数据的，现在更换了服务器并且自己重新上传了，可以请再一次审核吗

**Comment by linlinzzo** [comment]
@Big-Cake-jpg

**Comment by Big-Cake-jpg** [comment]
站内存在 HTTP 协议加载的资源，不满足开往对成员网站的要求：强制启用 HTTPS。

**Comment by jiangmiemie** [comment]
您好，8月16巡查，首页未发现开往徽标 @q1263868407
