### ISSUE TITLE
Pinpe

### ISSUE THREAD

**Issue by Pinpe** [travellings-link/travellings#1546]
### 网站名称

Pinpe

### 网站网址

https://pinpe.top

### 徽标位置

默认收起的顶栏，但是有图标提示

### 内容方向

主要是生活动态，其次是技术性教程和文章，等等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
