### ISSUE TITLE
月梦の技术博客

### ISSUE THREAD

**Issue by lim-yoona** [travellings-link/travellings#1547]
### 网站名称

月梦の技术博客

### 网站网址

https://ymiir.top/

### 徽标位置

侧栏

### 内容方向

分享关于计算机技术的知识。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
未找到开往外链。
![image](https://github.com/travellings-link/travellings/assets/76810494/2ed1a431-64f5-4ad9-804c-a633bc6a26b6)

**Comment by lim-yoona** [comment]
您好，开往外链已加在博客侧边栏。

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
