### ISSUE TITLE
拾梦纪 - 记录生活

### ISSUE THREAD

**Issue by Never2333** [travellings-link/travellings#1548]
### 网站名称

拾梦纪 - 记录生活

### 网站网址

https://never666.uk/

### 徽标位置

左侧栏

### 内容方向

拾梦纪 - 记录生活 是集记录生活，技术与游戏分享，攻略为一体的博客网站。本网站由四名大学生组成的 PG Organisation 负责运营和维护，也是 拾梦纪 项目开始的第一个项目。愿我们心中的那一个梦想可以延续下去。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
