### ISSUE TITLE
linlexiao's blog 申请

### ISSUE THREAD

**Issue by linlexiao0** [travellings-link/travellings#1549]
### 网站名称

linlexiao's blog

### 网站网址

https://linlexiao.com

### 徽标位置

顶栏

### 内容方向

主要分享信息竞赛内容。额外写一点其余编程技术

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
