### ISSUE TITLE
BLxcwg666 's Blog

### ISSUE THREAD

**Issue by BLxcwg666** [travellings-link/travellings#1553]
### 网站名称

BLxcwg666 's Blog

### 网站网址

https://blog.xcnya.cn

### 徽标位置

左侧栏

### 内容方向

主要更技术性教程类文章，偶尔闲谈几句，望收录喵~
还有上次的申请我记得是回复过的qaq
![image](https://github.com/travellings-link/travellings/assets/66854530/ce33a423-3ccd-49f4-80de-66defe2ddf67)

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
