### ISSUE TITLE
老咸鱼的池塘

### ISSUE THREAD

**Issue by miaokaXD** [travellings-link/travellings#1554]
### 网站名称

老咸鱼的池塘

### 网站网址

https://nixieka.top

### 徽标位置

顶部导航栏、网页底部

### 内容方向

> 行百里者半九十，致胜利者积跬步。

**想分享什么？**

一个网工铁憨憨的流水账，记录下学习、生活还有无止境的折腾。

**附加说明**

近段时间会陆续更新博客（旧博客的数据还在迁移中……），还请各位谅解，谢谢。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by miaokaXD** [comment]
您好，博客重新装修了，目前链接为 https://blog.nixieka.top ，RSS订阅地址为 https://blog.nixieka.top/atom.xml ，文章正在迁移，带来不便还请谅解，谢谢！
