### ISSUE TITLE
WenJing

### ISSUE THREAD

**Issue by LanHuangJG** [travellings-link/travellings#1560]
### 网站名称

WenJing

### 网站网址

https://blog.jxutcm.eu.org

### 徽标位置

底部

### 内容方向

网站开发 android开发

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，请您仔细阅读开往对成员网站文章数量的要求。我只在您的网站看到8篇文章哦。
