### ISSUE TITLE
色戒 - Lust Caution

### ISSUE THREAD

**Issue by eycn** [travellings-link/travellings#1561]
### 网站名称

色戒 - Lust Caution

### 网站网址

https://www.sej.cn

### 徽标位置

底部

### 内容方向

色戒 - Lust Caution(www.sej.cn)多的就不做介绍了，您会明白的(˵¯͒〰¯͒˵)！

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

另：推荐将开往外链放置在顶栏或侧栏。

**Comment by eycn** [comment]
ok

**Comment by Big-Cake-jpg** [comment]
2023 / 06 / 17 复查，PC 端无法找到开往外链。
![image](https://github.com/travellings-link/travellings/assets/76810494/0ce5b9a9-92d7-4982-9b19-b982a195c344)
