### ISSUE TITLE
博客更换域名

### ISSUE THREAD

**Issue by tab134suki** [travellings-link/travellings#1563]
[#1431](https://github.com/travellings-link/travellings/issues/1431)
咬一口激动的鱼
原域名：https://tabotef134.top/
现域名：https://jiyu134.top/
请更改一下，Thanks♪(･ω･)ﾉ

**Comment by baipin** [comment]
好了。

**Comment by linlinzzo** [comment]
@baipin 这个等会记得到 README 中也改一下。

**Comment by baipin** [comment]
> @baipin 这个等会记得到 README 中也改一下。

Ok!

**Comment by gxres042** [comment]
![image](https://github.com/travellings-link/travellings/assets/53113178/a2b0e9ca-f2b1-4e15-8af5-54c0bfd69536)
博主您好，您的博客对开往链接使用了 JS 延时跳转，导致浏览器拦截，建议您缩短延迟时间或取消延迟。
