### ISSUE TITLE
后退网页无法回到开往

### ISSUE THREAD

**Issue by baipin** [travellings-link/travellings#1564]
好久没用开往了，最近体验发现：
1.跳转到新的网页后，无法后退回到开往
2.并且现在有大量的死站和删去开往图标的网站（非常多，随便几次开往就有），使友链接力难以持续，体验比较差。

**Comment by jiangmiemie** [comment]
> 可以留在Github，
> 或者是减少目标前

我是一个爬虫工程师，我有个另辟蹊径的法子：后台不是有开往的博客地址URL嘛，可以每个月跑一次爬虫，可以通过切换浏览器头来访问手机端和电脑端，检测开往的URL是否在首页中，非常的easy。（这样可以自动化掉一部分，同时也保留路人提交的方式）我愿意公益做这个事情，但是跑爬虫的代码托管在哪里是个问题，如果项目团队愿意可以联系我。

**Comment by jiangmiemie** [comment]
> 

可以做的的功能包括：是否返回404 ， 首页是否有开往的URL， 此URL是否可见

**Comment by baipin** [comment]
> > 
> 
> 可以做的的功能包括：是否返回404 ， 首页是否有开往的URL， 此URL是否可见

@linlinzzo

**Comment by linlinzzo** [comment]
> 我是一个爬虫工程师，我有个另辟蹊径的法子：后台不是有开往的博客地址URL嘛，可以每个月跑一次爬虫，可以通过切换浏览器头来访问手机端和电脑端，检测开往的URL是否在首页中，非常的easy。（这样可以自动化掉一部分，同时也保留路人提交的方式）我愿意公益做这个事情，但是跑爬虫的代码托管在哪里是个问题，如果项目团队愿意可以联系我。

我们愿意采用这种方式，服务器可以用开往的源服务器（如果可以），但我好像不能从您的博客和 GitHub 账号上发现您的即时通信方式，麻烦请您添加一下我。

**Comment by linlinzzo** [comment]
@baipin 关于第一个问题，您看一下在开往的时候点击一下正在开往的页面，能不能解决问题。现在貌似要点击页面才能后退跳转。

**Comment by baipin** [comment]
> @baipin 关于第一个问题，您看一下在开往的时候点击一下正在开往的页面，能不能解决问题。现在貌似要点击页面才能后退跳转。

点击了一下 发现直接跳到Github页面了？

**Comment by jiangmiemie** [comment]
> 好久没用开往了，最近体验发现： 1.跳转到新的网页后，无法后退回到开往 2.并且现在有大量的死站和删去开往图标的网站（非常多，随便几次开往就有），使友链接力难以持续，体验比较差。

不查不知道，一查有30%的404和删去开往图标的网站，404的和删去开往的已标记。

**Comment by baipin** [comment]
> > 好久没用开往了，最近体验发现： 1.跳转到新的网页后，无法后退回到开往 2.并且现在有大量的死站和删去开往图标的网站（非常多，随便几次开往就有），使友链接力难以持续，体验比较差。
> 
> 不查不知道，一查有30%的404和删去开往图标的网站，404的和删去开往的已标记。

已经用您提供的表在做人工复检了。

**Comment by jiangmiemie** [comment]
![image](https://github.com/travellings-link/travellings/assets/69161207/8bb18226-546b-4c6b-98a4-74ac63002341)
我画了一个流程图，希望能帮这个项目保持活力

**Comment by jiangmiemie** [comment]
可以close了吧，应该都搞定了捏

**Comment by Big-Cake-jpg** [comment]
> 可以close了吧，应该都搞定了捏

一切都搞定了？那么非常感谢您对开往项目做出的贡献，祝您有愉悦的一天！
