### ISSUE TITLE
牛魔博客

### ISSUE THREAD

**Issue by fyniujin** [travellings-link/travellings#1565]
### 网站名称

牛魔博客

### 网站网址

https://www.nmwbk.com/

### 徽标位置

导航栏

### 内容方向

分享技术 共同成长 相互学习 扩展眼界

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
请设置正确的开往链接地址（请加上go.html）
