### ISSUE TITLE
daodaoshi

### ISSUE THREAD

**Issue by daodaoshi** [travellings-link/travellings#1572]
### 网站名称

daodaoshi

### 网站网址

https://www.daodaoshi.xyz

### 徽标位置

顶栏

### 内容方向

作为产品经理对生活和互联网的一些思考，同时会分享一些阅读、观影体验，以及一些技术相关内容

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
