### ISSUE TITLE
Yunxi Blog

### ISSUE THREAD

**Issue by zimoyunxi** [travellings-link/travellings#1574]
### 网站名称

子墨云溪

### 网站网址

https://zimoou.com

### 徽标位置

侧栏底部

### 内容方向

记录收藏，分享生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by jiangmiemie** [comment]
开往备案迁移中，我们会在8月7号后继续处理
