### ISSUE TITLE
shimmer

### ISSUE THREAD

**Issue by wp0403** [travellings-link/travellings#1577]
### 网站名称

shimmer

### 网站网址

https://wp-boke.work

### 徽标位置

网页底部（全站底部导航）

### 内容方向

生活、摄影、技术

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/7c221a4f-f92a-4b65-996b-edf86f45e13d)
PC 端无法在顶栏或底栏找到开往外链。

**Comment by wp0403** [comment]
啊？这个不是十年之约的传送门吗？我搞错了？

**Comment by wp0403** [comment]
非常抱歉，已添加，
<img width="1407" alt="image" src="https://github.com/travellings-link/travellings/assets/75709526/5235efae-53cd-4e3c-bdfe-b69541e33592">

**Comment by wp0403** [comment]
@Big-Cake-jpg 希望重新审批

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by jiangmiemie** [comment]
开往备案迁移中，我们会在8月7号后继续处理
