### ISSUE TITLE
绝对概括的切面

### ISSUE THREAD

**Issue by umezane06** [travellings-link/travellings#1580]
### 网站名称

绝对概括的切面

### 网站网址

https://umezane06.github.io/

### 徽标位置

顶栏

### 内容方向

自己的碎碎念和分享四处收集的各种方便工具

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by jiangmiemie** [comment]
开往备案迁移中，我们会在8月7号后继续处理
