### ISSUE TITLE
gorpeln的个人博客 - gorpeln

### ISSUE THREAD

**Issue by gorpeln** [travellings-link/travellings#1581]
### 网站名称

gorpeln的个人博客 - gorpeln

### 网站网址

https://gorpeln.cn

### 徽标位置

侧栏

### 内容方向

记录技术上的成长以及生活里的点点滴滴...

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
抱歉，我没有办法在移动端发现开往的链接。

**Comment by gorpeln** [comment]
已经修改完成

**Comment by baipin** [comment]
已收录，欢迎加入开往大家庭！

**Comment by gorpeln** [comment]
gorpeln的个人博客 - gorpeln(index: 749) 已经由 https://gorpeln.cn 迁移至 https://gorpeln.top，望处理。

**Comment by gorpeln** [comment]
。
