### ISSUE TITLE
慧行说

### ISSUE THREAD

**Issue by daniellauyu** [travellings-link/travellings#1582]
### 网站名称

慧行说

### 网站网址

https://liuyude.com

### 徽标位置

网页底部

### 内容方向

- 技术教程；
- 学习笔记；
- 生活随笔；

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
建立时间过短，还请稍后再来。

**Comment by linlinzzo** [comment]
@baipin 应该贴“待回应”标签。🤗

**Comment by baipin** [comment]
> @baipin 应该贴“待回应”标签。🤗

Ok

**Comment by daniellauyu** [comment]
> 建立时间过短，还请稍后再来。

管理你好，我的博客创建于15年，有域名注册时间跟网站备案时间可以佐证。
![image](https://github.com/travellings-link/travellings/assets/17739321/2c12379c-ad11-472d-bb3c-8e349192275c)
也有百度收录可以佐证。
![image](https://github.com/travellings-link/travellings/assets/17739321/a10df614-9d3d-45a2-87bf-769e728153e5)
所以不太理解这里指的建立时间过短是什么意思，望说明下谢谢

**Comment by baipin** [comment]
> > 建立时间过短，还请稍后再来。
> 
> 管理你好，我的博客创建于15年，有域名注册时间跟网站备案时间可以佐证。 ![image](https://user-images.githubusercontent.com/17739321/248774139-2c12379c-ad11-472d-bb3c-8e349192275c.png) 也有百度收录可以佐证。 ![image](https://user-images.githubusercontent.com/17739321/248773869-a10df614-9d3d-45a2-87bf-769e728153e5.png) 所以不太理解这里指的建立时间过短是什么意思，望说明下谢谢

抱歉，看岔了，正在添加

**Comment by baipin** [comment]
已添加，欢迎加入开往大家庭！
