### ISSUE TITLE
深秋’s blog

### ISSUE THREAD

**Issue by lateautumn2** [travellings-link/travellings#1584]
### 网站名称

深秋’s blog

### 网站网址

https://www.lateautumn.cn/

### 徽标位置

左侧栏

### 内容方向

技术教程；学习笔记；生活杂谈

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
博客有点咕咕，2022年和2021年的总结只差一篇文章。。。

**Comment by linlinzzo** [comment]
文章内容较少，再多坚持写一会吧。

**Comment by lateautumn2** [comment]
好的哈，写满20篇我再来申请
