### ISSUE TITLE
左耳

### ISSUE THREAD

**Issue by zuoer96** [travellings-link/travellings#1588]
### 网站名称

左耳

### 网站网址

https://nbchen.com

### 徽标位置

网页底部（开往徽章）+顶部友链（展开开往子菜单）

### 内容方向

我本是槐花院落闲散的人，满襟酒气，小池塘边跌坐看鱼，眉挑烟火过一生

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
规定中要求建立时间至少两个月，请稍后再来，感谢理解～
