### ISSUE TITLE
小嗷犬的技术小站

### ISSUE THREAD

**Issue by Marquis03** [travellings-link/travellings#1592]
### 网站名称

小嗷犬的技术小站

### 网站网址

https://blog.marquis.eu.org/

### 徽标位置

顶栏右侧

### 内容方向

计算机学习笔记，Python、C/C++、MATLAB、人工智能等。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端无法找到开往外链。
![image](https://github.com/travellings-link/travellings/assets/76810494/0bcff96e-7012-465d-8ea0-e9a3544e84cc)
