### ISSUE TITLE
倾丞の小窝 申请收录

### ISSUE THREAD

**Issue by Jochen233** [travellings-link/travellings#1593]
### 网站名称

倾丞の小窝

### 网站网址

https://blog.qcmoe.com/

### 徽标位置

电脑端 顶栏 底部     手机端 侧边栏 底栏

### 内容方向

这里是倾丞の小窝,记录倾丞的个人生活感触,这里是一个温馨的港湾,你可以与我进行心灵的交流,心随我意,路行千里。
我已经在爱发电进行支持，祝项目组越办越好！

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。
