### ISSUE TITLE
Echocbx的异次元-申请更改

### ISSUE THREAD

**Issue by Ezgx** [travellings-link/travellings#1594]
### 网站名称

Aegcbx的博客

### 网站网址

https://uu.sssu.us/

### 徽标位置

导航栏

### 内容方向

分享科技与狠活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Ezgx** [comment]
上一次申请的issue号：#1505

**Comment by linlinzzo** [comment]
> 上一次申请的issue号：#1505

是我们还没加上去吗？怎么重复申请了？

**Comment by jiangmiemie** [comment]
已更改，可在https://api.travellings.cn/all中查询
