### ISSUE TITLE
iiiillll 申请收录 

### ISSUE THREAD

**Issue by disfell** [travellings-link/travellings#1595]
### 网站名称

iiiillll

### 网站网址

~~https://www.iiiillll.cn/~~
https://lyp.ink/

### 徽标位置

PC：首页按钮、文章页侧栏；移动端：右下角火箭按钮

### 内容方向

记录生活、学习心得

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all) @disfell
