### ISSUE TITLE
倚栏听风申请加入

### ISSUE THREAD

**Issue by imxhe** [travellings-link/travellings#1596]
### 网站名称

倚栏听风

### 网站网址

https://abaa.cc

### 徽标位置

左侧栏第七个小火车图标

### 内容方向

希望博客记录一下我生活的琐事，分享一下我的经验和心得感悟。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
移动端没能发现开往链接。

**Comment by imxhe** [comment]
移动端链接位于右上角二级菜单最下面处
![移动端](https://img.abaa.cc/img/20230710094633.png)

**Comment by linlinzzo** [comment]
![Screenshot_20230710_100316_mark.via.jpg](https://github.com/travellings-link/travellings/assets/79007796/9302adf2-8821-4c0c-bd34-95e6290b6b07)我这里下拉不了。

**Comment by imxhe** [comment]
我调整了位置，现在应该可以了，麻烦在看一下，谢谢

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all)
