### ISSUE TITLE
沐泽的树洞

### ISSUE THREAD

**Issue by zelihole** [travellings-link/travellings#1598]
### 网站名称

沐泽的树洞

### 网站网址

https://zelihole.github.io/

### 徽标位置

首页顶部和底部

### 内容方向

我的生活和笔记，包括但不限于科技、素描等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by zelihole** [comment]
好的

**Comment by zelihole** [comment]
那么我等我有以后内容整改好了再重新来申请可以吗？

**Comment by Big-Cake-jpg** [comment]
> 那么我等我有以后内容整改好了再重新来申请可以吗？

可以的。
