### ISSUE TITLE
 碳狼's Blog

### ISSUE THREAD

**Issue by carbon-wolf** [travellings-link/travellings#1599]
### 网站名称

 碳狼的博客

### 网站网址

https://coolwolf.tk/

### 徽标位置

顶栏

### 内容方向

科技教程，日常生活之类的

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章的数量有点少，再多更新一点再来吧。

**Comment by carbon-wolf** [comment]
哦哦好的
