### ISSUE TITLE
萌言网

### ISSUE THREAD

**Issue by ZYQzhaochen** [travellings-link/travellings#1601]
### 网站名称

萌言网

### 网站网址

https://moey.cn

### 徽标位置

侧滑栏+页脚

### 内容方向

· 令人感动的句子/语录
· 二次元图片壁纸

非博客网站，主要提供上述的接口服务♥(｡￫v￩｡)♥

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by imxhe** [comment]
老二刺螈了  😂😂

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

> 不怕您笑话，我其实对这类网站的审核要求不是很清楚 XD

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all)
