### ISSUE TITLE
七号中微子

### ISSUE THREAD

**Issue by JollyLight** [travellings-link/travellings#1602]
### 网站名称

七号中微子

### 网站网址

https://jollylight.github.io

### 徽标位置

侧栏

### 内容方向

分享自己的所闻所感、兴趣爱好、以及一些自己的笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by JollyLight** [comment]
域名有更新，更新为：https://neutrino7.top
谢谢

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all)
