### ISSUE TITLE
histone's blog

### ISSUE THREAD

**Issue by HistoneVon** [travellings-link/travellings#1604]
### 网站名称

histone's blog

### 网站网址

https://histonevon.top/

### 徽标位置

网页底部（由于主题原因最适合放在底部，但一打开就能看到）

### 内容方向

分为三个方向
1. 技术：作为程序员，给大家分享自己学到的知识，主要部分
2. 生活：永远热爱生活，工作稳定了，会不定期更新
3. 旅行：十分热爱旅行，将记录自己走过的与看到的

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all)
