### ISSUE TITLE
Histcat's Blog

### ISSUE THREAD

**Issue by JesseJeson** [travellings-link/travellings#1607]
### 网站名称

Histcat's Blog

### 网站网址

https://blog.histcat.top/

### 徽标位置

顶栏

### 内容方向

我的日常分享以及oi笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all)
