### ISSUE TITLE
北方之狼

### ISSUE THREAD

**Issue by GoodBoyboy666** [travellings-link/travellings#1608]
### 网站名称

北方之狼

### 网站网址

https://blog.northwoolf.top

### 徽标位置

顶部

### 内容方向

从原博客独立出来的生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by jiangmiemie** [comment]
[欢迎加入开往的大家庭，5分钟后您可在成员列表中搜索到您的站点。](https://api.travellings.cn/all)

**Comment by HowieHz** [comment]
站长您好

您的域名根据我们的核查，已大致确定您的域名已到期。

我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。

![Image](https://github.com/user-attachments/assets/da079e3d-1622-41f5-83c1-11f68bf1f8c2)
