### ISSUE TITLE
王先森

### ISSUE THREAD

**Issue by 5279314** [travellings-link/travellings#1612]
### 网站名称

王先森

### 网站网址

https://www.boysec.cn

### 徽标位置

顶部，车图标

### 内容方向

分享关于运维、安全、DevOps、Python相关的经验和笔记。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
移动端无法找到开往外链。

**Comment by 5279314** [comment]
> 移动端无法找到开往外链。

移动端已添加

**Comment by Big-Cake-jpg** [comment]
iOS Safari 点击开往外链似乎无法跳转到开往的页面。

**Comment by 5279314** [comment]
> iOS Safari 点击开往外链似乎无法跳转到开往的页面。

已修改，现在应该可以访问了

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。

**Comment by baipin** [comment]
“开往”链接以弹出式窗口显示，这一般会被浏览器拦截，请知悉。

**Comment by linlinzzo** [comment]
已添加到数据库，index=852

**Comment by gxres042** [comment]
尊敬的站长您好，我是开往维护组成员 Restent Ou。

根据巡查，我发现您的站点的开往入口设置了延时跳转，这会导致浏览器判定为 **弹出式窗口 a.k.a. 弹窗** 并拦截。

![图片](https://github.com/travellings-link/travellings/assets/53113178/68da98d2-ef5c-4d6a-a412-f2fbd962b000)

请您在方便时修改一下，谢谢您的理解与支持！

**Comment by 5279314** [comment]
修复了，更新测试无弹窗了，请复查。
