### ISSUE TITLE
Lanbinの知识库

### ISSUE THREAD

**Issue by lanbinshijie** [travellings-link/travellings#1613]
### 网站名称

Lanbinの知识库

### 网站网址

https://lib.lanbin.top/

### 徽标位置

导航栏右侧第一个火车徽标

### 内容方向

九年级学生日常生活、上课笔记、生活随笔、知识分享、硬核知识和开发日记等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by lanbinshijie** [comment]
博客升级期，近两天可能无法正常访问，可以尝试下周看看。

**Comment by lanbinshijie** [comment]
@linlinzzo 请问什么时候 可以开始审核？

**Comment by Big-Cake-jpg** [comment]
不使用代理无法在中国大陆境内访问。
![image](https://github.com/travellings-link/travellings/assets/76810494/f495fbc5-0405-44be-a4e2-f941c8570a8b)

**Comment by lanbinshijie** [comment]
> 不使用代理无法在中国大陆境内访问。 ![image](https://user-images.githubusercontent.com/76810494/259723721-f495fbc5-0405-44be-a4e2-f941c8570a8b.png)

不使用代理可以在大部分中国大陆地区访问。原因尚不明晰，有可能是dns污染。

**Comment by lanbinshijie** [comment]
如果无法访问可以尝试使用移动数据或者手机热点，目前问了很多群友都说可以访问，部分地区的部分运营商出现了类似的情况，确认河北某地区出现了拦截。可以再试试能否访问。

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by jiangmiemie** [comment]
目前被屏蔽为诈骗网址，请检查是否被挂马。 @lanbinshijie

**Comment by lanbinshijie** [comment]
@jiangmiemie 经过排查后发现站点一切正常，可以恢复访问

**Comment by lanbinshijie** [comment]
@Big-Cake-jpg @linlinzzo @imba97 @jiangmiemie

**Comment by jiangmiemie** [comment]
好的。
