### ISSUE TITLE
沐泽的树洞

### ISSUE THREAD

**Issue by zelihole** [travellings-link/travellings#1616]
### 网站名称

沐泽的树洞

### 网站网址

https://zelihole.github.io/

### 徽标位置

电脑端在顶栏和底部都有，手机端仅在底部

### 内容方向

包括但不限于学习笔记、日常、~~我的废话~~。有时候发一些照片。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
博客内的文章有些少，要多写一点哦！观察期的一个月里多记录记录自己的生活吧。

**Comment by zelihole** [comment]
好的呢嘿嘿😁

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
已添加。

**Comment by Luochancy** [comment]
尊敬的站长您好，我是开往现任负责人洛寒兮。
目前根据我们的巡查，您的网站目前涉及 政治敏感 内容。
![IMG_20240504_011743](https://github.com/travellings-link/travellings/assets/86495643/a08c6bfb-cd73-479d-aea6-6b37d0cc0c73)
![IMG_20240504_011726](https://github.com/travellings-link/travellings/assets/86495643/c232327d-48b1-42f4-b3a3-e54636d8095e)
根据开往 2024 年 5 月 3 日版本的开往加入条件中，您的网站已经违反了我们加入条例的第三条：没有违法违规和影响访问体验的内容（如侵入式广告）
![IMG_20240504_011417](https://github.com/travellings-link/travellings/assets/86495643/a4bcce0e-5859-4288-934a-c1ebf53c79b5)
同时，我们根据 Issue 记录发现您前一条 Issue （[#1598](https://github.com/travellings-link/travellings/issues/1598)）曾因为相同问题被我们所驳回。
故在本次巡查后根据我们的规则将警告您请避免再次出现类似情况，如再次因相同问题被他人举报或巡查时检查到将永久驳回您的加入申请。
请您在于 北京时间 2024 年 5 月 4 日后的 7 个自然日内对您的网站进行整改，如超过整改期限，我们也将撤销您的成员资格。
如您对本违规警告有任何异议可直接在本 Issue 中进行回复。

开往现任负责人 洛寒兮
2024 年 05 月 04 日 (UTC+8)

**Comment by BLxcwg666** [comment]
抽象到家了，，，推荐直接去当主席

**Comment by ltzXiaoYanMo** [comment]
抽象到家了，，，推荐直接去当主席

**Comment by Luochancy** [comment]
您好，您已超过我们所限定的更改时间。根据目前对您站的观察，您并未做出修改。故撤销您的开往成员申请。您可修改网站后再次提交加入申请以恢复您的开往成员资格。
洛寒兮
2024年5月12日

**Comment by ltzXiaoYanMo** [comment]
主席怎么陨落了
