### ISSUE TITLE
极客郎

### ISSUE THREAD

**Issue by ximfem** [travellings-link/travellings#1618]
### 网站名称

极客郎

### 网站网址

https://ximfem.asia/

### 徽标位置

顶部导航栏

### 内容方向

计算机技术、网络技术等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by linlinzzo** [comment]
电脑端没有看到开往链接。

**Comment by linlinzzo** [comment]
哦，刚才没注意看。

**Comment by linlinzzo** [comment]
已添加到数据库，index=853

**Comment by xuanzhi33** [comment]
![image](https://github.com/travellings-link/travellings/assets/37460139/bc81e5ec-7ae5-466d-94d9-e9bd48eb1941)
您好，已完成修改
