### ISSUE TITLE
Mare_Infinitus

### ISSUE THREAD

**Issue by GrassBlock1** [travellings-link/travellings#1620]
### 网站名称

Mare_Infinitus

### 网站网址

https://lab.imgb.space/

### 徽标位置

桌面端顶部菜单 + 移动端站点标题下方图标

### 内容方向

也观察，也记录，也分享。
主要写些教程，偶尔分享对自己来说非同寻常的日常，以及自己的想法，是一个小杂货铺（？

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by linlinzzo** [comment]
审核通过，等待添加。

**Comment by linlinzzo** [comment]
已添加。
