### ISSUE TITLE
无名小站

### ISSUE THREAD

**Issue by waahah** [travellings-link/travellings#1622]
### 网站名称

无名小站

### 网站网址

https://waahah.xyz/

### 徽标位置

导航栏

### 内容方向

学习记录及笔记，记录分享自己那些年踩过的坑，记录填坑过程以帮助他人少走弯路

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请在显眼的地方添加开往**徽标**，例如网页底部。

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by waahah** [comment]
域名备案期间可能无法访问

**Comment by linlinzzo** [comment]
https://waahah.xyz/2023/09/01/push_sitemap_url_to_baidu_and_bing/

连九月份的文章都发出来了吗？

**Comment by baipin** [comment]
开往放在了默认收起的菜单中，烦请仔细阅读要求，谢谢～
