### ISSUE TITLE
无法打开开往

### ISSUE THREAD

**Issue by Bluemangoo** [travellings-link/travellings#1624]
![image](https://github.com/travellings-link/travellings/assets/63218454/617d62d4-f2d5-486e-b336-76fc20a81407)

以下链接全部试过了都是这样：
- [x] https://www.travellings.cn/go.html
- [x] https://www.travellings.cn/
- [x] https://travellings.cn/go.html
- [x] https://travellings.cn/

其它信息：
- 直连、代理都尝试过了，确认不是我的问题
- 我的ISP：`Chinanet (AS4134 CHINANET-BACKBONE)`

**Comment by Bluemangoo** [comment]
另外，
![image](https://github.com/travellings-link/travellings/assets/63218454/08a1cacb-0412-4cae-9668-d3300be908aa)

**Comment by jiangmiemie** [comment]
开往正处于更换服务器的状态，预计2周左右

**Comment by Bluemangoo** [comment]
你可以暂时把这个issue pin起来。

**Comment by jiangmiemie** [comment]
已PIN并在README文件显眼位置增加通知
