### ISSUE TITLE
lomtom

### ISSUE THREAD

**Issue by lomtom** [travellings-link/travellings#1628]
### 网站名称

lomtom

### 网站网址

https://lomtom.cn

### 徽标位置

网页底部

### 内容方向

有关go、k8s等笔记

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
@BLxcwg666 请您复查一下，如果没有问题，打上“审核通过”标签。
