### ISSUE TITLE
资源管理器博客-已修复

### ISSUE THREAD

**Issue by ZYGLQexplorer** [travellings-link/travellings#1630]
### 网站名称

资源管理器博客

### 网站网址

https://www.zyglq.cn/

### 徽标位置

顶栏

### 内容方向

个人的经验分享
上次申请issue: #956 网站号 518
迁移后忘记添加回来 现已重新添加 

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
出于安全考虑，我**个人推荐**将您的网站提交到 https://hstspreload.org/?domain=zyglq.cn 。

**Comment by linlinzzo** [comment]
已经把您的网站的状态从LOST改为RUN。
