### ISSUE TITLE
玖久的小窝

### ISSUE THREAD

**Issue by jiusi1314** [travellings-link/travellings#1632]
### 网站名称

玖久的小窝

### 网站网址

https://blog.zhuxu.xyz/

### 徽标位置

网页底部

### 内容方向

记录生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
个人推荐开启 HSTS，并提交到 https://hstspreload.org/ 。

**Comment by linlinzzo** [comment]
已经添加到数据库，index=855。
