### ISSUE TITLE
林墨白的博客

### ISSUE THREAD

**Issue by LMB520** [travellings-link/travellings#1633]
### 网站名称

LMB’Blog

### 网站网址

https://blog.lmb520.cn/

### 徽标位置

网页底部(因为模板的特殊性所以只有底部，但是全站为灰白色，所以黑色的gif很显眼)

### 内容方向

主要分享个人经验和网络教学。主要偏向于typecho和PHP

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/ac141b43-b64b-4831-8d67-608d0cf74b67)

**Comment by LMB520** [comment]
不好意思啊，今天晚上刚好服务器有些问题。稍等我弄好了再申请一次

**Comment by LMB520** [comment]
请求再次审核一下

**Comment by LMB520** [comment]
![Uploading Screenshot_2023_0811_142349.png…]()

**Comment by LMB520** [comment]
![Uploading Screenshot_2023_0811_142349.png…](1111)

**Comment by LMB520** [comment]
![Screenshot_2023_0811_142349](https://github.com/travellings-link/travellings/assets/127305127/97454b21-4703-4880-b168-803ac95bc5e8)

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/0d9a837c-d390-495e-8053-4948b55832ce)
？

**Comment by Big-Cake-jpg** [comment]
已移交组内其他维护者审核。

**Comment by LMB520** [comment]
呃呃呃呃呃呃，不好吧

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
用的 bearsimple 主题？

**Comment by LMB520** [comment]
是的，bearsimple主题。嘎嘎好用，简约不简单

**Comment by linlinzzo** [comment]
8.25观察：**个人建议**将不实用的功能隐藏，比如聊天功能，首先贵站已经完成了ICP备案，有内容审查方面的压力，另外评论功能貌似可以满足读者与您之间的交流？除此之外，个人建议更新一些生活类文章，感觉您网站上的技术相关文章有点水？（）

**Comment by LMB520** [comment]
好的收到，已经移出相关内容。水……呃呃呃呃呃还好吧。主要是自己写的不太精炼吧

**Comment by LMB520** [comment]
我写不来生活，我语文分不及格😭作文一大难题

**Comment by jiangmiemie** [comment]
已添加
