### ISSUE TITLE
蓝莓BLog

### ISSUE THREAD

**Issue by BlueLanM** [travellings-link/travellings#1636]
### 网站名称

LanM蓝莓

### 网站网址

https://lanm.love

### 徽标位置

网页顶部

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
未找到开往外链。

**Comment by BlueLanM** [comment]
> 未找到开往外链。

不好意思，现在已经添加到顶栏了，已重新申请。

**Comment by jiangmiemie** [comment]
您好，开往于8月11号已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站**至少一个月**。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

**Comment by linlinzzo** [comment]
8.25观察：**个人建议**隐藏影响浏览体验的东西，例如我在移动端看您的文章，下面可摆动的小女孩就会影响我的体验。当然这只是建议，根据《开往项目运维规定》基本原则第三条，我们没有权力**要求**您对您的网站做出某种调整。

**Comment by BlueLanM** [comment]
> 

了解，谢谢你的建议

**Comment by HowieHz** [comment]
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/4336ba0d-c458-4362-9747-5a82b2bd9b97)
