### ISSUE TITLE
云晓晨CatchWang

### ISSUE THREAD

**Issue by CatchWang-YXC** [travellings-link/travellings#1638]
### 网站名称

云晓晨CatchWang

### 网站网址

https://www.catchwang.com

### 徽标位置

网站底部：友链接力

### 内容方向

技术类 & 生活类 文章

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
目前网站无法访问。 403 Forbidden

**Comment by CatchWang-YXC** [comment]
修改站点链接，改为 https://blog.catchwang.com

**Comment by jiangmiemie** [comment]
9月26号11点整，站点无法访问：找不到 blog.catchwang.com 的服务器 IP 地址。
