### ISSUE TITLE
蓝莓のBlog

### ISSUE THREAD

**Issue by BlueLanM** [travellings-link/travellings#1640]
### 网站名称

LanM蓝莓

### 网站网址

https://lanm.love

### 徽标位置

网页顶栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
很不错的主题，开往于8月16号已收到您的申请，根据规则修改 6339667 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

您的技术栈与开往发展方向一致，如对开往维护开发感兴趣可申请加入技术组。
