### ISSUE TITLE
烙饼的碎碎念

### ISSUE THREAD

**Issue by laobinghu** [travellings-link/travellings#1647]
### 网站名称

烙饼的碎碎念

### 网站网址

https://laobinghu.top

### 徽标位置

网页底部

### 内容方向

个人的日常，学习的经历，生活的感想

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
您好，开往于8月11日已收到您的申请，根据规则 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 

您的博客⛔ 网页上的内容过少，博文只有几篇

建议✅ 内容更新充盈后再来申请试试。
