### ISSUE TITLE
棋`小站

### ISSUE THREAD

**Issue by qi1x** [travellings-link/travellings#1652]
### 网站名称

棋`小站

### 网站网址

https://blog.qi1.zone

### 徽标位置

侧栏

### 内容方向

以科技前沿、Python学习为主。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by qi1x** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月17日(星期四) 晚上10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [travellings-link/travellings] 棋`小站 (Issue #1652)





 
您好，开往已收到您的申请，根据规则修改 6339667 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by jiangmiemie** [comment]
已添加

**Comment by HowieHz** [comment]
最新地址 https://imqi1.com/
