### ISSUE TITLE
gcnanmu的博客

### ISSUE THREAD

**Issue by ldm0715** [travellings-link/travellings#1654]
### 网站名称

gcnanmuの博客

### 网站网址

https://hexo.gcnanmu3125.xyz

### 徽标位置

顶部菜单栏，网页底部

### 内容方向

个人的项目，一些简单实用的教程

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
文章数量有点少，多写写再来吧。

**Comment by ldm0715** [comment]
> 文章数量有点少，多写写再来吧。

按道理来说已经达到README中的数量要求，而且我没有一篇是转载

**Comment by ldm0715** [comment]
> 文章数量有点少，多写写再来吧。

了解，请更新README中关于文章数量的要求
