### ISSUE TITLE
正如的部落格

### ISSUE THREAD

**Issue by dongzhengru** [travellings-link/travellings#1655]
### 网站名称

正如的部落格

### 网站网址

https://blog.zhengru.top/

### 徽标位置

nav-right、footer

### 内容方向

这里有关于Java前后端开发的笔记，希望这些知识能对你有帮助。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
很不错的主题，开往于8月16号已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
