### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by Viper373** [travellings-link/travellings#1657]
### 网站名称

Viper3の小破站

### 网站网址

https://viper3.top

### 徽标位置

顶栏

### 内容方向

Repetition is the best teacher

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
推荐在页面底部添加开往LOGO链接。另外，移动端页面的访问体验不太好。

**Comment by Viper373** [comment]
您好，页面底部已添加，另外移动端的访问体验具体体现在哪些方面

**Comment by linlinzzo** [comment]
> 另外移动端的访问体验具体体现在哪些方面

移动端页面底部的 Label 挤在一块，页面卡顿，等等。

**Comment by Viper373** [comment]
已通过footer-pc.php与footer-mobile.php将移动端与PC/平板端区分，另外安装redis扩展与redis对象缓存插件，最后由于该域名使用腾讯CDN加速，在南方的访问体验可能稍差，本人北方，用了若干个设备测试，无大的问题（找南方的朋友测试过）

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们会继续观察您的博客一段时间。在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始算起。

**Comment by Viper373** [comment]
辛苦，感谢！
