### ISSUE TITLE
旋律的博客

### ISSUE THREAD

**Issue by JohnsonRan** [travellings-link/travellings#1665]
### 网站名称

旋律的博客

### 网站网址

https://e11z.net

### 徽标位置

侧栏

### 内容方向

记录自己遇到一些问题的解决方法

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
请使用新的开往链接。

**Comment by JohnsonRan** [comment]
> 请使用新的开往链接。

已经改掉了

**Comment by linlinzzo** [comment]
> 已经改掉了

麻烦请改为 https://www.travellings.cn/go.html ，谢谢。

**Comment by JohnsonRan** [comment]
> > 已经改掉了
> 
> 麻烦请改为 https://www.travellings.cn/go.html ，谢谢。

改掉了（虽然回的有点晚了

**Comment by Big-Cake-jpg** [comment]
抱歉，您的文章数量不足 20 篇，再多写一段时间吧😉
