### ISSUE TITLE
桜紺狸の部落阁

### ISSUE THREAD

**Issue by lemonstable** [travellings-link/travellings#1671]
### 网站名称

桜紺狸の部落阁

### 网站网址

https://www.skira.top

### 徽标位置

顶栏右上角

### 内容方向

一个闲聊萌新动漫技术交流站

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。

另：移动端无法在页面右上角找到开往外链。

**Comment by lemonstable** [comment]
已在移动端内添加开往，移动端可在侧边栏内，友链选项中找到开往

**Comment by lemonstable** [comment]
已在移动端内添加开往，移动端可在侧边栏内，友链选项中找到开往
