### ISSUE TITLE
TheIce

### ISSUE THREAD

**Issue by TheIce08** [travellings-link/travellings#1673]
### 网站名称

TheIce

### 网站网址

https://blog.081113.xyz/

### 徽标位置

顶栏右侧

### 内容方向

技术与个人生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by TheIce08** [comment]
移动端导航栏太小塞不下了 塞到页脚了 虽然但是...

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。
