### ISSUE TITLE
南栀 Space

### ISSUE THREAD

**Issue by nanzhi63** [travellings-link/travellings#1674]
### 网站名称

南栀 Space

### 网站网址

https://litkg.com

### 徽标位置

手机端只能在网页底部查看，pc端在右上角和网页底部查看

### 内容方向

二次元&数码知识

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
抱歉，您的网站不符合开往对成员网站文章的要求。
