### ISSUE TITLE
619's Blog

### ISSUE THREAD

**Issue by lifeafter619** [travellings-link/travellings#1677]
### 网站名称

619's Blog

### 网站网址

https://66619.eu.org/

### 徽标位置

顶栏，顶部“此刻”滚动栏，侧边公告栏

### 内容方向

撰写和分享学习和生活相关的的文章和自己制作项目的文章

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
文章不够 20 篇哦......再多写一段时间吧。

**Comment by Big-Cake-jpg** [comment]
> ![image](https://user-images.githubusercontent.com/65111206/263877003-0a1bb614-8610-4a81-a58d-412c4db89004.png) 我的文章纯原创，超过你们10篇的要求了 不过我再写写吧....

是这样吗......抱歉了，我一直以 20 篇的标准来审核成员网站，个人认为这样的门槛可能更低一点......

目前没有发现什么问题。根据规则修改 6339667 中的内容，我们将继续观察您的博客一段时间，在此期间烦请稍作等待，多谢理解。观察期从收到本消息起开始计算。

**Comment by lifeafter619** [comment]
感谢！
