### ISSUE TITLE
meiのblog

### ISSUE THREAD

**Issue by ssdomei232** [travellings-link/travellings#1679]
### 网站名称

meiのblog

### 网站网址

https://mmeiblog.cn/

### 徽标位置

顶栏

### 内容方向

一个倒霉蛋的博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
iOS Safari 无法展开折叠的侧栏，站内也无法找到开往外链。

**Comment by baipin** [comment]
无论是墙内墙外，打开都非常慢。此外，侧脸用Android的最新版Chrome也无法打开。还请复检～

**Comment by ssdomei232** [comment]
emm...手机端的侧边栏应该是blog主题的原因，我也不知道怎么解决，那个主题也经常犯病，我打算有空了找个好看的换了。打开慢是因为服务器拉跨，1h1g跑的halo，甚至需要经常手动重启，不过当时一次性买了半年，只能等到春节再换服务器了,开往在上方导航栏从左往右数第4个(

**Comment by ssdomei232** [comment]
不过我并没有考虑过海外地区的访问体验，海外地区解析了一个防止被ddos的ip，几乎没有访问体验，只是能看，因为我觉得老外应该不会看这玩意吧(  
静态的图片资源大部分都做了国内加速(

**Comment by baipin** [comment]
今天香港教育网访问正常

**Comment by baipin** [comment]
但是侧栏仍然无法打开

**Comment by ssdomei232** [comment]
目前已经修复了手机端侧栏无法展开的问题，不过并不能确定是什么原因造成的，因为我直接把主题重置了(

**Comment by ssdomei232** [comment]
不过重置以后所有问题居然都消失了，果然重装能够解决99%的问题(

**Comment by ssdomei232** [comment]
不过河南地区最近屏蔽了一车域名，可能无法正常访问

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 `6339667` 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。
