### ISSUE TITLE
没有楼的楼长的博客

### ISSUE THREAD

**Issue by ACnoway** [travellings-link/travellings#1680]
### 网站名称

没有楼的楼长的博客

### 网站网址

https://blog.imlzhyt.top/

### 徽标位置

顶栏左侧

### 内容方向

OI相关知识，以及个人的乱搞记录，我就是一天把服务器搞坏三次的乱搞小王子！

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。

**Comment by ACnoway** [comment]
更改了徽标位置，在页面最底部部分，麻烦了
