### ISSUE TITLE
牛牛技术客栈申请收录

### ISSUE THREAD

**Issue by tdxs** [travellings-link/travellings#1682]
### 网站名称

牛牛技术客栈

### 网站网址

https://www.nnjskz.cn/

### 徽标位置

底部

### 内容方向

技术，生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by tdxs** [comment]
审核官你好，请问我这网站有什么问题吗？

**Comment by jiangmiemie** [comment]
通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
