### ISSUE TITLE
AYX's Blog

### ISSUE THREAD

**Issue by Annran233** [travellings-link/travellings#1685]
### 网站名称

AYX's Blog

### 网站网址

https://ayx.669.ink

### 徽标位置

顶栏&网页底部

### 内容方向

个人生活，技术，还有视频文字稿一类的

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
嗯......文章数量仅有四篇，但开往要求至少有 20 篇文章。或许您可以尝试回忆一下之前写过的文章然后补上？

**Comment by jiangmiemie** [comment]
一个和审核无关的建议：

样式很好看，但是鼠标悬浮异常，鼠标放在开往上最右侧也会出现悬浮效果，发现是你DIV闭标签的位置放错了。改过来就行了。
![image](https://github.com/travellings-link/travellings/assets/69161207/a559fc6b-50ca-469c-b4c5-b6b1579749cd)
@Annran233

**Comment by Annran233** [comment]
博客炸了好几回了，文章丢了好几篇了...尽量补上

**Comment by jiangmiemie** [comment]
> 博客炸了好几回了，文章丢了好几篇了...尽量补上

您的站点似乎已经无法访问，恢复访问后可在此issue下回复以重新打开。

**Comment by baipin** [comment]
复检仍无法打开。

**Comment by Chenli-L** [comment]
如果复检第三次仍然打不开的话，不好意思。你的网站无法继续参与审核。下次请不要把你的狗屁垃圾网站提交给大家的开往大平台。真贱，浪费我们审核和开发者的时间。
