### ISSUE TITLE
龙鲲博客

### ISSUE THREAD

**Issue by beiminglongkun** [travellings-link/travellings#1686]
### 网站名称

龙鲲博客

### 网站网址

https://lkblog.net

### 徽标位置

顶部菜单

### 内容方向

生活记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。

**Comment by Chenli-L** [comment]
你好，感谢每一个贡献者。但是我尚未没有加入成功，我加上这个入口，那我这不就只是一个门口吗🤒
