### ISSUE TITLE
Shiroha 白羽的博客

### ISSUE THREAD

**Issue by Hukeqing** [travellings-link/travellings#1687]
### 网站名称

Shiroha 白羽的博客

### 网站网址

https://blog.mauve.icu

### 徽标位置

绝大部分页面的顶栏

### 内容方向

个人的学习、思考、生活分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Hukeqing** [comment]
P.S. 有 cf 的镜像地址 [https://blog-mirror.mauve.icu](https://blog-mirror.mauve.icu)，原地址为 GitHub Pages，若国内访问不稳定可以改用镜像地址

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。
