### ISSUE TITLE
SunnyLi's Blog

### ISSUE THREAD

**Issue by SunnyLi1106** [travellings-link/travellings#1689]
### 网站名称

SunnyLi's Blog

### 网站网址

https://sunnyli.xn--9traa.eu.org

### 徽标位置

顶部菜单

### 内容方向

分享OI与物理知识和平常信息技术的经验

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by jiangmiemie** [comment]
通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
