### ISSUE TITLE
Carol 小屋

### ISSUE THREAD

**Issue by carolcoral** [travellings-link/travellings#1690]
### 网站名称

Carol 小屋

### 网站网址

https://blog.cnkj.site

### 徽标位置

顶栏

### 内容方向

* 技术开发

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/88af1dda-9637-4dda-8496-ec1fd57e0e16)
建议修改重定向逻辑。

**Comment by carolcoral** [comment]
@Big-Cake-jpg 站点没有设置阻止，应该是你浏览器问题？我刚才尝试使用safari和chrome都可以正常打开：
<img width="1491" alt="image" src="https://github.com/travellings-link/travellings/assets/8952687/9f1f24e5-6225-4df7-94fd-b957768a091c">

**Comment by baipin** [comment]
1.手机版看不见开往连接
2.电脑版『开往』以弹出式窗口显示，这一般会遭到浏览器的拦截，请知悉～
