### ISSUE TITLE
彬红茶博客

### ISSUE THREAD

**Issue by binhongtea** [travellings-link/travellings#1691]
### 网站名称

彬红茶博客

### 网站网址

https://blog.binhongtea.top

### 徽标位置

网页底部，网页首页公告，图片

### 内容方向

分享博客，知识以及个人分享，希望在生活帮到大家

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by binhongtea** [comment]
首页轮播图有travelling的图片 请审核查看首页轮播图

**Comment by binhongtea** [comment]
首页轮播图有travelling的图片 请审核查看首页轮播图

**Comment by binhongtea** [comment]
底部栏也有!求审核通过，轮播图和底部栏都有了!

**Comment by BCTX2010** [comment]
您好，您的站点看上去没有什么问题。
根据[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)条例，我们会对您的网站进行一个月的观察期。在一个月后，您将正式进入开往。感谢支持！

**Comment by linlinzzo** [comment]
@BCTX2010 观察期后会再审一次，不一定意味着通过。

**Comment by jiangmiemie** [comment]
通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
