### ISSUE TITLE
Kidwen's Blog

### ISSUE THREAD

**Issue by kidwen** [travellings-link/travellings#1692]
### 网站名称

Kidwen's Blog

### 网站网址

https://blog.kidwen.top

### 徽标位置

顶栏

### 内容方向

技术笔记，热爱生活。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BCTX2010** [comment]
您好，您的站点看上去没有什么问题。
根据[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)条例，我们会对您的网站进行一个月的观察期。在一个月后，您将正式进入开往。感谢支持！

**Comment by jiangmiemie** [comment]
通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
