### ISSUE TITLE
Lumirant's Blog

### ISSUE THREAD

**Issue by lumirant** [travellings-link/travellings#1693]
### 网站名称

Lumirant's Blog

### 网站网址

https://blog.lumirant.top/

### 徽标位置

侧栏

### 内容方向

会发平一些时生活中发生的趣事，以及对这些事的感受等，也会分享有关技术方面的知识，或者是我做的一些小项目

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/travellings-link/travellings/assets/76810494/e7032762-6c52-49c5-b5de-90fab2bf3367)

**Comment by iridescent6911** [comment]
您的邮件已收到，我将会在三周内对有需要回复的邮件进行回复，请耐心等候，如三周内未收到回信，可重复发送该邮件

**Comment by iridescent6911** [comment]
不好意思，服务器Nginx防火墙的策略默认会阻止海外IP和VPN代理访问，已经将这个策略停止了，可以再审核一次吗

**Comment by jiangmiemie** [comment]
根据规则修改 6339667 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

**Comment by lumirant** [comment]
您的邮件已收到，我将会在三周内对有需要回复的邮件进行回复，请耐心等候，如三周内未收到回信，可重复发送该邮件
