### ISSUE TITLE
Chenli

### ISSUE THREAD

**Issue by Chenli-L** [travellings-link/travellings#1695]
### 网站名称

二月初二

### 网站网址

https://www.chenliss.cn/

### 徽标位置

底栏

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Chenli-L** [comment]
不好意思，我想问一下，观察期间我能获得别人来我博客的通道吗

**Comment by linlinzzo** [comment]
> 不好意思，我想问一下，观察期间我能获得别人来我博客的通道吗

抱歉，没有办法。

**Comment by linlinzzo** [comment]
对不起，您的网站不满足开往对成员网站文章数量的要求。

**Comment by Chenli-L** [comment]
噢，好的
