### ISSUE TITLE
刑辩人在路上

### ISSUE THREAD

**Issue by defender1989** [travellings-link/travellings#1696]
### 网站名称

刑辩人在路上

### 网站网址

https://xingbianren.cn

### 徽标位置

网页底部

### 内容方向

80后刑辩律师的办案手记。专注无罪辩护。反抗者的灵魂从未远去。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by defender1989** [comment]
友链位置调整到了侧边栏

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
个人**推荐**将开往徽标放置在显眼位置。

**Comment by defender1989** [comment]
我非常想这样做，可是我不会写代码😅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月9日(周六) 晚上11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [travellings-link/travellings] 刑辩人在路上 (Issue #1696)




 
个人推荐将开往徽标放置在显眼位置。

**Comment by jiangmiemie** [comment]
通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
