### ISSUE TITLE
Bing🐣

### ISSUE THREAD

**Issue by liub1934** [travellings-link/travellings#1698]
### 网站名称

Bing🐣

### 网站网址

https://liubing.me/

### 徽标位置

菜单栏右侧区域

### 内容方向

个人前端开发记录及个人收集的站点导航。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
@jiangmiemie 技术类博客您看一下吧，我不太懂得看。

**Comment by jiangmiemie** [comment]
这个站点很优质，根据规则修改 6339667 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

**Comment by jiangmiemie** [comment]
通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
