### ISSUE TITLE
FANTASY博客申请收录

### ISSUE THREAD

**Issue by sexyxlyWAol** [travellings-link/travellings#17]
## 网站名称
FANTASY博客
## 网站链接
https://blog.tigerxly.com/
## 徽标位置
右侧栏
## 推荐理由
看见朋友分享，觉得这个想法很妙。

**Comment by volfclub** [comment]
已收录

**Comment by vanfantasy2333** [comment]
FANTASY博客采用jsdelivr+github直接引入js的方式接入travelling，此更改对FANTASY博客无影响，感谢提醒

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by sexyxlyWAol** [comment]
FANTASY博客采用jsdelivr+github直接引入js的方式接入travelling，此更改对FANTASY博客无影响，感谢提醒

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现您未开启SSL，现已将您移除，如需加入开往，可再次按照流程申请。

**Comment by sexyxlyWAol** [comment]
感谢提醒，已修复问题，希望能直接恢复travellings名单，若您无法直接恢复，我明天重新申请，谢谢！

**Comment by jiangmiemie** [comment]
已直接恢复 @sexyxlyWAol

**Comment by HowieHz** [comment]
站长您好，经过人工巡查，发现您站点开往外链被设置为 `https://blog.tigerxly.com/travelling`，
这不是一个巡查范围内的开往外链，会导致巡查机无法正确检查外链状态，也无法通过开往跳转服务导航到您的站点。
请将页面上错误的开往外链替换为以下其中之一的链接来修复这个问题
```plaintext
https://www.travellings.cn/go.html
https://www.travellings.cn/plain.html
https://www.travellings.cn/coder-1024.html
https://www.travellings.cn/go-by-clouds.html
```

**Comment by sexyxlyWAol** [comment]
已更改，谢谢提醒

**Comment by HowieHz** [comment]
> 已更改，谢谢提醒

🤝感谢您对我们工作的配合，祝您生活愉快
