### ISSUE TITLE
云晓晨CatchWang

### ISSUE THREAD

**Issue by CatchWang-YXC** [travellings-link/travellings#1701]
### 网站名称

友链接力

### 网站网址

https://blog.catchwang.com

### 徽标位置

底部

### 内容方向

个人博客文章

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
目前没有发现什么问题。

您好，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by linlinzzo** [comment]
推荐将开往链接换用 www.travellings.cn，这样可以用国内CDN优化国内用户访问。

**Comment by CatchWang-YXC** [comment]
> 推荐将开往链接换用 [www.travellings.cn](http://www.travellings.cn) ，这样可以用国内CDN优化国内用户访问。

好滴，这就去改下

**Comment by jiangmiemie** [comment]
站点已无法打开
