### ISSUE TITLE
O泡

### ISSUE THREAD

**Issue by 40699523** [travellings-link/travellings#1702]
### 网站名称

O泡

### 网站网址

https://www.opw.cc/

### 徽标位置

右上

### 内容方向

生活，笔记，

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
https://blog.opw.cc/  似乎没有解析

**Comment by 40699523** [comment]
能打开了

**Comment by jiangmiemie** [comment]
根据规则修改 6339667 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
