### ISSUE TITLE
网站域名更换 - 1nonly's blog

### ISSUE THREAD

**Issue by ayorishy** [travellings-link/travellings#1706]
> 网站编号：772
> 
> 
> 
> ## 网站名称
> 💡从1nonly'sblog 更换为 ayorishy's blog
> 
> ## 网站网址
> * 💡从 https://blog.nonly.cn/ 更换为 https://blog.ban.moe
> * 网站状态： ![ayorishy's blog](https://camo.githubusercontent.com/a0c3c90dd7c230dd6aefd04dd703115a2d2d667a5104cdd5b67ff2603c5f3676/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470733a2f2f626c6f672e3233696b722e636f6d)
> 
> ## 徽标位置
> * 💡 侧栏
> 
> ### 请确认一下事项
> * [x]   我已确认以上事项

**Comment by jiangmiemie** [comment]
已处理，可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
