### ISSUE TITLE
静雨▪安蝉

### ISSUE THREAD

**Issue by kwxos** [travellings-link/travellings#1708]
### 网站名称

静雨▪安蝉

### 网站网址

https://blog.kwxos.top

### 徽标位置

顶栏，页尾

### 内容方向

世间万物，美景，生活，教程

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
手机版顶栏未见开往链接，烦请复检～

**Comment by baipin** [comment]
另外，电脑端开往也以弹出式窗口展示，这一般会遭到浏览器拦截，请知悉～

**Comment by baipin** [comment]
1.手机版看不见开往连接
2.电脑版『开往』以弹出式窗口显示，这一般会遭到浏览器的拦截，请知悉～

**Comment by kwxos** [comment]
顶栏页尾都有链接，顶栏手机版消失，是主题问题，并非我的问题

**Comment by baipin** [comment]
> 顶栏页尾都有链接，顶栏手机版消失，是主题问题，并非我的问题

主题你是可以修改的，建议手机版将开往链接放在菜单里。
