### ISSUE TITLE
lveMonsiのBlog

### ISSUE THREAD

**Issue by lveMonsi** [travellings-link/travellings#1711]
### 网站名称

lveMonsiのBlog

### 网站网址

https://blog.lvems.top

### 徽标位置

菜单栏

### 内容方向

技术分享、精品资源分享、记录生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
虽然纯原创内容不多，但是二创也算原创，期待后续更新更多原创好文，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
