### ISSUE TITLE
荒野孤灯

### ISSUE THREAD

**Issue by hygd0813** [travellings-link/travellings#1713]
### 网站名称

荒野孤灯

### 网站网址

https://www.80srz.com

### 徽标位置

头部

### 内容方向

typecho建站，个人生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
站点符合相关要求。
您好，开往已收到您的申请，根据规则修改 6339667 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）
