### ISSUE TITLE
极客指北申请收录

### ISSUE THREAD

**Issue by xmdesign6** [travellings-link/travellings#1716]
### 网站名称

极客指北

### 网站网址

https://www.90svip.cn/

### 徽标位置

网站导航栏

### 内容方向

探索科技之路，分享美好生活！

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或回复决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可以在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
