### ISSUE TITLE
LeZi的猫窝

### ISSUE THREAD

**Issue by LeZi04919** [travellings-link/travellings#1717]
### 网站名称

LeZi的猫窝

### 网站网址

https://leziblog.cn

### 徽标位置

菜单栏、首屏头像正下方

### 内容方向

技术分享、日常生活的碎碎念

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或回复决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可以在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
