### ISSUE TITLE
ADYUN

### ISSUE THREAD

**Issue by Adyun** [travellings-link/travellings#1718]
### 网站名称

ADYUN

### 网站网址

https://blog.adyun.design

### 徽标位置

顶栏右侧按钮

### 内容方向

记录分享设计、技术与生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
站点很优质，但是手机端的开往未显示。

**Comment by Adyun** [comment]
手机端已添加

**Comment by jiangmiemie** [comment]
根据规则https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或回复前决定至少将观察您的网站一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可以在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
