### ISSUE TITLE
小窝哟

### ISSUE THREAD

**Issue by XiaoWouU** [travellings-link/travellings#1719]
### 网站名称

小窝哟

### 网站网址

https://blog.528688.cn/

### 徽标位置

顶部

### 内容方向

学习网络知识、积累兴趣的地方.

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
站点很优质，但是手机端的开往未显示。

**Comment by XiaoWouU** [comment]
> 站点很优质，但是手机端的开往未显示。

正在改进

**Comment by jiangmiemie** [comment]
好的，优化完成后可以在此issue下回复重新申请审核。
