### ISSUE TITLE
takami's Crafted Pages

### ISSUE THREAD

**Issue by strangeZombies** [travellings-link/travellings#1724]
### 网站名称

takami's Crafted Pages

### 网站网址

https://page.takami.cyou

### 徽标位置

顶栏;网页底部

### 内容方向

一个敢于表达懦弱与失落的小透明，在社会边缘探索、倡导与行动，试图呈现的仍只不过是一处普遍的小树洞。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
已收到申请，站点内容与开往位置均符合要求。

但是你的响应时间有点异常，普遍响应速度较慢，检查你的网页加载顺序发现了一些css加载较慢，另外对于连接速度较慢的用户，通过 document.write() 动态注入的外部脚本会将网页加载延迟数十秒。可以考虑从这两个地方优化。优化后在https://boce.aliyun.com/detect/http 测试查看。如果响应时长过长，大部分检测程序都会杀掉这个站点认为无法连通。

![image](https://github.com/travellings-link/travellings/assets/69161207/45ca7f95-70e9-4e3e-ac3e-9d7a8659bd90)

![image](https://github.com/travellings-link/travellings/assets/69161207/8cd9e5ac-36a8-47ea-ae72-3893d28dc1c7)
