### ISSUE TITLE
彬红茶主页

### ISSUE THREAD

**Issue by binhongtea** [travellings-link/travellings#1726]
### 网站名称

彬红茶的个人主页

### 网站网址

https://binhongtea.top

### 徽标位置

首页大厅按钮，好友列表

### 内容方向

我的个人主页，导航到我的其他网站，如博客，技术等

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
站点内容没有什么问题，但是站点时间较短，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，观察期会适当延长。通过申请后，您可以在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
