### ISSUE TITLE
Joker2Yue的个人博客

### ISSUE THREAD

**Issue by Joker2Yue** [travellings-link/travellings#1728]
### 网站名称

Joker2Yue的个人博客

### 网站网址

https://blog.joker2yue.cn/

### 徽标位置

顶栏

### 内容方向

我的学习路程，心得与体会。生活、分享和感悟

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
无法打开，请站长确认站点状态。

**Comment by Joker2Yue** [comment]
已解决，请收录

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算，2023/10/18）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
