### ISSUE TITLE
链接出现故障

### ISSUE THREAD

**Issue by powerfullz** [travellings-link/travellings#1729]
有www前缀的开往域名无法使用，但没有www前缀的可以，大多数成员指向的都是有www的域名，导致现在几乎没法接力。

![图片](https://github.com/travellings-link/travellings/assets/61956140/05d7f403-576a-4552-ad08-a9dc04bdf0c7)

https://travellings.cn/go.html

目前只有这个链接能用，是不是伪静态写错了？

**Comment by linlinzzo** [comment]
您好，链接 https://www.travellings.cn/go.html 是可用的。如果您访问这个链接会出现跳转到 https://www.travellings.cn/go 的情况，麻烦您更新一下浏览器缓存。

**Comment by powerfullz** [comment]
抱歉，看来是我浏览器缓存的问题。
