### ISSUE TITLE
小u的个人博客

### ISSUE THREAD

**Issue by xiaou61** [travellings-link/travellings#1731]
### 网站名称

小u的个人博客

### 网站网址

https://newblog.guoyaxue.top/

### 徽标位置

右上角

### 内容方向

Java,java,springboot,mysql,redis,教程,git,软件,编程,开发,互联网,Java 基础,Java 教程,Java程序员进阶之路,Java 入门,Vue,前端,算法

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，我在移动端没能看到开往链接。另外，建议将域名直接解析到博客所在的空间，减少跳转。

**Comment by Big-Cake-jpg** [comment]
草，为什么是腾讯云 COS……

**Comment by xiaou61** [comment]
我一直用的是腾讯云的cos服务，下面是经过解析的地址
http://blog.xiaou61.top/
