### ISSUE TITLE
Ciics' Blog

### ISSUE THREAD

**Issue by moestd** [travellings-link/travellings#1734]
### 网站名称

Ciics' Blog

### 网站网址

https://www.c2ics.com

### 徽标位置

顶部导航栏, 页脚, 侧边栏底部

### 内容方向

生活，学习的技术，教程。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或回复前决定至少将观察您的网站一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可以在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
