### ISSUE TITLE
申请修改网站名称和域名

### ISSUE THREAD

**Issue by yunfanch** [travellings-link/travellings#1735]
### 网站名称

乙未博客

### 网站网址

https://yvii.cn/

### 徽标位置

顶栏

### 内容方向

原站  云帆沧海  yf-ch.com    202    申请修改信息

网站名称：乙未博客
网站域名：https://yvii.cn/
网站介绍：记录生活，分享与留存。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
已在原issue下处理
