### ISSUE TITLE
Idylaxity的个人空间

### ISSUE THREAD

**Issue by qaoxiang** [travellings-link/travellings#1737]
### 网站名称

Idylaxity的个人空间

### 网站网址

https://blog.qaoxiang.top/

### 徽标位置

顶栏

### 内容方向

建站，个人生活中发生的趣事，以及对这些事的感受等，也会分享有关技术方面的知识，或者是我做的一些小项目

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

**Comment by qaoxiang** [comment]
你好，本站名字已经更改，改为了“末羽酱”。希望你能抽出时间来更新一下信息谢谢。
