### ISSUE TITLE
愚人呓语集

### ISSUE THREAD

**Issue by ZHEYESHIYU** [travellings-link/travellings#1738]
### 网站名称

愚人呓语集

### 网站网址

https://www.yurenyiyuji.top/

### 徽标位置

导航栏（PC顶部，移动侧边）

### 内容方向

成长经历，随笔，读书笔记，评论文章

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
