### ISSUE TITLE
Diffday

### ISSUE THREAD

**Issue by diffday** [travellings-link/travellings#1740]
### 网站名称

Diffday的博客

### 网站网址

https://blog.diffday.com

### 徽标位置

电脑端网页顶栏

### 内容方向

读书笔记，生活感悟，技术总结

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
站点很优质，添加手机端即可。添加后可在此issue下@我

**Comment by diffday** [comment]
@jiangmiemie 手机端已添加

**Comment by jiangmiemie** [comment]
收到，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
