### ISSUE TITLE
FoksyM's blog

### ISSUE THREAD

**Issue by FoskyM** [travellings-link/travellings#1741]
### 网站名称

FoksyM's blog

### 网站网址

https://blog.fosky.top

### 徽标位置

侧栏与网页底部

### 内容方向

技术教程，经验分享，日常记录，实用工具

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

**Comment by HowieHz** [comment]
自动跳转 https://space.fosky.top/
修订链接

**Comment by HowieHz** [comment]
站长您好，经过人工巡查，发现您站点未设置开往外链。
这会导致巡查机无法正确检查外链状态，也无法通过开往跳转服务导航到您的站点。
请在页面添加以下其中之一的链接来修复这个问题
```plaintext
https://www.travellings.cn/go.html
https://www.travellings.cn/plain.html
https://www.travellings.cn/coder-1024.html
https://www.travellings.cn/go-by-clouds.html
```
