### ISSUE TITLE
王子高的个人博客

### ISSUE THREAD

**Issue by ZigaoWang** [travellings-link/travellings#1744]
### 网站名称

王子高的个人博客

### 网站网址

https://blog.zigaow.com

### 徽标位置

顶栏

### 内容方向

前端开发知识分享和个人生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
站点模板与文章内容很不错，但是文章数量较少，手机端无法访问开往。可以在更新更多文章之后直接在此issue下@我重新申请。
