### ISSUE TITLE
Tibrella 的隙间

### ISSUE THREAD

**Issue by Pinghigh** [travellings-link/travellings#1752]
### 网站名称

Tibrella 的隙间

### 网站网址

https://blog.tibrella.top/

### 徽标位置

顶栏和底部

### 内容方向

程序设计竞赛
前端
后端
PC 常识
嵌入式开发

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
