### ISSUE TITLE
阿啊阿吖丁 - 丁俊尧的个人网站

### ISSUE THREAD

**Issue by DingJunyao** [travellings-link/travellings#1753]
### 网站名称

阿啊阿吖丁 - 丁俊尧的个人网站

### 网站网址

https://4ading.com

### 徽标位置

顶栏（PC 端）；侧栏（移动端）

### 内容方向

我自己写的一些文章，随笔为主；以及技术相关的文章（目前围绕自己的主业——测试，但也会写一些别的）

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
