### ISSUE TITLE
Oragekk's Blog

### ISSUE THREAD

**Issue by OrageKK** [travellings-link/travellings#1754]
### 网站名称

Oragekk's Blog

### 网站网址

https://oragekk.me/

### 徽标位置

导航栏、footer

### 内容方向

到最后竟庆幸于夕阳仍留在身上，来不及讲故事多跌宕

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。
