### ISSUE TITLE
自游鱼-栗士杰个人博客

### ISSUE THREAD

**Issue by lishijie0821** [travellings-link/travellings#1768]
### 网站名称

自游鱼-栗士杰个人博客

### 网站网址

https://www.ziyouyu.cn/

### 徽标位置

菜单

### 内容方向

个人学习记录、生活唠叨、技术分享等！

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，您的网站不符合开往对新加入成员建站时间的要求。
