### ISSUE TITLE
积跬

### ISSUE THREAD

**Issue by zcwiki** [travellings-link/travellings#1771]
### 网站名称

终成博客

### 网站网址

https://blog.zc.wiki/

### 徽标位置

底部

### 内容方向

个人生活、技术博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by zcwiki** [comment]
徽标位置新增顶部右上

**Comment by jiangmiemie** [comment]
根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

通过申请后，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。

**Comment by zcwiki** [comment]
好像没有在名单中看到，名单似乎还是到912

**Comment by jiangmiemie** [comment]
> 好像没有在名单中看到，名单似乎还是到912

![image](https://github.com/travellings-link/travellings/assets/69161207/60e00219-cbe5-410b-ba9a-6fd6711f4b82)

现在应该能看到了
