### ISSUE TITLE
四月黎明

### ISSUE THREAD

**Issue by superlovelace** [travellings-link/travellings#1781]
### 网站名称

四月黎明

### 网站网址

https://superlovelace.top/

### 徽标位置

顶栏

### 内容方向

分享自己的学习笔记，记录问题解决方法。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
根据加入开往要求，您的博客包含其它维护组成员认为的不适宜内容。故驳回您的加入申请
