### ISSUE TITLE
某科学的贝壳

### ISSUE THREAD

**Issue by biliblihuorong** [travellings-link/travellings#1783]
### 网站名称

某科学的贝壳的博客

### 网站网址

https://blog.ning.moe/

### 徽标位置

左上角 | 网站底部

### 内容方向

Get busy living or get busy dying.

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
少见的较为高质量的技术类博客，咱倒是挺喜欢的，不过咱还是得按照规矩办事嘛~

根据开往规则修改[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)我们在决定您的申请通过或驳回申请前将进行为期至少一个月的观察（当收到本回复之日起作为观察期起始日）。当维护组通过您的审核或驳回您的审核时，本issue将会修改为特定的标签。请您耐心等待~

在审核通过后，您可在[开往成员列表](https://api.travellings.cn/all)检索到您的网站。

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
