### ISSUE TITLE
加入申请

### ISSUE THREAD

**Issue by Annicko** [travellings-link/travellings#1784]
网站名称
Aibei Tech

网站网址
https://bytespaces.com

徽标位置
左上角 

内容方向
👋 愿时光能缓，愿故人不散！

**Comment by linlinzzo** [comment]
@Luochancy 技术类博客交给你来看。

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
