### ISSUE TITLE
QingYu博客

### ISSUE THREAD

**Issue by landaiqin** [travellings-link/travellings#1785]
### 网站名称

QingYu

### 网站网址

https://landaiqing.space/

### 徽标位置

右上角

### 内容方向

清语，一个不轻语的网站~

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
这个网站咱并不太好判断是否该添加进开往成员列表，故邀请其他开往成员共同审查本加入申请。

**Comment by Cubik65536** [comment]
我发现很多信息都是直接从产品介绍页复制来的
虽然有这么个站可以帮助找到需要的东西，但是搜索引擎也行？
我也不是太好判断这个情况，我个人看法是这个站比较像采集站，不是非常合适加入开往

**Comment by linlinzzo** [comment]
对于非生活类博客的网站我不好加以评论，但**个人**主观感觉可能有内容堆砌的嫌疑。

**Comment by linlinzzo** [comment]
> 但好像有人已经把它添加到数据库里了？

我不太清楚是谁...目前有到观察期之后自动添加到数据库吗？

**Comment by Luochancy** [comment]
> > 但好像有人已经把它添加到数据库里了？
> 
> 我不太清楚是谁...目前有到观察期之后自动添加到数据库吗？

应该没有吧，好奇谁加的库

**Comment by jiangmiemie** [comment]
> > 但好像有人已经把它添加到数据库里了？
> 
> 我不太清楚是谁...目前有到观察期之后自动添加到数据库吗？

我有一个相关的代码但是只会生成数据库语句，之后人复制粘贴到另一个地方执行，完全隔离。所以不是这个程序的问题。

最好找到原因，知道数据库密码的人就我们几个，如果是人添加的提醒下就行，就怕是谁的程序判断逻辑写错了。

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~

**Comment by baipin** [comment]
站长您好，经巡查发现阁下网站无法打开，烦请复查，多谢。

**Comment by Big-Cake-jpg** [comment]
超时关闭，您的站点将被移出开往成员列表。

如有意向重新加入，请重新提交一个 Issue。
