### ISSUE TITLE
a.d博客-永远热爱

### ISSUE THREAD

**Issue by 2585570153** [travellings-link/travellings#1786]
### 网站名称

a.d博客-永远热爱

### 网站网址

https://blog.aiheadn.cn/

### 徽标位置

右上角

### 内容方向

爱你所爱，行你所行

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
根据加入开往要求，您的博客包含其它维护组成员认为的不适宜内容。故驳回您的加入申请
