### ISSUE TITLE
咱们俩博客

### ISSUE THREAD

**Issue by liucaptainapp** [travellings-link/travellings#1788]
### 网站名称

咱们俩の博客

### 网站网址

https://blog.liuayuan.com 

### 徽标位置

顶部导航栏

### 内容方向

分享学习过程、学习经验和生活分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by liucaptainapp** [comment]
好的 辛苦了

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
