### ISSUE TITLE
一一风和橘's画廊

### ISSUE THREAD

**Issue by yiyifengheju** [travellings-link/travellings#1790]
### 网站名称

一一风和橘's画廊

### 网站网址

https://gallery.mastermao.cn/

### 徽标位置

网页底部

### 内容方向

个人摄影展示，日常生活记录博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by Luochancy** [comment]
@linlinzzo 一个还不错的摄影博客
网站排版也都挺好的

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
