### ISSUE TITLE
留声与视 - 从未如此简单有趣

### ISSUE THREAD

**Issue by dorthl** [travellings-link/travellings#1791]
### 网站名称

留声与视

### 网站网址

https://www.nenufm.com

### 徽标位置

网页底部

### 内容方向

关注互联网及软件IT技术的个人博客，同时也记录个人的一路点滴。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
