### ISSUE TITLE
苏清明的摆烂空间

### ISSUE THREAD

**Issue by AnselF** [travellings-link/travellings#1792]
### 网站名称

苏清明的摆烂空间

### 网站网址

https://97772.top

### 徽标位置

顶栏

### 内容方向

一个自认为文艺网左的日常生活。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
