### ISSUE TITLE
皓然小站

### ISSUE THREAD

**Issue by HoronLee** [travellings-link/travellings#1793]
### 网站名称

皓然小站

### 网站网址

https://blog.horonlee.com

### 徽标位置

顶栏右侧

### 内容方向

生活分享，编程技术分享，云计算技术分享，Linux运维分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
PC端顶栏右侧可看到“开往”图标
移动端（手机版）界面暂未发现“开往”图标
且网站的建立时间并不符合

**Comment by Luochancy** [comment]
PC端顶栏右侧可看到“开往”图标
移动端（手机版）界面暂未发现“开往”图标
且网站的建立时间并不符合

**Comment by Luochancy** [comment]
抱歉，您的审核并不通过
理由：新成员建站建立时长并不符合开往的要求
引用相关条例：文档《加入开往》第一条第五款“网页已有较多内容（应有20篇文章或10篇原创文章，需要已持续更新两个月以上，更新时间自博客第一篇内容时间开始算起）”
