### ISSUE TITLE
秋至、枫以落

### ISSUE THREAD

**Issue by qiuzhi** [travellings-link/travellings#1795]
### 网站名称

秋至、枫以落

### 网站网址

https://blog.iqzhi.com

### 徽标位置

顶栏

### 内容方向

生活是美好的，会记录生活琐事；
折腾乐趣很多，分享工具与效率；
阅读使我安静，分享心得和体会；
平常想法较多，一本正经胡说八道。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Luochancy** [comment]
少见的及其老的博客，很多内容都算是运维会用得上的。当然，就算再好的博客也得按流程走嘛~

根据开往规则修改[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)我们在决定您的申请通过或驳回申请前将进行为期至少一个月的观察（当收到本回复之日起作为观察期起始日）。当维护组通过您的审核或驳回您的审核时，本issue将会修改为特定的标签。请您耐心等待！

在审核通过后，您可在[成员列表](https://api.travellings.cn/all)检索您的网站。

**Comment by BLxcwg666** [comment]
在查看您的网址时遇到了 DNS_PROBE_FINISHED_NXDOMAIN 错误，请检查您的 DNS 记录是否正确设置
很抱歉这么久才对您的申请做出回应 qaq

**Comment by qiuzhi** [comment]
> 在查看您的网址时遇到了 DNS_PROBE_FINISHED_NXDOMAIN 错误，请检查您的 DNS 记录是否正确设置 很抱歉这么久才对您的申请做出回应 qaq

今天9点左右使用的CDN出了问题，导致访问被阻断，目前已临时切换线路处理，请刷新缓存查看，造成困扰万分抱歉。

**Comment by BLxcwg666** [comment]
> > 在查看您的网址时遇到了 DNS_PROBE_FINISHED_NXDOMAIN 错误，请检查您的 DNS 记录是否正确设置 很抱歉这么久才对您的申请做出回应 qaq
> 
> 今天9点左右使用的CDN出了问题，导致访问被阻断，目前已临时切换线路处理，请刷新缓存查看，造成困扰万分抱歉。

目前已经添加了，欢迎加入开往大家庭~
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~

**Comment by qiuzhi** [comment]
感谢
