### ISSUE TITLE
赵彤刚的博客

### ISSUE THREAD

**Issue by ZhaoTonggang** [travellings-link/travellings#1796]
### 网站名称

赵彤刚的博客

### 网站网址

https://blog.heheda.top

### 徽标位置

网页底部【PS：网站没有使用类似于触底加载之类的功能，用户一眼就可以看到】

### 内容方向

知识，经验，灵感，生活琐碎，成长故事等。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
![Screenshot_20231202_230143_mark.via.jpg](https://github.com/travellings-link/travellings/assets/79007796/deb37de5-24be-4304-a6b9-7ca79d193aa8)这里的同意按键点不到哦，还有个人不太建议自动播放音乐。
