### ISSUE TITLE
烧瑚烙饼乱刨笔记

### ISSUE THREAD

**Issue by laobinghu** [travellings-link/travellings#1803]
### 网站名称

烧瑚烙饼乱刨笔记

### 网站网址

https://blog.laobinghu.top

### 徽标位置

顶栏-更多

### 内容方向

本人的学习经验和一些思考

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
初三的嘛，这么厉害...
（一个摸鱼高二学生路过）

**Comment by BLxcwg666** [comment]
在查看您的站点时遇到了 DNS_PROBE_FINISHED_NXDOMAIN，请检查您的 DNS 记录是否正确设置
非常抱歉这么久才对您的申请做出回应 qaq

**Comment by Luochancy** [comment]
通过ITDOG进行连通性检查，提示解析失败
查询https://blog.laobinghu.top/的DNS，发现A、AAAA、CNAME、SRV记录均为空
请检查你的域名DNS配置是否错误、是否解析错服务器
非常抱歉在你申请过后的这么久才进行审核
附上ITDOG网站访问检查截图
![Screenshot_2024-01-17-07-52-15-654_mark via](https://github.com/travellings-link/travellings/assets/86495643/6447e3d7-35f5-4d85-9c9f-6d0de9c53b8d)

**Comment by laobinghu** [comment]
抱歉，域名改为www.laobinghu.top了
且最近在迁移站点，预计2月初完成迁移
见谅

**Comment by laobinghu** [comment]
> 抱歉，域名改为www.laobinghu.top了 且最近在迁移站点，预计2月初完成迁移 见谅

改来改去决定域名确定为blog.laobinghu.top，不会再做修改了

**Comment by laobinghu** [comment]
博客已迁移完成，另外博客标题有更变，请查收（已在第一条issue修改）

**Comment by BLxcwg666** [comment]
更多里面的第一个 "跃迁" 麻烦改成开往哦 ~  
另外可以分享一下那个图标的 code 吗，我也用的事 mx-space 的 shiro 主题（  
还有就是建议把开往放在 footer，不然巡查可能扫不到（虽然后续有计划废除巡查）

**Comment by laobinghu** [comment]
完蛋，忘改文字了（
不过改这个比较麻烦，至少要在源码里改三处地方
要是实在有需求，可以直接fork我的（

**Comment by laobinghu** [comment]
![QQ截图20240128092747](https://github.com/travellings-link/travellings/assets/78538677/fbba0180-e446-407e-8fb3-32df663ddf1d)
修改完毕

**Comment by BLxcwg666** [comment]
加了喵 => list.travellings.cn
