### ISSUE TITLE
微光茶馆

### ISSUE THREAD

**Issue by KazariEX** [travellings-link/travellings#1807]
### 网站名称

微光茶馆

### 网站网址

https://bikariarchive.xyz

### 徽标位置

右侧栏

### 内容方向

个人小说网站

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
![Screenshot_20231202_231511_mark.via.jpg](https://github.com/travellings-link/travellings/assets/79007796/ce731409-a512-4da9-a1bb-4a36c3c71e6a)在via下页面会乱

**Comment by KazariEX** [comment]
这个浏览器似乎在某些情况下连媒体查询 4 级规范都不支持？有点意外

**Comment by KazariEX** [comment]
另外改了这个就有用吗，本站布局核心之一是容器查询，我不觉得媒体查询生效了页面就能正常。以及这是否是不得不解决的问题？我并没有找到必须向下兼容不定低版本浏览器的要求，如果要因为这个而对样式大动刀感觉不太能接受

**Comment by linlinzzo** [comment]
@KazariEX 关于这个问题，我这会让组里的其他成员重审。大概过一会你可以得到新的答复。

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
