### ISSUE TITLE
「一刀斩の小窝」->「千雪的咖啡厅」网站变更申请

### ISSUE THREAD

**Issue by chiyuki0325** [travellings-link/travellings#1813]
### 网站名称

千雪的咖啡厅

### 旧网站网址

https://blog.yidaozhan.top

### 新网站网址

https://blog.chyk.ink

**Comment by BLxcwg666** [comment]
![image](https://github.com/travellings-link/travellings/assets/66854530/945cca23-4134-4ffb-9cc0-aa4fcf0335b4)
已完成修改，请自行关闭issues

**Comment by linlinzzo** [comment]
Done. @BLxcwg666
