### ISSUE TITLE
寻科寻梦

### ISSUE THREAD

**Issue by 11adds** [travellings-link/travellings#1815]
### 网站名称

寻科寻梦

### 网站网址

https://tianchenstudio.org.cn/

### 徽标位置

网站底部

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
在访问时遇到了 ERR_CONNECTION_CLOSED，但通过 itdog 测速发现有部分地区可以访问，请检查您的 Web 服务器配置或者防火墙之类的东西
非常抱歉这么久才对您的申请做出回应qaq

**Comment by Luochancy** [comment]
通过ITDOG工具进行访问检查，出现全国大面积无法访问网站
通过福建电信网络与香港盈科电讯网络访问出现ERR_CONNECTION_CLOSED
请检查您的网站配置是否有问题，或检查您网站服务器所属的IDC运营商防火墙是否封堵了网站相关端口
非常抱歉在您申请的这么久以后才进行检查
附上ITDOG网站访问截图
![Screenshot_2024-01-17-07-43-57-704_mark via](https://github.com/travellings-link/travellings/assets/86495643/d980848e-235f-4089-88e8-66a6585b9190)
