### ISSUE TITLE
时光李记

### ISSUE THREAD

**Issue by Wing-Li** [travellings-link/travellings#1816]
### 网站名称

时光李记

### 网站网址

https://www.lylyl.cn/

### 徽标位置

顶部右上角，底部右下角

### 内容方向

关于技术，关于日常，一些思考。命运的转折点时刻在发生着

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
目前没有发现什么问题。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，谢谢理解。观察期从收到本消息起开始计算。

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~

**Comment by gxres042** [comment]
![image](https://github.com/travellings-link/travellings/assets/53113178/e955ba1b-87af-46c3-8ef2-e492ae0ec08f)
博主您好，您的博客对开往链接使用了 JS 延时跳转，导致浏览器拦截，建议您缩短延迟时间或取消延迟。

**Comment by Wing-Li** [comment]
> ![image](https://private-user-images.githubusercontent.com/53113178/300793934-e955ba1b-87af-46c3-8ef2-e492ae0ec08f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTIyMzUsIm5iZiI6MTcwOTY5MTkzNSwicGF0aCI6Ii81MzExMzE3OC8zMDA3OTM5MzQtZTk1NWJhMWItODdhZi00NmMzLThlZjItZTQ5MmFlMGVjMDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAyMjUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMzg4M2IzMDY1NDMwZmUzMjczZTJiYTE0NTM1YzU4ZDRlODExMjc3YWJkOTRkOTc5NWNlZjllOTIyZWQ3MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h0OTqGPakHggb7pxC_F_ioJQMfQEQlWkT5iAQvkK5hQ) 博主您好，您的博客对开往链接使用了 JS 延时跳转，导致浏览器拦截，建议您缩短延迟时间或取消延迟。

已更新
