### ISSUE TITLE
加入开往

### ISSUE THREAD

**Issue by cddone** [travellings-link/travellings#1817]
### 网站名称

cddone

### 网站网址

https://cddone.com

### 徽标位置

网页底部

### 内容方向

学习技术记录与分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by cddone** [comment]
技术文档记录和分享

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
