### ISSUE TITLE
民江技术栈

### ISSUE THREAD

**Issue by mjxdinfo** [travellings-link/travellings#1818]
### 网站名称

民江技术栈

### 网站网址

https://www.mjxdinfo.com

### 徽标位置

顶栏

### 内容方向

专注于硬件维护、操作系统、数据库、虚拟化、中间件、经验教程、视频资源等IT技术资源搜集共享与发布！

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
