### ISSUE TITLE
墨尘的生活小站

### ISSUE THREAD

**Issue by mnochen** [travellings-link/travellings#1821]
### 网站名称

墨尘的生活小站

### 网站网址

https://mnchen.cn/

### 徽标位置

顶栏

### 内容方向

网络生活分享

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by mnochen** [comment]
在吗，已经两个月了ʕ ᵔᴥᵔ ʔ

**Comment by Luochancy** [comment]
非常非常抱歉这么久才来审

根据开往规则修改[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)，我们在决定您的申请通过或驳回申请前将进行为期至少一个月的观察（当收到本回复之日起作为观察期起始日）。当维护组通过您的审核或驳回您的审核时，本issue将会修改为特定的标签。请您耐心等待~

在审核通过后，您可在[开往成员列表](http://list.travellings.cn)检索到您的网站。

**Comment by mnochen** [comment]
> 在访问时标题为 `页面没有找到`，内容如图（本人坐标美国洛杉矶）
> ![image](https://github.com/travellings-link/travellings/assets/66854530/24217a41-d9e8-4592-b733-89dee99baac5)
> 响应状态码为 200，是哪里出问题了吗

您好，可能是我对海外部分资源做了访问限制的原因，目前本人在国内访问正常，未出现css，JS丢失的情况![Screenshot_2024-01-19-14-17-54-083_com.microsoft.emmx.jpg](https://github.com/travellings-link/travellings/assets/122211251/357bc03c-2722-4de9-9b6e-8b24a67c7f59)

**Comment by xuanzhi33** [comment]
![image](https://github.com/travellings-link/travellings/assets/37460139/deac78ce-b28c-4270-a9a0-3e5f09a9edd4)
目前访问是正常了，但是您使用了JS延时跳转，由于间隔时间较长容易被浏览器拦截，建议缩短跳转的时间或改为立即跳转
