### ISSUE TITLE
Karl的博客

### ISSUE THREAD

**Issue by karltan0328** [travellings-link/travellings#1828]
### 网站名称

Karl的博客

### 旧网站网址

https://blog.karltan.com/

### 新网站网址

https://blog.karltan.com/

**Comment by karltan0328** [comment]
不好意思麻烦了，我把网站的名称修改了一下🥹

**Comment by linlinzzo** [comment]
已对网站地址进行了修改。

需要请您阅读的公告： https://github.com/orgs/travellings-link/discussions/1831
