### ISSUE TITLE
小小笔记大大用处

### ISSUE THREAD

**Issue by UPToZ-Core** [travellings-link/travellings#1833]
### 网站名称

小小笔记大大用处

### 网站网址

https://blog.uptoz.cn/

### 徽标位置

顶栏

### 内容方向

编程技术

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
在昨日（2023.12.6 UTF+8）过来看的时候网站还可访问，今日（2023.12.7 UTF+8）发现网站无法访问。虽说昨日已看得大差不差，但由于今天的确出现无法访问的问题。故我选择驳回本申请。（访问地址：厦门移动基站、香港电讯盈科服务器）

请在修复网站故障或对其进行解释后回复本issue，我将会再次对网站进行审核。否则根据规则本issue将在15天后自动关闭。

**Comment by UPToZ-Core** [comment]
> 在昨日（2023.12.6 UTF+8）过来看的时候网站还可访问，今日（2023.12.7 UTF+8）发现网站无法访问。虽说昨日已看得大差不差，但由于今天的确出现无法访问的问题。故我选择驳回本申请。
> 
> 请在修复网站故障或对其进行解释后回复本issue，我将会再次对网站进行审核。否则，根据规则，本issue将在15天后自动关闭。

博客部署在家中服务器，晚上因网络故障，导致博客无法访问，我深表歉意，已于今天8点15分恢复正常访问。

**Comment by Luochancy** [comment]
@UPToZ-Core 情况已了解
今天下午我将会再次对您的网站进行审核

**Comment by Luochancy** [comment]
根据开往规则修改[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)，我们在决定您的申请通过或驳回申请前将进行为期至少一个月的观察（当收到本回复之日起作为观察期起始日）。当维护组通过您的审核或驳回您的审核时，本issue将会修改为特定的标签。请您耐心等待~

在审核通过后，您可在[开往成员列表](https://api.travellings.cn/all)检索到您的网站。

**Comment by UPToZ-Core** [comment]
一个月的考察期已经到了哦，期待加入十年之约。

**Comment by linlinzzo** [comment]
@UPToZ-Core 这里是开往哦～

**Comment by UPToZ-Core** [comment]
> @UPToZ-Core 这里是开往哦～

哈哈哈 糊涂了。观察期亿满一个月啦。希望能够加入开往~ 开往新的世界~

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～ 
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
