### ISSUE TITLE
Travis' Blog

### ISSUE THREAD

**Issue by TravisRoad** [travellings-link/travellings#1835]
### 网站名称

Travis' Blog

### 网站网址

https://blog.lxythan2lxy.cn/

### 徽标位置

网站顶部和网站底部，手机端顶部折叠菜单中

### 内容方向

个人的游戏、生活、观影分享
偶尔分享下我的技术和代码

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
内容非常不错！

您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by Big-Cake-jpg** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~

注：由于一些原因（如 CDN 缓存），您可能无法立刻在成员列表中搜索到您的网站。
