### ISSUE TITLE
Green Dolphin Dance

### ISSUE THREAD

**Issue by greendolphindance** [travellings-link/travellings#1836]
### 网站名称

Green Dolphin Dance

### 网站网址

https://greendolphindance.com

### 徽标位置

网页底部

### 内容方向

个人随笔、软件分享、购物分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
除了文章数量不太够以外，其它都好。

根据规则修改 6339667 中新增的内容，我们将继续观察您的站点一段时间，在此期间烦请稍作等待，多谢理解。观察期从收到本通知起开始计算。

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
