### ISSUE TITLE
幺叁贰氪

### ISSUE THREAD

**Issue by 132k** [travellings-link/travellings#1839]
### 网站名称

晨风笔记

### 网站网址

https://www.chenlifeng.com/

### 徽标位置

底部右侧小部件

### 内容方向

日常随笔；代码教程；软件分享；技术博文。

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
在 view-source 看见了 travellings 的链接，但是好像并没有在主页看见诶，能指一下吗

**Comment by 132k** [comment]
> 在 view-source 看见了 travellings 的链接，但是好像并没有在主页看见诶，能指一下吗

你好，在底部右侧小部件中显示的黑色logo

**Comment by BLxcwg666** [comment]
是我瞎了，sry
已经加了喵 => list.travellings.cn

**Comment by 132k** [comment]
> 是我瞎了，sry 已经加了喵 => list.travellings.cn

言过了，改天我换一个浅色的logo更醒目些
