### ISSUE TITLE
◈星港◎Star☆的博客

### ISSUE THREAD

**Issue by Stars-harbor** [travellings-link/travellings#1844]
### 网站名称

◈星港◎Star☆的博客

### 网站网址

https://blog.starsharbor.com/

### 徽标位置

电脑端：页面顶栏右上角、页面底栏“服务”条目下；手机端：页面底栏“服务”条目下

### 内容方向

个人思考，记录生活

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～ 
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~ 
开往的QQ群：186690715
