### ISSUE TITLE
十二的编程笔记

### ISSUE THREAD

**Issue by Twelveeee** [travellings-link/travellings#1846]
### 网站名称

十二的编程笔记

### 网站网址

https://blog.twelveeee.top/

### 徽标位置

顶栏

### 内容方向

编程笔记，技术分享

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
很优质的内容~
您的申请已通过，欢迎加入开往大家庭～ 
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~ 
开往的QQ群：186690715
