### ISSUE TITLE
Hary的博客

### ISSUE THREAD

**Issue by harycc** [travellings-link/travellings#1849]
### 网站名称

Hary的博客

### 网站网址

https://hary.cc/

### 徽标位置

底部页脚位置

### 内容方向

个人随笔，生活分享，建站记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
推荐在顶栏或侧栏放置开往徽标。

**Comment by haryhan** [comment]
> 推荐在顶栏或侧栏放置开往徽标。
现在再底部放着，这样不行是吧

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～   
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~   
开往的QQ群：186690715
