### ISSUE TITLE
Zhu's Blog

### ISSUE THREAD

**Issue by azhu021** [travellings-link/travellings#1850]
### 网站名称

Zhu's Blog

### 网站网址

https://yfzhu.cn/

### 徽标位置

导航栏、底部

### 内容方向

计算机、股票业余爱好者

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~

注：由于一些原因（如 CDN 缓存），您可能无法立刻在成员列表中搜索到您的网站。
