### ISSUE TITLE
小林笔记

### ISSUE THREAD

**Issue by SenLinCloud** [travellings-link/travellings#1856]
### 网站名称

小林笔记

### 网站网址

https://m.senlinm.cn

### 徽标位置

PC端侧边栏【About Me】➕网站底部     移动端网站底部

### 内容方向

记录生活留住美好时刻 ，分享个人笔记！

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
推荐在顶栏或侧栏放置开往链接。

**Comment by linlinzzo** [comment]
您好，开往已收到您的申请，根据规则修改 https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b 中的内容，开往在做出审核通过或驳回决定前将观察您的网站至少一个月。请您耐心等待，谢谢。（观察期从收到本通知消息之日起算）

**Comment by SenLinCloud** [comment]
> 推荐在顶栏或侧栏放置往链接。

已放置

**Comment by SenLinCloud** [comment]
开启

**Comment by SenLinCloud** [comment]
> > 推荐在顶栏或侧栏放置往链接。
> 
> 已放置

**Comment by linlinzzo** [comment]
审核通过，等待添加到数据库。
