### ISSUE TITLE
好软猫

### ISSUE THREAD

**Issue by XMBLO** [travellings-link/travellings#1857]
### 网站名称

好软猫

### 网站网址

https://www.haoruanmao.com

### 徽标位置

网页底部

### 内容方向

专注好软件与资源分享的猫

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
这个网站对我个人来说存在争议（还提供下载 Via 浏览器？），所以我请组内其他两位成员来看一下。

**Comment by Luochancy** [comment]
感觉偏向内容集合的那种网站
不太好说

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～   
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~   
开往的QQ群：186690715
