### ISSUE TITLE
白馬空谷

### ISSUE THREAD

**Issue by androidmumo** [travellings-link/travellings#1858]
### 网站名称

白馬空谷

### 网站网址

https://blog.mcloc.cn

### 徽标位置

网页底部

### 内容方向

技术、个人记录

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～   
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~   
开往的QQ群：186690715
