### ISSUE TITLE
咸鱼小窝

### ISSUE THREAD

**Issue by f1shQAQ** [travellings-link/travellings#1859]
### 网站名称

咸鱼小窝

### 网站网址

https://qqquq.com

### 徽标位置

顶栏

### 内容方向

这里是一个自留地，分享一些个人笔记，也是在互联网上留下一些自己的印记把

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
文章数量有点少了，要多写点哦。
![image](https://github.com/travellings-link/travellings/assets/76810494/8e5af371-2764-4998-8647-8fb385b5444f)
