### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by 3554171776** [travellings-link/travellings#1861]
### 网站名称

夏末笔记

### 网站网址

https://www.xiamo.cc

### 徽标位置

底部

### 内容方向

若再许我少年时，一两黄金一两风，奈何十万八千梦,不见人间一两风-欢迎光临夏末笔记-记录生活与技术的个人博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
未能在 PC 端找到开往外链，请确认您是否在顶栏或底栏放置了开往外链。

**Comment by Big-Cake-jpg** [comment]
由于两周内未能得到您的回应，我们已拒绝本次申请。如您已完成相关更改，可以重新创建一个 Issue 进行申请。
