### ISSUE TITLE
陌子夕生活记

### ISSUE THREAD

**Issue by mozixicom** [travellings-link/travellings#1862]
### 网站名称

陌子夕生活记

### 网站网址

https://mozixi.com

### 徽标位置

页面顶部右侧

### 内容方向

陌子夕生活记，记录生活、学习、旅行和有趣的事。_你我皆是经尘客，何不浊酒忘忧愁。

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~
