### ISSUE TITLE
六月是只猫

### ISSUE THREAD

**Issue by 907344018** [travellings-link/travellings#1863]
### 网站名称

六月是只猫

### 网站网址

https://www.lyszm.com

### 徽标位置

页面顶部右侧

### 内容方向

生活，一半家长里短，一半山川湖海…

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~

注：由于一些原因（如 CDN 缓存），您可能无法立刻在成员列表中搜索到您的网站。
