### ISSUE TITLE
零一物语

### ISSUE THREAD

**Issue by lijianing8998** [travellings-link/travellings#1879]
### 网站名称

零一物语

### 网站网址

https://docn.net

### 徽标位置

顶部菜单&网站底部

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
