### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by indude1** [travellings-link/travellings#1880]
### 网站名称

indude-个人文章分享

### 网站网址

https://indude.cn/

### 徽标位置

侧栏

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～    
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~    
开往的QQ群：186690715
