### ISSUE TITLE
八九の日记

### ISSUE THREAD

**Issue by ahcc123** [travellings-link/travellings#1882]
### 网站名称

八九の日记

### 网站网址

https://bkm.net/

### 徽标位置

侧栏 朋友栏目

### 内容方向

生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
我没能在手机端看到开往的链接。

**Comment by Big-Cake-jpg** [comment]
由于两周内未能得到您的回应，我们已拒绝本次申请。如您已完成相关更改，可以重新创建一个 Issue 进行申请。
