### ISSUE TITLE
也被放进火川

### ISSUE THREAD

**Issue by hechuan4** [travellings-link/travellings#1884]
### 网站名称

也被放进河川

### 网站网址

https://hechuan.me/

### 徽标位置

左侧栏

### 内容方向

其它

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～    
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~    
开往的QQ群：186690715
