### ISSUE TITLE
怪胎博客

### ISSUE THREAD

**Issue by GeekF0rum** [travellings-link/travellings#1885]
### 网站名称

怪胎博客

### 网站网址

***

### 徽标位置

首页

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方
建议放置在您网站的顶栏~

**Comment by GeekF0rum** [comment]
![image](https://github.com/travellings-link/travellings/assets/153544876/abf0ebe6-1364-4360-9fb7-761949021ac9)
在这里不可以吗

**Comment by xuanzhi33** [comment]
您好，在Issues模板和审核规则中，均明确写明：只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低。请放在打开网页后能直接看到的地方。
开往想让访客有一个良好的连续跳转的体验，而您将链接放在众多友链的中间，且没有“开往”二字，访客很难轻松的找到这个链接。如您不愿意放置在顶栏，网站右侧的侧栏也是一个很好的选择。

**Comment by xuanzhi33** [comment]
另外，您的网站中一些“隐藏的付费内容”，根据标题推断可能存在违法违规，我们无法保证其内容的合法性，故无法给您通过审核，感谢您的理解~
