### ISSUE TITLE
关关和六六 ' blog

### ISSUE THREAD

**Issue by imGmc** [travellings-link/travellings#1886]
### 网站名称

关关和六六

### 网站网址

https://www.gmcllp.cn

### 徽标位置

顶栏

### 内容方向

生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
审核通过，等待添加到数据库。

**Comment by linlinzzo** [comment]
已添加到数据库。欢迎加入开往大家庭。

开往的QQ群：186690715
