### ISSUE TITLE
NorthSecond's Blog

### ISSUE THREAD

**Issue by NorthSecond** [travellings-link/travellings#1887]
### 网站名称

NorthSecond's Blog

### 网站网址

https://blog.yfyang.me/

### 徽标位置

顶栏 & 网页底部

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
