### ISSUE TITLE
LoliAPI

### ISSUE THREAD

**Issue by miaowmint** [travellings-link/travellings#1888]
### 网站名称

LoliAPI

### 网站网址

https://www.loliapi.com/

### 徽标位置

PC端右上角火车svg图标 移动端右上角展开栏

### 内容方向

提供免费API服务的站点

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
