### ISSUE TITLE
老K博客

### ISSUE THREAD

**Issue by GitHub-laok** [travellings-link/travellings#1889]
### 网站名称

老K博客

### 网站网址

https://laokbk.cn

### 徽标位置

底部

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～    
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~    
开往的QQ群：186690715
