### ISSUE TITLE
小李同学 Coding

### ISSUE THREAD

**Issue by LJJbyZJU** [travellings-link/travellings#1890]
### 网站名称

小李同学 Coding

### 网站网址

https://blog.xxfer.cn

### 徽标位置

网站右上角

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715

注：您使用了延时跳转，巡查系统有概率无法正确识别，请您在[开往成员列表](https://list.travellings.cn)留意您的网站状态
