### ISSUE TITLE
加入开往 申请收录

### ISSUE THREAD

**Issue by TrueSaveWorldPig** [travellings-link/travellings#1892]
### 网站名称

科技茶馆

### 网站网址

https://writes.cn

### 徽标位置

侧栏

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
DNS_PROBE_FINISHED_NXDOMAIN
![image](https://github.com/travellings-link/travellings/assets/66854530/f911858f-8c4d-4c96-a4bf-9ca556bebdb0)
跑路了咩？

**Comment by TrueSaveWorldPig** [comment]
在备案来自裴路明的iPhone客户端在 2024年1月21日，16:42，BLxcwg666 ***@***.***> 写道：﻿
DNS_PROBE_FINISHED_NXDOMAIN
image.png (view on web)
跑路了咩？

**Comment by BLxcwg666** [comment]
行，那等等吧

**Comment by TrueSaveWorldPig** [comment]
我可以先撤销，等弄好了再重新申请

**Comment by BLxcwg666** [comment]
可以
