### ISSUE TITLE
Yunyi's Blog

### ISSUE THREAD

**Issue by yunyit** [travellings-link/travellings#1894]
### 网站名称

Yunyi's Blog

### 网站网址

https://www.yunyitang.me/zh/

### 徽标位置

将 开往 的外链（https://www.travellings.cn/go.html）放置在了主页页首导航栏

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
