### ISSUE TITLE
申请收录：梦泽の日记

### ISSUE THREAD

**Issue by MengZeMC** [travellings-link/travellings#1895]
### 网站名称

梦泽の日记

### 网站网址

https://mengze2.cn/

### 徽标位置

网站底部

### 内容方向

技术类博客

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by BLxcwg666** [comment]
根据开往规则修改6339667，我们在决定您的申请通过或驳回申请前将进行为期至少一个月的观察（当收到本回复之日起作为观察期起始日）。当维护组通过您的审核或驳回您的审核时，本issue将会修改为特定的标签。请您耐心等待~

在审核通过后，您可在开往成员列表检索到您的网站。

**Comment by Big-Cake-jpg** [comment]
2024 / 01 / 20 复查，站点显示 403。
![image](https://github.com/travellings-link/travellings/assets/76810494/2851fc32-03e9-41e7-aa0b-0941198b6ecd)

**Comment by BLxcwg666** [comment]
> 2024 / 01 / 20 复查，站点显示 403。 ![image](https://private-user-images.githubusercontent.com/76810494/298288924-2851fc32-03e9-41e7-aa0b-0941198b6ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjI1NjksIm5iZiI6MTcwNTc2MjI2OSwicGF0aCI6Ii83NjgxMDQ5NC8yOTgyODg5MjQtMjg1MWZjMzItMDNlOS00MWU3LWFhMGItMDk0MTE5OGI2ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE0NTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjAxMTJhMGQ2NDhjMDJiM2RlOWVkYTI4MGYyOWIxYjY3YjEwOGE2YmM3NGM0NmZlMTU5MTAxNWIyOTMyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ypyC32jKaAesX1-LMcw54rIKWSSxEZLUCLKyrbrV1Vw)

我这能开，坐标美国洛杉矶
![image](https://github.com/travellings-link/travellings/assets/66854530/70a79729-85bd-4bba-b854-d4346d2f1833)

**Comment by MengZeMC** [comment]
> > 2024 / 01 / 20 复查，站点显示 403。 ![image](https://private-user-images.githubusercontent.com/76810494/298288924-2851fc32-03e9-41e7-aa0b-0941198b6ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjI1NjksIm5iZiI6MTcwNTc2MjI2OSwicGF0aCI6Ii83NjgxMDQ5NC8yOTgyODg5MjQtMjg1MWZjMzItMDNlOS00MWU3LWFhMGItMDk0MTE5OGI2ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE0NTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjAxMTJhMGQ2NDhjMDJiM2RlOWVkYTI4MGYyOWIxYjY3YjEwOGE2YmM3NGM0NmZlMTU5MTAxNWIyOTMyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ypyC32jKaAesX1-LMcw54rIKWSSxEZLUCLKyrbrV1Vw)
> 
> 我这能开，坐标美国洛杉矶
> ![image](https://github.com/travellings-link/travellings/assets/66854530/70a79729-85bd-4bba-b854-d4346d2f1833)
> 

我没有403，我这边正常，因为cdn问题，首次访问可能403

**Comment by linlinzzo** [comment]
@MengZeMC @NotBig_Cake

**Comment by Big-Cake-jpg** [comment]
审核通过，您可在[成员列表](https://list.travellings.cn)找到您的站点。

**Comment by linlinzzo** [comment]
@MengZeMC 抱歉，负责处理你这个issue的人回学校了。建议等下周。

**Comment by HowieHz** [comment]
站长与我说明站点已关闭，且域名过期后未续费，故从成员列表删除。
感谢您对开往项目的支持，欢迎您再次申请。
