### ISSUE TITLE
繁花会

### ISSUE THREAD

**Issue by aglaiabambi** [travellings-link/travellings#1901]
### 网站名称

繁花会

### 网站网址

https://akavalue.pages.dev/

### 徽标位置

网页底部

### 内容方向

其它

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
Cloudflare Pages 在大陆可能会没法打开，容易被巡查标 ERROR（
您的申请已通过，欢迎加入开往大家庭～   
您稍后可在[开往成员列表](https://list.travellings.cn)搜索到您的网站~   
开往的QQ群：186690715
