### ISSUE TITLE
申请加入 | 网站名称：Angine's Blog

### ISSUE THREAD

**Issue by angine04** [travellings-link/travellings#1902]
### 网站名称

Angine's Blog

### 网站网址

https://angine.tech

### 徽标位置

在桌面端：右侧侧栏和左侧导航（导航在某些设备可能自动收起）；手机端：页面底部和导航（默认收起）

### 内容方向

技术类博客

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by angine04** [comment]
另注：本博客兼有生活记录和技术类内容，但是相对以偏技术类的内容为主。

**Comment by BLxcwg666** [comment]
Very Beautiful！
根据开往规则修改[6339667](https://github.com/travellings-link/travellings/commit/633966700f916754b36d84b2a8cd236a218c134b)，我们在决定您的申请通过或驳回申请前将进行为期至少一个月的观察（当收到本回复之日起作为观察期起始日）。当维护组通过您的审核或驳回您的审核时，本issue将会修改为特定的标签。请您耐心等待~

在审核通过后，您可在[开往成员列表](https://api.travellings.cn/all)检索到您的网站。

**Comment by BLxcwg666** [comment]
另外可以把徽标放在显眼一点的地方吗，拜托了

**Comment by angine04** [comment]
竟然如此神速！
关于开往徽标，我已经在导航和侧栏都放置了，别的地方似乎都不太适合。不过我刚才手动把徽标的尺寸调大了些。

**Comment by BLxcwg666** [comment]
好的看到了，谢谢（主题是真的好看

**Comment by Big-Cake-jpg** [comment]
您的申请已通过，欢迎加入开往大家庭～
您现在可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~

注：由于一些原因（如 CDN 缓存），您可能无法立刻在成员列表中搜索到您的网站。
