### ISSUE TITLE
申请加入丨新锐博客

### ISSUE THREAD

**Issue by mowang2024** [travellings-link/travellings#1910]
### 网站名称

新锐博客

### 网站网址

https://www.loveuxr.com

### 徽标位置

导航栏

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
页内没看到开往徽标哦~

**Comment by mowang2024** [comment]
之前添加了没有保存菜单，现在网站已经有了

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
您稍后可在开往成员列表搜索到您的网站~
开往的QQ群：186690715
