### ISSUE TITLE
茗辰原博客

### ISSUE THREAD

**Issue by rumian0** [travellings-link/travellings#1914]
### 网站名称

茗辰原 の 异世界

### 网站网址

https://mcy.cloudns.org

### 徽标位置

页面底部

### 内容方向

生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在pc网页打开后就能看到的地方
建议放置在您网站的顶栏~

**Comment by xuanzhi33** [comment]
另外，根据审核规则，博客类网站应至少有20篇文章或10篇原创文章，需要已持续更新两个月以上
您的网站暂不符合标准（仅有7篇），请扩充内容后再来申请。
开往期待您的加入~

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715

**Comment by HowieHz** [comment]
站长您好
您的域名根据我们的核查，已大致确定您的域名 `liyy.us.kg` 已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。

**Comment by HowieHz** [comment]
link #2899
