### ISSUE TITLE
Cynosura

### ISSUE THREAD

**Issue by auroursa** [travellings-link/travellings#1921]
### 网站名称

Cynosura

### 网站网址

https://cynosura.one

### 徽标位置

导航栏

### 内容方向

生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
