### ISSUE TITLE
网站名称

### ISSUE THREAD

**Issue by q948818** [travellings-link/travellings#1922]
### 网站名称

boys博客

### 网站网址

https://boysblog.cn

### 徽标位置

网站顶栏

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by q948818** [comment]
手机端已在折叠的菜单栏中添加

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
