### ISSUE TITLE
Highligh

### ISSUE THREAD

**Issue by Bruce-WL** [travellings-link/travellings#1925]
### 网站名称

Highligh

### 网站网址

https://wanglin.blog

### 徽标位置

网站底部

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠）
建议放置在您网站的顶栏~

**Comment by BLxcwg666** [comment]
没看见开往的链接

**Comment by Bruce-WL** [comment]
已放置至顶栏
![image](https://github.com/travellings-link/travellings/assets/78944540/059933b4-e56f-440f-b20a-12dc0f939be6)

**Comment by Bruce-WL** [comment]
为了美观且放置到首页，手机端的开往放置到了底栏。

![image](https://github.com/travellings-link/travellings/assets/78944540/854c5af0-e68d-43f0-b9d8-89dc5f3d32df)

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
抱歉由于我的疏忽这么久才做出回应，ごめんなさい ~
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
