### ISSUE TITLE
裴先生笔记

### ISSUE THREAD

**Issue by TrueSaveWorldPig** [travellings-link/travellings#1927]
### 网站名称

裴先生笔记

### 网站网址

https://blog.peiluming.com

### 徽标位置

侧栏

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by TrueSaveWorldPig** [comment]
PC端加了就行了，我没打算做手机端

**Comment by TrueSaveWorldPig** [comment]
<img width="252" alt="image" src="https://github.com/travellings-link/travellings/assets/55381817/be3ba73a-51db-4336-bd23-1f1ba17ed5ce">
我添加到公告栏了

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
