### ISSUE TITLE
ScaredCube’s Site

### ISSUE THREAD

**Issue by ScaredCube** [travellings-link/travellings#1928]
### 网站名称

ScaredCube’s Site

### 网站网址

https://sccube.link

### 徽标位置

底栏

### 内容方向

技术类博客

### 请确认一下事项

- [ ] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠）
建议放置在您网站的顶栏~

**Comment by ScaredCube** [comment]
已修改，现在在首页社交链接栏

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715

**Comment by ScaredCube** [comment]
您好，请问有tg群组吗

**Comment by xuanzhi33** [comment]
https://t.me/TravellingsCN
