### ISSUE TITLE
Cloudchewie

### ISSUE THREAD

**Issue by Robert-Stackflow** [travellings-link/travellings#1930]
### 网站名称

Cloudchewie

### 网站网址

https://blog.cloudchewie.com

### 徽标位置

PC端：顶栏右侧按钮，顶栏最左侧按钮菜单；移动端：侧栏，顶栏最左侧按钮菜单

### 内容方向

技术类博客

### 请确认一下事项

- [x] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
