### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by akasasuka** [travellings-link/travellings#1943]
### 网站名称

厄尔科斯

### 网站网址

https://sikan.moe

### 徽标位置

顶栏、底部

### 内容方向

其它

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~
开往的QQ群：186690715
