### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by qqxt** [travellings-link/travellings#1944]
### 网站名称

小野博客

### 网站网址

https://lb5.net/

### 徽标位置

顶部菜单

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn/)搜索到您的网站~
开往的QQ群：186690715
