### ISSUE TITLE
jdjwzx233-blog 网址变更

### ISSUE THREAD

**Issue by jdjwzx233** [travellings-link/travellings#1946]
### 网站名称

jdjwzx233-blog

### 旧网站网址

https://jdjwzx233.cn/

### 新网站网址

https://www.jdjwzx233.cn/

**Comment by xuanzhi33** [comment]
您好，已为您更改。
请查看[开往成员列表](https://list.travellings.cn/)

**Comment by HowieHz** [comment]
link #1520
