### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by achuanya** [travellings-link/travellings#1947]
### 网站名称

游钓四方的博客

### 网站网址

https://lhasa.icu

### 徽标位置

右上角菜单栏，进入首页 菜单栏自动展开

### 内容方向

技术类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
审核通过，稍后您可在[成员列表](https://list.travellings.cn)中找到您的站点。
