### ISSUE TITLE
小稚生活志

### ISSUE THREAD

**Issue by 759689312** [travellings-link/travellings#1950]
### 网站名称

小稚生活志

### 旧网站网址

https://blog.oiii.top

### 新网站网址

https://ihello.cc

**Comment by 759689312** [comment]
为什么我在来往的成员名单里搜索不到我旧网址了🤣

**Comment by linlinzzo** [comment]
可能是因为[这个](https://www.travellings.cn/post/removed-dead-site)？

**Comment by linlinzzo** [comment]
可能是因为[这个](https://www.travellings.cn/post/removed-dead-site)？

**Comment by 759689312** [comment]
> 可能是因为[这个](https://www.travellings.cn/post/removed-dead-site)？

好像是，有一段时间更换域名了没申请更换，那我要重新申请吗

**Comment by 759689312** [comment]
> 可能是因为[这个](https://www.travellings.cn/post/removed-dead-site)？

好像是，有一段时间更换域名了没申请更换，那我要重新申请吗

**Comment by linlinzzo** [comment]
@759689312 抱歉，是的。
