### ISSUE TITLE
申请收录-Kegongteng

### ISSUE THREAD

**Issue by gtxykn0504** [travellings-link/travellings#1952]
### 网站名称

Kegongteng

### 网站网址

https://kegongteng.cn/

### 徽标位置

底部

### 内容方向

其它

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠）
建议放置在您网站的顶栏~

**Comment by gtxykn0504** [comment]
> 您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠） 建议放置在您网站的顶栏~

已改，麻烦了

**Comment by gtxykn0504** [comment]
> 您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠） 建议放置在您网站的顶栏~

![image](https://github.com/travellings-link/travellings/assets/67720340/144964ae-edb1-4d45-9b2d-62552c0d8381)

**Comment by xuanzhi33** [comment]
您的申请已通过，欢迎加入开往大家庭～
约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~
开往的QQ群：186690715
