### ISSUE TITLE
yf-ch.com

### ISSUE THREAD

**Issue by yunfanch** [travellings-link/travellings#1955]
### 网站名称

云帆沧海

### 旧网站网址

https://yf-ch.com

### 新网站网址

https://yfch.top/

**Comment by linlinzzo** [comment]
@yunfanch 抱歉，没能在列表中发现您的网站。请您阅读

**Comment by yunfanch** [comment]
> ### 网站名称
> 云帆沧海
> 
> ### 旧网站网址
> https://yf-ch.com
> 
> ### 新网站网址
> https://yfch.top/
