### ISSUE TITLE
十月遗忘诗

### ISSUE THREAD

**Issue by greniray** [travellings-link/travellings#1958]
### 网站名称

十月遗忘诗

### 网站网址

https://greniray.org

### 徽标位置

网页底部

### 内容方向

生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠）
建议放置在您网站的顶栏~

**Comment by greniray** [comment]
您好，我已将链接移动到网页header，请再次审核 谢谢～
