### ISSUE TITLE
雾林博客

### ISSUE THREAD

**Issue by baiwulin** [travellings-link/travellings#1970]
### 网站名称

雾林博客

### 网站网址

https://www.baiwulin.com/

### 徽标位置

左侧导航栏（PC端固定，移动端折叠）

### 内容方向

生活类博客

### 请确认一下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
尊敬的站长您好，我们接到反馈，确认您的站点目前处于无法访问状态（域名无解析，ERR_NAME_NOT_RESOLVED）。因此，您的站点目前已经被置为 ERROR 状态，暂无法通过开往跳转访问。

我们希望您能排查您站点的相关问题，并在 14 天内在本 Issue下方回复，以便我们将您的站点恢复正常跳转。

感谢您对开往的支持。
