### ISSUE TITLE
墨尘的生活小站

### ISSUE THREAD

**Issue by mnochen** [travellings-link/travellings#1976]
### 网站名称

墨尘

### 网站网址

https://mnchen.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by mnochen** [comment]
已修改开往跳转js由原先的5000值改为了100

**Comment by xuanzhi33** [comment]
您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by xuanzhi33** [comment]
估计是您的主题的原因 开往按钮在手机端自动隐藏了
您可以在顶栏“友链”菜单中再加一个开往链接，这样手机点击右上角菜单栏就可以看到开往链接了~

**Comment by mnochen** [comment]
> 估计是您的主题的原因 开往按钮在手机端自动隐藏了 您可以在顶栏“友链”菜单中再加一个开往链接，这样手机点击右上角菜单栏就可以看到开往链接了~

已在底栏和有链位置各加了一个跳转入口

**Comment by linlinzzo** [comment]
> 已在底栏和有链位置各加了一个跳转入口

@xuanzhi33
