### ISSUE TITLE
阿云的宝库

### ISSUE THREAD

**Issue by Irqis** [travellings-link/travellings#1977]
### 网站名称

阿云的宝库

### 网站网址

https://www.yunxge.cn

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by Irqis** [comment]
![image](https://github.com/travellings-link/travellings/assets/130670782/5a690189-5826-44ce-aed3-cda30c3bf5e2)
已添加，谢谢
