### ISSUE TITLE
申请变更：[老咸鱼的池塘]

### ISSUE THREAD

**Issue by miaokaXD** [travellings-link/travellings#1980]
### 原网址

https://nixieka.top

### 原 Issue 编号

#1554

### 新网站名称 (不更改名称请留空)

孤熵小狼

### 新网址（不更改网址请留空）

https://blog.nixieka.top

### 备注

您好，博客重新装修了，目前链接为 https://blog.nixieka.top ，RSS订阅地址为 https://blog.nixieka.top/atom.xml ，文章正在迁移，带来不便还请谅解，谢谢！

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
已给你的网站贴上标签：博客、技术类。
