### ISSUE TITLE
更新 Muyulong's Blog申请收录

### ISSUE THREAD

**Issue by muyulong** [travellings-link/travellings#20]
## 网站名称
Muyulong's Blog
## 网站链接
https://mmyyll.ml/
## 徽标位置
顶栏 友链页面
## 推荐理由
小透明萌新以后就跟着大佬们混了

**Comment by volfclub** [comment]
ssl 配置似乎有问题，无法打开网站。检查下？

**Comment by muyulong** [comment]
现在看看呢，应该没问题了

**Comment by volfclub** [comment]
可能和我代理有关，先收录了

**Comment by muyulong** [comment]
大佬，我回来了，博客现在能访问了
网站名称
Muyulong's Blog

网站链接
https://mmyyll.ml/

徽标位置
顶栏

推荐理由
分享一些学习经历，生活日常

**Comment by linlinzzo** [comment]
侧边栏在移动端收起时未在底部放置开往徽标。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已移除开往链接，现已将您移除，如需加入开往，可再次按照流程申请。 @muyulong
