### ISSUE TITLE
Kuka

### ISSUE THREAD

**Issue by Kukaina** [travellings-link/travellings#2002]
### 网站名称

Kuka

### 网站网址

https://www.xwsclub.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
初三、INFJ、原神、胡桃，看来可以做朋友了😉

**Comment by linlinzzo** [comment]
鉴于你的网站是技术类博客，我将你的申请分配给了 @Luochancy 。

**Comment by Luochancy** [comment]
我测原+技术佬+胡桃厨
这不得狠狠地通过
