### ISSUE TITLE
光溯星河

### ISSUE THREAD

**Issue by timeStarry** [travellings-link/travellings#2009]
### 网站名称

光溯星河

### 网站网址

https://blog.tsio.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by timeStarry** [comment]
> 您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

您好，已经修复手机端开往链接问题
位置：折叠菜单栏
样式：开往🚇
