### ISSUE TITLE
安凝雪科技

### ISSUE THREAD

**Issue by 661111** [travellings-link/travellings#2019]
### 网站名称

安凝雪科技

### 网站网址

https://www.anxkj.top

### 徽标位置

- [ ] 顶栏
- [x] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，您的开往链接设置不正确，应为go.html而不是docs/join
另外，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by 661111** [comment]
已修改

**Comment by BLxcwg666** [comment]
你好，当前时间 2024/02/19 21:49，位于中国浙江省温州市  
您的网站无法打开  
```
This site can’t be reachedwww.anxkj.top unexpectedly closed the connection.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_CLOSED
```

**Comment by 661111** [comment]
可能是缓存问题，清一下缓存
![fd9072a0fcf0396ef3f65a9c016ad33](https://github.com/travellings-link/travellings/assets/108344166/c5ad0c29-7140-4310-bc3b-97b5976ef294)

**Comment by xuanzhi33** [comment]
![image](https://github.com/travellings-link/travellings/assets/37460139/4e2deda0-1d37-4015-b0f3-d0f3fc081d4a)
2024-2-21 位于浙江省，仍然无法访问

**Comment by Luochancy** [comment]
您好，欢迎您申请加入开往
您的网站目前仅国内部分区域可正常访问，目前我所使用的网络环境（CNFJ ChinaMobile 5G,CNFJ ChinaTelecom）可正常访问。我通过 ITDog 进行网站访问测试，结果为大部分区域无法正常访问到您的网站。鉴于您的网站服务器 IP 位于 HK SAR，可以尝试使用第三方免费 CDN 服务对您的网站进行加速。
同时，如果多名开往维护组成员表示无法访问网站，我们有权驳回您的加入申请。请您在优化网站的访问情况后再次回复本 issue，我们将再次为您的申请进行审核！
附：ITDog 情况截图
![IMG_20240221_163130](https://github.com/travellings-link/travellings/assets/86495643/b60624bb-b154-4f17-a33f-54cff8e9eedb)

**Comment by 661111** [comment]
已配置完第三方cdn，目前itdog访问为200
![50d2c6574c7b141ab473e33d6c00950](https://github.com/travellings-link/travellings/assets/108344166/7329b4cb-60fd-4c77-8965-17d836e4859c)

**Comment by 661111** [comment]
已配置完第三方cdn，目前itdog访问为200
![50d2c6574c7b141ab473e33d6c00950](https://github.com/travellings-link/travellings/assets/108344166/7329b4cb-60fd-4c77-8965-17d836e4859c)

**Comment by xuanzhi33** [comment]
#2069
