### ISSUE TITLE
SWJ

### ISSUE THREAD

**Issue by ZGGSONG** [travellings-link/travellings#202]
## 网站名称

SWJ

## 网站链接

https://blog.zggsong.cn

## 徽标位置

侧边栏

![travelling](https://cdn.zggsong.cn/2020/06/16/bcc8795d88b53.png)

## 推荐理由

简单记录学习与生活

**Comment by volfclub** [comment]
已收录

**Comment by ZGGSONG** [comment]
# 更新一下站点(麻烦了)：

## 网站名称

ZGGSONG

## 网站链接

https://www.zggsong.cn

## 徽标位置

顶部导航栏

![](https://cdn.jsdelivr.net/gh/zggsong/cdn/blog/travellings.png)

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by linlinzzo** [comment]
没有看到开往链接？

**Comment by ZGGSONG** [comment]
已更新，底栏
另：域名已更新 zggsong.com
