### ISSUE TITLE
[Lan's Blog]

### ISSUE THREAD

**Issue by xiaoland** [travellings-link/travellings#2032]
### 网站名称

Lan's Blog

### 网站网址

https://blog.hadream.ltd

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
请注意，您的网站采用了二次跳转的形式，巡查系统可能无法正常识别，敬请留意成员列表中的巡查结果

**Comment by xuanzhi33** [comment]
建议改为直接跳转~

**Comment by xiaoland** [comment]
好的，我改一下
