### ISSUE TITLE
[Lan's Culture Blog 蓝之酱的人文博客]

### ISSUE THREAD

**Issue by xiaoland** [travellings-link/travellings#2033]
### 网站名称

Lan's Culture Blog 蓝之酱的人文博客

### 网站网址

https://culture.blog.hadream.ltd

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，您的主博客（https://blog.hadream.ltd/）已经是开往成员了。
开往暂不支持同类型子站点（博客）的同时添加。
感谢您对开往的支持！
