### ISSUE TITLE
串串狗 xk

### ISSUE THREAD

**Issue by kohunglee** [travellings-link/travellings#2042]
### 网站名称

串串狗 xk

### 网站网址

https://www.ccgxk.com/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [x] 我已确认以上事项

**Comment by linlinzzo** [comment]
这个其他是指？
