### ISSUE TITLE
申请变更：[朱某的小窝]

### ISSUE THREAD

**Issue by zhumou123** [travellings-link/travellings#2045]
### 原网址

https://www.coolku.cc/

### 原 Issue 编号

#1632

### 新网站名称 (不更改名称请留空)

朱某的小窝

### 新网址（不更改网址请留空）

https://blog.zhuxu.xyz/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
我没能在开往成员列表中发现你的网站，你的旧网站是否存在长期打不开或者没有放置开往链接的情况？

参见 https://www.travellings.cn/announcements/removed-dead-site

**Comment by zhumou123** [comment]
![57444870aa52c600b0847c0332727ed9](https://github.com/travellings-link/travellings/assets/76876737/2988ba8f-e55c-4a24-9c40-736cbf77be7a)
![d02a888599ad9621c3bfb7884d184363](https://github.com/travellings-link/travellings/assets/76876737/16c1bed1-0285-43d4-af0b-7f577a711db3)
是这样的 网站 原名叫[玖久的小窝]但是今天我在成员列表里查询发现 站点链接显示的并不是本人的站

**Comment by xuanzhi33** [comment]
![image](https://github.com/travellings-link/travellings/assets/37460139/142a77d6-753a-4b93-b844-07938bb3f6ce)
