### ISSUE TITLE
风呼呼

### ISSUE THREAD

**Issue by whooc** [travellings-link/travellings#2049]
### 网站名称

风呼呼

### 网站网址

https://whooc.com

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠）
建议放置在您网站的顶栏~

**Comment by whooc** [comment]
已经添加到顶栏
