### ISSUE TITLE
申请变更：[中古美少女计划]

### ISSUE THREAD

**Issue by joyingwol** [travellings-link/travellings#2051]
### 原网址

https://chukogals.top

### 原 Issue 编号

#687

### 新网址（不更改网址请留空）

https://blog.chukogals.top/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
对不起，我没能在列表中发现你的网站。请检查你的旧网站曾经是否解析异常或者长期处于 LOST 状态。

详见 https://www.travellings.cn/announcements/removed-dead-site

**Comment by joyingwol** [comment]
好的，可能是旧域名有一年以上未包含友链接力导致的LOST，我将重新申请
