### ISSUE TITLE
群青流星

### ISSUE THREAD

**Issue by SmileGuide** [travellings-link/travellings#2067]
### 网站名称

群青流星 U'Marine Meteoroid

### 网站网址

https://www.karlukle.site

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

技术、生活类混合

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by SmileGuide** [comment]
> 您的网站采用了二次跳转的形式，巡查系统可能无法识别，请留意 [成员列表](https://list.travellings.cn/) 中的巡查结果~
> 建议还是改为直接跳转~

@xuanzhi33  我的网站主题限制了在菜单栏上的外部跳转  
不改会有什么后果吗

**Comment by xuanzhi33** [comment]
你可以尝试在网站的页脚或其他地方加上开往链接，这样也能被巡查系统检测到。

**Comment by BLxcwg666** [comment]
> 你可以尝试在网站的页脚或其他地方加上开往链接，这样也能被巡查系统检测到。

![image](https://github.com/travellings-link/travellings/assets/66854530/ef7a76e3-80c7-4414-a48e-d49a7740669b)
not mind
