### ISSUE TITLE
安凝雪科技

### ISSUE THREAD

**Issue by 661111** [travellings-link/travellings#2069]
### 网站名称

星知空

### 网站网址

https://www.anxkj.top

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
未在侧栏发现开往徽标。

**Comment by 661111** [comment]
己在侧栏加开往微标

**Comment by 661111** [comment]
是
