### ISSUE TITLE
[时歌的博客]

### ISSUE THREAD

**Issue by Lapis0x0** [travellings-link/travellings#2078]
### 网站名称

时歌的博客

### 网站网址

https://www.lapis.cafe

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的网站采用了js延时跳转，默认会被浏览器屏蔽，建议缩短跳转时间或改为立即跳转~

**Comment by shizhiyun** [comment]
> 您的网站采用了js延时跳转，默认会被浏览器屏蔽，建议缩短跳转时间或改为立即跳转~

已更新主题版本，现在应该会立即跳转了:D
