### ISSUE TITLE
乌云盖雪

### ISSUE THREAD

**Issue by wygxmew** [travellings-link/travellings#2083]
### 网站名称

乌云盖雪

### 网站网址

https://wygxmew.github.io/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，根据审核规则，请将“开往”链接放置在网页打开后就能看到的地方（仅移动端允许折叠）
建议放置在您网站的顶栏~

**Comment by wygxmew** [comment]
现在我把顶栏也放上了，我博客的字比较小，可能有点费眼神。
麻烦您仔细看一下，也有可能是网页没加载出来。

**Comment by BLxcwg666** [comment]
啊始于2006，这么老吗（xm

**Comment by wygxmew** [comment]
感谢管理员给通过 ^_^，最早的博文是从06年开始的，但那时不是放在Github
