### ISSUE TITLE
[一颗橘子唐]

### ISSUE THREAD

**Issue by XiaoTangr** [travellings-link/travellings#2096]
### 网站名称

一颗橘子唐のBlog

### 网站网址

https://me.icefox.site;   https://www.icefox.site

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [x] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by XiaoTangr** [comment]
update

**Comment by linlinzzo** [comment]
没有在列表中找到原本的站点。

**Comment by XiaoTangr** [comment]
pls add my my link，my site will add url of travelling to nav in my blog site，i am update my site now（some pages are not update to host）

**Comment by linlinzzo** [comment]
Sorry. I misunderstood.

**Comment by XiaoTangr** [comment]
Doesn't matter

**Comment by XiaoTangr** [comment]
it doesn't matter
