### ISSUE TITLE
<Test Issues>

### ISSUE THREAD

**Issue by BLxcwg666** [travellings-link/travellings#2119]
### 网站名称

test

### 网站网址

https://test.cn

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
do test

**Comment by xuanzhi33** [comment]
测试下站点删除功能
