### ISSUE TITLE
申请变更：[微光档案]

### ISSUE THREAD

**Issue by KazariEX** [travellings-link/travellings#2124]
### 原网址

https://bikariarchive.xyz

### 原 Issue 编号

#1807

### 新网址（不更改网址请留空）

https://bikari.top

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
![image](https://github.com/travellings-link/travellings/assets/66854530/35ebfe43-8b79-4126-a802-733f0b2c5eac)
您好像使用了自签名证书，建议使用正式证书以免卡巡查
![image](https://github.com/travellings-link/travellings/assets/66854530/35edafc4-6ead-496e-aced-b062054fbed4)
