### ISSUE TITLE
南巷清风

### ISSUE THREAD

**Issue by ZhouBinxin** [travellings-link/travellings#2129]
### 网站名称

南巷清风

### 网站网址

https://blog.bxin.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的网站采用了js延时跳转，默认会被浏览器屏蔽，建议缩短跳转时间或改为立即跳转~
