### ISSUE TITLE
ARIA-COMPANY

### ISSUE THREAD

**Issue by shuiwudengli** [travellings-link/travellings#2137]
### 网站名称

ARIA-COMPANY

### 网站网址

https://aqua-aria.company/

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
![image](https://github.com/travellings-link/travellings/assets/66854530/aa92fd04-b596-449d-a81a-c5f7d119c31d)
我这怎么好使 🤔

**Comment by Luochancy** [comment]
> ![image](https://private-user-images.githubusercontent.com/66854530/313798527-aa92fd04-b596-449d-a81a-c5f7d119c31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODc3MjcsIm5iZiI6MTcxMDc4NzQyNywicGF0aCI6Ii82Njg1NDUzMC8zMTM3OTg1MjctYWE5MmZkMDQtYjU5Ni00NDlkLWE4MWEtYzVmN2QxMTljMzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4NDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYjNjNDJlNDE1YjQ2NjM2Mjg5NTczMDY0ZDVmMmNjN2Y5NDU1NDdjYzMxOTM3YmU4MmNkNWZjMGI0ZWQyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G0pgL_7Zp0QT2Urn2NwKXtEztrvWeSxn2rBUNZVCcvs) 我这怎么好使 🤔

所以就是很迷
我电脑端Edge看看

**Comment by shuiwudengli** [comment]
已知道谷歌为什么标记的原因了，但是因个人需要我不打算申诉，麻烦撤销申请。
