### ISSUE TITLE
xavier skip's blog

### ISSUE THREAD

**Issue by xavierskip** [travellings-link/travellings#2139]
### 网站名称

xavierskip's blog

### 网站网址

https://blog.xavierskip.com/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
我个人有点不太能判断是否通过，故邀请其他开往成员一同审核

**Comment by linlinzzo** [comment]
粗看一下，内容并不涉及**违法违规**。
