### ISSUE TITLE
[网站名称]夜象后花园

### ISSUE THREAD

**Issue by nagasawaja** [travellings-link/travellings#2141]
### 网站名称

夜象后花园

### 网站网址

https://beni.pub

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

**Comment by nagasawaja** [comment]
> 您好，手机端网页未找到开往的链接，请您添加（可以添加在折叠的菜单栏中）

已修正，
![{80302BBD-BD7F-48cb-8E57-DCADA6C27BE2}](https://github.com/travellings-link/travellings/assets/11144120/97cc91ef-326c-4dd4-b14d-b2e2478e6775)
