### ISSUE TITLE
[MRIANSY小站]

### ISSUE THREAD

**Issue by traition** [travellings-link/travellings#2142]
### 网站名称

MRIANSY

### 网站网址

https://mriansy.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
![image](https://github.com/travellings-link/travellings/assets/37460139/825df82e-0cc3-428d-85b1-08f8349b7664)

**Comment by traition** [comment]
![image](https://github.com/travellings-link/travellings/assets/46415774/a853c379-4ebb-462d-8c6e-cf6777524b16)
我更改了cdn设置，目前测试一切正常，烦请再次访问试试，若还是遇到问题请提供ip国际或者请求头响应头以便排查问题，谢谢🙏🏻️！
