### ISSUE TITLE
[清羽飞扬]

### ISSUE THREAD

**Issue by willow-god** [travellings-link/travellings#2145]
### 网站名称

LiuShen's Blog

### 网站网址

https://www.qyliu.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by willow-god** [comment]
<img width="1271" alt="image" src="https://github.com/travellings-link/travellings/assets/93815242/4b20f73b-9f71-4b83-bcca-3304e8ae7010">
电脑端页面：
<img width="293" alt="image" src="https://github.com/travellings-link/travellings/assets/93815242/4d818a9c-fd2d-47d3-ba1a-be4ca3d89e24">
手机端页面：

**Comment by linlinzzo** [comment]
建议更改为技术类博客...
