### ISSUE TITLE
申请变更：xuanzhi33 的小站

### ISSUE THREAD

**Issue by xuanzhi33** [travellings-link/travellings#2152]
### 原网址

https://www.xuanzhi33.cn

### 网站 ID

268

### 原 Issue 编号

#666666

### 新网站名称 (不更改名称请留空)

xuanzhi33的小站

### 新网址（不更改网址请留空）

https://www.xuanzhi33.cn

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Paper-Dragon** [comment]
工具不少啊

**Comment by xuanzhi33** [comment]
哦这是个测试啦
我拿我自己网站做成员列表的自动更新测试

**Comment by BLxcwg666** [comment]
建议新开一个issues测，我直接set了label，现有的 "信息修改完成" 不会被动，然后无法触发action的自动关闭

**Comment by xuanzhi33** [comment]
那我把我这个label删了
