### ISSUE TITLE
申请变更：运维开发绿皮书

### ISSUE THREAD

**Issue by Paper-Dragon** [travellings-link/travellings#2160]
### 原网址

https://paper-dragon.github.io

### 网站 ID

939

### 原 Issue 编号

#1799

### 新网站名称 (不更改名称请留空)

运维开发绿皮书

### 新网址（不更改网址请留空）

https://www.geekery.cn/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by xuanzhi33** [comment]
您的ID好像是939，不是726？
