### ISSUE TITLE
瀚星阁

### ISSUE THREAD

**Issue by 661111** [travellings-link/travellings#2162]
### 原网址

https://www.anxkj.top

### 网站 ID

1076

### 原 Issue 编号

#2069

### 新网站名称 (不更改名称请留空)

瀚星阁

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Paper-Dragon** [comment]
你的博客无法点击
![图片](https://github.com/travellings-link/travellings/assets/49874457/8e61ce86-ca2e-4da9-b062-b3a79ddd3855)

**Comment by linlinzzo** [comment]
已更改信息，不过这里发现您的网站在检测时没能发现徽标，可能是框架检测不出来，建议您在网站底部通过HTML标签添加徽标，谢谢。
