### ISSUE TITLE
申请变更：PJ568的博客

### ISSUE THREAD

**Issue by PJ-568** [travellings-link/travellings#2166]
`--已作废--`

**Comment by linlinzzo** [comment]
1. 原网址暂时没有发现访问问题
2. 支持HTTPS为开往成员的硬性要求

**Comment by PJ-568** [comment]
### 原网址

https://pj568.eu.org

### 网站 ID

955

### 原 Issue 编号

1832

### 新网站名称 (不更改名称请留空)

_No response_

### 新网址（不更改网址请留空）

https://pj568.sbs

### 备注

域名变更。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Paper-Dragon** [comment]
404 Not Found

**Comment by Paper-Dragon** [comment]
https://tools.pj568.sbs/incert/?link=/lib/tools/v86/ 这个不错，给博主点赞

**Comment by HowieHz** [comment]
link #1832
