### ISSUE TITLE
申请变更：[网站名称]

### ISSUE THREAD

**Issue by God-2077** [travellings-link/travellings#2168]
### 原网址

https://space520.eu.org

### 网站 ID

821

### 原 Issue 编号

1660

### 备注

Hi

我是 Space520 ，是曾经 [时空之歌][1] （or 时光之歌 ？）的博主。

[时空之歌][1][（https://space520.eu.org/）][1] 已经在三月末关闭了。网站运行了一年又三个月，经历了数次“灾难”后最终还是关闭了。

[时空之歌][1] 网站的部分页面已上传到 [GitHub Repositories][2]。

您可以将 [时空之歌][1] 移出 开往 页面，很高兴曾经能加入 开往 ，也希望 开往 能够长久运行下去。

———— Space520

[1]: https://space520.eu.org/
[2]: https://github.com/God-2077/blog-backup

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
很遗憾听到您要离开开往的消息，已为您移除在开往的站点数据  
感谢您对开往的支持，愿未来安好
