### ISSUE TITLE
刘郎阁

### ISSUE THREAD

**Issue by Lyj3254** [travellings-link/travellings#2174]
### 网站名称

刘郎阁

### 网站网址

https://yjvc.cn

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
我没能在移动端看到开往的链接。

**Comment by Lyj3254** [comment]
可以了
