### ISSUE TITLE
Oyiso's Blog

### ISSUE THREAD

**Issue by kannafay** [travellings-link/travellings#2176]
### 网站名称

Oyiso's Blog

### 网站网址

https://oyiso.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by kannafay** [comment]
加了qq群，管理还没审核

**Comment by Luochancy** [comment]
> 加了qq群，管理还没审核

应该通过了现在
