### ISSUE TITLE
lozhu's blog

### ISSUE THREAD

**Issue by lozhu20** [travellings-link/travellings#2183]
### 网站名称

lozhu's blog

### 网站网址

https://lozhu.happy365.day

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
个人备注：开往文字（徽标）位置在导航栏与页脚

**Comment by Luochancy** [comment]
博主您好，我是开往维护组现行负责人 洛寒兮。

非常抱歉由于我的疏忽误通过了您的加入申请，在此进行撤销操作。

您的站点目前不满足[开往对成员站点的要求](https://www.travellings.cn/docs/join#_1-%E6%82%A8%E7%9A%84%E7%BD%91%E9%A1%B5%E5%BA%94%E6%BB%A1%E8%B6%B3)：
![image](https://github.com/travellings-link/travellings/assets/76810494/37a229e2-4a51-40bd-a82c-9398f8e2c113)

因此，我撤销了您的申请，还请谅解。

如果您已修正了以上问题，可以在7个自然日内重新打开这个 Issue 进行申请。

**Comment by lozhu20** [comment]
Luochancy 您好！感谢您的及时审核。我的站点目前已有原创内容一百余篇，第一篇内容发布于2018年，不知为何不满足“网页已有较多内容”的要求，可否明确告知一下原因，以便我修正相关的问题，再次感谢！
![Screenshot 2024-04-12 at 01 29 46](https://github.com/travellings-link/travellings/assets/44923922/ed0236aa-3dc1-4492-a448-9694dea0432e)

**Comment by BLxcwg666** [comment]
太佬了

**Comment by Luochancy** [comment]
非常抱歉，可能由于我通过移动端查看网站直接由主页内容来进行判定导致的失误
刚刚我也仔细查看了您的网页归档模块，的确是从2018年起更新。
非常非常抱歉由于我的失误给您带来了不好的体验

**Comment by lozhu20** [comment]
没关系，小问题，已经顺利加入开往大家庭！
