### ISSUE TITLE
小窝哟博客

### ISSUE THREAD

**Issue by XiaoWoUi** [travellings-link/travellings#2184]
### 网站名称

小窝哟博客

### 网站网址

https://blog.528688.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
博主您好，我是开往维护组成员 洛寒兮。

首先，感谢您关注并申请加入开往这个项目。

但遗憾的是，您的站点目前不满足1.[开往对成员站点的要求](https://www.travellings.cn/docs/join#_1-%E6%82%A8%E7%9A%84%E7%BD%91%E9%A1%B5%E5%BA%94%E6%BB%A1%E8%B6%B3)：
![image](https://github.com/travellings-link/travellings/assets/76810494/37a229e2-4a51-40bd-a82c-9398f8e2c113)
2.移动端未发现开往徽标

并且，根据您文章的发布时间与 GitHub 仓库的提交记录来看，您的站点可能存在内容堆砌 / 采集站 / 内容农场的问题。因此，对于您的加入申请，我们不予审核通过，还请谅解。

如果您已修正了以上问题，可以再次打开一个 Issue 进行申请。

**Comment by BLxcwg666** [comment]
![image](https://github.com/travellings-link/travellings/assets/66854530/d812176c-eae0-4687-b6e7-67b4652317e4)
2024/4/13 re.  
HTTP 525

**Comment by Luochancy** [comment]
尊敬的开往成员您好，我是开往负责人洛寒兮
我们在近期的随机访问检查发现您的网站出现无法访问的问题
具体问题为无法进入您的网站。还请您对您的网站进行维修，以避免他人跳转时出现网站不可用的情况

以下是随机访问检查的详细信息
随机访问检查时间：2024 年 6 月 2 日 凌晨 3:40
随机访问检查的 IP：中国香港
随机访问检查状态：TimeOut (超时)
随机访问检查结果：失败

**Comment by Big-Cake-jpg** [comment]
超时关闭。如有需要可重新提交 Issue 申请。

**Comment by HowieHz** [comment]
巡查时发现无外链

此过期站点未能及时清理，已清理
https://web.archive.org/web/20250215144011/https://blog.528688.cn/
