### ISSUE TITLE
春何景明

### ISSUE THREAD

**Issue by qcyh** [travellings-link/travellings#2185]
### 网站名称

春何景明

### 网站网址

https://qcyh.github.io/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
由于该用户 GitHub 账号及其网站一并被删除，现直接将其从开往成员列表中移除。
