### ISSUE TITLE
coder-1024的穿梭页面无法使用

### ISSUE THREAD

**Issue by lawrenceshi** [travellings-link/travellings#2187]
开往页面（自定义跳转页）中的 coder-1024.html （链接https://www.travellings.cn/coder-1024.html）
![页面截图](https://github.com/travellings-link/travellings/assets/108813113/889c8078-cc02-4218-a3c8-2d5939479ef5)

在按照help命令的指示输入t(开始穿梭)然后输入Y（确认）后无法跳转

![无法跳转截图](https://github.com/travellings-link/travellings/assets/108813113/ba3c834f-3d48-47b8-8275-6cc03ecca17f)

但是我将这个链接手动复制到浏览器里是可以正常访问的 ，如图：

![图](https://github.com/travellings-link/travellings/assets/108813113/e78fa010-3ede-491a-8085-7d051e7168fb)

期望得到解决！

**Comment by lawrenceshi** [comment]
录屏：

https://github.com/travellings-link/travellings/assets/108813113/437bc4f7-8e75-4981-94c2-4894acf590d5

**Comment by xuanzhi33** [comment]
b0041efbf4130a077e2968b20ac13a6d382c5e96
已修复
