### ISSUE TITLE
AiQiji

### ISSUE THREAD

**Issue by JiQingzhe2004** [travellings-link/travellings#2190]
### 网站名称

AiQiji

### 网站网址

https://aiqji.com

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
很高兴您向我们提出加入请求  
但是很抱歉，在我看来，您的网站不满足以下两点  
![image](https://github.com/travellings-link/travellings/assets/66854530/bdd2cadb-18a1-46ac-90b4-be445f7b6cfe)
内容疑似过于低质，您可以补充多一点不水的内容后再来申请  
如果您不满足我对您做出的评价，您可以 at 组内其他成员来进行复审
