### ISSUE TITLE
紫云初

### ISSUE THREAD

**Issue by baivbai** [travellings-link/travellings#2195]
### 网站名称

紫云初

### 网站网址

https://ziyunchu.com

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
这标志放的，差点没看见

**Comment by baivbai** [comment]
哈哈哈你就说大不大吧哈哈哈






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 紫云初 (Issue #2195)





 
这标志放的，差点没看见
