### ISSUE TITLE
LvemiX⁹

### ISSUE THREAD

**Issue by LvemiX520** [travellings-link/travellings#2205]
### 网站名称

LvemiX⁹

### 网站网址

https://lvemix520.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
您好，我是开往现任负责人洛寒兮，感谢您申请加入开往。
根据我们的核查，您的网站目前文章数量不符合我们所标注的要求。建议您更新多篇博文后再次提交 Issue！
![1e06f69f06f9d38dc23018866dfce778](https://github.com/travellings-link/travellings/assets/86495643/63fa81cf-1569-4cde-856c-2c21a4bfbb73)
