### ISSUE TITLE
[蓝调时刻]

### ISSUE THREAD

**Issue by liuanchen** [travellings-link/travellings#2208]
### 网站名称

蓝调时刻

### 网站网址

https://www.landiaoshike.com

### 徽标位置

- [ ] 顶栏
- [X] #2275
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
尊敬的站长您好，

我是开往的维护组成员 Restent Ou。根据巡查结果，我们发现您的网站未设置开往的入口。

请您于方便的时候将开往入口补回。谢谢您的理解！

**Comment by Luochancy** [comment]
尊敬的站长您好
目前根据手动检查，您的网站已出现无法访问（HTTP 502）
请检查您的网站是否出现服务器宕机、网站服务被关闭或其他可能影响到网站正常访问的问题
感谢您的配合！

**Comment by Big-Cake-jpg** [comment]
超时关闭，您的站点将被移出开往成员列表。

如有意向重新加入，请重新提交一个 Issue。
