### ISSUE TITLE
SCP:SL二次元社区服务器

### ISSUE THREAD

**Issue by FXDYJ** [travellings-link/travellings#2211]
### 网站名称

二次元社区服务器

### 网站网址

https://www.scpsl2d.cc

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
没看懂贵站的含义，如果是游戏服务器类的网站，是不是更应该使用论坛框架而不是博客呢

**Comment by FXDYJ** [comment]
> 没看懂贵站的含义，如果是游戏服务器类的网站，是不是更应该使用论坛框架而不是博客呢

服务器大部分的讨论均在QQ内完成，网站的意义只是公告，公示，整理零散的信息

**Comment by FXDYJ** [comment]
后续我们会把在QQ群内的公告转移到该网站中

**Comment by BLxcwg666** [comment]
> > 没看懂贵站的含义，如果是游戏服务器类的网站，是不是更应该使用论坛框架而不是博客呢
> 
> 服务器大部分的讨论均在QQ内完成，网站的意义只是公告，公示，整理零散的信息

重读 https://www.travellings.cn/docs/join

**Comment by Luochancy** [comment]
您好，我是开往项目现任负责人洛寒兮
似乎我在哪里看到这个服务器的宣传片
但非常非常可惜，我必须得驳回与关闭这个issue
您的网站不符合加入开往的要求中的第一条第一款：
网页已有较多内容（应有 20 篇文章或 10 篇原创文章，需要网站已创办两个月以上，更新时间自博客第一篇内容时间开始算起）
故您的申请我将驳回与关闭这个issue
请在完成修改后重新开启issue进行申请！
