### ISSUE TITLE
[Jinbo Pan Website]

### ISSUE THREAD

**Issue by panjinbo** [travellings-link/travellings#2219]
### 网站名称

Jinbo Pan Website

### 网站网址

https://www.panjinbo.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
![image](https://github.com/travellings-link/travellings/assets/66854530/ab7945b2-1f97-430d-b0c6-fd41b250a051)
文章有点少了

**Comment by panjinbo** [comment]
https://www.panjinbo.com/blogs/
好像刚刚10篇原创文章？

**Comment by BLxcwg666** [comment]
给您磕一个
