### ISSUE TITLE
陈郑逸领域

### ISSUE THREAD

**Issue by fujianprovince** [travellings-link/travellings#2225]
### 网站名称

陈郑逸领域

### 网站网址

https://fujianprovince.github.io/

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
~~你们E人都这么喜欢实名上网吗，太恐怖了.webp~~

**Comment by fujianprovince** [comment]
> ~你们E人都这么喜欢实名上网吗，太恐怖了.webp~

哈哈，不知道是不是这样欸，现在属于实名和网名并用的状态（给了网上的朋友两个可选项，能记住哪个记哪个

**Comment by gxres042** [comment]
站长您好，开往巡查机器人无法识别到您的开往入口。

根据加入开往的要求，您需要将开往入口放置在一个您网页打开后就能看到的地方、以便友链能够继续接力下去。

**Comment by Big-Cake-jpg** [comment]
超时关闭，您的站点将被移出开往成员列表。

如有意向重新加入，请重新提交一个 Issue。
