### ISSUE TITLE
Aciano.top

### ISSUE THREAD

**Issue by Amnesia-f** [travellings-link/travellings#2230]
### 网站名称

Aciano

### 网站网址

https://aciano.top/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_20240504-140548_Firefox.png](https://github.com/travellings-link/travellings/assets/53113178/841f35c0-6786-4fc3-b635-46c41007e48d)

![Screenshot_20240504-140558_Firefox.png](https://github.com/travellings-link/travellings/assets/53113178/8d52e871-590c-4ed9-bc83-d463f98d7b79)

可以指一下在哪里吗？

**Comment by Amnesia-f** [comment]
> ![Screenshot_20240504-140548_Firefox.png](https://private-user-images.githubusercontent.com/53113178/327926969-841f35c0-6786-4fc3-b635-46c41007e48d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mjc1NjMsIm5iZiI6MTcxNDgyNzI2MywicGF0aCI6Ii81MzExMzE3OC8zMjc5MjY5NjktODQxZjM1YzAtNjc4Ni00ZmMzLWI2MzUtNDZjNDEwMDdlNDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEyNTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMzgxNzkzYzZhZGUxY2QwMzI3YTRmODc1MGZiMTJhYzUyYzQ2N2ZmY2UwNzFlNTkzOTQwOTJmN2VkYjk4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xg4dO9YidABzqkGVOUtclHLFfFcyFFH89XZxfLzeHBY)
> 
> ![Screenshot_20240504-140558_Firefox.png](https://private-user-images.githubusercontent.com/53113178/327926977-8d52e871-590c-4ed9-bc83-d463f98d7b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mjc1NjMsIm5iZiI6MTcxNDgyNzI2MywicGF0aCI6Ii81MzExMzE3OC8zMjc5MjY5NzctOGQ1MmU4NzEtNTkwYy00ZWQ5LWJjODMtZDQ2M2Y5OGQ3Yjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEyNTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2Y2JhZDRiNjBjZDEwNjA5YTVmYzRlY2E3MDBkNTljYzZmNDUxNjdhNzM3NjZiMTI2YzA0YWNjMDhlMTdjMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ko_HTBbihVQZE9pQWyFU5JvConzqFoUzErZMPhyvlAU)
> 
> 可以指一下在哪里吗？

**Comment by linlinzzo** [comment]
**推荐**在电脑端第一眼就能看到的地方放置开往链接。

**Comment by linlinzzo** [comment]
博主也是高中生嘛...😎
