### ISSUE TITLE
噗派吖

### ISSUE THREAD

**Issue by Puopa** [travellings-link/travellings#2239]
### 网站名称

噗派吖

### 网站网址

https://pupua.top

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，我是开往项目组成员 Restent Ou，很抱歉让您久等了！
我在访问您的站点时，并没有发现您放置了开往的入口：
![图片](https://github.com/travellings-link/travellings/assets/53113178/f0b8298f-870e-46b3-a176-c2ea404b0696)
![图片](https://github.com/travellings-link/travellings/assets/53113178/72fc62af-ec05-4d42-a6c5-e22b47198605)
如果您确认已经放置了开往入口，烦请您告知我具体在哪一个地方。谢谢！

**Comment by Puopa** [comment]
![image](https://github.com/travellings-link/travellings/assets/121792302/8d9a9e14-4dcc-4ecd-a64d-f72aa9b2e42a)
不好意思，应该是缓存的问题，我刚刚刷新了以下缓存并且预热了以下。

**Comment by gxres042** [comment]
唔......
缓存日期设的很长吗？在前一两天访问过你的站点，也是没有出现入口。
