### ISSUE TITLE
申请变更：晨阳的小站

### ISSUE THREAD

**Issue by pureskys** [travellings-link/travellings#2244]
### 原网址

https://www.puresky.top

### 网站 ID

1059

### 原 Issue 编号

#2044

### 新网站名称 (不更改名称请留空)

轻雅阁

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
现在改信息好像非常方便，我们这里点一下导入就可以了，Issue还能自动关。

**Comment by linlinzzo** [comment]
诗写得不错

**Comment by pureskys** [comment]
> 诗写得不错

哈哈，谢谢夸奖😁
