### ISSUE TITLE
曙光小破站

### ISSUE THREAD

**Issue by shuguangdream** [travellings-link/travellings#2245]
### 网站名称

曙光团队

### 网站网址

https://www.dawnteam.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核先打回。
我在手机端并没有看到开往入口，麻烦您检查一下？

**Comment by shuguangdream** [comment]
他有个搜索按钮,在搜索按钮的那个菜单里。
到时候给他弄到明显的地方。

**Comment by gxres042** [comment]
> 他有个搜索按钮,在搜索按钮的那个菜单里。
> 到时候给他弄到明显的地方。

...不用改了，手机端找得到就可以。
我的错，不好意思><
