### ISSUE TITLE
申请变更：听得入迷空间

### ISSUE THREAD

**Issue by tdrme** [travellings-link/travellings#2248]
### 原网址

https://www.tdrme.cn

### 网站 ID

168

### 原 Issue 编号

381

### 新网站名称 (不更改名称请留空)

听得入迷空间

### 新网址（不更改网址请留空）

https://blog.tdrme.cn/

### 备注

反馈个问题吧，这个申请表变更信息的表单页面有些问题，在电脑端打开，最底下的按钮是超出屏幕的，并且无法上划。在手机端显示才能完整。
https://list.travellings.cn/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
> 反馈个问题吧，这个申请表变更信息的表单页面有些问题，在电脑端打开，最底下的按钮是超出屏幕的，并且无法上划。在手机端显示才能完整。

Bug assign to @xuanzhi33
