### ISSUE TITLE
Haoyu的博客

### ISSUE THREAD

**Issue by Ghyuav** [travellings-link/travellings#2256]
### 网站名称

Haoyu的博客

### 网站网址

https://g-haoyu.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，建议您在电脑端上将开往入口放在显眼的地方、以便友链接力下去，不推荐您放在折叠菜单里哦。^w^

**Comment by Ghyuav** [comment]
你好，电脑端目前已放入默认显示的菜单了啦😊

**Comment by linlinzzo** [comment]
@Ghyuav ？怎么自己关掉了？

**Comment by Ghyuav** [comment]
诶，好像手误点到了😓

**Comment by gxres042** [comment]
不好意思让您久等了，您的审核通过。*w*
