### ISSUE TITLE
Morick莫里克

### ISSUE THREAD

**Issue by Morick66** [travellings-link/travellings#2257]
### 网站名称

Morick莫里克

### 网站网址

https://www.morick66.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，有两点需要您注意一下：

- 根据我自己的判断指标，您的网站的有效文章似乎只有 9 篇（已撇除不应属于文章的「关于我」和没有什么内容的「Hello World」）。如果您这 9 篇文章都属于您的原创文章，您仍需要再提交一篇原创文章，反之则需要提交 11 篇文章；
- 我未在手机端上看到你设置的开往入口，可以指一下在手机端上您放在哪了吗？

**Comment by Morick66** [comment]
好的，我有效文章数量足够后再重新申请。
> 手机上开往我设置在了侧边栏底部。
![e5381b91bbdc863fdc028d961c6fe09](https://github.com/travellings-link/travellings/assets/60544711/1daa7002-b808-4c89-99be-3ab44e4afcdd)
