### ISSUE TITLE
王一川

### ISSUE THREAD

**Issue by kpretty** [travellings-link/travellings#2258]
### 网站名称

小王的大数据驿站

### 网站网址

https://uhope.fun

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
文章有点少了
![image](https://github.com/travellings-link/travellings/assets/66854530/5e240b63-b796-4537-9638-71724550e79a)
