### ISSUE TITLE
申请变更：[凉心的小窝]

### ISSUE THREAD

**Issue by 52Lxcloud** [travellings-link/travellings#2262]
### 原网址

https://www.xia.lt/

### 网站 ID

未收录

### 原 Issue 编号

#539

### 新网站名称 (不更改名称请留空)

凉心's Blog

### 新网址（不更改网址请留空）

https://www.lxink.cn/

### 备注

新布局采用侧边资料栏显示`开往`

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by 52Lxcloud** [comment]
应该是，之前域名过期就忘记更换了

**Comment by linlinzzo** [comment]
> 应该是，之前域名过期就忘记更换了

麻烦您用申请收录的模板重新填一下，谢谢。
