### ISSUE TITLE
[TNT我的世界论坛]

### ISSUE THREAD

**Issue by TNTnext** [travellings-link/travellings#2263]
### 网站名称

Tntmcbbs

### 网站网址

https://www.tntmcbbs.cn/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

论坛

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
欸，这个头像感觉有点像孙子烧烤的。

**Comment by linlinzzo** [comment]
有待组内讨论

**Comment by TNTnext** [comment]
我明天补几篇文章

**Comment by BLxcwg666** [comment]
论坛怎么了，我觉得没问题啊
