### ISSUE TITLE
[Memory Dairy]

### ISSUE THREAD

**Issue by Yc100** [travellings-link/travellings#2271]
### 网站名称

Memory Dairy

### 网站网址

https://yc100.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
文章有点少了......

![Screenshot_20240528-061423_Firefox.png](https://github.com/travellings-link/travellings/assets/53113178/55c5ed97-ce26-42a8-b569-38d7ab63af18)

![Screenshot_20240528-061549_Firefox.png](https://github.com/travellings-link/travellings/assets/53113178/292d470e-5f3d-40ee-8f7f-fdc11c5516f3)

并且我在手机端上没有看到您的网站有开往入口，不过电脑端有。

**Comment by Yc100** [comment]
好的 谢谢 我再完善一下

**Comment by Yc100** [comment]
已做调整，望审核 https://yc100.github.io/
