### ISSUE TITLE
椋鸟小窝

### ISSUE THREAD

**Issue by StarlingLin** [travellings-link/travellings#2274]
### 网站名称

StarlingLin的博客

### 网站网址

https://www.starlinglin.top/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_20240530-203014_Firefox.png](https://github.com/travellings-link/travellings/assets/53113178/0a229c36-bf39-43b9-9a22-71d6d2db2ff4)

建议不要再使用纸飞机图标。
