### ISSUE TITLE
迷失的小K

### ISSUE THREAD

**Issue by SmallKi-d** [travellings-link/travellings#2281]
### 网站名称

迷失的小K

### 网站网址

https://blog.kclub.tech/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_20240601-205417_Firefox.png](https://github.com/travellings-link/travellings/assets/53113178/8711de11-fa65-4448-94e7-e053aeecffc2)

麻烦您将顶栏的开往入口修改一下

**Comment by ltzXiaoYanMo** [comment]
> ![Screenshot_20240601-205417_Firefox.png](https://private-user-images.githubusercontent.com/53113178/335802362-8711de11-fa65-4448-94e7-e053aeecffc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzA5NTYsIm5iZiI6MTcxNzI3MDY1NiwicGF0aCI6Ii81MzExMzE3OC8zMzU4MDIzNjItODcxMWRlMTEtZmE2NS00NDQ4LTk0ZTctZTA1M2FlZWNmZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE5MzczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NDIxZGU2NTRmZjA2ZDNjMGJiNmExMmFlODVhYWRmOTJiZjk2MTEwYjhmYWEzYzYxY2M0YmY4NGRmMTBhOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lcq3eXkMgQUu2tZ5mtDzyBlYz9r_sqQiF2k-QnbeW2U)
> 
> 麻烦您将顶栏的开往入口修改一下

。。。你知道这一串鸟语是啥意思吗

**Comment by SmallKi-d** [comment]
已将异步跳转时间缩短，麻烦再检查一下，谢谢

**Comment by gxres042** [comment]
嗯，没问题了
