### ISSUE TITLE
枫落丰源の小窝

### ISSUE THREAD

**Issue by Qiufengluoyes** [travellings-link/travellings#2282]
### 网站名称

枫落丰源の小窝

### 网站网址

https://feng1026.fun/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [x] 我已确认以上事项

**Comment by Luochancy** [comment]
您好，我是开往现任负责人洛寒兮，感谢您申请加入开往。
根据我们的核查，您的网站目前文章总数不符合我们在开往加入要求的第一条第五款：网页已有较多内容（应有 20 篇文章或 10 篇原创文章，需要网站已创办两个月以上，更新时间自博客第一篇内容时间开始算起）
请您进行整改后回复本 Issue 或重新提交新的 Issue 以供我们审核。非常感谢您的配合！
![1e06f69f06f9d38dc23018866dfce778](https://github.com/travellings-link/travellings/assets/86495643/63fa81cf-1569-4cde-856c-2c21a4bfbb73)

**Comment by gxres042** [comment]
由于您长时间未回应，该 Issue 现已关闭。

后续您可重新提交申请，感谢您的理解与支持。
