### ISSUE TITLE
boychai's blog

### ISSUE THREAD

**Issue by BoyChai** [travellings-link/travellings#2292]
### 网站名称

boychai's blog

### 网站网址

https://blog.boychai.xyz/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

https://image.boychai.xyz/img/%E5%A4%B4%E5%83%8F.jpg

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
需要提醒您一下：如果您的「徽标位置」没有选择「其它」，请不要填写接下来的「更具体的徽标位置」。
