### ISSUE TITLE
viisaus

### ISSUE THREAD

**Issue by Joviisaus** [travellings-link/travellings#2294]
### 网站名称

viisaus(小欧同学）

### 网站网址

https://viisaus.tech

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您似乎在使用 HeoBlog 衍生主题，该主题的开往入口在手机端并不能看到。

![Screenshot_2024-06-05-16-27-36-173_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/c7222c4f-33ab-4b20-8218-3d6b1164c735)

以及，该主题的开往入口使用了 JavaScript 延时跳转。浏览器会判定为弹窗并进行拦截，需要您自行关掉延时跳转，或是在当前标签页跳转、而不是新建一个标签页。

![Screenshot_2024-06-05-16-27-48-347_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/3f579a18-d09f-4338-a33b-d03cee377b64)

**Comment by Joviisaus** [comment]
所述问题已经修复，现在开往入口在手机端仍然可以显示，页面跳转修改为当前标签页跳转，不会被当作弹窗处理
