### ISSUE TITLE
HOM

### ISSUE THREAD

**Issue by homteam** [travellings-link/travellings#2295]
### 网站名称

HOMteam

### 网站网址

https://homteam.github.io

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的文章数量并没有达到加入开往的需求。

![图片](https://github.com/travellings-link/travellings/assets/53113178/a6b898d5-95b5-4515-a3ad-d9e5290e5a84)

以及，您所使用的貌似是 hexo-theme-anzhiyu 主题，默认设置会导致浏览器拦截：

![图片](https://github.com/travellings-link/travellings/assets/53113178/d1f2a2ad-4113-45a7-9341-d369a37d04d5)

同时，我并没有看到您侧栏放置了开往入口。

![图片](https://github.com/travellings-link/travellings/assets/53113178/293a1376-4a7c-424b-aecd-1cf3f2ea5498)

![图片](https://github.com/travellings-link/travellings/assets/53113178/f9d7eb6d-b305-495f-b612-c984a04466fb)

**Comment by gxres042** [comment]
以及，我想要问你一个问题：

你的这个账号在前天才注册，昨天才将网站静态资源文件上传、并通过 GitHub Pages 发布，那么你前几个月的文章是怎么来的？

如果这些文章就是在前几个月发布的，由于我不知道你发布在了哪里，所以请将你当时发布这些文章的网站原始链接发上来。

**Comment by ltzXiaoYanMo** [comment]
> 以及，我想要问你一个问题：
> 
> 你的这个账号在前天才注册，昨天才将网站静态资源文件上传、并通过 GitHub Pages 发布，那么你前几个月的文章是怎么来的？
> 
> 如果这些文章就是在前几个月发布的，由于我不知道你发布在了哪里，所以请将你当时发布这些文章的网站原始链接发上来。

不好说，~~人家要是刚想开源节流呢~~

**Comment by gxres042** [comment]
由于您长时间未回应，该 Issue 现已关闭。您可以在符合加入条件的情况下、重新提交一个 Issue 以申请加入开往。

**Comment by homteam** [comment]
> 以及，我想要问你一个问题：
> 
> 你的这个账号在前天才注册，昨天才将网站静态资源文件上传、并通过 GitHub Pages 发布，那么你前几个月的文章是怎么来的？
> 
> 如果这些文章就是在前几个月发布的，由于我不知道你发布在了哪里，所以请将你当时发布这些文章的网站原始链接发上来。

原本部署在gitee，然后gitee关闭了gitee pages功能所以转到github了，原来地址在：https://gitee.com/HOMteam/HOMteam，当时不太懂网络和计算机（虽然时间也不算太久）所以没有仔细阅读条件以及在侧边栏添加开往。（最近才发现github这个未读消息功能，没有及时看到这个，抱歉了）

**Comment by ltzXiaoYanMo** [comment]
> > 以及，我想要问你一个问题：
> > 
> > 你的这个账号在前天才注册，昨天才将网站静态资源文件上传、并通过 GitHub Pages 发布，那么你前几个月的文章是怎么来的？
> > 
> > 如果这些文章就是在前几个月发布的，由于我不知道你发布在了哪里，所以请将你当时发布这些文章的网站原始链接发上来。
> 
> 原本部署在gitee，然后gitee关闭了gitee pages功能所以转到github了，原来地址在：https://gitee.com/HOMteam/HOMteam，当时不太懂网络和计算机（虽然时间也不算太久）所以没有仔细阅读条件以及在侧边栏添加开往。（最近才发现github这个未读消息功能，没有及时看到这个，抱歉了）

你只能重新开一个了，这个Issue大概人家也不管了

**Comment by homteam** [comment]
问一下点击开往的时候会弹出窗口怎么解决<img src="https://upload-bbs.miyoushe.com/upload/2023/03/09/3173bc3e69fcfebecfda741340c9ad22_6841250310756275678.png" alt="开拓者 吃瓜ing" width="75" >

**Comment by gxres042** [comment]
> 问一下点击开往的时候会弹出窗口怎么解决<img src="https://upload-bbs.miyoushe.com/upload/2023/03/09/3173bc3e69fcfebecfda741340c9ad22_6841250310756275678.png" alt="开拓者 吃瓜ing" width="75" >

主题塞了个 JavaScript 的 `window.open()`，而浏览器不允许这个 JavaScript 方式。

可以考虑将它当作正常的 nav item 添加，我已经很久没用过 Hexo 了，故我也不能给你一个准确的答案（
