### ISSUE TITLE
梦爱吃鱼

### ISSUE THREAD

**Issue by JLinMr** [travellings-link/travellings#2299]
### 网站名称

梦爱吃鱼

### 网站网址

https://blog.bsgun.cn/

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您使用的主题，若访客点击顶部的开往入口，在延时跳转的倒计时结束后，浏览器会把它当作弹窗并拦截处理，需要站长您修改相关配置。

![图片](https://github.com/travellings-link/travellings/assets/53113178/eed2e014-b7e4-4626-8d49-19b570cbad27)

其次，访问您的站点时发现，尝试查看您的文章详情时，点击文章卡片后无法跳转到文章详情页，需要您自行检查。

---

以及，您在站点末尾添加了开往的链接，徽标位置可以多选一个 **底部**。

**Comment by JLinMr** [comment]
底部已勾选

**Comment by JLinMr** [comment]
> 您使用的主题，若访客点击顶部的开往入口，在延时跳转的倒计时结束后，浏览器会把它当作弹窗并拦截处理，需要站长您修改相关配置。

> 以及，您在站点末尾添加了开往的链接，徽标位置可以多选一个 **底部**。

这个顶部的，是否因为你开了插件，Edge和chrome正常使用我这边不会被拦截，底部已勾选

**Comment by JLinMr** [comment]
> 您使用的主题，若访客点击顶部的开往入口，在延时跳转的倒计时结束后，浏览器会把它当作弹窗并拦截处理，需要站长您修改相关配置。

> 以及，您在站点末尾添加了开往的链接，徽标位置可以多选一个 **底部**。

这个顶部的，是否因为你开了插件，Edge和chrome正常使用我这边不会被拦截，底部已勾选
