### ISSUE TITLE
Haidong Xin - Homepage

### ISSUE THREAD

**Issue by xhd0728** [travellings-link/travellings#2300]
### 网站名称

Haidong Xin - Homepage

### 网站网址

https://xhd0728.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
二次元头像的 GitHub 账号配上了极为震撼的个人主页
