### ISSUE TITLE
XenWayne's Blog

### ISSUE THREAD

**Issue by XenWayne** [travellings-link/travellings#2303]
### 网站名称

XenWayne's Blog

### 网站网址

https://xenwayne.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
看你博客偏技术类的文章较多，我帮你分配给 @gxres042 审核。
