### ISSUE TITLE
申请变更：1nonly's blog

### ISSUE THREAD

**Issue by aayorishy** [travellings-link/travellings#2304]
### 原网址

https://blog.ban.moe

### 网站 ID

711

### 原 Issue 编号

#1706

### 新网站名称 (不更改名称请留空)

LIFE - 优生活

### 新网址（不更改网址请留空）

https://ulife.ink

### 备注

由于数据都存放在朋友的服务器上，前两个月他的服务器商跑路，导致数据全部丢失。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
![Screenshot_20240608_132109_mark via](https://github.com/travellings-link/travellings/assets/79007796/c5c4f096-1baa-4dda-8f53-3e24e0fa6e6e)
？

**Comment by aayorishy** [comment]
> ![Screenshot_20240608_132109_mark via](https://private-user-images.githubusercontent.com/79007796/337834777-c5c4f096-1baa-4dda-8f53-3e24e0fa6e6e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjQ0NTgsIm5iZiI6MTcxNzgyNDE1OCwicGF0aCI6Ii83OTAwNzc5Ni8zMzc4MzQ3NzctYzVjNGYwOTYtMWJhYS00ZGRhLThmNTMtM2UyNGUwZmE2ZTZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA1MjIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YmI5M2ExMmY0NjFlMDMzN2ZkNjhkNGQ4OWIyM2FkNDQ0YzY2NTFmYzEwMzBjOTgyMGJjNjRhYWYzYjY1OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b5R4SbShMpHFWvUvAFBrj1VgEKyf4uSQevbmyi8GF9s) ？

在迁移服务器，抱歉，可能要一个小时左右才能恢复

**Comment by linlinzzo** [comment]
> 可能要一个小时左右才能恢复

那这个issue我先放着，你迁移好了在这里说一声。

**Comment by aayorishy** [comment]
> > 可能要一个小时左右才能恢复
> 
> 那这个issue我先放着，你迁移好了在这里说一声。

好嘞，哥

**Comment by aayorishy** [comment]
> > 可能要一个小时左右才能恢复
> 
> 那这个issue我先放着，你迁移好了在这里说一声。

好了，可以访问了，麻烦了。

**Comment by linlinzzo** [comment]
网站状态需要等到下一次机器巡查时恢复。
