### ISSUE TITLE
ice's blog

### ISSUE THREAD

**Issue by huanghong888** [travellings-link/travellings#2305]
### 网站名称

一个有趣的小站

### 网站网址

https://ice-crean.xyz/

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
题外话：友链貌似不说friendly哦

**Comment by linlinzzo** [comment]
小学快毕业就建了这么一个像样的博客，后生可畏。

**Comment by linlinzzo** [comment]
不过你的网站目前内容比较少，等你多发点文章之后，欢迎你再来申请。

**Comment by huanghong888** [comment]
多谢指正，我会尽力更新文章的！

**Comment by gxres042** [comment]
如果你准备好了，可以重新开启这个 Issue 喔。
