### ISSUE TITLE
申请变更：湘铭呀！

### ISSUE THREAD

**Issue by xiangmingya** [travellings-link/travellings#2314]
### 原网址

https://www.xiangming.site

### 网站 ID

639

### 原 Issue 编号

#1330

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
所以你变更了啥？

**Comment by gxres042** [comment]
（擦汗）这个情况下你应该新建一个空白 Issue....

**Comment by xiangmingya** [comment]
谢谢
