### ISSUE TITLE
浅小兮の梦

### ISSUE THREAD

**Issue by sunrixet** [travellings-link/travellings#2315]
### 网站名称

浅小兮の梦

### 网站网址

https://zxwlove.xyz

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的内容还不是很丰富，并且更新时间不足两个月。

![图片](https://github.com/travellings-link/travellings/assets/53113178/b38d594c-a8d3-4ea0-b4fe-721aceac2a84)

**Comment by sunrixet** [comment]
好的，我已收到贵站（社区）回复，我将会丰富我的博客网站，感谢收录！

**Comment by sunrixet** [comment]
好的，我已收到贵站（社区）回复，我将会丰富我的博客网站，感谢收录！

**Comment by gxres042** [comment]
如果您认为您的站点满足了加入开往的要求，重新开启这个 Issue 再次申请即可
