### ISSUE TITLE
朽丘博

### ISSUE THREAD

**Issue by lkcdm** [travellings-link/travellings#2316]
### 网站名称

朽丘博

### 网站网址

https://koxiuqiu.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

如果是PC段则是在右上角第一个，如果是移动端是右上角打开折叠

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by lkcdm** [comment]
你好，因本站正在进行备案步骤，暂时停止了解析服务。等待备案完成后将尽快恢复。歉意

**Comment by tcomil** [comment]
查了圣经 猫不会下地狱🌝但是你肯定遭报应康
