### ISSUE TITLE
阿狸鹿丫

### ISSUE THREAD

**Issue by szzhongzi** [travellings-link/travellings#2317]
### 网站名称

Aliluya's Blog

### 网站网址

https://blog.aliluya.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

blog顶部左上角四叶草位置

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的网站创办日期时长并不够两个月，不符合开往的加入申请。

![图片](https://github.com/travellings-link/travellings/assets/53113178/8ea1859b-5dd8-4d10-8b20-86d1b87ead22)

**Comment by szzhongzi** [comment]
> 那个成立的日期和时间还不到两个月，不符合开设加入申请的条件。
> 
> ![图片](https://private-user-images.githubusercontent.com/53113178/339334136-8ea1859b-5dd8-4d10-8b20-86d1b87ead22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzcwNzQsIm5iZiI6MTcxODI3Njc3NCwicGF0aCI6Ii81MzExMzE3OC8zMzkzMzQxMzYtOGVhMTg1OWItNWRkOC00ZDEwLThiMjAtODZkMWI4N2VhZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDExMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzU2YTkxOTRjZTQ1MTZjMDlmYmIzYmU2MzBmNDkyMmNiYjlmYjhiMDlkYTQzZjRjNzU4YzgzYmEwYjZiMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hpt7uqQn42f95KaxniglqpACzRK0jd0DWtiZ8H5Kb4)

好的，我满足之后再申请！！！谢谢！！

**Comment by gxres042** [comment]
满足了之后重新开启这个 Issue 即可

**Comment by szzhongzi** [comment]
重新申请!!!!
