### ISSUE TITLE
[晨鹤部落格]

### ISSUE THREAD

**Issue by ichenhe** [travellings-link/travellings#2320]
> 之前申请过，但不知道为什么在查询系统里搜不到，也没收到过巡检不通过通知。 见 #669

### 网站名称

晨鹤部落格

### 网站网址

https://chenhe.me

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
> 之前申请过，但不知道为什么在查询系统里搜不到，也没收到过巡检不通过通知。 见 https://github.com/travellings-link/travellings/issues/669

有可能是数据库对接的问题，目前的开往成员列表里没有您的数据 ><

**Comment by gxres042** [comment]
@ichenhe 由于你加了这一行，数据库那边没有正确录入。:thinking:

![图片](https://github.com/travellings-link/travellings/assets/53113178/a926bbcf-b84c-4824-8828-e9ee91704cb0)

**Comment by ichenhe** [comment]
@gxres042 尴尬。。我把那行删了，可以重试吗
