### ISSUE TITLE
[沧海的空间]

### ISSUE THREAD

**Issue by Deepsea-CN** [travellings-link/travellings#2322]
### 网站名称

沧海的空间

### 网站网址

https://halloworlds.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gtxykn0504** [comment]
之后注意开issue的时候要改下title噢
