### ISSUE TITLE
北歌

### ISSUE THREAD

**Issue by kinsey973** [travellings-link/travellings#2326]
### 网站名称

北沐城歌

### 网站网址

https://kinsey973.github.io/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的开往入口处在一个桌面端首页默认收起的菜单里。建议在页脚多加一个？

**Comment by kinsey973** [comment]
但我不知道在哪个文件里修改

**Comment by kinsey973** [comment]
我不知道在哪个文件里修改代码

**Comment by gxres042** [comment]
> 您好，我不知道在哪个文件里修改代码

请搜索 hexo-theme-yun 的相关源码

**Comment by kinsey973** [comment]
ok,放页面最下方了
