### ISSUE TITLE
小明的部落格

### ISSUE THREAD

**Issue by xiaoming-crypto** [travellings-link/travellings#2328]
### 网站名称

小明的部落格

### 网站网址

https://www.xmdblog.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
文章数量还不够加入开往的要求哦。

![Screenshot_2024-06-17-13-11-34-554_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/86113dda-eb0e-44e8-b0ec-a984cdd9954a)

当前有效文章数量只有 5 篇，Hello World 并不算。

以及你顶栏的开往徽章在哪里？

![Screenshot_2024-06-17-13-16-11-185_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/87727504-94a2-40bf-b8e0-3930eab633f5)

**Comment by xiaoming-crypto** [comment]
<img width="704" alt="image" src="https://github.com/travellings-link/travellings/assets/97712373/17af0df9-dfcd-43e5-891d-d2745214f400">
在这里，文章我再写写吧

**Comment by gxres042** [comment]
到时候想再次申请的话，重新开启这个 issue 即可
