### ISSUE TITLE
[企鹅的小站]

### ISSUE THREAD

**Issue by penguinway** [travellings-link/travellings#2331]
### 网站名称

企鹅的小站

### 网站网址

https://penguinway.space

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by linlinzzo** [comment]
看了首页的文章貌似技术类的文章会更多一点。

**Comment by linlinzzo** [comment]
@gxres042 组里考虑加一个round robin吗？不然感觉手动分配的话会偏向于你。

**Comment by gxres042** [comment]
> @gxres042 组里考虑加一个round robin吗？不然感觉手动分配的话会偏向于你。

可以吧？

**Comment by gxres042** [comment]
虽然审核过了，但是你的站点并没有与生活有特别大关系的内容，反倒是技术内容占了大比。后面内容方向我会手动改成技术。
