### ISSUE TITLE
凌云·LinYun

### ISSUE THREAD

**Issue by wuyuhanzijin** [travellings-link/travellings#2336]
### 网站名称

凌云·LinYun

### 网站网址

https://www.linyunlink.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的有效文章数量不够十篇，不符合加入开往的要求，因此您的申请被驳回。

以及，我看到您写了两篇关于 Cloudflare Workers 的文章，很好奇为什么您会选择用 Workers Route 而不是 Custom Domain 呢？

**Comment by wuyuhanzijin** [comment]
其实还有2篇文章还没有从旧博客迁移，请问一下博客被驳回，需要再开一个Issues吗？
PS 我关于Cloudflare Worker的文章是针对Github全站加速的，Custom Domain应该是Github Page的东西吧（雾

**Comment by BLxcwg666** [comment]
> 其实还有2篇文章还没有从旧博客迁移，请问一下博客被驳回，需要再开一个Issues吗？ PS 我关于Cloudflare Worker的文章是针对Github全站加速的，Custom Domain应该是Github Page的东西吧（雾

你好  
![image](https://github.com/travellings-link/travellings/assets/66854530/819b5851-d74b-4c4d-933e-9bf4639f0b40)

**Comment by BLxcwg666** [comment]
还有咱就是说你的教程中反代的目标是 www.github.com ，实际上该地址会 301 到 github.com ，所以你的反代有什么意义吗，发文之前自己测试过了吗

**Comment by wuyuhanzijin** [comment]
可以看一下我的站点 https://github.linyunlink.top/
并没有重定向

**Comment by wuyuhanzijin** [comment]
我测试没有问题，但是我发现www.github.com确实会重定向到github.com，我觉得我去修改一下更严谨，但是实际使用并没有产生错误，也可以正常下载github上的文件，大概4mb/s

**Comment by BLxcwg666** [comment]
workers 几行代码能解决的事也是能让你整了一坨，也是佩服

**Comment by wuyuhanzijin** [comment]
那么请问可以给一下你的方案吗？我借鉴一下

**Comment by wuyuhanzijin** [comment]
重新提起申请，目前博客正在企划的文章：铜镜实验：以铜为镜可以正衣冠 现在完成
加上Hello World(包含内容中原创的短诗)以及其他文章一共10篇文章 请审核
其他内容我的博客会继续更新跟进

**Comment by gxres042** [comment]
其实

标有「通知」的文章并不能算是文章

看过了，并不能作数。博主还要对「原创文章」这个概念有一定的了解

**Comment by wuyuhanzijin** [comment]
好的，感谢审核大大。目前博客文章12篇，通知2篇，其余10篇均为本人原创文章，请审核。感谢审核大大不辞辛劳帮助审核，大大辛苦了
原创文章链接
https://www.linyunlink.top/article/hello-world
https://www.linyunlink.top/article/post-230716
