### ISSUE TITLE
XXX

### ISSUE THREAD

**Issue by zsh1116** [travellings-link/travellings#2338]
### 网站名称

XXX

### 网站网址

https://xxx.kesug.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by zsh1116** [comment]
之前信息填错，现在信息已更新

**Comment by gxres042** [comment]
想了想还是过了，久等了
