### ISSUE TITLE
云深知处

### ISSUE THREAD

**Issue by noname-jiang** [travellings-link/travellings#2339]
### 网站名称

云深知处

### 网站网址

https://www.jjy2023.cn/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![图片](https://github.com/travellings-link/travellings/assets/53113178/062b477e-7c5b-4428-987e-8783d18fcc28)
![图片](https://github.com/travellings-link/travellings/assets/53113178/40931177-59ea-4544-9c94-36a1bc4760ae)

**Comment by gxres042** [comment]
由于您长时间未回应，该 Issue 现已手动关闭。您可重新提起一个 Issue 以申请加入开往。
