### ISSUE TITLE
存档计划

### ISSUE THREAD

**Issue by lakejason0** [travellings-link/travellings#2340]
### 网站名称

存档计划

### 网站网址

https://lakeus.xyz

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

页面状态标志（位于页面内容h1标题右侧）

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by lakejason0** [comment]
一些小小的code snippet，如果有其他MediaWiki网站参与开往计划的话可以参考：
在LocalSettings.php中加入以下内容，在底部添加图标：
```php
$wgFooterIcons['joinedin']['travelling'] = [
    "src" => "https://www.travellings.cn/assets/logo.svg",
    "url" => "https://www.travellings.cn/go.html",
    "alt" => "开往-友链接力",
];
```
如果使用了我开发的MediaWiki皮肤[Lakeus](https://github.com/lakejason0/mediawiki-skins-Lakeus)，那么在页面状态标志处与我站同样的配置复现：
```php
$wgLakeusCustomIndicators = [
    [
        "id" => "mw-indicator-travelling",
        "class" => "mw-indicator",
        "html" => '<div class="mw-parser-output"><a href="https://www.travellings.cn/go.html" target="_blank" rel="noopener" title="开往-友链接力"><img src="https://www.travellings.cn/assets/logo.gif" alt="开往-友链接力" width="120"></a></div>',
    ]
];
```
最后，通过MediaWiki:Sidebar添加链接虽然容易，但请同时在LocalSettings.php内添加以下内容来让友链可以被搜索引擎承认：
```php
$wgNoFollowDomainExceptions[] = "travellings.cn";
```
MediaWiki:Sidebar内添加的内容：
```
* friendlink
** https://www.travellings.cn/go.html |friendlink-travelling
```
这么添加后，也需要在MediaWiki:Friendlink页面和MediaWiki:friendlink-travelling填入想要显示的文本，否则会原样显示英文。在子页面（如/en）下可加入相应的多语言版本。

**Comment by linlinzzo** [comment]
之前自己几度想要建立一个维基，但后面都缺乏毅力，没坚持下来。

**Comment by linlinzzo** [comment]
https://lakeus.xyz/-/2486 这里的MCW相关写得跟开往的博客一样啊，哈哈哈。😄
