### ISSUE TITLE
SerMsCoding

### ISSUE THREAD

**Issue by SerMs** [travellings-link/travellings#2344]
网站名称
SerMsCoding

网站网址
https://blog.serms.top/

徽标位置
 - [x] 顶栏
 - [ ] 侧栏
 - [x] 底部（只选此项一般无法通过审核）
 - [ ] 其它 
 
更具体的徽标位置
No response

内容方向
生活兼技术

请确认以下事项
- [x] 我已确认以上事项

**Comment by gxres042** [comment]
？你确定你是用了模板申请的吗

**Comment by SerMs** [comment]
昨天找了半天没看到,后面就自己手写了
![image](https://github.com/travellings-link/travellings/assets/67584847/1ae2683b-e0aa-48d4-ad58-3c4a04eaaa1f)

**Comment by gxres042** [comment]
> 昨天找了半天没看到,后面就自己手写了,你看是否需要我重新在用模板在申请一次
> ![image](https://github.com/travellings-link/travellings/assets/67584847/1ae2683b-e0aa-48d4-ad58-3c4a04eaaa1f)
> 

按你这个格式，应该不会影响....如果影响到的话会联系您重写（（
