### ISSUE TITLE
辰溪

### ISSUE THREAD

**Issue by cenxi2002** [travellings-link/travellings#2346]
### 网站名称

b.waychenxi.top

### 网站网址

 https://b.waychenxi.top

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

我的手机端开往是放在了侧栏，电脑端是顶栏

### 内容方向

生活兼技术

### 备注

希望能够同意我加入博客开往，谢谢

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
你都不仔细看一下要求的吗...

![Screenshot_2024-06-24-06-12-01-768_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/0aae768f-f9ee-44f0-97cb-51de96d3744f)
