### ISSUE TITLE
阿狸鹿丫

### ISSUE THREAD

**Issue by szzhongzi** [travellings-link/travellings#2348]
### 网站名称

阿狸鹿丫 BLOG

### 网站网址

https://blog.aliluya.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

blog顶部左上角四叶草位置

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
您好，我是开往维护组现任负责人洛寒兮

由于您的网站不符合我们加入规则 240624 修订版的第一条第七款 “网页已有较多内容（应有 20 篇文章或 10 篇原创文章，需要网站已创办两个月以上，更新时间自博客第一篇内容时间开始算起）”

同时为了保证开往成员站文章质量，我们疑似您的网站为 内容农场 ，判决依据为加入规则 240624 修订版中第一条第二款 “网页已有较多内容（应有 20 篇文章或 10 篇原创文章，需要网站已创办两个月以上，更新时间自博客第一篇内容时间开始算起）”

故我们驳回您的申请，请在修改完成后回复本 Issue 或重新开启新的 Issue

感谢您的理解与配合！
（附具体条例截图）
![IMG_20240625_011734](https://github.com/travellings-link/travellings/assets/86495643/47419036-1172-4a4c-a583-abd6bba52c64)

**Comment by szzhongzi** [comment]
时间应该够两个月啦。文章都是自己编辑的啊。不是采集的。

**Comment by Luochancy** [comment]
> 时间应该够两个月啦。文章都是自己编辑的啊。不是采集的。

主要是很多内容能在搜索引擎找到类似的
而且不单单要满足 2 个月，还得满足 20 篇文章或者 10 篇原创文章的最低要求

**Comment by szzhongzi** [comment]
> > 时间应该够两个月啦。文章都是自己编辑的啊。不是采集的。
> 
> 主要是很多内容能在搜索引擎找到类似的 而且不单单要满足 2 个月，还得满足 20 篇文章或者 10 篇原创文章的最低要求

好的，谢谢！
