### ISSUE TITLE
Dannile's Neverland

### ISSUE THREAD

**Issue by ac8186** [travellings-link/travellings#2349]
### 网站名称

Dannile's Neverland

### 网站网址

https://bull.eu.org

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
eu.org 在国内部分地区的解析比较差，我个人还是建议博主备一个自己的独立域名，或是别的（
