### ISSUE TITLE
[小苏打笔记]

### ISSUE THREAD

**Issue by ccfread** [travellings-link/travellings#2352]
### 网站名称

小苏打笔记

### 网站网址

https://www.teh.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

手机端在折叠菜单栏

### 内容方向

生活兼技术

### 备注

随缘记录生活和学习的博客小站，也会写短的日记

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-06-24-23-56-56-111_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/168d5350-f04e-4edb-8ed4-d3d1d2021e78)

你这是怕被海外 IP 打还是

**Comment by ccfread** [comment]
之前被打了一次，就暂关闭海外IP了，当前已经打开了。还需要问一下，海外IP是必须要一直开吗？

**Comment by gxres042** [comment]
> 还需要问一下，海外IP是必须要一直开吗？

不用，只是我审核时用的设备长期跨墙
