### ISSUE TITLE
Cyrus's Ship

### ISSUE THREAD

**Issue by CyrusChen-2007** [travellings-link/travellings#2353]
### 网站名称

Cyrus's Ship

### 网站网址

https://www.cyrusblog.net/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
后生可畏，加油
