### ISSUE TITLE
[iCKG 渝见]

### ISSUE THREAD

**Issue by heilinzz** [travellings-link/travellings#2354]
### 网站名称

iCKG 渝见

### 网站网址

https://www.ickg.net

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
手机端找不到开往的入口

**Comment by heilinzz** [comment]
![微信图片_20240625105021](https://github.com/travellings-link/travellings/assets/157586025/434693f9-ba3e-43d4-a646-7907a41bbfbb)

**Comment by heilinzz** [comment]
![Uploading 微信图片_20240625105021.jpg…]()
