### ISSUE TITLE
行之风の树洞

### ISSUE THREAD

**Issue by acgdlr** [travellings-link/travellings#2357]
### 网站名称

行之风の树洞

### 网站网址

https://acgdlr.fun/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
![image](https://github.com/travellings-link/travellings/assets/66854530/4802eaee-b1ee-4ccc-b9f1-6940bde3adcf)
