### ISSUE TITLE
申请变更：[网站名称]

### ISSUE THREAD

**Issue by LYXOfficial** [travellings-link/travellings#2358]
### 原网址

https://yisous.xyz

### 网站 ID

559

### 原 Issue 编号

1171

### 新网站名称 (不更改名称请留空)

Ariasakaの小窝

### 新网址（不更改网址请留空）

https://blog.yaria.top

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
救命，下次记得把标题改一下

**Comment by LYXOfficial** [comment]
> 救命，下次记得把标题改一下

好的，光看着下面的没注意上面的了（）

**Comment by HowieHz** [comment]
link #1171
