### ISSUE TITLE
网络一隅／Net`Corner

### ISSUE THREAD

**Issue by cc2007** [travellings-link/travellings#2359]
### 网站名称

网络一隅／Net`Corner

### 网站网址

https://cloud.sd.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
~~由于您的网站速度在我的设备上慢到我实在无法相信，因此 ~~您的申请可能会延后几天得到答复。

**Comment by gxres042** [comment]
> > ~~由于您的网站速度在我的设备上慢到我实在无法相信，因此~~ 您的申请可能会延后几天得到答复。
> 
> ![image](https://github.com/travellings-link/travellings/assets/88186750/62683333-5b21-4453-ba04-eb67055dbafa)
> 应该不至于吧（ 就是一般美国主机的速度吧💦

所以我也有点奇怪....裸脸和挂代理都是这样

得麻烦您等几天了
