### ISSUE TITLE
浅小兮の梦

### ISSUE THREAD

**Issue by sunrixet** [travellings-link/travellings#2361]
### 网站名称

浅小兮の梦

### 网站网址

https://zxwlove.xyz

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-06-30-22-36-27-739_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/2ef2b86a-5553-4b54-a6aa-780f24fac7d1)

顶部的开往入口是否使用了 `window.open()` ？

**Comment by sunrixet** [comment]
使用了windows.open(),需要修改吗

**Comment by sunrixet** [comment]
![屏幕截图 2024-07-01 092653](https://github.com/travellings-link/travellings/assets/138977560/ea51b288-34ee-4cb7-ace5-515169b41afa)

**Comment by gxres042** [comment]
> ![屏幕截图 2024-07-01 092653](https://github.com/travellings-link/travellings/assets/138977560/ea51b288-34ee-4cb7-ace5-515169b41afa)
> 

...这个操作会导致浏览器拦截，因为 timeout 实在是太长了
建议你删了 "_blank" 那个，然后部署上去、换个浏览器点开往入口，看看还有没有提示弹出式窗口拦截

**Comment by sunrixet** [comment]
删除“-blank”后无变化，已作出修改，双击可以跳过拦截（window.open应该是自动拦截）

**Comment by gxres042** [comment]
> 删除“-blank”后无变化，已作出修改，双击可以跳过拦截（window.open应该是自动拦截）

window.open 如果跟用户触发的操作间隔太长都会被拦截，「应该」可以去掉了
