### ISSUE TITLE
[每晚故事会丨资源发布网]

### ISSUE THREAD

**Issue by coffiner** [travellings-link/travellings#2362]
### 网站名称

每晚故事会丨资源发布网

### 网站网址

https://fb.xuexiao.wiki

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

网赚

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
您好，我是开往现任负责人洛寒兮
根据我们的审核，您的网站不符合开往加入规则当中的第一条第二款 “ 禁止采集站内容农场（对多站点聚合，源站不提供的数据进行统计不在此列。博客网站如果可以在搜索引擎中搜到很多相同的内容可能会被判定为“内容农场”） ”。
我们查看您的网站时，发现您约 2250 条博文当中竟然有约 2240 条博文的日期是在 2024 年 06 月 29 日至 2024 年 06 月 30 日的。正常人根本做不到几乎在一天半的时间里面编辑并发布 2000+ 条博文，故我们严重怀疑贵站为内容采集站。为了增强开往成员站的质量，我们决定驳回申请并手动关闭本 Issue 。
如发现您再次提交类似的网站申请，则我们将会把您加入项目还没到。为了减轻维护组工作压力，请您理解我们为什么这么做。

洛寒兮
2024 年 07 月 01 日
![IMG_20240701_004600](https://github.com/travellings-link/travellings/assets/86495643/45e41d51-e06d-4fb1-894c-1163d5df8eaa)

**Comment by Luochancy** [comment]
（以下内容不代表开往维护组的观点）
不是什么积极分子你一天半不到发2000+博文
我看的人都傻了
什么东西都有，我算的页数*单页文章数
我受不了，谁家积极分子啊
搁谁都想骂人
别乱增加维护组的审核压力

**Comment by coffiner** [comment]
了解的，原因是以前的旧文章放进去了，内容还在更新的，原因是先前的文章问题导致的，所以刚好我在提交的文章属于第二条里的内容农场，抱歉了。我会继续努力，争取早日获得审核，谢谢。
