### ISSUE TITLE
Feizhuqwq

### ISSUE THREAD

**Issue by feizhuqwq** [travellings-link/travellings#2363]
### 网站名称

The Feizhuqwq

### 网站网址

https://blog.feizhuqwq.com/

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
能放到侧栏吗谢谢你

**Comment by feizhuqwq** [comment]
抱歉，可以只添加底部吗

**Comment by gxres042** [comment]
![Screenshot_2024-07-05-17-55-32-825_com.github.android.jpg](https://github.com/travellings-link/travellings/assets/53113178/85615bc3-d381-4b6c-9ab3-0035adfaaf75)

你觉得这个选项是什么意思呢

**Comment by gxres042** [comment]
由于您长时间未回复，故 Issue 已手动关闭。
若要再次申请，您可以重新提起一个 Issue。
