### ISSUE TITLE
[慧心谷]

### ISSUE THREAD

**Issue by qyxhjoyb** [travellings-link/travellings#2365]
### 网站名称

慧心谷

### 网站网址

https://joyb.cc

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
根据你的第一篇文章更新时间来推算，你的站点创办日期还不足两个月、不符合加入开往的条件，因此我驳回了您的申请。

![Screenshot_2024-07-01-23-20-10-306_org.mozilla.firefox.jpg](https://github.com/travellings-link/travellings/assets/53113178/c04f2607-1e2f-482f-bef3-c0991c212016)

您可以在确认满足加入开往的所有条件下、重新申请加入开往。

**Comment by qyxhjoyb** [comment]
好~~~的(u‿ฺu✿ฺ)🥲
