### ISSUE TITLE
晚夜的个人博客

### ISSUE THREAD

**Issue by ixihcj** [travellings-link/travellings#2370]
### 网站名称

晚夜的个人博客

### 网站网址

https://www.iczrx.cn

### 徽标位置

- [ ] 顶栏
- [x] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![图片](https://github.com/travellings-link/travellings/assets/53113178/ce15e239-85d8-4845-83d3-1d79ab4efa46)

**Comment by ixihcj** [comment]
已添加侧栏
