### ISSUE TITLE
探人间

### ISSUE THREAD

**Issue by xyhcode** [travellings-link/travellings#2371]
### 网站名称

探人间

### 网站网址

https://www.hydsb0.com

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![图片](https://github.com/travellings-link/travellings/assets/53113178/a64181e5-99a9-48e8-b782-b8be2edad554)

![图片](https://github.com/travellings-link/travellings/assets/53113178/71af8630-f862-4ac3-8782-6a7cb58f037c)

**Comment by xyhcode** [comment]
> ![图片](https://private-user-images.githubusercontent.com/53113178/345393406-a64181e5-99a9-48e8-b782-b8be2edad554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTM0MDYtYTY0MTgxZTUtOTlhOS00OGU4LWI3ODItYjhiZTJlZGFkNTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2VhM2RkNDM2YmUxNTc3ZDk1NjY3ODFkN2I4ZjEzM2I4NmU4NTIwYWYyOWEyNjcyYmI3MzkxYTBhNmQ2ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PkAnpFeo6pHR6UMydeC6mFyGEsbUUTAW4o_3yO-c2A)
> 
> ![图片](https://private-user-images.githubusercontent.com/53113178/345393487-71af8630-f862-4ac3-8782-6a7cb58f037c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTM0ODctNzFhZjg2MzAtZjg2Mi00YWMzLTg3ODItNmE3Y2I1OGYwMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMWZmYzkzY2JhNTFlZTBjMjIyOGM5ODA0NWQ0NzAwZTlkZmNjMjIyMzQzZDU0NzY5NDBmMjQ5NzEyZTc2YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jvwDiFKN1b8RVCaxhBsIgDYyTA3X0V2vnHYqt08g8SU)
> 
> 并且你将开往入口放到了侧边的哪里？
> 
> ![图片](https://private-user-images.githubusercontent.com/53113178/345394105-476b01a6-8e9b-4e30-9fab-5002ea8066ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQxMDUtNDc2YjAxYTYtOGU5Yi00ZTMwLTlmYWItNTAwMmVhODA2NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMThkODYwZDFiZDliZTYwNGNkYWZlNDkxZDI3ODg0N2M5MjY5N2M1NmZiMWFjOWU0ZTZlNzY2MGVjNGIzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkwwVP_EuCn08iF9qG7Wps3qAcuJKSLFCVVlftFKBog) ![图片](https://private-user-images.githubusercontent.com/53113178/345394147-e8d5cb00-faf3-47bf-b58d-8faa54632531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQxNDctZThkNWNiMDAtZmFmMy00N2JmLWI1OGQtOGZhYTU0NjMyNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MjVkNmExNjdhZDNhMzI2NWI4NTIzNTBkNmViZmM0NjMzMjEyOTAzN2QwNmJiZGZjYWE1NzYwYzFhNmYyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJQaU5dg5pEVJrdtJBNhFiCLO1OQAJ_tZh5GTLD1PIo) ![图片](https://private-user-images.githubusercontent.com/53113178/345394202-6bb98015-ce31-4bdf-94d3-4979013d4369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQyMDItNmJiOTgwMTUtY2UzMS00YmRmLTk0ZDMtNDk3OTAxM2Q0MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MjM3MGMwNTBiMWU4ZTJkM2ViODY0ZWEzZDY4NGIxYTgyOGNmMWVlZDkxOGQ2YTA3ZDE0YzU0OWZkZjA0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9un5ZFKg-wnVxlSR01RSgjsxKLsa47QmoHHfXVD6Jvw) ![图片](https://private-user-images.githubusercontent.com/53113178/345394289-424dc86c-9150-44ce-b303-3af7f8f146f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQyODktNDI0ZGM4NmMtOTE1MC00NGNlLWIzMDMtM2FmN2Y4ZjE0NmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZWIwMDY4Y2MwMDYwNjZhYTFkYWUzOWVhNDk0ZTIxMzg0MWNkYmMyZDJkYjMwYTJlNDcwMGI3NmUzYzBiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mlgErocsXYDHU6-hHntgIg9bEnYkUF5nrRcR6JWqbpg)

那就只有顶栏吧 之前手机端的时候在右侧 现在改没了 抱歉

**Comment by gxres042** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/53113178/345393406-a64181e5-99a9-48e8-b782-b8be2edad554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTM0MDYtYTY0MTgxZTUtOTlhOS00OGU4LWI3ODItYjhiZTJlZGFkNTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2VhM2RkNDM2YmUxNTc3ZDk1NjY3ODFkN2I4ZjEzM2I4NmU4NTIwYWYyOWEyNjcyYmI3MzkxYTBhNmQ2ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PkAnpFeo6pHR6UMydeC6mFyGEsbUUTAW4o_3yO-c2A)
> > ![图片](https://private-user-images.githubusercontent.com/53113178/345393487-71af8630-f862-4ac3-8782-6a7cb58f037c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTM0ODctNzFhZjg2MzAtZjg2Mi00YWMzLTg3ODItNmE3Y2I1OGYwMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMWZmYzkzY2JhNTFlZTBjMjIyOGM5ODA0NWQ0NzAwZTlkZmNjMjIyMzQzZDU0NzY5NDBmMjQ5NzEyZTc2YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jvwDiFKN1b8RVCaxhBsIgDYyTA3X0V2vnHYqt08g8SU)
> > 并且你将开往入口放到了侧边的哪里？
> > ![图片](https://private-user-images.githubusercontent.com/53113178/345394105-476b01a6-8e9b-4e30-9fab-5002ea8066ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQxMDUtNDc2YjAxYTYtOGU5Yi00ZTMwLTlmYWItNTAwMmVhODA2NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMThkODYwZDFiZDliZTYwNGNkYWZlNDkxZDI3ODg0N2M5MjY5N2M1NmZiMWFjOWU0ZTZlNzY2MGVjNGIzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkwwVP_EuCn08iF9qG7Wps3qAcuJKSLFCVVlftFKBog) ![图片](https://private-user-images.githubusercontent.com/53113178/345394147-e8d5cb00-faf3-47bf-b58d-8faa54632531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQxNDctZThkNWNiMDAtZmFmMy00N2JmLWI1OGQtOGZhYTU0NjMyNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MjVkNmExNjdhZDNhMzI2NWI4NTIzNTBkNmViZmM0NjMzMjEyOTAzN2QwNmJiZGZjYWE1NzYwYzFhNmYyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJQaU5dg5pEVJrdtJBNhFiCLO1OQAJ_tZh5GTLD1PIo) ![图片](https://private-user-images.githubusercontent.com/53113178/345394202-6bb98015-ce31-4bdf-94d3-4979013d4369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQyMDItNmJiOTgwMTUtY2UzMS00YmRmLTk0ZDMtNDk3OTAxM2Q0MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MjM3MGMwNTBiMWU4ZTJkM2ViODY0ZWEzZDY4NGIxYTgyOGNmMWVlZDkxOGQ2YTA3ZDE0YzU0OWZkZjA0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9un5ZFKg-wnVxlSR01RSgjsxKLsa47QmoHHfXVD6Jvw) ![图片](https://private-user-images.githubusercontent.com/53113178/345394289-424dc86c-9150-44ce-b303-3af7f8f146f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQyODktNDI0ZGM4NmMtOTE1MC00NGNlLWIzMDMtM2FmN2Y4ZjE0NmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZWIwMDY4Y2MwMDYwNjZhYTFkYWUzOWVhNDk0ZTIxMzg0MWNkYmMyZDJkYjMwYTJlNDcwMGI3NmUzYzBiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mlgErocsXYDHU6-hHntgIg9bEnYkUF5nrRcR6JWqbpg)
> 
> 那就只有顶栏吧 之前手机端的时候在右侧 现在改没了 抱歉

草，顶栏那个是有点问题的

我没记错的话，那会在开往五月博客里写有：这个开往入口在用户点击后 timeout 5000ms 才执行一个 JavaScript 的 `window.open()` 调用方式，直接被浏览器拦了下来

~~您动手能力强的话要不改一下~~

**Comment by xyhcode** [comment]
> > > ![图片](https://private-user-images.githubusercontent.com/53113178/345393406-a64181e5-99a9-48e8-b782-b8be2edad554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTM0MDYtYTY0MTgxZTUtOTlhOS00OGU4LWI3ODItYjhiZTJlZGFkNTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2VhM2RkNDM2YmUxNTc3ZDk1NjY3ODFkN2I4ZjEzM2I4NmU4NTIwYWYyOWEyNjcyYmI3MzkxYTBhNmQ2ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PkAnpFeo6pHR6UMydeC6mFyGEsbUUTAW4o_3yO-c2A)
> > > ![图片](https://private-user-images.githubusercontent.com/53113178/345393487-71af8630-f862-4ac3-8782-6a7cb58f037c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTM0ODctNzFhZjg2MzAtZjg2Mi00YWMzLTg3ODItNmE3Y2I1OGYwMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMWZmYzkzY2JhNTFlZTBjMjIyOGM5ODA0NWQ0NzAwZTlkZmNjMjIyMzQzZDU0NzY5NDBmMjQ5NzEyZTc2YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jvwDiFKN1b8RVCaxhBsIgDYyTA3X0V2vnHYqt08g8SU)
> > > 并且你将开往入口放到了侧边的哪里？
> > > ![图片](https://private-user-images.githubusercontent.com/53113178/345394105-476b01a6-8e9b-4e30-9fab-5002ea8066ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQxMDUtNDc2YjAxYTYtOGU5Yi00ZTMwLTlmYWItNTAwMmVhODA2NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMThkODYwZDFiZDliZTYwNGNkYWZlNDkxZDI3ODg0N2M5MjY5N2M1NmZiMWFjOWU0ZTZlNzY2MGVjNGIzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkwwVP_EuCn08iF9qG7Wps3qAcuJKSLFCVVlftFKBog) ![图片](https://private-user-images.githubusercontent.com/53113178/345394147-e8d5cb00-faf3-47bf-b58d-8faa54632531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQxNDctZThkNWNiMDAtZmFmMy00N2JmLWI1OGQtOGZhYTU0NjMyNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MjVkNmExNjdhZDNhMzI2NWI4NTIzNTBkNmViZmM0NjMzMjEyOTAzN2QwNmJiZGZjYWE1NzYwYzFhNmYyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJQaU5dg5pEVJrdtJBNhFiCLO1OQAJ_tZh5GTLD1PIo) ![图片](https://private-user-images.githubusercontent.com/53113178/345394202-6bb98015-ce31-4bdf-94d3-4979013d4369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQyMDItNmJiOTgwMTUtY2UzMS00YmRmLTk0ZDMtNDk3OTAxM2Q0MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MjM3MGMwNTBiMWU4ZTJkM2ViODY0ZWEzZDY4NGIxYTgyOGNmMWVlZDkxOGQ2YTA3ZDE0YzU0OWZkZjA0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9un5ZFKg-wnVxlSR01RSgjsxKLsa47QmoHHfXVD6Jvw) ![图片](https://private-user-images.githubusercontent.com/53113178/345394289-424dc86c-9150-44ce-b303-3af7f8f146f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDQ2MTEsIm5iZiI6MTcyMDAwNDMxMSwicGF0aCI6Ii81MzExMzE3OC8zNDUzOTQyODktNDI0ZGM4NmMtOTE1MC00NGNlLWIzMDMtM2FmN2Y4ZjE0NmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZWIwMDY4Y2MwMDYwNjZhYTFkYWUzOWVhNDk0ZTIxMzg0MWNkYmMyZDJkYjMwYTJlNDcwMGI3NmUzYzBiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mlgErocsXYDHU6-hHntgIg9bEnYkUF5nrRcR6JWqbpg)
> > 
> > 
> > 那就只有顶栏吧 之前手机端的时候在右侧 现在改没了 抱歉
> 
> 草，顶栏那个是有点问题的
> 
> 我没记错的话，那会在开往五月博客里写有：这个开往入口在用户点击后 timeout 5000ms 才执行一个 JavaScript 的 `window.open()` 调用方式，直接被浏览器拦了下来
> 
> ~您动手能力强的话要不改一下~

顶栏改了 等会提交更新就好了

**Comment by xyhcode** [comment]
> 哦对了，这个开往入口，手机端应该是看不见的
> 
> 方便的话在页脚加一个也行？

手机端页脚加不了 直接满了

**Comment by gxres042** [comment]
> > 哦对了，这个开往入口，手机端应该是看不见的
> > 
> > 方便的话在页脚加一个也行？
> 
> 手机端页脚加不了 直接满了

那您找个合适的地方放吧（）手机端现在是看不到的

手机端左上角那个菜单或许可以？
