### ISSUE TITLE
HenryWHU

### ISSUE THREAD

**Issue by HenryMoreau** [travellings-link/travellings#2373]
### 网站名称

Henry Moreau

### 网站网址

https://henrywhu.cn

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

桌面版页面中十分显眼的位置

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
博客的文章还是太少了...?

数了一下，除开介绍那篇有 6 篇，加入开往的其中一个要求是 10 篇原创文章

**Comment by gxres042** [comment]
由于您长时间未回应，您的申请现已被驳回。
如需重新申请，请重新阅读加入开往的要求并提起一个新的 Issue。感谢您的理解。
