### ISSUE TITLE
寻梦城

### ISSUE THREAD

**Issue by it985** [travellings-link/travellings#2377]
### 网站名称

寻梦城

### 网站网址

https://blog.study996.cn

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

博友圈二级目录里

### 内容方向

生活兼技术

### 备注

糖果补充能量，谎言侵蚀灵魂。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
怕被海外 ip 打就写 waf 啊，能不能不要直接ban掉。。。

**Comment by it985** [comment]
博客程序报错，现在再审核一下，谢谢

**Comment by gxres042** [comment]
忘了，真的不好意思><
