### ISSUE TITLE
TJY's Blog

### ISSUE THREAD

**Issue by TJY-github** [travellings-link/travellings#2380]
### 网站名称

TJY's Blog

### 网站网址

https://tjy-github.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

顶部右方的链接，第二个选项卡

### 内容方向

生活兼技术

### 备注

博客暂时建立了2天，后续将更新更多，我最近在处理一些博客的功能，我保证的哈

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by TJY-github** [comment]
当然，若审核将此申请驳回，我也不会因此而不再申请。
再次感谢Travellings项目给予博主们宣传自己博客、论坛或项目的展示机会~Thanks♪(･ω･)ﾉ

**Comment by gxres042** [comment]
孩子我想问你一个问题

你真的有好好看加入开往的要求吗...

**Comment by TJY-github** [comment]
没有仔细看呢，当然我在发这次申请后已经仔细阅读了

**Comment by gxres042** [comment]
![图片](https://github.com/travellings-link/travellings/assets/53113178/bff45409-1cb8-4492-9dc9-566fb1cba261)

**Comment by gxres042** [comment]
孩子你还是先发展一下自己的网站吧。就我个人而言，我不能确定你能否坚持在做博客这条路上走下去。
