### ISSUE TITLE
MC-Sep

### ISSUE THREAD

**Issue by mc-sep** [travellings-link/travellings#2391]
### 网站名称

Minecraft-Sep

### 网站网址

https://mc-sep.js.cool

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
？这个 Issue 是哪来的，你的网站已经在开往成员列表里了

**Comment by mc-sep** [comment]
不是，这是之前没用的（没有10篇文章自己取消的）
