### ISSUE TITLE
Henry的博客

### ISSUE THREAD

**Issue by HenryMoreau** [travellings-link/travellings#2393]
### 网站名称

Henry的博客

### 网站网址

https://blog.henrywhu.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
文章略有点少了……之后要记得多写一点哦

**Comment by HenryMoreau** [comment]
感谢提醒，已做修改
