### ISSUE TITLE
Ghost_chu's Blog

### ISSUE THREAD

**Issue by Ghost-chu** [travellings-link/travellings#2395]
### 网站名称

Ghost_chu's Blog

### 网站网址

https://www.ghostchu.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

PC 顶部导航栏 ，靠右侧的链接按钮第一个（主题自带）；底部 SVG 标签

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
站长您好，我是开往维护团队成员 Big_Cake。

很抱歉，您的站点样式可能存在问题，因此您的加入申请我们不予通过。

![image](https://github.com/user-attachments/assets/f7d283b3-ab89-44b2-a1b1-348e2a0aa5a4)

测试时使用的设备信息如下：

- Windows 11, build 26120.961
- Chrome Canary 128.0.6597.0

如果您已修正了以上问题，请在这个 Issue 下回复，我们会尽快复查的。

**Comment by Ghost-chu** [comment]
您好，经查样式没有问题。还请您尝试在无痕标签页中打开。

![image](https://github.com/user-attachments/assets/60299a5a-171a-4e0e-af49-212d7f9eb967)

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/user-attachments/assets/13851108-1788-4556-9223-1a03a436cca2)

这边使用 Chrome 无痕模式和访客档案均无法正常加载样式……

网络环境为山西太原电信，DNS 使用 223.5.5.5

我已将您的请求移交给组内其他成员进行处理，您可能需要多等一段时间。

**Comment by Ghost-chu** [comment]
> 站长您好，我是开往维护团队成员 Big_Cake。
> 
> 很抱歉，您的站点样式可能存在问题，因此您的加入申请我们不予通过。
> 
> ![image](https://private-user-images.githubusercontent.com/76810494/348741253-f7d283b3-ab89-44b2-a1b1-348e2a0aa5a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTQ2MTUsIm5iZiI6MTcyMTA1NDMxNSwicGF0aCI6Ii83NjgxMDQ5NC8zNDg3NDEyNTMtZjdkMjgzYjMtYWI4OS00NGIyLWExYjEtMzQ4ZTJhMGFhNWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5M2MwMTcxYmZhOTQ5NGNiY2ZjZjcyNTg1ZTU4NWE2MDcxN2RkYzZjMmY5ZDgzYmQ5NGRjOGQ0MjI4MmVjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0K11VZMhd0B_BAEa1yyqeyrBQTXnqh1AxvE2xqvTwY)
> 
> 测试时使用的设备信息如下：
> 
> * Windows 11, build 26120.961
> * Chrome Canary 128.0.6597.0
> 
> 如果您已修正了以上问题，请在这个 Issue 下回复，我们会尽快复查的。

维护成员您好，您的ISP似乎正在对我站进行网络劫持。我站支持且强制使用 HTTPS 安全传输协议。但在您的截图中，您似乎正在使用 HTTP 协议。我怀疑您可能遭遇了中间人攻击（任何HTTP请求都会被强制重定向到HTTPS）。请您尝试为域名手动添加 https 前缀，强制浏览器通过 HTTPS 方式访问。排除您的ISP页面劫持。

**Comment by Big-Cake-jpg** [comment]
> 但在您的截图中，您似乎正在使用 HTTP 协议。

我是开启了强制 HTTPS 并正确使用了 HTTPS 协议的。

![image](https://github.com/user-attachments/assets/fdd443ae-6c4d-4261-90df-5372ffabe2e8)

Chrome 对于 HTTPS 连接在导航栏中正常显示的图标即为截图中所显示的。

![image](https://github.com/user-attachments/assets/93003382-b38d-46b8-abad-337ac521c7ad)

**Comment by Ghost-chu** [comment]
> ![image](https://private-user-images.githubusercontent.com/76810494/348744946-13851108-1788-4556-9223-1a03a436cca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTQ4MDcsIm5iZiI6MTcyMTA1NDUwNywicGF0aCI6Ii83NjgxMDQ5NC8zNDg3NDQ5NDYtMTM4NTExMDgtMTc4OC00NTU2LTkyMjMtMWEwM2E0MzZjY2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0NDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZTY0ZGU3NWI3YzRkZTRkMmNjNDc2ZTJjZDU2ZjI5YThhNGQyYjY5ZWI3NDQzNTE4M2VlM2QzMDQzODRmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDPnJauv7SvhuDfaPNoONuMGMCiSiQ4WAIlP1zTYL-8)
> 
> 这边使用 Chrome 无痕模式和访客档案均无法正常加载样式……
> 
> 网络环境为山西太原电信，DNS 使用 223.5.5.5
> 
> 我已将您的请求移交给组内其他成员进行处理，您可能需要多等一段时间。

您好，感谢您付出时间测试。由于近期 PCDN 恶意刷流攻击，我将部分山西、江苏、安徽的IP地址进行了屏蔽，您可能所属 IP 段被 CDN/WAF 拦截。

**Comment by gxres042** [comment]
已复查，您的申请已通过。

感谢您的耐心等候。
