### ISSUE TITLE
Lu笔记

### ISSUE THREAD

**Issue by luuu11** [travellings-link/travellings#2397]
### 网站名称

寻光记

### 网站网址

https://lu1104.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
站长您好，我是开往维护团队成员 Big_Cake。

非常遗憾的是，您的站点目前不满足我们对成员网站的要求：至少十篇原创文章或二十篇文章，建站已满两个月以上。

因此对于您的申请，我们不予审核通过，请您谅解。

若您已修正了以上问题，请在该 Issue 下回复。

**Comment by luuu11** [comment]
1

**Comment by luuu11** [comment]
> 站长您好，我是开往维护团队成员 Big_Cake。
> 
> 非常遗憾的是，您的站点目前不满足我们对成员网站的要求：至少十篇原创文章或二十篇文章，建站已满两个月以上。
> 
> 因此对于您的申请，我们不予审核通过，请您谅解。
> 
> 若您已修正了以上问题，请在该 Issue 下回复。

1

**Comment by gxres042** [comment]
严格来说，「每日资讯」与「给博客评论区添加背景」不能算是您的原创文章。因此，您的有效文章只有八篇。

因此，您的申请已被驳回。我建议您多发表一些包含自己的想法、意见等的文章。
