### ISSUE TITLE
老朝奉

### ISSUE THREAD

**Issue by abcdhjkl103** [travellings-link/travellings#2398]
### 网站名称

老朝奉

### 网站网址

https://xn--otsr53afot.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-07-16-19-04-54-188_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/23109c2a-b811-484d-877d-ce46d5759709)
