### ISSUE TITLE
tinsir888's blog

### ISSUE THREAD

**Issue by tinsir888** [travellings-link/travellings#2400]
### 网站名称

tinsir888

### 网站网址

https://tinsir888.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

右上角 接力 - 开往

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，对于新申请的 github.io 域名站点，我们会提高巡查要求。您是否同意？

**Comment by tinsir888** [comment]
> 站长您好，对于新申请的 github.io 域名站点，我们会提高巡查要求。您是否同意？

同意~
