### ISSUE TITLE
申请收录Boffee’s Blog

### ISSUE THREAD

**Issue by BugBubbles** [travellings-link/travellings#2401]
### 网站名称

Das Blog von BugBubbles

### 网站网址

https://bugbubbles.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，对于新申请的 github.io 域名站点，我们会提高巡查要求。您是否同意？

**Comment by BugBubbles** [comment]
我同意
