### ISSUE TITLE
申请变更：zd 小达's blog

### ISSUE THREAD

**Issue by zdxiaoda** [travellings-link/travellings#2402]
### 原网址

https://blog.zhangda.xyz

### 网站 ID

659

### 原 Issue 编号

#1397

### 新网站名称 (不更改名称请留空)

zd小达's blog

### 新网址（不更改网址请留空）

https://blog.xiaoda.fun

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，根据您原 Issue 填写的徽标位置，请您记得添加回页脚的开往徽标哦。
