### ISSUE TITLE
咖啡豆子coffee的小站

### ISSUE THREAD

**Issue by kfdzcoffee** [travellings-link/travellings#2407]
### 网站名称

咖啡豆子coffee的小站

### 网站网址

https://kfdzcoffee.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
半夜点进去突然播放音乐，差点给吓到...

**Comment by kfdzcoffee** [comment]
您好     我已经收到了您向我发送的邮件，会尽快回复。此件为自动答复，请勿直接回复。顺颂     时祺
