### ISSUE TITLE
诗岸梦行舟

### ISSUE THREAD

**Issue by 735690757** [travellings-link/travellings#2412]
### 网站名称

诗岸梦行舟Blog

### 网站网址

https://735690757.github.io/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [x] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，对于使用 github.io 域名的新申请站点，我们可能会在日后提高巡查要求。

您是否同意？

**Comment by 735690757** [comment]
好的，没问题
