### ISSUE TITLE
Nibbles Blog

### ISSUE THREAD

**Issue by NibblesProject** [travellings-link/travellings#2414]
### 网站名称

Nibbles Blog

### 网站网址

https://nibbles.cn/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-07-23-16-30-56-067_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/2f638fb2-6817-4325-bb78-d9504cadddeb)

《就差一点》

**Comment by NibblesProject** [comment]
你好，我已经发布了10篇文章了，可以再看看嘛？麻烦了
