### ISSUE TITLE
像素光影屋

### ISSUE THREAD

**Issue by iskssssss** [travellings-link/travellings#2416]
### 网站名称

像素光影屋

### 网站网址

https://www.kongsheng.top

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

🛫

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
由于您最后一次更新文章是在 2021 年，并且我无法判断您在这段时间内是否有过更新，故您的申请需要进行进一步讨论。

**Comment by iskssssss** [comment]
> 由于您最后一次更新文章是在 2021 年，并且我无法判断您在这段时间内是否有过更新，故您的申请需要进行进一步讨论。

足迹板块今年有更新过，如果算的话。
![image](https://github.com/user-attachments/assets/f3970b7d-d9ea-4129-a581-7c51a4056093)

**Comment by iskssssss** [comment]
> > > 由于您最后一次更新文章是在 2021 年，并且我无法判断您在这段时间内是否有过更新，故您的申请需要进行进一步讨论。
> > 
> > 
> > 足迹板块今年有更新过，如果算的话。
> > ![image](https://private-user-images.githubusercontent.com/53375843/351922573-f3970b7d-d9ea-4129-a581-7c51a4056093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDEwMjcsIm5iZiI6MTcyMTkwMDcyNywicGF0aCI6Ii81MzM3NTg0My8zNTE5MjI1NzMtZjM5NzBiN2QtZDllYS00MTI5LWE1ODEtN2M1MWE0MDU2MDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5NDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODU0MGExYTNkYmU0MDQ1NTE4ODI1ZWZiM2FiYmM2MTI0Y2RjMWZjNjRmZmM1Y2Y0MTU4Y2UyZmRmODA4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7YfZUkiQ-hYiy1vyicKP8sg8-jH6R6VGWiXVUsOSqnU)
> 
> 更新周期可以再加强一点（

好的👌
