### ISSUE TITLE
Invictusme's Blog

### ISSUE THREAD

**Issue by inv1ctusme** [travellings-link/travellings#2417]
### 网站名称

Invictusme's Blog

### 网站网址

https://invictusme.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-07-24-18-13-30-613_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/c10b6c60-b3d2-48b4-ba23-0fed88cbcb20)
