### ISSUE TITLE
JomBarry

### ISSUE THREAD

**Issue by JomBarry** [travellings-link/travellings#2422]
### 网站名称

JomBarry

### 网站网址

https://blog.jombarry.online/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
![image](https://github.com/user-attachments/assets/226ded68-e5d3-4591-82ca-6b1720820db2)
404

**Comment by JomBarry** [comment]
已经调整，辛苦审核一下吧
