### ISSUE TITLE
Striker's Blog

### ISSUE THREAD

**Issue by Nightingale0504** [travellings-link/travellings#2423]
### 网站名称

Striker's Blog

### 网站网址

https://hacknetvault.top

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-07-26-23-57-09-385_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/df146828-10dc-4114-b908-8478c6b543fa)

![Screenshot_2024-07-26-23-58-00-759_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/ec285411-6696-4e7b-962e-d28fbff9a14e)
