### ISSUE TITLE
[llnancy's home]

### ISSUE THREAD

**Issue by llnancy** [travellings-link/travellings#2426]
### 网站名称

llnancy 的主页

### 网站网址

https://lilu.org.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
舔狗语录太草了
