### ISSUE TITLE
JomBarry

### ISSUE THREAD

**Issue by JomBarry** [travellings-link/travellings#2428]
### 网站名称

JomBarry

### 网站网址

https://blog.jombarry.online

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

顶部菜单和右侧网站公告

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，您的站点似乎拦截了开往巡查机器人。这将会导致您的网站被判定为状态异常，从而导致开往的访客无法访问到您的网站。

请根据 https://www.travellings.cn/docs/qa.html#q-%E5%B7%A1%E6%9F%A5%E6%9C%89%E4%BB%80%E4%B9%88%E7%89%B9%E5%BE%81%E5%92%A9 的相关指示将开往巡查机器人的 user-agent 在您的 WAF 中放行。

**Comment by Big-Cake-jpg** [comment]
似乎已恢复。
![image](https://github.com/user-attachments/assets/97445538-4b44-485f-8b7c-81909b186540)
