### ISSUE TITLE
小步的客栈

### ISSUE THREAD

**Issue by abcxiaobu** [travellings-link/travellings#2435]
### 网站名称

小步的客栈

### 网站网址

https://www.xiaobu.xyz/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 备注

网址已备案,内容虽然目前较少,但会持续更新,希望能给个机会

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-08-02-18-51-10-585_com.github.android-edit.jpg](https://github.com/user-attachments/assets/c90377fa-9028-4d53-b508-5e1029759a31)

**Comment by abcxiaobu** [comment]
已经满足10篇博客啦

**Comment by gxres042** [comment]
擦汗

#2445
