### ISSUE TITLE
申请状态变更：游钓四方的博客

### ISSUE THREAD

**Issue by achuanya** [travellings-link/travellings#2437]
### 原网址

https://lhasa.icu

### 网站 ID

1032

### 原 Issue 编号

#1032

### 备注

博客一直都正常，修改状态

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
......您其实可以开一个空白模板。

**Comment by gxres042** [comment]
站长您好，巡查机器人检测到您的站点上不存在开往入口。

请您抽空将开往入口补回。

**Comment by achuanya** [comment]
> 站长您好，巡查机器人检测到您的站点上不存在开往入口。
> 
> 请您抽空将开往入口补回。

在订阅页面，做成RSS页面了
![image](https://github.com/user-attachments/assets/ffee9390-d5f7-4b9a-801e-098bc052b987)

**Comment by gxres042** [comment]
![Screenshot_2024-08-04-02-05-57-468_com.android.chrome.jpg](https://github.com/user-attachments/assets/e7ee822b-04ca-490c-bb10-1320846ceef7)

**Comment by Big-Cake-jpg** [comment]
超时关闭，您的站点将被移出开往成员列表。

如有意向重新加入，请重新提交一个 Issue。
