### ISSUE TITLE
菲兹克斯喵的blog

### ISSUE THREAD

**Issue by Physics-nya** [travellings-link/travellings#2438]
### 网站名称

菲兹克斯喵的blog

### 网站网址

https://physics-nya.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

\

### 内容方向

生活兼技术

### 备注

因为还只是一名学生，所以没有购买自己的域名，用的是GitHub Pages分配的域名。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
根据加入开往的要求，使用 `github.io` 域名的新申请网站将会提高巡查要求。请问站长您是否同意？

**Comment by Physics-nya** [comment]
同意，谢谢🙏
