### ISSUE TITLE
老朝奉

### ISSUE THREAD

**Issue by abcdhjkl103** [travellings-link/travellings#2439]
### 网站名称

老朝奉

### 网站网址

https://xn--otsr53afot.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
我个人认为你可以在今后的文章中多写写自己的见解😂
