### ISSUE TITLE
云之彼端

### ISSUE THREAD

**Issue by future382** [travellings-link/travellings#2442]
### 网站名称

云之彼端

### 网站网址

https://blog.biltune.top

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![image](https://github.com/user-attachments/assets/496f12ea-f5ca-4a48-b8e8-44d948a5767f)

您可以多放一个入口在页脚。Valaxy 框架可参考：https://github.com/YunYouJun/valaxy/blob/main/demo/yun/components/YunFooter.vue
