### ISSUE TITLE
小常の博客

### ISSUE THREAD

**Issue by kennedyniu** [travellings-link/travellings#2443]
### 网站名称

小常の博客

### 网站网址

https://cylife.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

在网站刚打开后加载时会在中间显示徽标，然后在顶部关于本人按钮点开后的页面上方就是徽标

### 内容方向

生活兼技术

### 备注

这个网站是我高中时做的，当时的域名和服务器都过期了。现在是新弄的，为了给之前高中写的博客留个纪念，之前发的一些博客什么的，图片会显示不出来。（因为图片找不到了）

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![image](https://github.com/user-attachments/assets/75c901ce-817a-40ef-98d2-d90bb00db1f5)

**Comment by kennedyniu** [comment]
ok

**Comment by gxres042** [comment]
太久了我懒得等了

不是强制项，先给你通过了，后面自行修一下
