### ISSUE TITLE
小步的博客

### ISSUE THREAD

**Issue by abcxiaobu** [travellings-link/travellings#2447]
### 网站名称

小步的博客

### 网站网址

https://www.xiaobu.xyz/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 备注

已经有10篇博客啦

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
？不是哥们，你都进成员列表了怎么还在开 Issue

![Screenshot_2024-08-07-10-05-19-525_com.android.chrome.jpg](https://github.com/user-attachments/assets/6a69283b-133f-4a5b-90d1-6bb3ce8714b1)
