### ISSUE TITLE
单项式的笔记本

### ISSUE THREAD

**Issue by BCMonomial** [travellings-link/travellings#2453]
### 网站名称

单项式的笔记本

### 网站网址

https://www.bcmonomial.xyz/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/2148adab-ec75-4e55-a4cd-ac1ca8b77b83)
从[成员列表](https://list.travellings.cn/)跳转会出现这个页面，希望站长修复一下

**Comment by BCMonomial** [comment]
咦，坏了，防盗链忘了放行了，我的问题

**Comment by BCMonomial** [comment]
> ![Image](https://github.com/user-attachments/assets/2148adab-ec75-4e55-a4cd-ac1ca8b77b83)
> 从[成员列表](https://list.travellings.cn/)跳转会出现这个页面，希望站长修复一下
> 

已经处理了，烦请再检查一下

**Comment by HowieHz** [comment]
> > ![Image](https://github.com/user-attachments/assets/2148adab-ec75-4e55-a4cd-ac1ca8b77b83)
> > 从[成员列表](https://list.travellings.cn/)跳转会出现这个页面，希望站长修复一下
> 
> 已经处理了，烦请再检查一下

感谢您的回复，以及可以正常访问了

![Image](https://github.com/user-attachments/assets/2e1a9f64-98b5-4368-a0ad-9466de4d25a2)
