### ISSUE TITLE
码农明明桑

### ISSUE THREAD

**Issue by sangmingming** [travellings-link/travellings#2455]
### 网站名称

码农明明桑

### 网站网址

https://isming.me

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-08-09-23-16-39-988_com.github.android-edit.jpg](https://github.com/user-attachments/assets/463c5c1c-0614-42c6-a729-9c72c72273c1)
