### ISSUE TITLE
云城星海

### ISSUE THREAD

**Issue by yuncheng2024** [travellings-link/travellings#2457]
### 网站名称

云城星海

### 网站网址

https://www.ccssna.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
根据第一篇文章开始算起，您的站点建立时间不足两个月、不满足加入开往的要求，因此我驳回了您的申请。

**Comment by yuncheng2024** [comment]
你好，今天是8月25日，就差一天就满两个月了，待审核老师再次看到此申请应该满两个月了。希望加入开往，谢谢
