### ISSUE TITLE
DuckXu's Site

### ISSUE THREAD

**Issue by ScDuckXu** [travellings-link/travellings#2459]
### 网站名称

DuckXu's Site

### 网站网址

https://i.duckxu.com

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

顶栏有json问题放不了外来链接，只能放页面最下面了。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-08-11-01-08-00-336_com.github.android.jpg](https://github.com/user-attachments/assets/da0cc5bc-7986-45d1-b727-58328fb18cad)

哥们可以多放一个别的位置吗

**Comment by ScDuckXu** [comment]
您好，
顶栏有了，但是必须点进去后再点击一下文字。
原主题的JSON问题，无法使顶栏跳转到外部链接，只能二段跳，望谅解

**Comment by NydiaY** [comment]
烦请加一个预期无法访问。阿里云服务器被打了。谢谢！

**Comment by ScDuckXu** [comment]
烦请加一个“预期无法访问”Lable，非常感谢。
阿里云服务器被打了。24h恢复。
