### ISSUE TITLE
Lincol29’s Blog

### ISSUE THREAD

**Issue by lincol29** [travellings-link/travellings#2468]
### 网站名称

Lincol29’s Blog

### 网站网址

https://www.lincol29.cn

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

友链界面

### 内容方向

生活兼技术

### 备注

一名 Java 转 C# 开发的码农，分享一些项目中使用的技术和知识。以及 wordpres 建站技巧

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您站的开往入口呢？

![image](https://github.com/user-attachments/assets/d3983e09-39a6-457e-8a81-a516b4b75e7b)

**Comment by lincol29** [comment]
![image](https://github.com/user-attachments/assets/a719650f-a2f9-42fb-aa9a-8b355aeb8fb5)
已更新。请知悉！

**Comment by lincol29** [comment]
> 您站的开往入口呢？
> 
> ![image](https://private-user-images.githubusercontent.com/53113178/361410338-d3983e09-39a6-457e-8a81-a516b4b75e7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTk5MDksIm5iZiI6MTcyNDcxOTYwOSwicGF0aCI6Ii81MzExMzE3OC8zNjE0MTAzMzgtZDM5ODNlMDktMzlhNi00NTdlLThhODEtYTUxNmI0Yjc1ZTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAwNDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNmMyNzQ2M2Q3NWVhZWE3MTg2MTMyZDk5YWRmOWFjODg4NTIyMjczZWEwZjU0YmM0YmEyMTk1YzBmNTczNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2U3eZCer3veNdp97I3d1wHDkOGUzlmnW9bXPt7x0rA)

已更新

**Comment by gxres042** [comment]
👌
