### ISSUE TITLE
[网站名称]三十里海河

### ISSUE THREAD

**Issue by mtongi** [travellings-link/travellings#2469]
### 网站名称

三十里海河

### 网站网址

https://ihaihe.cn/

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [x] 其它

### 更具体的徽标位置

底部链接栏

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by mtongi** [comment]
https://ihaihe.cn/link 
同时添加入友情链接页面

**Comment by gxres042** [comment]
![Screenshot_2024-08-13-19-05-26-448_com.github.android-edit.jpg](https://github.com/user-attachments/assets/61499ef1-5413-405c-9604-2066011572a5)

页脚的开往链接不能算是一个很明显的地方（手机端折叠菜单另谈），故我们在 Issue template 标记了「只此选项一般无法通过审核」。而友链页的开往链接就更谈不上明显了，这也是为什么没有这个选项给站长们选择。

**Comment by gxres042** [comment]
> 可是……站点 没有侧栏啊

顶栏没有办法添加外部链接吗？

**Comment by mtongi** [comment]
PC端已添加，但站点主题在移动端所有顶栏都会被折叠

**Comment by gxres042** [comment]
手机端折叠不受影响，只要能找得到就行。

我们或许会在后面优化一下相关规则。
