### ISSUE TITLE
Akina's blog

### ISSUE THREAD

**Issue by AkinaAcct** [travellings-link/travellings#2473]
### 网站名称

Akina's blog

### 网站网址

https://blog.nnyyaa.eu.org/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

综合、技术类博客

### 备注

顶栏在ua为pc模式时出现，侧栏在ua为移动设备时出现。

### 请确认以下事项

- [x] 我已确认以上事项

**Comment by gxres042** [comment]
根据要求，使用了 eu.org 域名的新申请站点将会提高审核要求和巡查要求。

根据目前的审核情况，您的站点不符合提高后的审核要求：不论是原创文章还是非原创，站内文章数量应有 20 篇。

**Comment by AkinaAcct** [comment]
> 根据要求，使用了 eu.org 域名的新申请站点将会提高审核要求和巡查要求。
> 
> 根据目前的审核情况，您的站点不符合提高后的审核要求：不论是原创文章还是非原创，站内文章数量应有 20 篇。

了解。
我会尽可能更新内容。
