### ISSUE TITLE
--MR_Blog

### ISSUE THREAD

**Issue by MRoldL001** [travellings-link/travellings#2479]
### 网站名称

--MR_Blog

### 网站网址

https://www.mroldl001.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-08-18-08-47-41-086_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/675ba655-3f17-443e-8c01-4cc1ec93bbe1)
