### ISSUE TITLE
洛卡日记

### ISSUE THREAD

**Issue by 2665646185** [travellings-link/travellings#2480]
### 网站名称

洛卡日记

### 网站网址

https://luoca.cn

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
可以再多写一点文章的说
