### ISSUE TITLE
青枫博客

### ISSUE THREAD

**Issue by Misakacn** [travellings-link/travellings#2481]
### 网站名称

青枫博客

### 网站网址

 https://shuaige.cc

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-08-19-12-28-46-437_com.github.android.jpg](https://github.com/user-attachments/assets/42ca84a1-eda9-4361-a8cd-b81d2c5408cf)

您的站点不符合要求，故该申请一次驳回。
