### ISSUE TITLE
smallfang's blog

### ISSUE THREAD

**Issue by smallfangqwq** [travellings-link/travellings#2484]
### 网站名称

smallfang's blog

### 网站网址

https://blog.smallfang.fun

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
哥们签个证书？过期两天了

**Comment by smallfangqwq** [comment]
谢谢提醒。。。

**Comment by smallfangqwq** [comment]
fixed

**Comment by gxres042** [comment]
请等待下一次巡查重置您的网站状态。
