### ISSUE TITLE
[希米的日志]

### ISSUE THREAD

**Issue by erecc** [travellings-link/travellings#2486]
### 网站名称

Ximi's Diary

### 网站网址

https://www.ximi.me/

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

链接放置在 RSS，站点地图，左侧边

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
这个位置属于页脚了......
而且为什么在我这边看，颜色很淡、差一点就分辨不出文字......

**Comment by erecc** [comment]
为了美观不方便其它位置添加，既然如此那撤销申请吧

**Comment by gxres042** [comment]
![1724322120843.jpg](https://github.com/user-attachments/assets/7279ce93-0851-4f29-89d3-3382f3f92194)

那确实得拒了
