### ISSUE TITLE
小七的个人页

### ISSUE THREAD

**Issue by duanqi19931210** [travellings-link/travellings#2496]
### 网站名称

小七的个人页

### 网站网址

https://xqcc.site/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
你的个人页挺好的。虽然文章数量正好到达一个最低要求，但你还有一个跑步板块，提高了内容的丰富度。

继续加油！

**Comment by gxres042** [comment]
![image](https://github.com/user-attachments/assets/5646adfd-7512-4ba4-9a2a-1181d5eab567)
![image](https://github.com/user-attachments/assets/42f86113-1e80-4263-8eb4-cb536ec181bf)


等一下，您站该不会是 Vite 脚手架搭起来的吧......
