### ISSUE TITLE
COOL

### ISSUE THREAD

**Issue by upwardme** [travellings-link/travellings#250]
## 网站名称
COOL
## 网站链接
https://www.coolku.cc
## 徽标位置
网站顶部导航
## 推荐理由
想认识更多的朋友，想拥有更广的见识。

**Comment by volfclub** [comment]
已收录

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页未使用SSL，现已将您移除，如需加入开往，可在此issue下再次按照流程申请，并@管理员快速审核。 @upwardme

**Comment by upwardme** [comment]
@jiangmiemie  已部署证书，烦请再次审核。

**Comment by jiangmiemie** [comment]
> @jiangmiemie 已部署证书，烦请再次审核。

已更新
