### ISSUE TITLE
Teror

### ISSUE THREAD

**Issue by sysfox** [travellings-link/travellings#2500]
### 网站名称

Teror的客栈

### 网站网址

https://blog.trfox.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-08-28-12-29-52-299_com.android.chrome.jpg](https://github.com/user-attachments/assets/ef3a1d39-e2c9-4314-8a21-bd3363db7e52)

你确定是顶栏吗.....?

**Comment by sysfox** [comment]
哥们咱不能拿电脑浏览器看吗？
<img width="1680" alt="Snipaste_2024-08-28_16-03-51" src="https://github.com/user-attachments/assets/00574692-4631-49f5-b5ad-95ab9a1f7360">

**Comment by gxres042** [comment]
行，但哥们知道手机端必须也得看到（不论是否在折叠菜单内）吗

不知道你是不是用的安知鱼主题，是的话那手机端绝对看不到

**Comment by sysfox** [comment]
哦？我是用的Solitude主题，我尝试修改下看能否实现

在 2024-08-28 18:33:04，"Restent Ou" ***@***.***> 写道：


行，但哥们知道手机端必须也得看到（不论是否在折叠菜单内）吗

不知道你是不是用的安知鱼主题，是的话那手机端绝对看不到

**Comment by sysfox** [comment]
> 行，但哥们知道手机端必须也得看到（不论是否在折叠菜单内）吗
> 
> 不知道你是不是用的安知鱼主题，是的话那手机端绝对看不到

已确认，在不砍掉随机跳转功能按钮情况下，手机端不放在折叠菜单内不可能实现，请问在折叠菜单内添加可行吗？

**Comment by sysfox** [comment]
如果不行的话，那我把随机跳转功能砍了
