### ISSUE TITLE
Leo2011的博客

### ISSUE THREAD

**Issue by worker2011** [travellings-link/travellings#2507]
### 网站名称

Leo2011的博客

### 网站网址

https://leo2011.eu.org/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
对于使用 `eu.org` 域名的新申请站点，我们将会提高审核要求和巡查要求。

您的站点目前已符合了提高后的审核要求。对于巡查要求的提高，您是否同意？

**Comment by worker2011** [comment]
> 对于使用 `eu.org` 域名的新申请站点，我们将会提高审核要求和巡查要求。
> 
> 您的站点目前已符合了提高后的审核要求。对于巡查要求的提高，您是否同意？

可以的，一般崩溃也就是更新站点的时候，大概时间能控制在10min以内，请管理员大大不要那么急就标异常。

另外，能不能公示一下提高后的要求，以免某些使用相同域名的人改都不知道怎么改。

**Comment by gxres042** [comment]
> 请管理员大大不要那么急就标异常。

以每日凌晨四点的巡查为准。

> 另外，能不能公示一下提高后的要求，以免某些使用相同域名的人改都不知道怎么改。

会考虑，现阶段文档。。。很乱。
