### ISSUE TITLE
开往又又访问异常，请维护团队处理

### ISSUE THREAD

**Issue by lifetech2024** [travellings-link/travellings#2512]
开往又又访问异常，请维护团队处理。
![屏幕截图 2024-08-31 173825](https://github.com/user-attachments/assets/198fd47f-3da5-4633-a269-9e1233cf388f)

**Comment by Big-Cake-jpg** [comment]
国内 CDN 被跑 PCDN 的死妈仔刷流量导致的。

已恢复 ✅
