### ISSUE TITLE
信也のブログ

### ISSUE THREAD

**Issue by senshinya** [travellings-link/travellings#2514]
### 网站名称

信也のブログ

### 网站网址

https://shinya.click

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
怎么你们都喜欢这么分🤯

**Comment by senshinya** [comment]
> 怎么你们都喜欢这么分内容板块🤯

hhh 基于 vitepress 是这样的
