### ISSUE TITLE
[it备忘录]

### ISSUE THREAD

**Issue by chenjia404** [travellings-link/travellings#2518]
### 网站名称

it备忘录

### 网站网址

https://blog.chenjia.info

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核结果：

1. 建站时间不足两个月，我们以第一篇文章的发布日期计算、不考虑此前是否有删库等现象发生；
2. 国内无法访问（Page not found）。

综上所述，您的申请被驳回。建议您在解决国内无法访问的问题并额外等待 1~2 个月再来。

> 注：国内无法访问，就算你进了列表，每日巡查给你站标记 ERROR 后也不会有人跳转过去。

**Comment by baipin** [comment]
保留建站时间不足的审核意见，“国内无法访问”的问题发现已经解决（使用cloudflare），建议两个月以后再次在本issue下comment以再次申请，多谢。

**Comment by gxres042** [comment]
由于长时间未回应，该 Issue 已关闭。
