### ISSUE TITLE
Lin-Blog

### ISSUE THREAD

**Issue by lineryyds** [travellings-link/travellings#2520]
### 网站名称

Lin-Blog

### 网站网址

https://lin-blog.xyz

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核结果：文章数量不足。

注意，十篇文章要求全部为 **原创文章**，若含有非原创文章需要至少 20 篇。

单纯的资源分享不能算是原创文章。。这种搜索引擎都能搜出一抓相同的来。 ~~建议多分享一点生活文章再来申请，被拒一次没事反正还能有第二次~~
