### ISSUE TITLE
申请变更：长江南北青

### ISSUE THREAD

**Issue by ymckc** [travellings-link/travellings#2524]
### 原网址

https://ymckc.cn

### 网站 ID

631

### 原 Issue 编号

#1332

### 新网站名称 (不更改名称请留空)

菜地 - 西伯利亚之霜

### 新网址（不更改网址请留空）

https://ymckc.su

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by BLxcwg666** [comment]
![image](https://github.com/user-attachments/assets/655f0457-1470-425d-ba77-2d8db2fe0ad6)
https://www.travellings.cn/docs/join.html #4
故拒绝
