### ISSUE TITLE
申请变更：噗派吖

### ISSUE THREAD

**Issue by Puopa** [travellings-link/travellings#2525]
### 原网址

https://pupua.top

### 网站 ID

1168

### 原 Issue 编号

2239

### 新网址（不更改网址请留空）

https://ppyia.com

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
网站CSS加载错误，烦请检查，多谢。

**Comment by Puopa** [comment]
已更正，麻烦
