### ISSUE TITLE
F-K-A - 生命不息，运动不止💪

### ISSUE THREAD

**Issue by fka923** [travellings-link/travellings#2527]
### 网站名称

F-K-A - 生命不息，运动不止💪

### 网站网址

https://fengkeao.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核结果：

1. 根据你的主题来看，顶栏开往按钮在手机端不可见，建议添加到手机端可见的侧栏；
2. 歌词不能算是原创文章，故有效文章 9 篇。

综上所述，您的站点不符合加入开往的要求，但修改后或许可以达到。故先驳回您的申请，待您整改完成后在本 Issue 重新要求审核即可。

**Comment by fka923** [comment]
修改完毕，请求重新审核

**Comment by gxres042** [comment]
您使用的是什么主题？

![Screenshot_20240909-184931.png](https://github.com/user-attachments/assets/6648cedc-0846-4baa-ab35-396de5ef6c10)

**Comment by fka923** [comment]
安知鱼主题
https://docs.anheyu.com/
https://github.com/anzhiyu-c/hexo-theme-anzhiyu

**Comment by gxres042** [comment]
> 安知鱼主题
> https://docs.anheyu.com/
> https://github.com/anzhiyu-c/hexo-theme-anzhiyu

。。安知鱼，这下不奇怪了
建议您根据官方可能有的指导将开往的延时跳转给关掉，这边先通过您的申请、除了这个之外没有什么太大的问题
