### ISSUE TITLE
[文奚.技术驿站]

### ISSUE THREAD

**Issue by LiuTnn** [travellings-link/travellings#2532]
### 网站名称

ex.文奚-技术驿站

### 网站网址

ex.https://vxcode.top

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by LiuTnn** [comment]
添加头部位置

**Comment by LiuTnn** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by baipin** [comment]
我是开网维护组的baipin。您的地址（ex.）导致系统识别错误，我已经做出修改，您不需要任何操作，多谢配合。
