### ISSUE TITLE
申请变更：ex.https://vxcode.top

### ISSUE THREAD

**Issue by LiuTnn** [travellings-link/travellings#2534]
### 原网址

1320

### 网站 ID

1321

### 原 Issue 编号

2532

### 新网站名称 (不更改名称请留空)

文奚-技术驿站

### 新网址（不更改网址请留空）

https://vxcode.top

### 备注

去除开往地址携带（ex.）

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by LiuTnn** [comment]
重新提申请

**Comment by gxres042** [comment]
请不要一会开一会关 Issue。
已手动为您修改。
