### ISSUE TITLE
[文奚.技术驿站]

### ISSUE THREAD

**Issue by LiuTnn** [travellings-link/travellings#2535]
### 网站名称

文奚.技术驿站

### 网站网址

https://vxcode.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
此网站已经收录（#2532），请不要重复提交，多谢。
