### ISSUE TITLE
[皓然小站]

### ISSUE THREAD

**Issue by HoronLee** [travellings-link/travellings#2538]
### 网站名称

皓然小站

### 网站网址

https://blog.horonlee.com

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
由于 Yun 主题的侧边栏特殊性，容我们思考一下
