### ISSUE TITLE
鹊楠的小窝

### ISSUE THREAD

**Issue by QNquenan** [travellings-link/travellings#2539]
### 网站名称

鹊楠的小窝

### 网站网址

https://blog.quenan.love

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
移动端徽标异常
![Screenshot_2024-09-10-20-54-28-420_mark via](https://github.com/user-attachments/assets/07a7f3a1-48bb-4b3d-a48c-a96aeb4a9bbf)

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/5cf24694-388c-4662-afe4-00bc435ee6c9)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
