### ISSUE TITLE
小王的大数据驿站

### ISSUE THREAD

**Issue by kpretty** [travellings-link/travellings#2542]
### 网站名称

小王的大数据驿站

### 网站网址

https://uhope.fun

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
受主题限制，您的网站在移动端看不到开往的入口。

建议您在侧边栏多添加一个开往入口。

**Comment by kpretty** [comment]
> 受主题限制，您的网站在移动端看不到开往的入口。
> 
> 建议您在侧边栏多添加一个开往入口。

移动端侧边栏已添加开网入口
