### ISSUE TITLE
申请变更：浓烟下与荒野

### ISSUE THREAD

**Issue by 17Gump** [travellings-link/travellings#2546]
### 原网址

https://www.nongyanxia.cn

### 网站 ID

332

### 原 Issue 编号

716

### 新网站名称 (不更改名称请留空)

浓烟下与荒野

### 新网址（不更改网址请留空）

https://www.nongyanxia.com

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_20240913-231550.png](https://github.com/user-attachments/assets/9cbbd2de-1a49-4fdb-ac37-e94796bffa82)

**Comment by gxres042** [comment]
眼瞎了，以为是新申请（

**Comment by HowieHz** [comment]
llink #716
