### ISSUE TITLE
Cola

### ISSUE THREAD

**Issue by Apursuit** [travellings-link/travellings#2547]
### 网站名称

Cola

### 网站网址

https://the0n3.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

导航栏

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核有点晚了不好意思（）

**Comment by Apursuit** [comment]
没关系没关系哈哈。感谢师傅😊

github-actions[bot] ***@***.***> 于 2024年9月17日周二 09:37写道：
