### ISSUE TITLE
[xyx404]

### ISSUE THREAD

**Issue by xyx404** [travellings-link/travellings#2550]
### 网站名称

xyx404's blog

### 网站网址

https://xyx404.github.io/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

手机在侧栏及底部，电脑在顶栏及底部

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
由于您的网站使用了 github.io 域名，我们会在今后的巡查中提高对您的站点状态的关注。
