### ISSUE TITLE
[网站名称]御枫林下的小站

### ISSUE THREAD

**Issue by AGEN233** [travellings-link/travellings#2551]
### 网站名称

御枫林下的小站

### 网站网址

https://agen233.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

顶部导航栏右侧

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
网站的内容没有什么问题，就是 Sotitude 顶栏那个开往按钮在 移动端 Chrome 下看不到（即使开了桌面端模式），待会有空用电脑看一下。

**Comment by AGEN233** [comment]
好的好的（
移动端页面的开往按钮目前已经修好了（（
