### ISSUE TITLE
夜空星光

### ISSUE THREAD

**Issue by xingstar520** [travellings-link/travellings#2560]
### 网站名称

star.blog

### 网站网址

https://xingstar.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核结果：

1. 建议用手机看看您的网站，能否看到开往的徽标（
2. 您的唯一开往徽标使用了 JavaScript 的 `window.open()` 方法跳转到接力页，导致用户必须得告诉浏览器是否继续跳转。

综上所述，您的申请暂时被驳回。请于 15 天内回应此 Issue 并处理上述的问题。

> 注：我不建议使用安知鱼自带的开往链接，建议在其 Nav 设置中额外放一个。以及检查一下您的网站 PWA 信息是不是您自己的（
