### ISSUE TITLE
PeterTech

### ISSUE THREAD

**Issue by Peter267** [travellings-link/travellings#2561]
### 网站名称

PeterTech

### 网站网址

https://peter267.zeabur.app

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

我已确认我使用的免费域名peter267.zeabur.app存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：
1. 多次巡查发现网站为 404 状态
2. 超过一年未更新文章
3. 人工巡查发现网站样式错误
4. 网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容

我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

Peter267-peter267.zeabur.app
2024.9.22
### 请确认以下事项

- [X] 我已确认以上事项

**Comment by mc-sep** [comment]
？？？

**Comment by mc-sep** [comment]
zeabur.app你确定过得了审？

**Comment by Peter267** [comment]
> zeabur.app你确定过得了审？
官方说了：对于处于 [Public Suffix List](https://publicsuffix.org/list/public_suffix_list.dat) 内的免费域名，站长需要提出 eTLD 免责声明后确定继续加入开往

**Comment by mc-sep** [comment]
那我也不知道了

**Comment by mc-sep** [comment]
你看我的Issue

**Comment by mc-sep** [comment]
我正好卡在中间

**Comment by Peter267** [comment]
> 我正好卡在中间 #2432

zeabur.app在[Public Suffix List](https://publicsuffix.org/list/public_suffix_list.dat)里面

**Comment by mc-sep** [comment]
我知道

**Comment by mc-sep** [comment]
我的意思是，我的域名不在里面，但是因为我审核的时候还没有生效

**Comment by mc-sep** [comment]
我看看怎么高 eTLD免责声明

**Comment by Peter267** [comment]
> 我看看怎么高 eTLD免责声明

嗯，但是我很好奇你为什么会这么快回复我

**Comment by mc-sep** [comment]
我刚好在看别人的Issues

**Comment by mc-sep** [comment]
看到你正好申请了就来冒个泡

**Comment by mc-sep** [comment]
@Peter267 明天加个友链呗（不过我好像不符合要求）

**Comment by Peter267** [comment]
> @Peter267 明天加个友链呗（不过我好像不符合要求）

请在**博客**的评论区联系我

**Comment by Luochancy** [comment]
站长您好，根据开往规则修改 **[#2433](https://github.com/travellings-link/travellings/pull/2433)**，您使用的 *.zeabur.app 需要对您使用在 Public Suffix List 进行eTLD免责声明。由于我们暂未在官网提供相应模板，故在此将声明模板提供给您

以下为声明模板，您需要修改相关信息后发布在这个 issue 下方：
我已确认我使用的免费域名 [你的域名] 存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：

1. 多次巡查发现网站为 404 状态
2. 超过一年未更新文章
3. 人工巡查发现网站样式错误
4. 网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容

我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

[您的GitHub用户名+网站域名]
[日期]

**Comment by Peter267** [comment]
我已确认我使用的免费域名peter267.zeabur.app存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：
1. 多次巡查发现网站为 404 状态
2. 超过一年未更新文章
3. 人工巡查发现网站样式错误
4. 网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容

我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

Peter267-peter267.zeabur.app
2024.9.22
