### ISSUE TITLE
[忆光博客]

### ISSUE THREAD

**Issue by eraycc** [travellings-link/travellings#2563]
### 网站名称

忆光博客

### 网站网址

https://blog.eray.cc/

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
动态标题挺有意思，但很卡就是了（
