### ISSUE TITLE
[姓王者的博客]

### ISSUE THREAD

**Issue by xingwangzhe** [travellings-link/travellings#2564]
### 网站名称

姓王者的博客

### 网站网址

https://xingwangzhe.fun

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

你别说fun域名直接买三年还真不到100：）

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_20240922-191200.png](https://github.com/user-attachments/assets/3e5e994a-755e-42cb-893a-cd43b19f5343)

你这 live2d 貌似有点挡路了...?

**Comment by xingwangzhe** [comment]
> ![Screenshot_20240922-191200.png](https://private-user-images.githubusercontent.com/53113178/369682986-3e5e994a-755e-42cb-893a-cd43b19f5343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDg0OTksIm5iZiI6MTcyNzAwODE5OSwicGF0aCI6Ii81MzExMzE3OC8zNjk2ODI5ODYtM2U1ZTk5NGEtNzU1ZS00MmNiLTg5M2EtY2Q0M2IxOWY1MzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDEyMjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYWM4YTVkNTI1OTg1OTQzZDU5NjdhMzk2NjdiNGQ1N2ZmOTlmMjU1YmU4ODIxMmZiOTY4YzE3Njc4NzNkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qt6H-1ctw8O9se1z-8TwRDBpHZkX6pixE8MBmaRm2hk)
> 
> 你这 live2d 貌似有点挡路了...?


点击床能收回，我想我得缩小一下手机端live2d的大小了：（

**Comment by xingwangzhe** [comment]
或者还是不在手机端设置live2d好了，我已经在移动端关闭了live2d

**Comment by xingwangzhe** [comment]
> ![Screenshot_20240922-191200.png](https://private-user-images.githubusercontent.com/53113178/369682986-3e5e994a-755e-42cb-893a-cd43b19f5343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzQ3NDUsIm5iZiI6MTcyOTA3NDQ0NSwicGF0aCI6Ii81MzExMzE3OC8zNjk2ODI5ODYtM2U1ZTk5NGEtNzU1ZS00MmNiLTg5M2EtY2Q0M2IxOWY1MzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEwMjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzY5NGUxYzE3YjFhM2I5ZmM0MjM4OTc5MjM5ZDFlYTRmOTY1MTM3ZDdlZTQ0ZTc1NzM4NzY2NzU3MDNlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3n_RXAnqaf39MKPc9Q0WiAzpn5tRoqyT0MzD7sHgJCE)
> 
> 你这 live2d 貌似有点挡路了...?

管理员您好，我的网站正在进行备案，会关闭一段时间
![image](https://github.com/user-attachments/assets/472f4b40-f0cb-4eac-aa77-81a81908c92d)

**Comment by xingwangzhe** [comment]
都到2025年了，我早就已经备完案了()
