### ISSUE TITLE
MeeGo&hez博客

### ISSUE THREAD

**Issue by MeeGo-0** [travellings-link/travellings#2572]
### 网站名称

MeeGo&hez

### 网站网址

https://www.xiaohez.cc/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

导航栏右上角

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的博客虽然已有十二篇文章，但貌似不是您原创，并且搜索引擎可搜出大量相同的内容。

根据开往要求，网站不得包含可在搜索引擎中搜到很多的相同的内容（即「内容农场」），因此您的申请被驳回。

如果您有任何异议，可在 15 天内在本 Issue 下提问。
