### ISSUE TITLE
帽岛 Hat's Land

### ISSUE THREAD

**Issue by Alice39s** [travellings-link/travellings#2574]
### 网站名称

帽岛 Hat's Land

### 网站网址

https://www.hats-land.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
~~好神奇的主题~~

啊不，是这默认主题改的很不错
