### ISSUE TITLE
[静水深流]

### ISSUE THREAD

**Issue by 2010HCY** [travellings-link/travellings#2575]
### 网站名称

2010HCY

### 网站网址

https://2010hcy.us.kg

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

在右上角的开往下个博客

### 内容方向

生活兼技术

### 备注

博客目前仍在持续更新

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
站长您好，根据开往规则修改 #2433，您使用的 *.us.kg 需要对您使用在 Public Suffix List 的免费二级域名进行 eTLD 免责声明。

以下为声明模板，您需要修改相关信息后发布在本 Issue 下方。

我已确认我使用的免费域名 [你的域名] 存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：

- 多次巡查发现网站为 404 状态；
- 超过一年未更新文章；
- 人工巡查发现网站样式错误；
- 网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容。

我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

[您的GitHub用户名+网站域名]
[日期]

**Comment by 2010HCY** [comment]
审核好快啊

**Comment by 2010HCY** [comment]
我已确认我使用的免费域名 [https://2010hcy.us.kg] 存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：

多次巡查发现网站为 404 状态；
超过一年未更新文章；
人工巡查发现网站样式错误；
网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容。

**Comment by gxres042** [comment]
>我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。
>
>[您的GitHub用户名+网站域名]
>[日期]

**Comment by 2010HCY** [comment]
我已确认我使用的免费域名 [https://2010hcy.us.kg] 存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：

多次巡查发现网站为 404 状态；
超过一年未更新文章；
人工巡查发现网站样式错误；
网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容。
我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

[2010HCY-https://2010hcy.us.kg]
[2024.9.26]

**Comment by gxres042** [comment]
站长您好，在这里特地通知您：

1. 复审您的站点发现有「内容农场」现象（「水果忍者」一夜消失）以及维护组认为不适宜的内容（您后来发布的两篇骂人小妙招）；
2. 您似乎使用电子邮件对我们的成员进行了骚扰。

并且我进行了统计，您于 10 月 2 日起在开往群内多次违反了我们的群规、并对他人的聊天体验造成了影响，这其中包括您在群聊内分发梯子链接。

综上所述，加上您已主动移除开往链接，我们已将您的网站从开往列表中移除。

---

以下是我的个人观点，与开往及其维护组没有任何关系。

如果您认为「更改群昵称跳脸他人」、「无意义刷屏」、「分发梯子链接」等行为被禁言就成为您仇恨我们的理由，那么您更应该好好接受完九年义务教育和之后的高中、大学教育，好好了解什么场合什么话该说什么话不该说。

开往一直欢迎并尊重各年龄段的站长，但这不应该成为影响他人聊天体验甚至违反群规的「挡箭牌」。

如果您之后再有任何骚扰开往现有成员 / 创建垃圾议题（Issue）的行为，我会考虑进行拉黑处理。

Sincerely.
