### ISSUE TITLE
SeanDictionary | 折腾日记

### ISSUE THREAD

**Issue by SeanDictionary** [travellings-link/travellings#2576]
### 网站名称

SeanDictionary | 折腾日记

### 网站网址

https://seandictionary.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
很高兴您已经拿下了人生第一个博客

但是加入开往需要建站两个月以上，多等等一个月再来申请吧~
