### ISSUE TITLE
西巴博客

### ISSUE THREAD

**Issue by hhhhhhos** [travellings-link/travellings#2583]
### 网站名称

西巴博客

### 网站网址

https://yjzblog.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
手机端找不到开往的链接。

**Comment by hhhhhhos** [comment]
你好 已添加

**Comment by HowieHz** [comment]
自动重定向至 https://www.yjztest.top/xiba-newblog/home
修改链接
