### ISSUE TITLE
衍锦[yanjin.me]

### ISSUE THREAD

**Issue by fyanjin** [travellings-link/travellings#2584]
### 网站名称

衍锦[yanjin.me]

### 网站网址

https://www.yanjin.me

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_2024-09-29-23-53-52-946_com.android.chrome.jpg](https://github.com/user-attachments/assets/5f9b7525-79fb-4e39-b459-655400dabd17)

网站响应时间过长，申请暂不处理。

**Comment by fyanjin** [comment]
刚才正在更换服务器，没想到提交审核会这么快，现在已经迁移完毕，网站已经可以正常访问，申请重新审核。

**Comment by gxres042** [comment]
刚睡醒（
