### ISSUE TITLE
Pak

### ISSUE THREAD

**Issue by Yixuan-Wang** [travellings-link/travellings#2585]
### 网站名称

Pak

### 网站网址

https://blog.yixuan-wang.site

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

https://blog.yixuan-wang.site/friends 和 https://blog.yixuan-wang.site 的 Friends 列表首位

### 内容方向

生活兼技术

### 备注

![图片](https://github.com/user-attachments/assets/12e4e1b4-ef92-4c67-ad17-81f3eebf5d90)

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/dff13480-06ef-448d-b625-3d79be095b8a)
无开往外链

**Comment by HowieHz** [comment]
> 开往服务在北美访问返回 403 Forbidden，无法正常使用，已通过后台提交退出申请

感谢您的回复。开往外链跳转服务地址为
https://www.travellings.cn/go.html
https://www.travellings.cn/plain.html
https://www.travellings.cn/coder-1024.html
https://www.travellings.cn/go-by-clouds.html
暂未检测出不可用的情况

主站地址为
https://www.travellings.cn    [\[IA\]](https://web.archive.org/web/20250225085348/https://www.travellings.cn/)
也暂未检测出不可用的情况

根据您的要求，我们将删除您的开往成员信息，欢迎随时重新提出申请，感谢您对开往的支持。祝您生活愉快！
