### ISSUE TITLE
申请变更：茗辰原 の 异世界

### ISSUE THREAD

**Issue by rumian0** [travellings-link/travellings#2590]
### 原网址

https://mcy.cloudns.org

### 网站 ID

1023

### 原 Issue 编号

#1914

### 新网址（不更改网址请留空）

https://h.liyy.us.kg/

### 备注

你好麻烦更改下域名

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
link #2899
