### ISSUE TITLE
申请变更：茗辰原 の 异世界

### ISSUE THREAD

**Issue by rumian0** [travellings-link/travellings#2591]
### 原网址

https://mcy.cloudns.org

### 网站 ID

1023

### 原 Issue 编号

#1914

### 新网址（不更改网址请留空）

https://h.liyy.us.kg/

### 备注

我已确认我使用的免费域名 [[你的域名](https://h.liyy.us.kg/)] 存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：
多次巡查发现网站为 404 状态
超过一年未更新文章
人工巡查发现网站样式错误
网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容
我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

[rrumian0+https://h.liyy.us.kg/]
[2024/10/03]

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
link #2899
