### ISSUE TITLE
爱吾线报

### ISSUE THREAD

**Issue by bellafay** [travellings-link/travellings#2593]
### 网站名称

爱吾线报

### 网站网址

https://25xianbao.com

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的网站存在内容农场现象，即搜索引擎可搜到很多相同的内容。故您的申请被驳回。

**Comment by bellafay** [comment]
绝对没有啊 有也是别人抄我的  你可以看看发布时间

**Comment by gxres042** [comment]
我们其实不注重谁抄谁，这涉及到「抄袭」而不是「内容农场」

所以你会发现开往的成员列表里很少有这样的网站，因为分享白嫖资源这种过个几天就泛滥了......
