### ISSUE TITLE
Admibrill的小站

### ISSUE THREAD

**Issue by admibrill** [travellings-link/travellings#2594]
### 网站名称

Admibrill

### 网站网址

https://blog.qyadbr.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
审核结果：

- 博客建站时长未达两个月；
- 博客文章数量不足 10 篇（原创）。

故您的申请被驳回。过一段时间再来吧~
