### ISSUE TITLE
小熊奶糖's Blog

### ISSUE THREAD

**Issue by ShenHai152** [travellings-link/travellings#2596]
### 网站名称

小熊奶糖's Blog

### 网站网址

https://www.bearcandy.top/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Big-Cake-jpg** [comment]
![image](https://github.com/user-attachments/assets/2be5e743-e701-4f3b-819d-346673770b8c)

**Comment by gxres042** [comment]
您已长时间未回复，本 Issue 现已关闭。
