### ISSUE TITLE
申请变更：Zeruns's Blog

### ISSUE THREAD

**Issue by zeruns** [travellings-link/travellings#2598]
### 原网址

https://blog.zeruns.tech

### 网站 ID

896

### 原 Issue 编号

#26

### 备注

网站正常，为什么显示error

![image](https://github.com/user-attachments/assets/c367dda0-d6d8-49ad-8038-0dc077938189)

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您可以将光标放在叉叉上看到原因。
貌似是机器人巡查时遇到了 SSL 问题。

**Comment by zeruns** [comment]
> 您可以将光标放在叉叉上看到原因。 貌似是机器人巡查时遇到了 SSL 问题。

直接访问是正常的

**Comment by gxres042** [comment]
直接访问当然是正常的呀。。巡查机器人用的是 Axios
我今晚有空看一下吧

**Comment by gxres042** [comment]
您的问题已解决。
