### ISSUE TITLE
申请变更：LIFE - 优生活

### ISSUE THREAD

**Issue by aayorishy** [travellings-link/travellings#2602]
### 原网址

https://ulife.ink

### 网站 ID

711

### 原 Issue 编号

#1706

### 新网站名称 (不更改名称请留空)

ayorishy

### 新网址（不更改网址请留空）

https://ashy.me

### 备注

由于更换国内服务器以及域名，目前也正在备案。所以近半个月可能无法正常访问.

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
若您的网站备案完成，请在下面留言。

**Comment by aayorishy** [comment]
已完成
