### ISSUE TITLE
九陌斋博客

### ISSUE THREAD

**Issue by MinChess** [travellings-link/travellings#2605]
### 网站名称

九陌斋博客

### 网站网址

https://blog.jiumoz.top

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
未发现开往图标，敬请检查，多谢。

**Comment by MinChess** [comment]
已在底部菜单添加入口，辛苦处理一下！

**Comment by gxres042** [comment]
大概、或许会在今天晚上给您答复。
