### ISSUE TITLE
翰林的小站

### ISSUE THREAD

**Issue by abc1763613206** [travellings-link/travellings#2606]
### 网站名称

翰林的小站

### 网站网址

https://blog.hanlin.press

### 徽标位置

- [ ] 顶栏
- [x] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

友链页 https://blog.hanlin.press/friends/

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![image](https://github.com/user-attachments/assets/66b9deb5-0880-410e-bf76-377b0d5174a9)

emmm 能不能放在您的主页的页脚
这样子就符合规定了，规定要求将开往链接放在打开您的网站就能看到的地方

**Comment by abc1763613206** [comment]
oops 我才发现写错链接了，按照 https://blog.hanlin.press 裁定吧（

**Comment by gxres042** [comment]
![image](https://github.com/user-attachments/assets/54de7289-0dea-44fc-bf4e-f44ca95d3e71)

这是您的博客打开后的界面，只需要将开往链接放在这个页面下可见的地方即可。

Stellar 的页脚很下所以一般不过审（）

**Comment by abc1763613206** [comment]
![image](https://github.com/user-attachments/assets/8575a3c9-0d3e-41f7-8b3c-6ad4c50ee66c)
在主页与*功能页*侧边栏加了个看上去比较显眼的按钮   
对比了下发现文章页和目录打架比较影响观感，没加

**Comment by gxres042** [comment]
![image](https://github.com/user-attachments/assets/c1bd3d99-2096-4b17-8240-8042951a5e1e)

下面这排如果可以自定义的话，考虑放一个🚆上去？这样或许不会影响观感emm

申请先放行了

**Comment by abc1763613206** [comment]
> ![image](https://private-user-images.githubusercontent.com/53113178/375767949-c1bd3d99-2096-4b17-8240-8042951a5e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTMxMjQsIm5iZiI6MTcyODY1MjgyNCwicGF0aCI6Ii81MzExMzE3OC8zNzU3Njc5NDktYzFiZDNkOTktMjA5Ni00YjE3LTgyNDAtODA0Mjk1MWE1ZTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEzMjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Y2I3ZTlkMWVhMmQ0NmFjMGYyOTAzZmU3MmRhMDIyODU2Zjg3ODlmYzZkOTI2ZTgwNTMwMmNkZjg1OWFiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XQ5QOflwRI8cD7kDpvXk01Gc78O55idQh6-bjfToRxQ)
> 
> 下面这排如果可以自定义的话，考虑放一个🚆上去？这样或许不会影响观感emm
> 
> 申请先放行了

我确实实验过，然后发现 [train-subway](https://registry.npmmirror.com/@fortawesome/fontawesome-free/6.6.0/files/svgs/solid/train-subway.svg) 与同系列图标不一样大，调不动

**Comment by gxres042** [comment]
> 我确实实验过，然后发现 [train-subway](https://registry.npmmirror.com/@fortawesome/fontawesome-free/6.6.0/files/svgs/solid/train-subway.svg) 与同系列图标不一样大，调不动

太恐怖了，插个 SVG（？

**Comment by abc1763613206** [comment]
我的 stellar 深度微调过，等我找到合适的解决/替换方案可能会替换成类似这样的方案？
![image](https://github.com/user-attachments/assets/888e324a-83ef-4e0e-b502-1bb69b9d6200)

**Comment by gxres042** [comment]
> 我的 stellar 深度微调过，等我找到合适的解决/替换方案可能会替换成类似这样的方案？

可以的
