### ISSUE TITLE
Ziyang-bai的个人主页

### ISSUE THREAD

**Issue by Ziyang-Bai** [travellings-link/travellings#2609]
### 网站名称

Ziyang-bai的个人主页

### 网站网址

https://ziyang-bai.github.io/

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

中央“友情链接”处的“Traveling!”

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
有一点难定标准，说内容丰富吧好像也不是特别丰富......

**Comment by Luochancy** [comment]
请问一下能提供一个贵站文章链接吗或者您对本站的定义是什么？

**Comment by Ziyang-Bai** [comment]
这个网站主要是为了给老设备使用的导航网站，预计收录一下玩这些上世纪计算机的网站。至于文章是没有的，有也在ljnt.xyz里。
