### ISSUE TITLE
申请变更：PeterTech

### ISSUE THREAD

**Issue by Peter267** [travellings-link/travellings#2611]
### 原网址

https://peter267.zeabur.app

### 网站 ID

1339

### 原 Issue 编号

2561

### 备注

希望增加分类，分类为 blog hybrid
![image](https://github.com/user-attachments/assets/7bb2077e-fb92-49cd-95c5-1ac6e3925265)

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by baipin** [comment]
1.一般来说，使用第三方二级域名的网站，对内容的要求相对为高，可以丰富您的网站内容后再申请。
2.“开往”链接只能在页脚找到

**Comment by Peter267** [comment]
@baipin 
收到，感谢，意思是第三方二级域名网站不支持添加分类吗

**Comment by gxres042** [comment]
Label 可以打，但我们咕了好久来着....?
