### ISSUE TITLE
[tcmiku的档案库]

### ISSUE THREAD

**Issue by tcmiku** [travellings-link/travellings#2613]
### 网站名称

tcmiku的档案库

### 网站网址

https://tcmiku.github.io/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
使用 `github.io` 域名的新申请站点将会提高巡查要求。请问您是否同意？

**Comment by tcmiku** [comment]
同意
