### ISSUE TITLE
JxSimple:简序

### ISSUE THREAD

**Issue by LeGarry** [travellings-link/travellings#2618]
### 网站名称

JxSimple:简序

### 网站网址

https://www.jxsimple.online/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
Heo 系主题的顶栏开往按钮在手机端不可见，需要额外在侧栏或页脚添加一个。

**Comment by Allenyou1126** [comment]
您好，由于您长时间未作出回复，我们将关闭该 Issue，如您已经更正了该问题，请重新提交一个新 Issue，感谢您对开往的支持。
