### ISSUE TITLE
米露小窝

### ISSUE THREAD

**Issue by Mxmilu666** [travellings-link/travellings#2624]
### 网站名称

米露小窝

### 网站网址

https://milu.ink

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
多写点文章哦

**Comment by Mxmilu666** [comment]
> 多写点文章哦

学生党，所以没怎么写文章，会尽量抽出时间来的写的（
