### ISSUE TITLE
王一土的个人网站

### ISSUE THREAD

**Issue by Darin1123** [travellings-link/travellings#2626]
### 网站名称

王一土的个人网站

### 网站网址

https://zhejianglao.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

主页topbar的右上角和底部的footer

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
根据您的 [第一篇文章](https://zhejianglao.cn/blog/view/35) 的发布日期，您的建站时间未满 2 个月。过一段时间再来吧！

**Comment by Darin1123** [comment]
您好！

最早的一篇是2024年8月19日，请查看，谢谢！

第一篇的地址：https://zhejianglao.cn/blog/view/4



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Restent Ou ***@***.***>
发送时间: Saturday, October 19, 2024 7:46:17 PM
收件人: travellings-link/travellings ***@***.***>
抄送: Zefeng Wang ***@***.***>; Author ***@***.***>
主题: Re: [travellings-link/travellings] 王一土的个人网站 (Issue #2626)


根据您的 第一篇文章<https://zhejianglao.cn/blog/view/35> 的发布日期，您的建站时间未满 2 个月。过一段时间再来吧！

―

**Comment by Darin1123** [comment]
[最早的一篇](https://zhejianglao.cn/blog/view/2)是在2024年8月18日发布的
