### ISSUE TITLE
[November] 菰城鸥鹭的大学之道

### ISSUE THREAD

**Issue by Ivan0610** [travellings-link/travellings#2627]
### 网站名称

菰城鸥鹭的大学之道

### 网站网址

https://www.gcoulu.cn （麻烦将这一lssues放到11月再处理，服务器迁移至国内，现在正在进行ICP备案，谢谢！）

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

其它

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
现在已经是十一月了，建议什么时候能访问了自己吱一声（

**Comment by Ivan0610** [comment]
> 现在已经是十一月了，建议什么时候能访问了自己吱一声（

今天备案刚过，已经可以访问了~
