### ISSUE TITLE
LS-Shandong 的博客

### ISSUE THREAD

**Issue by LS-Shandong** [travellings-link/travellings#2628]
### 网站名称

LS-Shandong 的博客

### 网站网址

https://ls-shandong.github.io

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [x] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 备注

网站的内容主要属于技术类，有些时候会发布文艺类文章。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by LS-Shandong** [comment]
我已确认我使用的免费域名 ls-shandong.github.io 存在于 Public Suffix List 内，我已知悉开往规则中对于免费二级域名所要求的内容。已知悉开往维护组在遇到以下情况时可能会执行先撤销后通知：
多次巡查发现网站为 404 状态
超过一年未更新文章
人工巡查发现网站样式错误
网站包含黄色类、赌博类、暴力类、政治类、恐怖类等内容
我承诺我的网站不会发生以上阐述的内容，在发生已执行先撤销后通知之后，我将对此处理不会有任何异议。

LS-Shandong ls-shandong.github.io
2024-10-20

**Comment by LS-Shandong** [comment]
@Big-Cake-jpg 已声明。

**Comment by HowieHz** [comment]
站点自动重定向至 https://ls-shandong.codeberg.page/
修改链接
