### ISSUE TITLE
柒柒零笔

### ISSUE THREAD

**Issue by xheicloud** [travellings-link/travellings#2633]
### 网站名称

柒柒零笔 - 技术分享 | 共同学习 | 进步你我

### 网站网址

https://www.770b.cn/

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
您好
[贵站在我们审核后判断疑似“可在搜索引擎中搜到很多的相同的内容（即「内容农场」）”（参考[开往加入条件](https://www.travellings.cn/docs/join.html)）

您可在修改完成后重新开启此issue，无需再次提交新的issue进行审核，避免重复记录！

**Comment by xheicloud** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
