### ISSUE TITLE
[懒人导航网]

### ISSUE THREAD

**Issue by udayun** [travellings-link/travellings#2634]
### 网站名称

懒人导航网

### 网站网址

https://www.onenav.cc

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
您的网站存在内容农场现象，因此我驳回了您的申请。
