### ISSUE TITLE
申请变更：阈

### ISSUE THREAD

**Issue by WhyLIM** [travellings-link/travellings#2638]
### 原网址

https://www.limina.top

### 网站 ID

240

### 原 Issue 编号

#510

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by WhyLIM** [comment]
> 请问你想更改什么？

不知道为什么网站列表里我的网站被标记为LOST了

**Comment by gxres042** [comment]
> 不知道为什么网站列表里我的网站被标记为LOST了

![image](https://github.com/user-attachments/assets/bd5ab199-3ac4-4e49-8988-91e192873092)

您的网站使用了 CSR，因此巡查机器人请求您的网站时无法发现 Travellings 字样。

**Comment by gxres042** [comment]
原因我们大概知道了

您的网站在国内访问长时间处于加载中（广西电信家宽实测），导致我们的 brwoser 巡查直接报错；并且，Imsyy's homepage 是一个 CSR 项目，Axios 无法读取到页面实际上有什么内容，故给您的网站标记了 LOST。

**Comment by WhyLIM** [comment]
> 原因我们大概知道了
> 
> 您的网站在国内访问长时间处于加载中（广西电信家宽实测），导致我们的 brwoser 巡查直接报错；并且，Imsyy's homepage 是一个 CSR 项目，Axios 无法读取到页面实际上有什么内容，故给您的网站标记了 LOST。

了解了。关于您说的加载问题我有一点疑问，这个主页部署在杭州的服务器上，理论上应该不会出现长时间加载的问题，测速网站的测试也基本是秒加载

![}163@DVI3RSU4X%~{G8 MAW](https://github.com/user-attachments/assets/fd913835-5814-43db-8db8-93cd227eb9a1)

第二个问题我暂时没有精力解决，再次感谢您的回复。

**Comment by gxres042** [comment]
哦 TTFB 就是没问题，问题很可能出在 CSR 上。

测速网站一般测的是访客能多久得到回应。但 CSR 还要等 JavaScript 执行完才能看到你的网站到底有什么，而国内的加载时长正好超过了巡查机器人的超时设定（30s）。

**Comment by WhyLIM** [comment]
> 哦 TTFB 就是没问题，问题很可能出在 CSR 上。
> 
> 测速网站一般测的是访客能多久得到回应。但 CSR 还要等 JavaScript 执行完才能看到你的网站到底有什么，而国内的加载时长正好超过了巡查机器人的超时设定（30s）。
> 
> 建议的话就是，如果他这个项目还保留有 index.html 就在 head 那里加一个 travellings 的注释吧......

已经添加，蒙混过关（

**Comment by gxres042** [comment]
![IMG_20241101_121124_542.jpg](https://github.com/user-attachments/assets/672f1688-4d69-4a84-a723-b939a4cdd169)
