### ISSUE TITLE
Liu Zijian's Blog

### ISSUE THREAD

**Issue by changelzj** [travellings-link/travellings#2641]
### 网站名称

Liu Zijian's Blog

### 网站网址

https://blog.liuzijian.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
站长您好，您的网站中存在内容农场现象（文章存在大量完全由AI生成的内容），因此您的申请将被驳回。如有异议请comment。
