### ISSUE TITLE
一粒微尘

### ISSUE THREAD

**Issue by catxian** [travellings-link/travellings#2644]
### 网站名称

一粒微尘

### 网站网址

https://blog.667408.xyz/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 备注

先记录建站的过程，后面更新自己的生活日常

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
加入开往需要建站已满两个月。不急，慢慢来。

你顺便还可以解决下面这个东西：

![image](https://github.com/user-attachments/assets/a9e1b869-6fbb-49ef-89fc-dc0a6e8b429b)

**Comment by catxian** [comment]
好的，回头弄好这个够时间再申请
