### ISSUE TITLE
[Eamon's Blog]

### ISSUE THREAD

**Issue by THUDBT** [travellings-link/travellings#2646]
### 网站名称

Eamon

### 网站网址

https://fanyiming.life

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

首页“链接”Section下

### 内容方向

生活兼技术

### 备注

网站布局问题，不适合挂在顶栏

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
这个位置......也行吧
