### ISSUE TITLE
[网站名称]渊澄

### ISSUE THREAD

**Issue by miaoyanginfo** [travellings-link/travellings#2652]
### 网站名称

渊澄

### 网站网址

https://ycyc.win

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置
侧栏文字链接，页面底部图片链接。

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
NexT 这个主题样式的侧栏在桌面端是默认可见的吗？
