### ISSUE TITLE
[December] 蓝兮笔记

### ISSUE THREAD

**Issue by 12112138** [travellings-link/travellings#2655]
### 网站名称

蓝兮笔记

### 网站网址

http://buemo.cn/

### 徽标位置

- [ ] 顶栏
- [x] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

底部版权位置

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![Screenshot_20241031-235459_Trebuchet.png](https://github.com/user-attachments/assets/cb216274-82a3-4e26-ac8a-a767fc396057)

别是要 IPV6 才能打开吧？

并且，如果开往徽标不再在用户打开的页面视图（不滚动的情况下）里，那就是不合格。

**Comment by 12112138** [comment]
已修改
![image](https://github.com/user-attachments/assets/366203b6-bc85-4795-9b9d-e7305c3fa829)

**Comment by gxres042** [comment]
![{52201AFB-5374-4D61-841D-935D3953CDD0}](https://github.com/user-attachments/assets/8a5958d0-7406-4720-a338-c0da1d57d219)

emmmmm 怎么说呢，您的建站时长貌似只有一个月（

**Comment by 12112138** [comment]
那我等两个月以后再提交

匿名君
***@***.***








---原始邮件---
发件人: &quot;Restent ***@***.***&gt;
发送时间: 2024年11月3日(周日) 上午7:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [travellings-link/travellings] 蓝兮笔记 (Issue #2655)




 
52201AFB-5374-4D61-841D-935D3953CDD0.png (view on web)
 
emmmmm 怎么说呢，您的建站时长貌似只有一个月（
 
&mdash;

**Comment by gxres042** [comment]
可以先晾着一个月（
