### ISSUE TITLE
Riseforever's Site

### ISSUE THREAD

**Issue by LumingStudio** [travellings-link/travellings#2658]
### 网站名称

Riseforever's Site

### 网站网址

https://i.riseforever.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

本站是新站，虽然还未满足【网站更新需求】，但是保证活跃更新与用心维护。我工作的站点可见https://luming.chgskj.cn/。请通过，谢谢站长~

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![{B9A01DF8-C9C1-4111-A115-FF692983270A}](https://github.com/user-attachments/assets/c1dcc024-b38c-48cf-aa9a-95981242353b)

文章只有四篇哦？其他的周记呢？
