### ISSUE TITLE
rainsin's blog

### ISSUE THREAD

**Issue by rainsins** [travellings-link/travellings#2663]
### 网站名称

rainsin's blog

### 网站网址

https://blog.rainsin.cn

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by rainsins** [comment]
点错了，😅。
![小黑子-022](https://github.com/user-attachments/assets/8450e05b-dbbb-44eb-aad4-82ede0f2291f)

**Comment by gxres042** [comment]
你点了 Close issue，我在后台那边就没法扫到你的 Issue 并把你网站添加进成员列表了，刚刚才发现。。

下次注意（

**Comment by rainsins** [comment]
OK
