### ISSUE TITLE
站点状态异常：牛牛技术客栈

### ISSUE THREAD

**Issue by tdxs** [travellings-link/travellings#2664]
### 原网址

https://www.nnjskz.cn

### 网站 ID

822

### 原 Issue 编号

#822

### 备注

为什么我的站点是LOST？可以访问的呀

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
你要不看看你自己的网站有没有开往徽标，尤其是首页

https://www.travellings.cn/docs/qa.html#%E5%B7%A1%E6%9F%A5%E7%8A%B6%E6%80%81%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D

**Comment by gxres042** [comment]
大概知道问题在哪里了，等我们处理

**Comment by tdxs** [comment]
好的
