### ISSUE TITLE
yngcy

### ISSUE THREAD

**Issue by yngcy** [travellings-link/travellings#2665]
### 网站名称

yngcy

### 网站网址

https://blog.yngcy.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![{A3CCFE62-EAE6-4FC4-BC5B-3C6D559B132E}](https://github.com/user-attachments/assets/c0b20b86-5cfe-441e-8898-9094ab3debef)

安知鱼通病，建议自行修一下（

**Comment by yngcy** [comment]
已修

**Comment by yngcy** [comment]
> ![{A3CCFE62-EAE6-4FC4-BC5B-3C6D559B132E}](https://private-user-images.githubusercontent.com/53113178/383129210-c0b20b86-5cfe-441e-8898-9094ab3debef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTg2NDUsIm5iZiI6MTczMDgxODM0NSwicGF0aCI6Ii81MzExMzE3OC8zODMxMjkyMTAtYzBiMjBiODYtNWNmZS00NDFlLTg4OTgtOTA5NGFiM2RlYmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNWQ0NmIwNGExYTRiYTQ0YjVkYzdmMTg0YzJlZDVmZmNhZThmYmYwOTI5YWRlOGUwMzU5OTIxODUyMDRkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QT-j6F3EQmfZQ1Mub-3gLfS0bQbZ9_TYn5WnU0OCj4Y)
> 
> 安知鱼通病，建议自行修一下（

已修。
