### ISSUE TITLE
墨颜丶

### ISSUE THREAD

**Issue by JerrryWang** [travellings-link/travellings#2667]
### 网站名称

墨颜丶的小站

### 网站网址

https://wangjieyu.vip/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

顶栏右侧小火车

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
![{CE9F76B0-A46C-4DF7-8586-202E8474C6DA}](https://github.com/user-attachments/assets/a799901f-3e47-4c98-b555-2d028c74ad54)

安知鱼通病，建议修一下

以及这玩意在移动端上可能不显示，也建议自查（
