### ISSUE TITLE
报纸屋

### ISSUE THREAD

**Issue by VichainLee** [travellings-link/travellings#2668]
### 网站名称

Vichain的报纸屋

### 网站网址

https://v.bearcabbage.top

### 徽标位置

- [ ] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

顶栏下方，一看就能看见的地方

### 内容方向

生活类博客

### 请确认以下事项

- [x] 我已确认以上事项

**Comment by gxres042** [comment]
![{EA293F72-7007-40E1-B83A-E231C96EE7D8}](https://github.com/user-attachments/assets/9104d636-72c5-4ea6-a2c8-a17cc69d301b)

?
