### ISSUE TITLE
无别小站

### ISSUE THREAD

**Issue by Tiper-In-Github** [travellings-link/travellings#2677]
### 网站名称

无别小站

### 网站网址

https://wubie.quanmwl.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
emmmm 有点晚审核了。你的网站貌似只建站一个月？建议等一段时间再来申请（
