### ISSUE TITLE
报纸屋

### ISSUE THREAD

**Issue by VichainLee** [travellings-link/travellings#2679]
### 网站名称

Vichain的报纸屋

### 网站网址

https://v.bearcabbage.top

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
可能要晚点审，最近有点忙
