### ISSUE TITLE
申请变更：996 worker's ICU

### ISSUE THREAD

**Issue by Blackmesa-Canteen** [travellings-link/travellings#2683]
### 原网址

https://www.996workers.icu

### 网站 ID

287

### 原 Issue 编号

#1767

### 新网站名称 (不更改名称请留空)

996Workers.org

### 新网址（不更改网址请留空）

https://www.996workers.org

### 备注

在https://list.travellings.cn 查了下，发现状态是LOST，因为域名还是之前的icu域名而不是org域名，麻烦您检查一下看看，谢谢！

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by gxres042** [comment]
更新后解决
