### ISSUE TITLE
[阿星球广播电台]

### ISSUE THREAD

**Issue by Owaii-Chan** [travellings-link/travellings#2687]
### 网站名称

阿星球广播电台

### 网站网址

https://me.owaii.net

### 徽标位置

- [ ] 顶栏
- [X] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 更具体的徽标位置

侧边栏

### 内容方向

生活类博客

### 备注

通过吧球球了

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
尊敬的站长您好，根据开往加入规则，您的站点不符合以下标准：

> 您的网站应有 20 篇文章或 10 篇原创文章
> 您的网站应已创办两个月以上

因此，您的申请将被驳回。您可以在符合标准后再次申请。感谢您的支持。
