### ISSUE TITLE
申请变更：泯轲旧博客

### ISSUE THREAD

**Issue by minke233** [travellings-link/travellings#2698]
### 原网址

https://mknb.cc

### 网站 ID

1308

### 原 Issue 编号

#2501

### 新网站名称 (不更改名称请留空)

泯轲旧博客

### 新网址（不更改网址请留空）

https://145.net.cn

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
这里看到您 https://145.net.cn/ [网站截图](https://web.archive.org/web/20250202145351/https://145.net.cn/) 指定新博客站点为 https://kz.mk/ ，已更新信息
