### ISSUE TITLE
申请变更：梅之夏

### ISSUE THREAD

**Issue by Mcenahle** [travellings-link/travellings#2700]
### 原网址

https://blog.mcenahle.com/

### 网站 ID

1194

### 原 Issue 编号

#2280

### 新网址（不更改网址请留空）

https://blog.mcenahle.sh.cn/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Mcenahle** [comment]
麻烦问一下，我这个域名虽然在 Public Suffix List 之中，但是这个域名我是付费购买的，也需要进行 eTLD 免责声明吗？

付款记录截图：

![image](https://github.com/user-attachments/assets/51e950fd-f3de-40bb-87a5-90289fa495a3)

**Comment by Luochancy** [comment]
您好
根据我们的条款与CNNIC发布的相关信息，地区.cn类域名在中国大陆地区可以正常销售并购买

通过CNNIC的Whois系统查询到以下信息：
域名: mcenahle.sh.cn
ROID: 20241107s10********1469-cn
域名状态: clientTransferProhibited
注册者: 该域名已采取WHOIS隐私保护服务
所属注册服务机构: 腾讯云计算（北京）有限责任公司
域名服务器: *****.dnspod.net
域名服务器: *****.dnspod.net
注册时间: 2024-11-07 18:04:33
到期时间: 2025-11-07 18:04:33
DNSSEC: unsigned

请核对以上信息是否正确，如正确请回复正确并@我进行下一步审核

**Comment by Mcenahle** [comment]
@Luochancy 以上信息正确。
