### ISSUE TITLE
Finneas's 一个经济学小登的主页

### ISSUE THREAD

**Issue by FinneasY** [travellings-link/travellings#2705]
### 网站名称

ex. Finneas's

### 网站网址

https://blog.econfinny.com/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
您好，您的站点目前只有4篇文章，不符合以下标准：

> 您的网站应有 20 篇文章或 10 篇原创文章

因此，我们将驳回您的申请。您可以在达到要求后重新提交申请。感谢您的支持。
