### ISSUE TITLE
星空博客

### ISSUE THREAD

**Issue by 913117760** [travellings-link/travellings#2711]
### 网站名称

星空博客

### 网站网址

https://www.uk01.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [x] 我已确认以上事项

**Comment by 913117760** [comment]
您好，因为博客之前数据有改版数据库错误导致站点全都被删除，所以重新开始创建新的博客内容。并不存在内容农场现象。谢谢🙏

**Comment by Allenyou1126** [comment]
站长您好，您的站点中 [十分钟！免费部署一个自己的短链服务](https://www.uk01.cn/165.html) 为未标明出处的转载，原文地址为 [此页面](http://edisonz.cn/archives/short-link-deploy)，经过讨论我们认为您的站点暂不符合加入开往的要求，因此我们将驳回您的申请。

本Issue将被关闭。您可以在对站点进行整改后重新提交申请。感谢您对开往的支持。
