### ISSUE TITLE
萌萌猫的小破站

### ISSUE THREAD

**Issue by fishcpy** [travellings-link/travellings#2713]
### 网站名称

萌萌猫的小破站

### 网站网址

https://blog.mengmengmao.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by fishcpy** [comment]
目前只有bing和google可以搜到googlr还没有添加站点地图

**Comment by fishcpy** [comment]
目前只有bing和google可以搜到google还没有添加站点地图

**Comment by Allenyou1126** [comment]
您好，您的站点目前只有7篇文章，不符合以下标准：

> 您的网站应有 20 篇文章或 10 篇原创文章

因此，我们将驳回您的申请。您可以在达到要求后重新提交申请。感谢您的支持。
