### ISSUE TITLE
10590的学术垃圾桶

### ISSUE THREAD

**Issue by Yesord** [travellings-link/travellings#2714]
### 网站名称

10590的学术垃圾桶

### 网站网址

https://blog.yesord.top

### 徽标位置

- [X] 顶栏
- [X] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 备注

Share knowledge, foster innovation; Open minds, build the future.

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
站长您好，经过人工巡查，发现您站点开往外链设置情况比较特殊，
这会导致巡查机无法正确检查外链状态，也无法通过开往跳转服务导航到您的站点。
请在页面上添加一条注释，
包括以下其中之一的链接来修复这个问题
```plaintext
https://www.travellings.cn/go.html
https://www.travellings.cn/plain.html
https://www.travellings.cn/coder-1024.html
https://www.travellings.cn/go-by-clouds.html
```

**Comment by Rolenx** [comment]
收到，现已添加注释https://www.travellings.cn/go.html

<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/f0bac294-e340-46bc-9991-670b6a6ed2a0" />

**Comment by Yesord** [comment]
现已添加注释 https://www.travellings.cn/go.html

<img width="1474" alt="Image" src="https://github.com/user-attachments/assets/1e74540f-9a03-45f3-9d1b-edf9d2506cea" />

**Comment by HowieHz** [comment]
> 现已添加注释 https://www.travellings.cn/go.html
> 
> <img alt="Image" width="1474" src="https://private-user-images.githubusercontent.com/142188839/415193046-1e74540f-9a03-45f3-9d1b-edf9d2506cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwNTgzNDksIm5iZiI6MTc0MDA1ODA0OSwicGF0aCI6Ii8xNDIxODg4MzkvNDE1MTkzMDQ2LTFlNzQ1NDBmLTlhMDMtNDVmMy05ZDFiLWVkZjlkMjUwNmNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMFQxMzI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDRjZTNiODFmMDViYTY0N2EyZjU3YmJlY2Q3MzJjNjMzZWRjZDVmNmRmM2NmNWZmMjk3NmE3NTg2NmEwMjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VXHB37K3PG0zeGpdFEJkZOal44en4bpOt4Qq3QNpwLM">

收到，感谢您的回复

![Image](https://github.com/user-attachments/assets/f7baca12-54ce-4e78-be3c-360b8f3805bf)
