### ISSUE TITLE
Riseforever

### ISSUE THREAD

**Issue by LumingStudio** [travellings-link/travellings#2720]
### 网站名称

Riseforever

### 网站网址

https://i.riseforever.cn/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

先前审核通过，但未添加。

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
尊敬的站长您好，我们正在对开往API服务器进行一些迁移，预计将于12月13日完成，在此期间更新延迟是正常的，感谢您的支持。

本Issue将关闭。
