### ISSUE TITLE
小明的部落格

### ISSUE THREAD

**Issue by xiaoming-crypto** [travellings-link/travellings#2729]
### 网站名称

小明的部落格

### 网站网址

https://www.xmdblog.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
由于安知鱼主题的 bug，建议您手动修改以防止巡查时将您的站点标注为异常。

请参见[该公告](https://www.travellings.cn/blog/202405.html)
