### ISSUE TITLE
ADLAMP

### ISSUE THREAD

**Issue by 28778** [travellings-link/travellings#2733]
### 网站名称

ADLAMP

### 网站网址

https://blog.adlamp.cn

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
尊敬的站长您好，您的站点在文章页面第二页等内页缺少开往徽标，我们建议您补充相关链接，感谢您对开往的支持。

**Comment by 28778** [comment]
好的，正在解决中，我也不知道为什么开往的徽标会在文章页面消失。（请问到这里我的网站是已经是加入开往了吗）

**Comment by Allenyou1126** [comment]
您的站点已经通过审核，但是由于近期我们正在对开往服务器进行迁移，所以成员列表更新可能会有延迟。正常情况下本Issue被Bot关闭后即可在成员列表找到您的站点。
