### ISSUE TITLE
申请变更：[OnlyTL]

### ISSUE THREAD

**Issue by OnlyTL** [travellings-link/travellings#2742]
### 原网址

https://www.cbxg.icu/

### 网站 ID

306

### 原 Issue 编号

#615 

### 新网站名称 (不更改名称请留空)

OnlyTL

### 新网址（不更改网址请留空）

https://onlytl.com/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by mc-sep** [comment]
..

**Comment by OnlyTL** [comment]
> .. 标题打错了

已更新
