### ISSUE TITLE
XingJiのBlog

### ISSUE THREAD

**Issue by XingJi-love** [travellings-link/travellings#2744]
### 网站名称

XingJiのBlog

### 网站网址

https://love.xingji.fun/

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

技术类博客

### 备注

希望加入开往大家庭

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
站长您好，您博客中的部分内容有可能侵犯了 B 站课堂的版权（全文均为直接引用无版权说明的 PPT），且无原创内容，因此我们将驳回您的申请。

本 Issue 将关闭，您可以在移除相应内容后重新提交申请，感谢您对开往的支持。
