### ISSUE TITLE
[如趣]

### ISSUE THREAD

**Issue by hw2001aq** [travellings-link/travellings#2746]
### 网站名称

如趣

### 网站网址

https://blog.sofuns.com

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [X] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活类博客

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
站长您好，您的站点中 [点评丨“预制人”成热梗，谨防形成的“人机人格”](https://blog.sofuns.com/2024/12/13/writing/2024-12-13%E9%A2%84%E5%88%B6%E4%BA%BA%E2%80%9D%E6%88%90%E7%83%AD%E6%A2%97%EF%BC%8C%E8%B0%A8%E9%98%B2%E5%BD%A2%E6%88%90%E7%9A%84%E2%80%9C%E4%BA%BA%E6%9C%BA%E4%BA%BA%E6%A0%BC/) 为未标明出处的转载，原文地址为 [此页面](https://www.qlwb.com.cn/detail/25293271.html)，经过讨论我们认为您的站点暂不符合加入开往的要求，因此我们将驳回您的申请。

本Issue将被关闭。您可以在对站点进行整改后重新提交申请。感谢您对开往的支持。
