### ISSUE TITLE
申请变更：揽星

### ISSUE THREAD

**Issue by zcwiki** [travellings-link/travellings#2756]
### 原网址

https://www.lanxing.net/

### 网站 ID

869

### 原 Issue 编号

2115

### 新网站名称 (不更改名称请留空)

积跬

### 新网址（不更改网址请留空）

https://www.jikui.cn/

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by HowieHz** [comment]
link #2115

**Comment by HowieHz** [comment]
link #1771
