### ISSUE TITLE
KEKKJ BLOG

### ISSUE THREAD

**Issue by KEKKJ123** [travellings-link/travellings#2760]
### 网站名称

KEKKJ BLOG - 小世界的一瞥

### 网站网址

https://kekkj123.github.io/

### 徽标位置

- [x] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [ ] 其它

### 内容方向

生活兼技术

### 备注

感谢开往组的付出！

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Luochancy** [comment]
站长您好
根据我们的检查，您的站点不符合我们加入要求当中的“您的网站应有 20 篇文章或 10 篇原创文章”

我们根据开往规则修改 **[#2433](https://github.com/travellings-link/travellings/pull/2433)**，您使用的 *.github.io 需要对您使用在 Public Suffix List 的免费二级域名进行eTLD免责声明，可在下次申请时附上eTLD免责声明

您可在达到要求后再次申请开往，为了节约您与开发组的时间，可以达到要求后 ReOpen 该 Issue 进行审核。

开往维护组 负责人 洛寒兮
2024.12.28
