### ISSUE TITLE
亚斯之声

### ISSUE THREAD

**Issue by Owaii-Chan** [travellings-link/travellings#2766]
### 网站名称

亚斯之声

### 网站网址

https://we.owaii.net

### 徽标位置

- [X] 顶栏
- [ ] 侧栏
- [ ] 底部（只选此项一般无法通过审核）
- [X] 其它

### 更具体的徽标位置

顶栏的“其他”菜单

### 内容方向

生活类博客

### 备注

𝗪𝗲 𝗔𝗿𝗲 𝗛𝘂𝗺𝗮𝗻 𝗕𝗲𝗶𝗻𝗴𝘀, 𝗡𝗼𝘁 𝗛𝘂𝗺𝗮𝗻 𝗗𝗼𝗶𝗻𝗴𝘀.

### 请确认以下事项

- [X] 我已确认以上事项

**Comment by Allenyou1126** [comment]
尊敬的站长您好，您的站点创建时间未达到两个月（从第一篇文章发布起），根据以下规定我们将驳回您的申请：

> 您的网站应已创办两个月以上。我们会根据网站内第一篇文章的发布日期计算。

本 Issue 将被关闭，您可以在达到要求后重新提交申请，感谢您对开往的支持。
