### ISSUE TITLE
鲸一

### ISSUE THREAD

**Issue by AJRECHO** [travellings-link/travellings#301]
## 网站名称
鲸一—不是忙着活就是忙着死
## 网站链接
https://www.saroin.com/
## 徽标位置
左侧栏
## 推荐理由
活着就意味着必须要做点什么！

**Comment by volfclub** [comment]
已收录

**Comment by HAHH9527** [comment]
贵站证书已过期，请及时检查

**Comment by A7103** [comment]
如果处理好了可以重开此issue申请恢复 cc @HAHH9527
