### ISSUE TITLE
飞刀博客

### ISSUE THREAD

**Issue by libasten** [travellings-link/travellings#303]
## 网站名称
飞刀博客
## 网站链接
https://www.feidaoboke.com/
## 徽标位置
侧栏（⚠ 打开网页后能直接看到）
## 推荐理由
独立的个人博客

**Comment by volfclub** [comment]
建议位置靠上一些，打开网页可以直接看到

**Comment by superLicw** [comment]
已经挪到上面，打开网页第一屏就能看到的位置了，希望通过审核。

**Comment by volfclub** [comment]
已收录

**Comment by libasten** [comment]
您好，早些时候本人网站（飞刀博客，飞刀博客 - 独立的个人博客 (feidaoboke.com)&nbsp;）因为本人域名忘记续费中断了解析导致无法访问。
现在已经续费，网站已经正常访问。
请问可否加回来？
谢谢！
&nbsp;


lichengwu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月1日(星期一) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [travellings-link/travellings] 飞刀博客 (#303)





 
您好。我们开往维护组近期对成员进行了复查，您的网站已在 #1120 中被删除，删除的原因可能是：
  
您的网站打不开（无法访问、服务器出错）
 
您的网站不支持 HTTPS
 
您的网站可能存在违规内容
  
如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。
 
开往维护组 林林
 2022 年 8 月

**Comment by linlinzzo** [comment]
按照重新申请收录处理

**Comment by linlinzzo** [comment]
等会能将“友链动力”改成“开往”吗？

**Comment by linlinzzo** [comment]
已添加，等待合并。

**Comment by libasten** [comment]
> 等会能将“友链动力”改成“开往”吗？

已经更新。
