### ISSUE TITLE
UTOPIA

### ISSUE THREAD

**Issue by ukityh** [travellings-link/travellings#332]
## 网站名称

UTOPIA

## 网站链接

https://ishya.top/

## 徽标位置

头部

## 推荐理由

分享我的学习笔记、见闻和作品

**Comment by volfclub** [comment]
已收录

**Comment by xuanzhi33** [comment]
您好，您的网站直接输入域名访问是正常的，但是从开往跳转提示403
从github等其他网站跳转也提示403
怀疑是全站都开了防盗链 有referrer就ban
建议将防盗链规则仅用于资源文件

**Comment by Luochancy** [comment]
您好，目前根据巡查系统的再次检查，您的网站已经可以正常的被我们巡查到。故我们撤销相关标签！
