### ISSUE TITLE
优速VPSUR测评

### ISSUE THREAD

**Issue by Bruceau** [travellings-link/travellings#338]

**Comment by volfclub** [comment]
已收录

**Comment by Bruceau** [comment]
非常感谢呀

**Comment by linlinzzo** [comment]
未能看见开往链接。

**Comment by linlinzzo** [comment]
@HAHH9527 待办：删除该网站。

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月
