### ISSUE TITLE
幼稚园园长

### ISSUE THREAD

**Issue by yzyyz1387** [travellings-link/travellings#361]
## 网站名称
幼稚园园长

## 网站链接
https://yzyyz.top

## 徽标位置
主导航&侧栏

## 推荐理由
坚持写博文的独立博主，分享生活、各种实用文章

**Comment by volfclub** [comment]
抱歉，没有找到链接

**Comment by yzyyz1387** [comment]
这也太晚了吧阿这，我现在加



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2021年2月13日(周六) 下午4:33
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "幼稚园园长"<1796031384@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [volfclub/travellings] 幼稚园园长 (#361)




 
抱歉，没有找到链接

**Comment by yzyyz1387** [comment]
已经重新添加接力链接



---原始邮件---
发件人: "逊狼"<notifications@github.com&gt;
发送时间: 2021年2月13日(周六) 下午4:33
收件人: "volfclub/travellings"<travellings@noreply.github.com&gt;;
抄送: "幼稚园园长"<1796031384@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [volfclub/travellings] 幼稚园园长 (#361)




 
抱歉，没有找到链接

**Comment by volfclub** [comment]
已收录

**Comment by MYXXTS** [comment]
您的网站在巡查时未按照标准放置开往链接，请及时修改

**Comment by yzyyz1387** [comment]
> 您的网站在巡查时未按照标准放置开往链接，请及时修改

已经做出相应调整
