### ISSUE TITLE
Stalo's Note

### ISSUE THREAD

**Issue by stalomeow** [travellings-link/travellings#483]
## 网站名称
Stalo's Note

## 网站链接
https://note.stalomeow.com/

## 徽标位置
顶栏

## 推荐理由
分享各种知识

**Comment by volfclub** [comment]
已收录

**Comment by gxres042** [comment]
站长您好，您的 jin-yuhan.github.io 站点已失效。

请问您是否需要更新您的网站信息？

* 由于您提交申请的站点已失效，15 天内未应答将会把该站点从开往列表中移除。感谢您的理解~

**Comment by stalomeow** [comment]
链接更新为 https://note.stalomeow.com/，名称更新为 Stalo's Note
