### ISSUE TITLE
Yamdr申请收录

### ISSUE THREAD

**Issue by Yamdr** [travellings-link/travellings#5]

**Comment by volfclub** [comment]
已收录，
推荐在顶部导航加入 Travelling 外链

**Comment by qystudio0** [comment]
请更换开往链接

**Comment by Yamdr** [comment]
已更换，辛苦管理员重新审核重定向一下

**Comment by Yamdr** [comment]
> 请更换开往链接

已更换，辛苦管理员重新审核审核一下

**Comment by qystudio0** [comment]
感谢

**Comment by linlinzzo** [comment]
开往徽标首屏未显示。

**Comment by essesoul** [comment]
![image](https://user-images.githubusercontent.com/58624474/179385133-4a2b6849-1c3f-437f-9d89-4bceb4f174a3.png)
链接还是有问题，请改为https://travellings.link

**Comment by Yamdr** [comment]
好的，会尽快



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月17日(周日) 中午1:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [travellings-link/travellings] Yamdr申请收录 (#5)




 

 链接还是有问题，请改为https://travellings.link

**Comment by Yamdr** [comment]
抱歉&nbsp; 最近工作事情较多，已调整更换为新链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月2日(周二) 中午12:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [travellings-link/travellings] Yamdr申请收录 (#5)




 
距离上次等待您的回复，已经过去15天，团队将关闭您的本次请求，如您后续希望继续申请，可以重新提交 Issue 再次申请。感谢您对 开往-友链接力 的支持！

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
