### ISSUE TITLE
K'Blog

### ISSUE THREAD

**Issue by AmazingK64** [travellings-link/travellings#543]
## 网站名称
K'Blog

## 网站网址
https://www.amazingk.cn/

## 徽标位置
顶栏，网页底部

## 推荐理由
作为列车的一员，很乐意参与的列车的行驶中
日常分享写的一点东西，一些技术文档

**Comment by AmazingK64** [comment]
已完成修改，请适时收入谢谢

**Comment by AmazingK64** [comment]
> 【💥重要！】 抱歉 @AmazingK64，由于不可抗力（ https://www.vercel-status.com/incidents/r758bhbklgfd ）导致 Travelling 在国内访问变得“艰难”，我们不得不放弃 Vercel 。
> 为确保后续的顺畅访问，请尽快将您网站 Travelling 指向的域名（包括图片素材），从【 https://travellings.now.sh 】更新为【 https://travellings.link 】。我们也会进行重定向处理，谢谢。
> 
> a. 如需任何帮助，请直接此回复 issue，并查看已更新的 Readme。
> b. 如已完成修改，可点击【Close issue】按钮关闭此 issue （如未收录请勿关闭）。

已完成修改，请适时收入谢谢

**Comment by volfclub** [comment]
已收录（重复）
