### ISSUE TITLE
【关于vercel被墙】vercel在国内被墙

### ISSUE THREAD

**Issue by xinjiajuan** [travellings-link/travellings#566]
https://travellings.now.sh/ 链接重定向在vercel域名，近日vercel被墙，在国内部分地区无法打开。请注意此问题。

**Comment by volfclub** [comment]
有什么好的建议吗

**Comment by ghostsf** [comment]
= = 改下啊

**Comment by ZONGQUAN-HU** [comment]
> 有什么好的建议吗

我想到的解决方案有以下几点：
1.将托管项目转移到国内服务器。
2.使用cdn加速，跳过防火墙。
3.如果域名没有备案，cdn可以使用cf。
4.vercel添加了针对国内优化的cname域名，（但个人认为以后还是有被墙的可能）详见https://www.vercel-status.com/incidents/r758bhbklgfd

**Comment by ZONGQUAN-HU** [comment]
我的博客也是部署在vercel，目前我使用cf的cdn可以在国内正常使用

**Comment by volfclub** [comment]
> = = 改下啊

其实目前是有 github page ，netlify，cloudflare page 镜像地址的。但大家都用的是vercel的地址……改的话需要大家一起改

**Comment by volfclub** [comment]
> > 有什么好的建议吗
> 
> 我想到的解决方案有以下几点：
> 1.将托管项目转移到国内服务器。
> 2.使用cdn加速，跳过防火墙。
> 3.如果域名没有备案，cdn可以使用cf。
> 4.vercel添加了针对国内优化的cname域名，（但个人认为以后还是有被墙的可能）详见https://www.vercel-status.com/incidents/r758bhbklgfd

其实我也有放在vercel的项目，域名是我自己的，访问跟正常……这个项目也有镜像，但是可能要求大家一起改域名了。

当初觉得不用续费的域名可能更好，因为哪天如果我暴毙了，项目也能继续。

前些日子我就看vercel又被滥用的趋势……看起来不幸的应验了。

**Comment by volfclub** [comment]
![Screenshot_2021-05-17-19-04-38-337_com.chrome.dev.jpg](https://user-images.githubusercontent.com/47265026/118478717-c83b8300-b742-11eb-978f-5bd15d849000.jpg)

https://www.vercel-status.com/incidents/r758bhbklgfd

**Comment by ZONGQUAN-HU** [comment]
> > > 有什么好的建议吗
> > 
> > 我想到的解决方案有以下几点：
> > 1.将托管项目转移到国内服务器。
> > 2.使用cdn加速，跳过防火墙。
> > 3.如果域名没有备案，cdn可以使用cf。
> > 4.vercel添加了针对国内优化的cname域名，（但个人认为以后还是有被墙的可能）详见https://www.vercel-status.com/incidents/r758bhbklgfd
> 
> 其实我也有放在vercel的项目，域名是我自己的，访问跟正常……这个项目也有镜像，但是可能要求大家一起改域名了。
> 
> 当初觉得不用续费的域名可能更好，因为哪天如果我暴毙了，项目也能继续。
> 
> 前些日子我就看vercel又被滥用的趋势……看起来不幸的应验了。

- 不用一起改域名的，如果你的DNS支持多线路解析，可以一个域名实现多线路解析。
- 另外，项目本身readme就是你自己的域名，其他域名都不明显，大家都是用你的域名了。
- 目前cf在国内速度还是能接受的，可以考虑，或者使用其他cdn，可以跳过防火墙

**Comment by volfclub** [comment]
> 
> 
> > > > 有什么好的建议吗
> > > 
> > > 
> > > 我想到的解决方案有以下几点：
> > > 1.将托管项目转移到国内服务器。
> > > 2.使用cdn加速，跳过防火墙。
> > > 3.如果域名没有备案，cdn可以使用cf。
> > > 4.vercel添加了针对国内优化的cname域名，（但个人认为以后还是有被墙的可能）详见https://www.vercel-status.com/incidents/r758bhbklgfd
> > 
> > 
> > 其实我也有放在vercel的项目，域名是我自己的，访问跟正常……这个项目也有镜像，但是可能要求大家一起改域名了。
> > 当初觉得不用续费的域名可能更好，因为哪天如果我暴毙了，项目也能继续。
> > 前些日子我就看vercel又被滥用的趋势……看起来不幸的应验了。
> 
>     * 不用一起改域名的，如果你的DNS支持多线路解析，可以一个域名实现多线路解析。
> 
>     * 另外，项目本身readme就是你自己的域名，其他域名都不明显，大家都是用你的域名了。
> 
>     * 目前cf在国内速度还是能接受的，可以考虑，或者使用其他cdn，可以跳过防火墙

目前的 https://travellings.now.sh 这个域名是 vercel 提供的

**Comment by ZONGQUAN-HU** [comment]
@volfclub 那残了，怎么办？

**Comment by volfclub** [comment]
> 
> 
> @volfclub 那残了，怎么办？

我在联系下vercel，看看能不能处理下dns问题，不行地话，我认为只能一起改了——可能项目也废了

**Comment by ZONGQUAN-HU** [comment]
> > @volfclub 那残了，怎么办？
> 
> 我在联系下vercel，看看能不能处理下dns问题，不行地话，我认为只能一起改了——可能项目也废了

好吧

**Comment by volfclub** [comment]
> 
> 
> 💥 抱歉 @ZONGQUAN-HU，由于不可抗力（[https://www.vercel-status.com/incidents/r758bhbklgfd）导致](https://www.vercel-status.com/incidents/r758bhbklgfd%EF%BC%89%E5%AF%BC%E8%87%B4) Travelling 在国内访问变得“艰难”，我们不得不放弃 Vercel 。
> 请尽快将您网站 Travelling 指向的域名，从【travellings.now.sh】修改为【xxxxx】，后续也会重定向于此，谢谢。
> 如需任何帮助，请回复本 issue，而非此条回复（本回复来自 bot）。

我设定了词机器人，有必要时会尽快通知大家

**Comment by thezzisu** [comment]
可以考虑使用cloudflare pages

**Comment by volfclub** [comment]
> 
> 
> 可以考虑使用cloudflare pages

https://travellings.pages.dev

**Comment by ZONGQUAN-HU** [comment]
> > 
> > 
> > 可以考虑使用cloudflare pages
> 
> https://travellings.pages.dev

![Screenshot_20210517-225257_Chrome.png](https://user-images.githubusercontent.com/36360150/118509481-a5b96200-b762-11eb-8ad4-8291c62a5b4f.png)
在没有挂梯子的情况下，转跳到github是没有用的，github在国内也不好使，还是套个cdn吧

**Comment by thezzisu** [comment]
https://vercel.com/support/articles/using-cloudflare-with-vercel vercel支持用cf代理

**Comment by volfclub** [comment]
> 
> 
> https://vercel.com/support/articles/using-cloudflare-with-vercel vercel支持用cf代理
> 
> 目前基本几个免费的jamstack部署就cf（或套cf）最稳

个人认为，更像是域名被毙了。travellings 用的是 vercel 的默认域名 now.sh 所以挂了。

嗯……事实上，我发现我旧的项目全都从now.sh变成vercel.app了（now.sh））——  https://travellings.vercel.app/，现在，我还是自己准备个域名好。

Custom Domains and Automatic URLs ending in now.sh will instead end in vercel.app.

**Comment by baipin** [comment]
大陆地区已经恢复正常访问。 @volfclub

**Comment by volfclub** [comment]
> 
> 
> 大陆地区已经恢复正常访问。 @volfclub

![图片](https://user-images.githubusercontent.com/47265026/119249607-73798b80-bbcc-11eb-927e-b5dd200dd455.png)
虽然官方是这么说的，但我测试了依旧不行

**Comment by ZONGQUAN-HU** [comment]
> > 大陆地区已经恢复正常访问。 @volfclub
> 
> ![图片](https://user-images.githubusercontent.com/47265026/119249607-73798b80-bbcc-11eb-927e-b5dd200dd455.png)
> 虽然官方是这么说的，但我测试了依旧不行

ping不好测试，可能会禁用ping，用get测试

**Comment by baipin** [comment]
> > 大陆地区已经恢复正常访问。 @volfclub
> 
> ![图片](https://user-images.githubusercontent.com/47265026/119249607-73798b80-bbcc-11eb-927e-b5dd200dd455.png)
> 虽然官方是这么说的，但我测试了依旧不行

下午又被封了

**Comment by ZONGQUAN-HU** [comment]
> > 大陆地区已经恢复正常访问。 @volfclub
> 
> ![图片](https://user-images.githubusercontent.com/47265026/119249607-73798b80-bbcc-11eb-927e-b5dd200dd455.png)
> 虽然官方是这么说的，但我测试了依旧不行

要是考虑到项目未来发展，还是换一个自己的长期域名，这样更换服务源不会再换域名了，只需要换解析。这样项目自己也可以有很大的网络选择性和自定义。

**Comment by ZONGQUAN-HU** [comment]
![image](https://user-images.githubusercontent.com/36360150/119258550-bce1cf00-bbfc-11eb-8023-2973686e472a.png)
域名还有得选，哈哈哈哈 @volfclub

**Comment by volfclub** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/36360150/119258550-bce1cf00-bbfc-11eb-8023-2973686e472a.png)
> 域名还有得选，哈哈哈哈 @volfclub

我看看买一个

**Comment by volfclub** [comment]
![IMG_20210524_223132.jpg](https://user-images.githubusercontent.com/47265026/119362954-db6cc680-bcdf-11eb-853f-ada3416b1b10.jpg)

大家好，已经没救了，我们得换新域名了🤪

**Comment by ZONGQUAN-HU** [comment]
> ![IMG_20210524_223132.jpg](https://user-images.githubusercontent.com/47265026/119362954-db6cc680-bcdf-11eb-853f-ada3416b1b10.jpg)
> 
> 大家好，已经没救了，我们得换新域名了🤪

快买域名，哈哈哈哈😁😁

**Comment by volfclub** [comment]
来看看我们的新域名，https://travellings.link ，托关于 cloudflare page

**Comment by ZONGQUAN-HU** [comment]
> 来看看我们的新域名，https://travellings.link ，托关于 cloudflare page

为啥不买cn或者其他的域名？

**Comment by volfclub** [comment]
> 
> 
> > 来看看我们的新域名，https://travellings.link ，托关于 cloudflare page
> 
> 为啥不买cn或者其他的域名？

因为便宜，即使没人愿意捐赠，我也很乐意为他续费。
以及寓意不错，从一个链接到下一个链接。

**Comment by ZONGQUAN-HU** [comment]
> > 
> > 
> > > 来看看我们的新域名，https://travellings.link ，托关于 cloudflare page
> > 
> > 为啥不买cn或者其他的域名？
> 
> 因为便宜，即使没人愿意捐赠，我也很乐意为他续费。
> 以及寓意不错，从一个链接到下一个链接。

可以吧，用这个域名推行这个项目，老哥，我域名还没审核哦，排了一个月的队了😆😆

**Comment by volfclub** [comment]
> 
> 
> > > > 来看看我们的新域名，https://travellings.link ，托关于 cloudflare page
> > > 
> > > 
> > > 为啥不买cn或者其他的域名？
> > 
> > 
> > 因为便宜，即使没人愿意捐赠，我也很乐意为他续费。
> > 以及寓意不错，从一个链接到下一个链接。
> 
> 可以吧，用这个域名推行这个项目，老哥，我域名还没审核哦，排了一个月的队了😆😆

都赖内卷，加班，还有拖延症

**Comment by ZONGQUAN-HU** [comment]
> > 
> > 
> > > > > 来看看我们的新域名，https://travellings.link ，托关于 cloudflare page
> > > > 
> > > > 
> > > > 为啥不买cn或者其他的域名？
> > > 
> > > 
> > > 因为便宜，即使没人愿意捐赠，我也很乐意为他续费。
> > > 以及寓意不错，从一个链接到下一个链接。
> > 
> > 可以吧，用这个域名推行这个项目，老哥，我域名还没审核哦，排了一个月的队了😆😆
> 
> 都赖内卷，加班，还有拖延症

换域名勤快嘛哈哈

**Comment by baipin** [comment]
> > > > > 来看看我们的新域名，https://travellings.link ，托关于 cloudflare page
> > > > 
> > > > 
> > > > 为啥不买cn或者其他的域名？
> > > 
> > > 
> > > 因为便宜，即使没人愿意捐赠，我也很乐意为他续费。
> > > 以及寓意不错，从一个链接到下一个链接。
> > 
> > 
> > 可以吧，用这个域名推行这个项目，老哥，我域名还没审核哦，排了一个月的队了😆😆
> 
> 都赖内卷，加班，还有拖延症

老哥我已经排了2个月了#522

**Comment by MBRjun** [comment]
嘶,今天网站维护 点开往提醒我更新域名
能用大陆的镜像尽量备案用大陆的
cf目前还是比较稳的,github不建议,大陆dns污染和部分地区屏蔽

**Comment by Angel0726** [comment]
> https://www.vercel-status.com/incidents/r758bhbklgfd

vecel自己*.vercel.app的域名是不是不可以套cf

**Comment by MBRjun** [comment]
> > https://www.vercel-status.com/incidents/r758bhbklgfd
> 
> vecel自己*.vercel.app的域名是不是不可以套cf

能套CDN，但是CF在中国大陆访问很慢，大陆用还不如不套

**Comment by Angel0726** [comment]
> > > https://www.vercel-status.com/incidents/r758bhbklgfd
> > 
> > 
> > vecel自己*.vercel.app的域名是不是不可以套cf
> 
> 能套CDN，但是CF在中国大陆访问很慢，大陆用还不如不套

那可以在哪里套cdn 怎么套

**Comment by raingnight** [comment]
访问 https://travellings.cn/go.html 出现请求跨域问题，导致不能正常跳转
跨域的请求如下：
https://api.travellings.cn/random

**Comment by linlinzzo** [comment]
> 访问 https://travellings.cn/go.html 出现请求跨域问题，导致不能正常跳转
> 跨域的请求如下：
> https://api.travellings.cn/random

请您尝试访问 https://www.travellings.cn/go.html

目前只设置了含有 www 的白名单，等会会尝试弄上通配符。
