### ISSUE TITLE
Zhou‘s Blog申请收录

### ISSUE THREAD

**Issue by Dreamink0** [travellings-link/travellings#61]

**Comment by volfclub** [comment]
已收录，
建议在底部再插一个徽标。

**Comment by Zhou216** [comment]
已修改。
以及请求更新一下博客名称
Zhou's Blog 现已改为 梦墨's Blog
谢谢！

**Comment by volfclub** [comment]
网址打不开了

**Comment by linlinzzo** [comment]
您好。我们开往维护组近期对成员进行了复查，您的网站已在 travellings-link/travellings#1120 中被删除，删除的原因可能是：

- 您的网站打不开（无法访问、服务器出错）
- 您的网站不支持 HTTPS
- 您的网站可能存在违规内容

如果您对这个决定存在异议，或者您的网站重新符合了收录条件想要加入开往，请及时通过社区等渠道与我们联系。

开往维护组 林林
2022 年 8 月

**Comment by Dreamink0** [comment]
您好，博客更換域名爲 dreamo.ink。

**Comment by linlinzzo** [comment]
等会更新。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Dreamink0** [comment]
已更换！
