### ISSUE TITLE
李本伟的博客

### ISSUE THREAD

**Issue by Li-Zi-stu** [travellings-link/travellings#641]
## 网站名称
李本伟的博客

## 网站网址
https://blog.libw.cc/

## 徽标位置
导航栏-顶栏（⚠ 打开网页后能直接看到）

## 推荐理由
分享游戏、科学、编程，同时和大家一起交流成长😜

**Comment by volfclub** [comment]
顺便提一句，你的H5小游戏挂了

**Comment by Li-Zi-stu** [comment]
> 顺便提一句，你的H5小游戏挂了

**Comment by Li-Zi-stu** [comment]
> 肥提一句，你的H5小游戏挂了

没啊，正常啊

**Comment by volfclub** [comment]
![图片](https://user-images.githubusercontent.com/47265026/129445921-a56ffce8-e966-4c43-b0ec-cb990faf1c05.png)
`https://fucklxlsjq-4gpnzgz047c8e967-1253889763.tcloudbaseapp.com/index.html?fucklxlsjq`

**Comment by Li-Zi-stu** [comment]
> ![图片](https://user-images.githubusercontent.com/47265026/129445921-a56ffce8-e966-4c43-b0ec-cb990faf1c05.png)
> `https://fucklxlsjq-4gpnzgz047c8e967-1253889763.tcloudbaseapp.com/index.html?fucklxlsjq`

修好了，你刷新一下，那个提示框是一个脚本加载的

**Comment by volfclub** [comment]
已收录

**Comment by linlinzzo** [comment]
没有看到开往链接
