### ISSUE TITLE
陆尧顶瓜瓜

### ISSUE THREAD

**Issue by LUKECLEVER** [travellings-link/travellings#650]
## 网站名称
陆尧顶瓜瓜

## 网站网址
https://blog.luyaoguagua.top/

## 徽标位置
顶栏（⚠ 打开网页后能直接看到）

## 推荐理由
陆尧顶瓜瓜

**Comment by volfclub** [comment]
您的网页显示挂掉了

**Comment by LUKECLEVER** [comment]
已恢复。麻烦您再审查一下。谢谢

**Comment by LUKECLEVER** [comment]
麻烦啦。

**Comment by LUKECLEVER** [comment]
![% EG(H(Y 4XFB1SUMT)E{QX](https://user-images.githubusercontent.com/60529895/129584689-b97e3c8d-b6e0-4063-9451-f3741f9f99c9.jpg)
这是电脑版的图片。Microsoft edge

**Comment by LUKECLEVER** [comment]
网站在测压，可能会有一点卡。

**Comment by LUKECLEVER** [comment]
测压详情：
![image](https://user-images.githubusercontent.com/60529895/129708938-4697dbfe-14db-4998-a241-f9fc6fe49e4e.png)

**Comment by LUKECLEVER** [comment]
![image](https://user-images.githubusercontent.com/60529895/130081837-7c450907-7628-4abf-8676-e2cbd33dcc6c.png)
可以承受每秒7次的访问。

**Comment by LUKECLEVER** [comment]
改个网址：https://blogr.luyaoguagua.top

**Comment by linlinzzo** [comment]
没有看到开往链接。
