### ISSUE TITLE
MikeC's Blog

### ISSUE THREAD

**Issue by MikeC-Cn** [travellings-link/travellings#668]
## 网站名称
MikeC's Blog

## 网站网址
[https://oiermikec.fun/](https://oiermikec.fun/)

## 徽标位置
侧栏

## 推荐理由
分享学习编程历程，热爱生活。

**Comment by volfclub** [comment]
已收录

**Comment by MikeC-Cn** [comment]
申请更改信息  
  
## 网站名称
CasparC

## 网站网址
[https://casparc.cn/](https://casparc.cn/)

## 徽标位置
底部

## 推荐理由
分享学习编程历程，热爱生活。

**Comment by essesoul** [comment]
文章有点少

**Comment by essesoul** [comment]
@MikeC-Cn 请尽快完善网站内容，否则网站将被移除
