### ISSUE TITLE
Ryan Wang 的博客申请收录

### ISSUE THREAD

**Issue by ruibaby** [travellings-link/travellings#7]
## 网站名称

Ryan Wang's Blog

## 网站链接

https://ryanc.cc

## 徽标位置

全页面的底部，以及 https://ryanc.cc/p/about

## 推荐理由

我觉得这个想法很赞，值得推广下去。

**Comment by volfclub** [comment]
已收录，
建议顶部导航插入 Travelling

**Comment by linlinzzo** [comment]
网站未发现开往徽标。

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by jiangmiemie** [comment]
@ruibaby  王老师，你开往标记是不是更新博客之后忘记加上了。
