### ISSUE TITLE
iqia

### ISSUE THREAD

**Issue by minglinxuan** [travellings-link/travellings#703]
## 网站名称:iqia
（💡 会在 Readme 中展示给大家）

## 网站网址:https://blog.iqia.top
（💡 必须是 https 网站）

## 徽标位置:页脚动图Gif 暗黑风格更明显
（💡 只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低；
核心要求是放在 PC 打开网页后能**直接看到的地方**——一般而言，顶栏或固定的侧栏是不错的选择，具体示例可参见 Readme 或已收录的网站）

## 推荐理由:个人博客 爱好交友
（💡 不会展示在 Readme）

**Comment by linlinzzo** [comment]
https://github.com/travellings-link/travellings/discussions/954 反馈未添加

**Comment by HAHH9527** [comment]
检查发现已正确添加
