### ISSUE TITLE
收录更新-煎饼果子

### ISSUE THREAD

**Issue by PancakeCN** [travellings-link/travellings#706]
## 网站名称
煎饼果子

## 网站网址
原18号网站（果子小酱  https://sublimerui.top ）
需更新为：名称：煎饼果子   地址：https://owobest.com

原19号网站（Sakura  https://cwxyr.me ）
需更新为：名称：Sakura   地址：https://blog.moej.cn

## 徽标位置
18号网站：中心
19号网站：顶栏

## 推荐理由
QAQ咱换了域名和服务器，麻烦审核大大更新一下啦~

**Comment by linlinzzo** [comment]
侧边栏在移动端收起时未在底部放置开往徽标。

**Comment by HAHH9527** [comment]
@PancakeCN 
贵站 owobest.com SSL证书失效
地址重定向至 cak.moe
是否需要修改开往地址

**Comment by PancakeCN** [comment]
需要的，域名已更改至cak.moe。感谢提醒~

**Comment by A7103** [comment]
https://github.com/travellings-link/travellings/pull/1209 已更改，关闭此issue

**Comment by A7103** [comment]
@PancakeCN  `https://blog.moej.cn` SSL证书失效，请核实

**Comment by A7103** [comment]
暂时移除网站，如有需要可重新申请

**Comment by jiangmiemie** [comment]
您的网站于2023年8月15日巡查发现首页已无法访问，现已将您移除，如需加入开往，可再次按照流程申请。
