### ISSUE TITLE
PhyllisJohnson

### ISSUE THREAD

**Issue by PJIDC** [travellings-link/travellings#744]
## 网站名称
> PhyllisJohnson

## 网站网址
> https://iguangdie.xyz

## 徽标位置
> - 网站底部、右侧栏

## 内容方向
> VPS测评、Linux教程

**Comment by linlinzzo** [comment]
让你久等了，明天处理。
另：网站名是否应该为PJIDC？

**Comment by qystudio0** [comment]
建议添加一些非盈利性内容

**Comment by linlinzzo** [comment]
网站证书出现问题
