### ISSUE TITLE
一潭星动。

### ISSUE THREAD

**Issue by jiangshanghan** [travellings-link/travellings#752]
## 网站名称
一潭星动
（江的存文处）

## 网站网址
https://jiangshanghan.art.blog/

## 徽标位置
https://jiangshanghan.art.blog/link1/
这是一个专门用于放置友情链接的页签。

## 内容方向
小说、旅行见闻、美食推荐、学习笔记、网上冲浪

**Comment by jiangshanghan** [comment]
我再顺便提一个类似的随机抽选访问博客的地方 https://theforest.link/ 
但需要注意的是这个工具并没有限制博客的语言，当然也没有限制写作的主题。
我在这随机到过一个介绍各种字体的网站，也有个人生活记录的站。

**Comment by volfclub** [comment]
您好，请参照 readme 放置链接

**Comment by jiangshanghan** [comment]
> 您好，请参照 readme 放置链接

https://jiangshanghan.art.blog/link1/ 

已放置链接

**Comment by linlinzzo** [comment]
我没能从首页看到链接。
