### ISSUE TITLE
Molink

### ISSUE THREAD

**Issue by Torther** [travellings-link/travellings#753]
## 网站名称
Molink

## 网站网址
https://mol.ink

## 徽标位置
左侧栏

## 内容方向
知识，教程，杂话，生活

**Comment by volfclub** [comment]
已收录

**Comment by volfclub** [comment]
证书有问题

**Comment by linlinzzo** [comment]
我把网址换成https://blog.mol.ink/ 试一下。

**Comment by linlinzzo** [comment]
欸？没有开往链接。。。

**Comment by Torther** [comment]
> 欸？没有开往链接。。。

不好意思，之前内容丢失了，目前是这几天刚建立的，还没有加上

**Comment by linlinzzo** [comment]
> 不好意思，之前内容丢失了，目前是这几天刚建立的，还没有加上

你加上后叫我一下。

**Comment by Torther** [comment]
> > 不好意思，之前内容丢失了，目前是这几天刚建立的，还没有加上
> 
> 你加上后叫我一下。

已添加

**Comment by linlinzzo** [comment]
等会处理。
