### ISSUE TITLE
Fix [飞刀博客] [云帆沧海]

### ISSUE THREAD

**Issue by yzqzss** [travellings-link/travellings#762]
ID:202
云帆沧海
https://yunfanch.com/
该网站SSL证书已续签，已恢复正常。

https://github.com/saveweb/doing/issues/110

**Comment by yzqzss** [comment]
ID:204
飞刀博客
已恢复正常

**Comment by linlinzzo** [comment]
没有在首页中发现“开往”。

**Comment by yzqzss** [comment]
> 没有在首页中发现“开往”。

确实没有了。

**Comment by linlinzzo** [comment]
请关闭这个issue，等待站长添加链接后再申请。

**Comment by yzqzss** [comment]
> ID:204 飞刀博客 已恢复正常

右下角的友链中的友链动力字样即为开往的链接。

**Comment by linlinzzo** [comment]
> https://www.feidaoboke.com/ 右下角的友链中的友链动力字样即为开往的链接。

已重新启动添加程序。

**Comment by linlinzzo** [comment]
https://github.com/travellings-link/travellings/pull/1034
