### ISSUE TITLE
新分享

### ISSUE THREAD

**Issue by hanhang2015** [travellings-link/travellings#765]
## 网站名称
新分享

## 网站网址
 https://www.hyh.ac.cn

## 徽标位置
顶栏

## 内容方向
网站内容主要是分享学习所得、生活感悟。

**Comment by volfclub** [comment]
抱起，没有找到

**Comment by volfclub** [comment]
抱歉，没有找到开往

**Comment by hanhang2015** [comment]
之前重新弄了一下网站，所以链接就没有加上，，，现在已经重新加上啦!

**Comment by hanhang2015** [comment]
因为重新弄了嘛，所以很多文章就没保存，，，

**Comment by linlinzzo** [comment]
你再多写一些内容再通知我们。
