### ISSUE TITLE
启小凡

### ISSUE THREAD

**Issue by qiXiaoFanTomato** [travellings-link/travellings#778]
## 网站名称
启小凡

## 网站网址
https://www.qixiaofan.icu

## 徽标位置
顶栏

## 内容方向
学习java的过程与分享

**Comment by volfclub** [comment]
网站似乎打不开了

**Comment by qiXiaoFanTomato** [comment]
> 网站似乎打不开了

需要手动输入，我这边能进入

**Comment by Jiaocz** [comment]
> > 网站似乎打不开了
> 
> 需要手动输入，我这边能进入

在首页设置防盗链会导致任何有Referer的连接跳转过去都被拦截，包括travellings.link，希望可以修改配置

**Comment by qiXiaoFanTomato** [comment]
> > > 网站似乎打不开了
> > 
> > 
> > 需要手动输入，我这边能进入
> 
> 在首页设置防盗链会导致任何有Referer的连接跳转过去都被拦截，包括 travellings.link，希望可以修改配置

解决了

**Comment by essesoul** [comment]
未找到开往图标或链接
![image](https://user-images.githubusercontent.com/58624474/179334723-96e682b8-d108-4977-b338-6e9336ed2f4f.png)
![image](https://user-images.githubusercontent.com/58624474/179334727-b5aff4e8-d77e-4ec1-85eb-d891dbe95a9c.png)
