### ISSUE TITLE
饼干博客

### ISSUE THREAD

**Issue by bnganblog** [travellings-link/travellings#781]
## 网站名称
饼干博客

## 网站网址
https://g8d.xyz

## 徽标位置
侧栏

## 内容方向
java，技术分享，后端开发，自动化框架，数据接口

**Comment by volfclub** [comment]
网站似乎打不开

**Comment by bnganblog** [comment]
域名到期了，关注我的tg：bnganblog 恢复后会告知

逊狼 ***@***.***> 于2022年4月4日周一 21:38写道：

**Comment by Jiaocz** [comment]
@bnganblog 后续恢复后来这里继续申请即可。15天后Issue会自动关闭，届时可以重新提交Issue

**Comment by bnganblog** [comment]
bngan.com 备用域名正常

github-actions[bot] ***@***.***> 于2022年4月28日周四 12:46写道：

**Comment by Jiaocz** [comment]
@bnganblog 重新提交Issue申请即可
