### ISSUE TITLE
六花丶紫

### ISSUE THREAD

**Issue by amber6hua** [travellings-link/travellings#787]
## 网站名称
六花丶紫

## 网站网址
https://ambercc.gitee.io/

## 徽标位置
顶部

## 内容方向
分享个人遇到的技术问题

> 【填写时请删除带有 💡 的提示内容行（包括这句）】

**Comment by linlinzzo** [comment]
文章才两页？再多写写？

**Comment by amber6hua** [comment]
好的

**Comment by amber6hua** [comment]
> 文章才两页？再多写写？

好的
