### ISSUE TITLE
璃墨的小站

### ISSUE THREAD

**Issue by Limour-dev** [travellings-link/travellings#796]
## 网站名称
璃墨的小站

## 网站网址
https://limour.top

## 徽标位置
网页底部

## 内容方向
好奇心旺盛驱使下的杂七杂八的探索过程

**Comment by linlinzzo** [comment]
符合条件，等会处理。

**Comment by linlinzzo** [comment]
推荐放在顶栏侧栏等打开网页就能看到的地方，便于访客看到并点击
