### ISSUE TITLE
肥猪qwq

### ISSUE THREAD

**Issue by feizhuqwq** [travellings-link/travellings#802]
## 网站名称

肥猪qwq

## 网站网址

https://www.feizhuqwq.com

## 徽标位置

固定的侧栏 (左侧)
Font Awesome图标

## 内容方向
教程，分享一些实用的工具，争取周更

**Comment by linlinzzo** [comment]
开往的链接呢？

**Comment by feizhuqwq** [comment]
抱歉，时间有点久了，网站在一次改版中去掉了链接，现已重新添加

**Comment by HAHH9527** [comment]
请再多更新一些文章，目前建议20篇以上
