### ISSUE TITLE
可能是一个问题网页？

### ISSUE THREAD

**Issue by gone1724** [travellings-link/travellings#803]
# 如题

[https://jinqimu.xyz/](https://jinqimu.xyz/)

**Comment by gone1724** [comment]
我只是无意间刷到的，[https://travellings.link/   网页 ](https://travellings.link/) 网页把我跳转到[这里](https://jinqimu.xyz/)了

_列表里有一个[https://jinqimu.github.io/](https://jinqimu.github.io/)应该是是正确的_

**Comment by linlinzzo** [comment]
能提供一下网站前面的序号吗？
