### ISSUE TITLE
For XX - 专注于技术本身

### ISSUE THREAD

**Issue by kecikeci** [travellings-link/travellings#806]
## 网站名称

For XX - 专注于技术本身

## 网站网址

https://4xx.me

## 徽标位置

底部

## 内容方向

技术博客
For XX技术博客,专注于技术本身!分享Java/Web等编程技术教程干货,Linux服务器教程,最新IT资讯等!

**Comment by linlinzzo** [comment]
推荐放在顶栏侧栏等打开网页就能看到的地方，便于访客看到并点击
