### ISSUE TITLE
冻符「Minus-K」域名更换

### ISSUE THREAD

**Issue by kawashiro-ryofu** [travellings-link/travellings#808]
## 网站名称
> 冻符「Minus-K」

## 网站网址
> ~~https://www.kawashiros.club~~ 不再使用
> [https://bkryofu.xyz/](https://bkryofu.xyz/)

## 徽标位置
> 顶部

## 内容方向
> 生活、人文、技术
> etc.

**Comment by linlinzzo** [comment]
请提供网站编号。

**Comment by kawashiro-ryofu** [comment]
> 

它当初收录的时候没有给我网站编号啊……

你是指那个js脚本里面的，存放各个网站URL的数组中本站URL的下标的值吗？是341
