### ISSUE TITLE
闲花手札

### ISSUE THREAD

**Issue by ialoe** [travellings-link/travellings#821]
## 网站名称
> - 闲花手札

## 网站网址
> - [https//:www.islu.cn](https://www.islu.cn/)

## 徽标位置
> - 网页底部

## 内容方向
> - 学习笔记，生活记录等等

**Comment by linlinzzo** [comment]
网站地址那两个杠没有加。

**Comment by ialoe** [comment]
> 



> 网站地址那两个杠没有加。

感谢提醒

**Comment by linlinzzo** [comment]
推荐放在顶栏侧栏等打开网页就能看到的地方，便于访客看到并点击
