### ISSUE TITLE
兴哥's Blog

### ISSUE THREAD

**Issue by huxinga1** [travellings-link/travellings#827]
## 网站名称
> - 兴哥's Blog

## 网站网址
> - https://blog.hux6.com

## 徽标位置
> - 左侧导航   左下角标志

## 内容方向
> - 个人生活分享，照片分享等

**Comment by linlinzzo** [comment]
文章有点少，请再更新一点试试。

**Comment by huxinga1** [comment]
已收到您的邮件，我将尽快查收，给予回复。如有急事请电话联系：17347861940

**Comment by huxinga1** [comment]
已收到您的邮件，我将尽快查收，给予回复。如有急事请电话联系：17347861940

**Comment by huxinga1** [comment]
已收到您的邮件，我将尽快查收，给予回复。如有急事请电话联系：17347861940
