### ISSUE TITLE
fly6022

### ISSUE THREAD

**Issue by fly6022** [travellings-link/travellings#829]
## 网站名称
> fly6022

## 网站网址
> https://fly6022.fun/

## 徽标位置
> 网站侧边栏（可直接看到）

## 内容方向
> 编程有关 / 游戏 / 生活

**Comment by HAHH9527** [comment]
内容较少，请再努力多更新几篇文章

**Comment by fly6022** [comment]
> 内容较少，请再努力多更新几篇文章

好的，谢谢。
