### ISSUE TITLE
FiveFire的博客

### ISSUE THREAD

**Issue by fivefirex** [travellings-link/travellings#830]
## 网站名称
> - 💡 FiveFire的博客

## 网站网址
> - 💡 https://fivefirex.github.io/

## 徽标位置
> - 💡 顶部菜单

## 内容方向
> - 💡 编程开发
> - 💡 个人随笔
> - 💡 技术杂谈

**Comment by fivefirex** [comment]
很抱歉，由于源码管理疏忽造成了不必要的麻烦。
文件已经push至github，请等待page加载成功后再次刷新查看。
由于清明节原因，网站颜色为黑白。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volfclub/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月4日(星期一) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [volfclub/travellings] FiveFire的博客 (Issue #830)





 
我没能看到“开往”链接。

**Comment by linlinzzo** [comment]
网站有点少，请再更新试一下。
