### ISSUE TITLE
站点更换域名

### ISSUE THREAD

**Issue by Langwenchong** [travellings-link/travellings#834]
申请将原5515 | 顶栏 | 雨中的博客 | `https://www.wenchong.space/`的域名
修改为|551 | 顶栏 | 雨中的博客 |`https://blog.coolchong.cn`|

**Comment by linlinzzo** [comment]
现在编号才到417，哪来551？

**Comment by Langwenchong** [comment]
> 现在编号才到417，哪来551？

抱歉抱歉，应该是339

**Comment by linlinzzo** [comment]
已修改。请关闭issue

**Comment by Langwenchong** [comment]
> 已修改。请关闭issue

谢谢你😘

**Comment by A7103** [comment]
@Langwenchong `blog.coolchong.cn` 网站无法访问

**Comment by A7103** [comment]
暂时移除网站，如有需要可重新申请

**Comment by linlinzzo** [comment]
网站无法访问

**Comment by linlinzzo** [comment]
网站HTTPS不可用

**Comment by Langwenchong** [comment]
您好，站点已经恢复麻烦您重新添加一下，url更换为hhtps://coolchong.cn🥰
