### ISSUE TITLE
泠泫凝的异次元空间

### ISSUE THREAD

**Issue by LxnChan** [travellings-link/travellings#835]
## 网站名称
【泠泫凝的异次元空间】

## 网站网址
【https://lxnchan.cn】

## 徽标位置
【顶栏/导航栏/侧边栏“看这里，不迷路”】
![Pic20220120a](https://flow.lxnchan.cn/files/pic/pic20220120a.png)

## 内容方向
运维技巧和科技内容，记录日常生活中遇到的问题和解决方案。

**Comment by linlinzzo** [comment]
开往的链接呢？

**Comment by LxnChan** [comment]
> 开往的链接呢？

由于之前长时间（超过30天）没有得到您的回复，目前相关代码段已经被注释。

如确认收录，将取消相关注释。

**Comment by linlinzzo** [comment]
> 由于之前长时间（超过30天）没有得到您的回复，目前相关代码段已经被注释。
> 
> 如确认收录，将取消相关注释。

你添加完链接后，我们才能按照流程给你处理。

**Comment by LxnChan** [comment]
> > 由于之前长时间（超过30天）没有得到您的回复，目前相关代码段已经被注释。
> > 如确认收录，将取消相关注释。
> 
> 你添加完链接后，我们才能按照流程给你处理。

![image](https://user-images.githubusercontent.com/46388610/163170675-2f42dbe7-030b-4110-bffe-8b0aaabab148.png)
已更新，如未出现相关更改可`Ctrl+F5`强制刷新，若仍未出现请联系我；具体更改内容请参看本站[更新日志](https://lxnchan.cn/version/)。
