### ISSUE TITLE
zhekunのblog

### ISSUE THREAD

**Issue by zhekunren** [travellings-link/travellings#839]
## 网站名称
zhekunのblog

## 网站网址
https://zhekunren.github.io/

## 徽标位置
顶栏

## 内容方向
编程、随笔、嵌入式开发

**Comment by gxres042** [comment]
站长您好，您的站点 zhekunren.github.io 站点已失效。

请问您是否需要更新您的站点信息？

* 由于您的站点已失效，15 天内未应答将会把您的站点从开往成员列表中移除。感谢您的理解~

**Comment by gxres042** [comment]
因您 15 天内未回复，您的站点已从数据库中删除。若您重新建站，可再次提起一个 Issue 重新申请。感谢您对我们的支持。
