### ISSUE TITLE
蓝奇导航

### ISSUE THREAD

**Issue by Lanky6** [travellings-link/travellings#843]
## 网站名称
> 蓝奇导航

## 网站网址
> https://lanky.cn/

## 徽标位置
> 顶部菜单栏

## 内容方向
> 网址导航 | 收录国内外热冷门网站，无广告无病毒。从心出发，用爱发电！

**Comment by Lanky6** [comment]
开往项目长时间没有维护，再加上我所在地区打开开往连接超时，故已经将链接下架。

**Comment by Lanky6** [comment]
> 我没能看到“开往”链接。


开往项目长时间没有维护，再加上我所在地区打开开往连接超时，故此前已经将链接从网页下架。
我会在明天晚上前再次上架。但网站打不开也应该解决一下，现在vercel很好用

**Comment by linlinzzo** [comment]
> > 我没能看到“开往”链接。
> 
> 开往项目长时间没有维护，再加上我所在地区打开开往连接超时，故此前已经将链接从网页下架。 我会在明天晚上前再次上架。但网站打不开也应该解决一下。

明天上架的时候提醒我们一下。另外，开往目前使用了组织，而vercel托管组织仓库是要付费的（而这笔钱并不必要）。你那边的 jsdelivr 可以使用吗？不然可以考虑使用无缝接力。

**Comment by Lanky6** [comment]
我这边测试是中国联通（广电网络）无法正常访问

**Comment by Lanky6** [comment]
> > > 我没能看到“开往”链接。
> > 
> > 
> > 开往项目长时间没有维护，再加上我所在地区打开开往连接超时，故此前已经将链接从网页下架。 我会在明天晚上前再次上架。但网站打不开也应该解决一下。
> 
> 明天上架的时候提醒我们一下。另外，开往目前使用了组织，而vercel托管组织仓库是要付费的（而这笔钱并不必要）。你那边的 jsdelivr 可以使用吗？不然可以考虑使用无缝接力。


我这边测试是中国联通（广电网络）无法正常访问

**Comment by linlinzzo** [comment]
那 github.io 呢？尝试一下 https://travellings-link.github.io/travellings/ 。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 蓝奇导航 (Issue #843)





    
我没能看到“开往”链接。
  
开往项目长时间没有维护，再加上我所在地区打开开往连接超时，故此前已经将链接从网页下架。 我会在明天晚上前再次上架。但网站打不开也应该解决一下。
  
明天上架的时候提醒我们一下。另外，开往目前使用了组织，而vercel托管组织仓库是要付费的（而这笔钱并不必要）。你那边的 jsdelivr 可以使用吗？不然可以考虑使用无缝接力。
  
我这边测试是中国联通（广电网络）无法正常访问

**Comment by Lanky6** [comment]
github.io可以正常访问

**Comment by linlinzzo** [comment]
那可以将链接换为github.io




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 蓝奇导航 (Issue #843)





 
github.io可以正常访问

**Comment by Lanky6** [comment]
现已上架
