### ISSUE TITLE
请在标题这写“网站名称”

### ISSUE THREAD

**Issue by cwwwxx** [travellings-link/travellings#858]
## 网站名称
> - 💡 XX Blog；

## 网站网址
> - 💡 (https://xxb-dev.cn/)；
> - 会坚持这个域名~

## 徽标位置
> -  只放在“网页底部”，或只放在“默认收起的菜单里”，审核通过率较低。请放在打开网页后能**直接看到的地方**（顶栏或固定的侧栏是不错的选择，可参见 Readme 或已收录的网站）；

## 内容方向
我想在网络世界中分享我的学习经验以及奇遇（我也很乐意用户们来分享~）

**Comment by cwx-dev** [comment]
注：网址大多了，其正确网址为 xxb-dev.cn！

**Comment by cwx-dev** [comment]
注意：访问上网址会出错因为打多了两个字符 其正确网址为xxb-dev.cn

**Comment by linlinzzo** [comment]
你可以直接修改issue的，标题也该改一下。

**Comment by HAHH9527** [comment]
请强制启用https并添加证书，还有目前你的站点貌似还是空置的没有任何实质性的内容
