### ISSUE TITLE
Ojhdt's Blog 申请收录

### ISSUE THREAD

**Issue by ojhdt** [travellings-link/travellings#86]
## 网站名称
Ojhdt's Blog
## 网站链接
https://blog.ojhdt.com/
## 徽标位置
侧栏
## 推荐理由
一个记录所见所想,分享认知的博客。游戏推荐,软件教程,资源共享,日常随笔交友的集合地。
~~大佬都加入了，鄙站岂能缺席~~

**Comment by volfclub** [comment]
建议在打开网页后能直接看到的地方放一个外链，如顶部导航

**Comment by ojhdt** [comment]
> 建议在打开网页后能直接看到的地方放一个外链，如顶部导航

@volfclub 
因顶栏大小限制，为兼顾移动设备的浏览体验，仅加入一个icon。见谅。
若不符合规范请再次提出修改

**Comment by volfclub** [comment]
已收录

**Comment by rabbitxuanxuan** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by gxres042** [comment]
站长您好，您的站点出现了无法访问的情况：

![图片](https://github.com/travellings-link/travellings/assets/53113178/8a12c667-cac8-4460-b050-06a2cd0202fd)

烦请您检查网站的运行状态。

**Comment by Big-Cake-jpg** [comment]
超时关闭。如有需要可重新提交 Issue 申请。
