### ISSUE TITLE
Byzliu's Blog

### ISSUE THREAD

**Issue by Byz-liu** [travellings-link/travellings#863]
## 网站名称
[**Byzliu's Blog**](https://byzliublog.xyz/)

## 网站网址
https://byzliublog.xyz/

## 徽标位置
侧边导航栏；底部。

## 内容方向

- 分想一些简单的教程。
- 杂谈。
- 记录自己喜欢的一些事情。

**Comment by linlinzzo** [comment]
贵站因为无法访问于 #1185 撤下。
