### ISSUE TITLE
🧰 好工具周刊 - 发现并分享有趣，有创意，免费、好用的工具，每周四发布

### ISSUE THREAD

**Issue by PipecraftNet** [travellings-link/travellings#870]
## 网站名称
好工具周刊

## 网站网址
https://discuss-cn.bestxtools.com/

## 徽标位置
顶栏

## 内容方向
发现并分享有趣，有创意，免费、好用的工具，每周四发布。

**Comment by PipecraftNet** [comment]
@linlinzzo 已恢复正常，请确认，谢谢。

**Comment by linlinzzo** [comment]
> @linlinzzo 已恢复正常，请确认，谢谢。

网站还在排队处理。重置是我的问题，不代表网站访问出现问题。

**Comment by PipecraftNet** [comment]
> > @linlinzzo 已恢复正常，请确认，谢谢。
> 
> 网站还在排队处理。重置是我的问题，不代表网站访问出现问题。

好的 👌

**Comment by PipecraftNet** [comment]
开往地址已修改为 https://www.travellings.cn/go.html

**Comment by PipecraftNet** [comment]
请删除此站点的开往成员信息，此站点已停用。

**Comment by HowieHz** [comment]
> 请删除此站点的开往成员信息，此站点已停用。

感谢您的回复。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。祝您生活愉快！
