### ISSUE TITLE
Redish101博客

### ISSUE THREAD

**Issue by Redish101** [travellings-link/travellings#872]
## 网站名称
Redish101博客

## 网站网址

https://blog.redish101.tk
## 徽标位置
左侧固定侧边栏，在主页和非报错页面的所有页面显示

## 内容方向
我的个人博客，专注于分享Python与一些应用软件的介绍

**Comment by Redish101** [comment]
网站框架更新了，把开往图标放到了上端导航栏
![Redish101.github.io](https://cdn.jsdelivr.net/gh/Redish101/redish101.github.io@gh-pages/img/20220302195350.png)

**Comment by Redish101** [comment]
又更新了，迁移到可redish101.tk

**Comment by Redish101** [comment]
@volfclub 狼导，能不能审核快点？我想加入维护

**Comment by linlinzzo** [comment]
就两篇文章？多发一点再来吧。

**Comment by Redish101** [comment]
？
不是有23篇？

**Comment by Redish101** [comment]
我处理一下

**Comment by linlinzzo** [comment]
![捕获](https://user-images.githubusercontent.com/79007796/161719160-945b9f41-e619-4703-91f3-388af0f60a13.PNG)

**Comment by qystudio0** [comment]
就4篇
