### ISSUE TITLE
Bi_Gu's Blog

### ISSUE THREAD

**Issue by DaBiGu** [travellings-link/travellings#874]
## 网站名称
> Bi_Gu's Blog

## 网站网址
> https://www.dabigu.xyz

## 徽标位置
> 左侧导航栏

## 内容方向
> 课堂笔记，生活日常，技术开发

**Comment by essesoul** [comment]
网站https://www.dabigu.xyz/出现错误
![image](https://user-images.githubusercontent.com/58624474/180633655-4f5523bf-cca5-4514-908c-1e004e434be3.png)

**Comment by DaBiGu** [comment]
修改链接为https://dabigu.xyz

**Comment by linlinzzo** [comment]
能提供一下网站序号吗？

**Comment by essesoul** [comment]
<html>
<body>


459 | 侧栏
-- | --



</body>
</html>

**Comment by linlinzzo** [comment]
修改完毕，等待合并。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/4059708d-0c2a-409f-91a6-6745a4900a19)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
