### ISSUE TITLE
Oasis's Blog

### ISSUE THREAD

**Issue by imoasislee** [travellings-link/travellings#879]
## 网站名称
Oasis's Blog

## 网站网址
https://blog.imoasislee.com

## 徽标位置
侧栏和底部

## 内容方向
C语言与算法的学习历程

**Comment by yzqzss** [comment]
补充：此为更换 id:21 的域名。

21 | QUIT | Oasis's Blog | https://blog.imoasis.cn

**Comment by linlinzzo** [comment]
域名解析出现问题。
