### ISSUE TITLE
gao_cai_shengの小小博客

### ISSUE THREAD

**Issue by qwq233** [travellings-link/travellings#880]
## 网站名称
> - gao_cai_shengの小小博客

## 网站网址
> - [https://qwq2333.top/](https://qwq2333.top/)

## 徽标位置
> 顶部
## 内容方向
> 技术向+生活向分享
> 杂七杂八评论

**Comment by HAHH9527** [comment]
目前内容有些少，请再努力多更新一些吧

**Comment by qwq233** [comment]
> 目前内容有些少，请再努力多更新一些吧

有没有一个大概的标准什么的

**Comment by HAHH9527** [comment]
>1. 您的网页应满足：
>- 愿为开放的网络做出贡献（如乐于分享知识经验等）；
>- 禁止采集站内容农场（对多站点聚合，源站不提供的数据进行统计不在此列）；
>- 没有违法以及影响体验的内容（如侵入式广告等）；
>- 正常更新维护中（国内无法正常访问会被移除）；
>- 网页已有较多内容（建议20篇以上，已持续更新一段时间）；
>- 强制启用 https 。

20篇左右，请加油
