### ISSUE TITLE
懵懂の初一少年的博客

### ISSUE THREAD

**Issue by Fgaoxing** [travellings-link/travellings#883]
## 网站名称
懵懂の初一少年的博客
## 网站网址
https://www.yt-blog.top/
## 徽标位置
底部和更多菜单
## 内容方向
编程

**Comment by linlinzzo** [comment]
打开时提示“友链获取失败”

**Comment by Fgaoxing** [comment]
那是Qexo的问题刷新即可！

**Comment by linlinzzo** [comment]
文章有点少，再更新一点吧。

**Comment by Fgaoxing** [comment]
多少张？

**Comment by linlinzzo** [comment]
> 多少张？

20篇。

**Comment by Fgaoxing** [comment]
20篇，妈呀太难了，我努努力吧

**Comment by linlinzzo** [comment]
> 20篇，妈呀太难了，我努努力吧

不急，慢慢更。

**Comment by MBRjun** [comment]
> 20篇，妈呀太难了，我努努力吧

慢慢水（x
我两年120篇

**Comment by MBRjun** [comment]
建议别**太**花哨，我电脑打开掉帧厉害（

**Comment by linlinzzo** [comment]
自动播放音乐？？？

**Comment by MBRjun** [comment]
> 自动播放音乐？？？

现在大多数的现代浏览器会默认阻止音乐自动播放

**Comment by linlinzzo** [comment]
> > 自动播放音乐？？？
> 
> 现在大多数的现代浏览器会默认阻止音乐自动播放

chrome 没有。。。

**Comment by Fgaoxing** [comment]
额

**Comment by MBRjun** [comment]
> > > 自动播放音乐？？？
> > 
> > 
> > 现在大多数的现代浏览器会默认阻止音乐自动播放
> 
> chrome 没有。。。

楼主网站看起来并不会自动播放（
主要问题是卡（

**Comment by Fgaoxing** [comment]
我给禁用了，我不喜欢实际上，但是为了满足别人

**Comment by Fgaoxing** [comment]
不是卡，是cloudflare太慢了

**Comment by Fgaoxing** [comment]
多访问几次就好了

**Comment by MBRjun** [comment]
> 不是卡，是cloudflare太慢了

我扔到 Google Pagespeed Insight 去看一眼
// 怎么别人的 CF 就没问题呢

**Comment by MBRjun** [comment]
> 不是卡，是cloudflare太慢了

![Snipaste_2022-04-08_14-54-30](https://user-images.githubusercontent.com/55020690/162380964-72687416-add9-470e-85ba-c7f8c9127a4d.png)

**Comment by Fgaoxing** [comment]
额

**Comment by MBRjun** [comment]
> 不是卡，是cloudflare太慢了

![Snipaste_2022-04-08_14-56-04](https://user-images.githubusercontent.com/55020690/162381121-e186e8c0-9177-4685-9fe2-52ee0b346833.png)
不要推锅给 CF（
![Snipaste_2022-04-08_14-57-37](https://user-images.githubusercontent.com/55020690/162381329-08c64169-11dc-4177-99c7-03344e06c2c6.png)
![Snipaste_2022-04-08_14-57-29](https://user-images.githubusercontent.com/55020690/162381338-786f42f2-a5c5-4c3f-99ec-aabb3c59eed4.png)
按照上面的建议优化下吧

**Comment by Fgaoxing** [comment]
我说的就是

**Comment by MBRjun** [comment]
> 我说的就是

你网站打开就要消耗 10MB 网络流量（建议控制在 <3MB）
我的建议是：
- 先给你网站的图片进行 Web 压缩（这不难，只需要前往 https://squoosh.app ）
- 然后给静态内容开 Brotli（CloudFlare 我记得支持）
- 然后删点 JS

![Snipaste_2022-04-08_15-05-41](https://user-images.githubusercontent.com/55020690/162382784-37004a29-7d05-4957-b989-eccae6e1c6a0.png)

**Comment by Fgaoxing** [comment]
我一部分都是用的7bu

**Comment by MBRjun** [comment]
> 我一部分都是用的7bu

但是你网站的性能真的很低，找个垃圾点的设备打开下你就知道有多卡了（[可以顺便拿我的来对比](https://blog.mbrjun.cn/)）
我的性能低并不是指加载慢，是你网站 JS 占用实在离谱

**Comment by Fgaoxing** [comment]
有几个是我自己写的，可能有一点慢

**Comment by MBRjun** [comment]
> 有几个是我自己写的，可能有一点慢

先去压缩你的图片...

**Comment by Fgaoxing** [comment]
算了

**Comment by Fgaoxing** [comment]
我把travellings全撤了

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by Fgaoxing** [comment]
https://www.yt-blog.top/，现在速度可以了，和国内有的一拼，当时我不想加了
