### ISSUE TITLE
朝露碎梦 申请收录

### ISSUE THREAD

**Issue by MaiSuiMiao** [travellings-link/travellings#884]
## 网站名称
> - 朝露碎梦

## 网站网址
> - https://aibofan.com

## 徽标位置
> - 侧栏

## 内容方向
> - 个人分享

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by linlinzzo** [comment]
没有发现开往链接。

**Comment by MaiSuiMiao** [comment]
![image](https://user-images.githubusercontent.com/10583191/210854110-aa36e443-ca42-4047-b0c3-f0941f93b054.png)
开往连接一直位于侧边栏内
