### ISSUE TITLE
吹雪·Sakaino 

### ISSUE THREAD

**Issue by Cy-Sakaino** [travellings-link/travellings#888]
## 网站名称
吹雪·Sakaino

## 网站网址
https://isaka.qmqaq.top

## 徽标位置
网页顶栏，网页页脚

## 内容方向
一只鸽子的贵阳日常
写写谱子，写写教程，分享学习心得（

**Comment by Cy-Sakaino** [comment]
我自己访问时没有出现任何问题
由于性能限制有时会504，但是刷新之后 就好了
响应速度测试也正常，在250ms（香港）到<1ms（美国）

**Comment by HAHH9527** [comment]
建站时间较短，且文章不多，再更新一点吧

**Comment by Cy-Sakaino** [comment]
ok
