### ISSUE TITLE
肉松的站

### ISSUE THREAD

**Issue by rousongs** [travellings-link/travellings#893]
## 网站名称
>肉松的站

## 网站网址
> https://rousongs.com

## 徽标位置
> 右侧栏

## 内容方向
>生活日记、技术教程、办公软件技巧分享。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
