### ISSUE TITLE
FUNS

### ISSUE THREAD

**Issue by zfuns** [travellings-link/travellings#894]
## 网站名称
> FUNS

## 网站网址
> [https://xda.plus](https://xda.plus)

## 徽标位置
> 顶栏

## 内容方向
> 个人博客

**Comment by HAHH9527** [comment]
开往标志不符合规范，不易被人认出。
以及你的开往链接是自行定义的，无法访问到其他开往页面。

**Comment by xyzbz** [comment]
兄弟，你打的ddos吗












宋
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Apr 7, 2022 20:59 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [travellings-link/travellings] FUNS (Issue #894)




 
Closed #894.

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
