### ISSUE TITLE
梦墨's Blog

### ISSUE THREAD

**Issue by Dreamink0** [travellings-link/travellings#895]
## 网站名称
梦墨's Blog
## 网站网址
https://dreamo.ink

## 徽标位置
顶栏右侧
## 内容方向
生活、评测、笔记

**Comment by HAHH9527** [comment]
此链接不可见开往 blog 子页面可见开往，是否考虑将主页面也加入开往按钮。
另外内容比较少，建议已更新半年以上，20篇左右文章。

**Comment by Dreamink0** [comment]
收到，會往首頁添加開往按鈕
內容的話正在補充，博客其實已經開了一年多，前段時間丟了數據之後重新搭建
正在復原

**Comment by HAHH9527** [comment]
好的 文章恢复后再次回复此issue即可
