### ISSUE TITLE
Weclont Blog

### ISSUE THREAD

**Issue by weclont** [travellings-link/travellings#904]
已经更新域名。
## 网站名称
Weclont Blog

## 网站网址
https://blog.fwder.cn/

## 徽标位置
左侧栏

## 内容方向
技术开发内容以及各种原创教程

**Comment by HAHH9527** [comment]
侧栏默认收起，开往链接不太显眼，可否进行调整

**Comment by weclont** [comment]
> 侧栏默认收起，开往链接不太显眼，可否进行调整

感觉调到底栏更不显眼。。还是就让它在侧栏吧ww

**Comment by weclont** [comment]
> 捉大佬(

wwwww
