### ISSUE TITLE
放养平凡

### ISSUE THREAD

**Issue by ba2in9a** [travellings-link/travellings#905]
## 网站名称
> - 放养平凡；

## 网站网址
> - https://ba2in9a.top；

## 徽标位置
> - 网页顶部，网页底部；

## 内容方向
> - 我仍相信人间滚烫

**Comment by linlinzzo** [comment]
等会处理。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
