### ISSUE TITLE
举报 有网站为博彩内容

### ISSUE THREAD

**Issue by qystudio0** [travellings-link/travellings#910]
https://www.mmcee.cn/无意间打开travelings的跳转到此

**Comment by qystudio0** [comment]
@volfclub

**Comment by volfclub** [comment]
估计域名失效了，被他人买了，我稍后处理下

**Comment by qystudio0** [comment]
有计划招收更多维护者吗

**Comment by volfclub** [comment]
> 有计划为项目招收更多维护者吗

可以问下 @linlinzzo ，目前是由他主要维护的。
个人认为项目的维护者多一些好，因为现在网站越来越多，一个人维护太吃力了。

**Comment by qystudio0** [comment]
是的，可以为项目邀请一些维护者，而不是以pr的方式，这生效慢，且不方便

**Comment by linlinzzo** [comment]
> 是的，可以为项目邀请一些维护者，而不是以pr的方式，这生效慢，且不方便，希望我也可以参与进来

https://github.com/volfclub/travellings/issues/912

**Comment by qystudio0** [comment]
处理完成
