### ISSUE TITLE
鼎天网络社区

### ISSUE THREAD

**Issue by essesoul** [travellings-link/travellings#911]
## 侧栏，如下图
![image](https://user-images.githubusercontent.com/58624474/161677487-a1036db3-17db-49e1-ab31-fb6a37f74a44.png)

## 内容方向
互联网资源分享，技术教程，网友聊天讨论

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
