### ISSUE TITLE
阿巴

### ISSUE THREAD

**Issue by aba3812** [travellings-link/travellings#913]
## 网站名称
阿巴
## 网站网址
https://www.aba.pet/%e9%bb%84%e7%bd%91/
## 徽标位置
顶部导航 底部
## 内容方向
个人博客

**Comment by linlinzzo** [comment]
就2篇？文章数量有点少，再发点吧。

**Comment by aba3812** [comment]
老网站奔了啥都没了才弄的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [travellings-link/travellings] 阿巴 (Issue #913)





 
就2篇？文章数量有点少，再发点吧。

**Comment by linlinzzo** [comment]
你内容补充好再叫我们吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 阿巴 (Issue #913)





 老网站奔了啥都没了才弄的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年4月6日(星期三) 下午5:17 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [travellings-link/travellings] 阿巴 (Issue #913) 
 
 
 
 
 
   
 就2篇？文章数量有点少，再发点吧。

**Comment by aba3812** [comment]
再次盛情 文章数量即将突破两位数

**Comment by aba3812** [comment]
> 再次申请 文章数量即将突破到两位数

**Comment by linlinzzo** [comment]
> > 再次申请 文章数量即将突破到两位数

20篇再提醒我们。
