### ISSUE TITLE
卫可冬的个人网站

### ISSUE THREAD

**Issue by weekdawn** [travellings-link/travellings#914]
## 卫可冬的个人网站
> - 卫可冬的个人网站

## 网站网址
> - https://weekdawn.github.io/

## 徽标位置
> - 顶栏

## 内容方向
> - 资源 共享 生活 学习

**Comment by weekdawn** [comment]
您发的信件我已收到！                                 周黎明（weekdawn）This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
