### ISSUE TITLE
失效网页提交

### ISSUE THREAD

**Issue by qystudio0** [travellings-link/travellings#915]
各位如果在使用开往发现，异常网站可以在这里添加不要再重开issue了，谢谢
已经处理的会删除

**Comment by qystudio0** [comment]
> https://pzwd.net 无法打开 回报500
> https://www.mrgod.cn 已无开往链接

谢谢你的回复

**Comment by PipecraftNet** [comment]
@HAHH9527 @qystudio0 
> > https://pzwd.net 无法打开 回报500
> > https://www.mrgod.cn 已无开往链接
> 
> 谢谢你的回复

抛砖问答 https://pzwd.net 已恢复正常，请确认，谢谢。(https://github.com/travellings-link/travellings/commit/68ecfa542e35e8ee727e890fdb10e7a8237e9b1c)

**Comment by qystudio0** [comment]
> @HAHH9527 @qystudio0 
> > > https://pzwd.net 无法打开 回报500
> > > https://www.mrgod.cn 已无开往链接
> > 
> > 谢谢你的回复
> 
> 抛砖问答 https://pzwd.net 已恢复正常，请确认，谢谢。(https://github.com/travellings-link/travellings/commit/68ecfa542e35e8ee727e890fdb10e7a8237e9b1c)

请等待回复

**Comment by MBRjun** [comment]
### [137] 简兮小站 
https://www.zk1220.com
80、443端口拒绝连接
```
root@MBR-Server:~$ curl -I www.zk1220.com
curl: (7) Failed to connect to www.zk1220.com port 80: Connection refused
root@MBR-Server:~$ curl -I https://www.zk1220.com
curl: (7) Failed to connect to www.zk1220.com port 443: Connection refused
```

**Comment by MBRjun** [comment]
### [166] SSL | Lime Network Blog
https://blog.limecho.net/
TLS 证书已过期一个月，http 出现 403，忽略证书错误出现 403，主站无法回源(Cloudflare 526)
```
NET::ERR_CERT_DATE_INVALID
-------- EXTEND INFORMATION --------
root@MBR-Server:~$ curl -I http://blog.limecho.net/
HTTP/1.1 403 Forbidden
Content-Length: 0
X-NWS-LOG-UUID: 9006352362291617501
Connection: keep-alive
Server: SLT
Date: Fri, 08 Apr 2022 03:46:21 GMT
X-Cache-Lookup: Return Directly

root@MBR-Server:~$ curl -I https://blog.limecho.net/
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@MBR-Server:~$ curl -I -k https://blog.limecho.net/
HTTP/2 403
content-length: 0
x-nws-log-uuid: 10079188012060660085
server: SLT
date: Fri, 08 Apr 2022 03:46:45 GMT
x-cache-lookup: Return Directly
```

**Comment by MBRjun** [comment]
### [180] ERROR | 神州部落格
https://www.szfc13.cn/
Timeout + TCP RST
```
-------- EXTEND INFORMATION --------
root@MBR-Server:~$ curl -I http://www.szfc13.cn/
curl: (7) Failed to connect to www.szfc13.cn port 80: Connection timed out
root@MBR-Server:~$ curl -I https://www.szfc13.cn/
curl: (7) Failed to connect to www.szfc13.cn port 443: Connection timed out
```

**Comment by HAHH9527** [comment]
https://www.mmcee.cn/ 菠菜

**Comment by qystudio0** [comment]
> https://www.mmcee.cn/ 菠菜

这个在js中已经被我移除了且确认了

**Comment by qystudio0** [comment]
wulinzeng.vip

**Comment by qystudio0** [comment]
https://[heshun.run](https://heshun.run/)/

**Comment by PipecraftNet** [comment]
https://blog.bugcola.com/note
这个网站因为验证 referer, 通过【开往】访问无法正常显示。如下面截图所示。

<img width="875" alt="2022-04-12-17-36-31" src="https://user-images.githubusercontent.com/88728670/162930208-1c6fa05a-7c0c-4d76-8d06-c8ad5fcf90b9.png">

**Comment by ZanyXD** [comment]
> https://blog.bugcola.com/note 这个网站因为验证 referer, 通过【开往】访问无法正常显示。如下面截图所示。
> 
> <img alt="2022-04-12-17-36-31" width="875" src="https://user-images.githubusercontent.com/88728670/162930208-1c6fa05a-7c0c-4d76-8d06-c8ad5fcf90b9.png">
> 
> @ZanyXD #495

没有注意到开往更换域名了>_<
已经把travellings.link加入referer白名单

**Comment by PipecraftNet** [comment]
https://www.flagg.cn/ 无法访问



280 | 顶栏 | Caveolae - 乔治 | https://www.flagg.cn
-- | -- | -- | --

**Comment by hyb-oyqq** [comment]
https://here.sy/
介个网站好像已经没有开往的链接了，算失效不qwq

**Comment by qystudio0** [comment]
https://ddg.ink/

**Comment by zhx6** [comment]
71 | 顶栏 | iSwl's Blog | https://blog.iswl.vip
麻烦名称修改成DoveのBlog，域名替换成https://blog.sdgou.cc/

**Comment by bilibili-ZYGLQexplorer** [comment]
![图片](https://user-images.githubusercontent.com/66054495/165024683-deeb1603-3339-4d7a-a5a3-94ac0779766e.png)

https://www.mmcee.cn/ 菠菜

**Comment by HAHH9527** [comment]
[imfurry.com](https://imfurry.com/) 无法访问

**Comment by qystudio0** [comment]
> ![图片](https://user-images.githubusercontent.com/66054495/165024683-deeb1603-3339-4d7a-a5a3-94ac0779766e.png)
> 
> https://www.mmcee.cn/ 菠菜

已修复

**Comment by p0josec** [comment]
https://www.moeor.com/ 无法访问了。
<img width="774" alt="image" src="https://user-images.githubusercontent.com/102736032/168402225-e57cd0fd-7072-4e41-bad9-ac604eff5c18.png">

**Comment by p0josec** [comment]
https://yiqiangshiyia.cn/ 访问不到

**Comment by Bestynily** [comment]
https://www.mrgod.cn  已经恢复访问   开往链接在右侧栏位置展示

**Comment by yzqzss** [comment]
277 | Caviar-X的博客 | https://caviar-x.top
-- | -- | --

原域名已过期释放，新域名为 https://pigeons.icu/ ，但新博客没有加开往的链接。

---
@yuzijiangorz @Caviar-X #472

**Comment by HAHH9527** [comment]
https://blog.jerryiweb.com/
无法访问

**Comment by MoeCinnamo** [comment]
> ### [137] ERROR | 简兮小站
> https://www.zk1220.com 80、443端口拒绝连接
> 
> ```
> -------- EXTEND INFORMATION --------
> root@MBR-Server:~$ curl -I www.zk1220.com
> curl: (7) Failed to connect to www.zk1220.com port 80: Connection refused
> root@MBR-Server:~$ curl -I https://www.zk1220.com
> curl: (7) Failed to connect to www.zk1220.com port 443: Connection refused
> ```

https://www.zk1220.com/

已恢复

**Comment by qystudio0** [comment]
> > ### [137] ERROR | 简兮小站 
> > [https://www.zk1220.com ](https://www.zk1220.com) 80、443端口拒绝连接 
> > ```
> > -------- EXTEND INFORMATION --------
> > root@MBR-Server:~$ curl -I www.zk1220.com
> > curl: (7) Failed to connect to www.zk1220.com port 80: Connection refused
> > root@MBR-Server:~$ curl -I https://www.zk1220.com
> > curl: (7) Failed to connect to www.zk1220.com port 443: Connection refused
> > ```
> 
> [https://www.zk1220.com/ ](https://www.zk1220.com/)
> 
> 已恢复

![图片](https://user-images.githubusercontent.com/78479629/173216968-d200842d-4bae-41ca-b0b9-0ef85dfc7b08.png)

**Comment by MoeCinnamo** [comment]
> > > ### [137] ERROR | 简兮小站
> > > [https://www.zk1220.com ](https://www.zk1220.com) 80、443端口拒绝连接
> > > ```
> > > -------- EXTEND INFORMATION --------
> > > root@MBR-Server:~$ curl -I www.zk1220.com
> > > curl: (7) Failed to connect to www.zk1220.com port 80: Connection refused
> > > root@MBR-Server:~$ curl -I https://www.zk1220.com
> > > curl: (7) Failed to connect to www.zk1220.com port 443: Connection refused
> > > ```
> > 
> > 
> > [https://www.zk1220.com/ ](https://www.zk1220.com/)
> > 已恢复
> 
> ![图片](https://user-images.githubusercontent.com/78479629/173216968-d200842d-4bae-41ca-b0b9-0ef85dfc7b08.png)

我有时可以访问，有时无法访问。目前它并不稳定，应该恢复的并不好。

**Comment by BowenYoung** [comment]
https://imcys.com/
该站点cdn使用jsd，因此目前css和js都无法加载，只剩首页错乱样式了

**Comment by MBRjun** [comment]
> https://imcys.com/ 该站点cdn使用jsd，因此目前css和js都无法加载，只剩首页错乱样式了

CSS JS都403了😂

**Comment by MBRjun** [comment]
emc2.tk 域名虚无了  
解析 ``NXDOMAIN``
WHOIS ``FAILED``

**Comment by HAHH9527** [comment]
[notes.zhangxiaocai.cn](https://notes.zhangxiaocai.cn/)
无法访问

**Comment by HAHH9527** [comment]
[vpsur.com](https://vpsur.com/)
无开往徽标

**Comment by qystudio0** [comment]
> > > > ### [137] ERROR | 简兮小站
> > > > [https://www.zk1220.com ](https://www.zk1220.com) 80、443端口拒绝连接
> > > > ```
> > > > -------- EXTEND INFORMATION --------
> > > > root@MBR-Server:~$ curl -I www.zk1220.com
> > > > curl: (7) Failed to connect to www.zk1220.com port 80: Connection refused
> > > > root@MBR-Server:~$ curl -I https://www.zk1220.com
> > > > curl: (7) Failed to connect to www.zk1220.com port 443: Connection refused
> > > > ```
> > > 
> > > 
> > > [https://www.zk1220.com/ ](https://www.zk1220.com/)
> > > 已恢复
> > 
> > ![图片](https://user-images.githubusercontent.com/78479629/173216968-d200842d-4bae-41ca-b0b9-0ef85dfc7b08.png)
> 
> 我有时可以访问，有时无法访问。目前它并不稳定，应该恢复的并不好。

我们的要求是绝大多数用户正常访问避免浪费流量

**Comment by HAHH9527** [comment]
https://www.ysazw.cn/
无法访问

**Comment by Big-Cake-jpg** [comment]
https://realmicah.xyz
貌似无法访问
![image](https://user-images.githubusercontent.com/76810494/177904457-d4dc2f8d-da9c-4910-ba9f-7262fbde9c4a.jpeg)

**Comment by essesoul** [comment]
https://chuxjian.asia/
目前无法访问
![image](https://user-images.githubusercontent.com/58624474/179328791-943a6d54-d3fa-4e32-ae01-9d2e25cdd450.png)
![image](https://user-images.githubusercontent.com/58624474/179328794-518fe765-ffa4-4fac-9aa1-54bc6d154132.png)

**Comment by essesoul** [comment]
https://zzzing.cn/
访问报错，应该是typecho设置的问题
![image](https://user-images.githubusercontent.com/58624474/179331247-333cbc78-0629-4a0f-b0da-6d2791582a0d.png)

**Comment by linlinzzo** [comment]
失效网站提交请移步至 https://docs.qq.com/form/page/DQ0dkT1NoeUFQa2dF 。
