### ISSUE TITLE
一腔诗意啊

### ISSUE THREAD

**Issue by yiqiangshiyia** [travellings-link/travellings#916]
## 网站名称
一腔诗意啊

## 网站网址
https://yiqiangshiyia.github.io/

## 徽标位置
友情链接

## 内容方向
编程和互联网技术分享

**Comment by linlinzzo** [comment]
没有找到开往链接

**Comment by yiqiangshiyia** [comment]
> 没有找到往链接
![Uploading QQ截图20220407124257.png…]()

**Comment by linlinzzo** [comment]
@yiqiangshiyia  你图片没传完。

**Comment by A7103** [comment]
@yiqiangshiyia  SSL证书失效，请检查

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
站长您好

您的域名根据我们的核查，已大致确定您的域名已到期。

我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
![Image](https://github.com/user-attachments/assets/8741e5cd-24cc-41e0-8543-e99b48712caa)
![Image](https://github.com/user-attachments/assets/29dba684-8ed1-4faa-ac75-177133765113)

**Comment by HowieHz** [comment]
link https://yiqiangshiyia.cn
