### ISSUE TITLE
May be

### ISSUE THREAD

**Issue by vippass4** [travellings-link/travellings#917]

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by vippass4** [comment]
网站名称：是礼物阿
网站网址: https://www.1ninhg.cn/
徽标位置:顶部导航栏
内容方向：记录一下生活轨迹，吐槽一下生活、工作等，平时会更新一些个人感觉不错的文章内容，希望每一位读者静心阅读。

**Comment by linlinzzo** [comment]
麻烦给出成员列表左侧的网站序号，谢谢。

**Comment by vippass4** [comment]
我看了下，序号为484.可能更换域名的原因，状态为QUIT。

**Comment by vippass4** [comment]
> 麻烦给出成员列表左侧的网站序号，谢谢。

我看了下，序号为484.可能更换域名的原因，状态为QUIT。

**Comment by vippass4** [comment]
@linlinzzo 我看了下，序号为484.可能更换域名的原因，状态为QUIT。

**Comment by HowieHz** [comment]
link #585
