### ISSUE TITLE
开往网站故障·无跳转

### ISSUE THREAD

**Issue by Lanky6** [travellings-link/travellings#921]
北京2022年4月7日23:40开往所有网站无法正常跳转，一直显示开往中页面。

**Comment by Jiaocz** [comment]
请问你是通过后退返回的开往网站无法跳转，还是说直接打开的开往不跳转

**Comment by linlinzzo** [comment]
https://github.com/travellings-link/travellings/commit/dcfae9500e84d201330556bcc864cf10f39fe4f2
应该是js的问题，你过后试一下。
