### ISSUE TITLE
Jun 申请收录

### ISSUE THREAD

**Issue by zlemoni** [travellings-link/travellings#925]
### 网站名称

Jun

### 网站网址

https://blog.junrz.cn

### 徽标位置

顶栏

### 内容方向

生活，笔记

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/989db757-1792-4709-95a3-05a27f61b2ff)
站长您好
您的域名根据我们的核查，已大致确定您的域名已到期。
我们将删除您的开往成员信息，欢迎重新提出申请，感谢您对开往的支持。
