### ISSUE TITLE
问泽卌

### ISSUE THREAD

**Issue by wzwzx** [travellings-link/travellings#928]
### 网站名称

问泽卌

### 网站网址

https://wzwzx.cn

### 徽标位置

网页底部及侧栏

### 内容方向

个人生活与技术

**Comment by linlinzzo** [comment]
没有找到开往链接，文章数量有点少。

**Comment by wzwzx** [comment]
现已加入，感谢

**Comment by linlinzzo** [comment]
文章数量过少，请多发一些再申请。
