### ISSUE TITLE
一蓑烟雨的博客

### ISSUE THREAD

**Issue by easyf12** [travellings-link/travellings#932]
### 网站名称

一蓑烟雨的博客

### 网站网址

https://www.easyf12.top/

### 徽标位置

顶栏

### 内容方向

闲适的生活。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by baipin** [comment]
站长您好，经巡查发现阁下网站无法打开，烦请复查，多谢。

**Comment by baipin** [comment]
代号对应错误，其实是另一个与您无关网站发现出错，问题已经被发现，您无需做进一步操作。
