### ISSUE TITLE
Astrophel's Blog

### ISSUE THREAD

**Issue by Astrophel02** [travellings-link/travellings#933]
### 网站名称

Astrophel's Blog

### 网站网址

https://www.astrophel.top

### 徽标位置

顶栏和侧栏

### 内容方向

自己的小窝，分享有趣的内容和学到的知识

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
