### ISSUE TITLE
尖嘴钳子_lyon的记事本

### ISSUE THREAD

**Issue by ming8918** [travellings-link/travellings#936]
### 网站名称

尖嘴钳子_lyon的记事本

### 网站网址

https://lml023.top

### 徽标位置

网页顶部菜单栏
网页底部页脚栏

### 内容方向

一个可访问的记事本，总是关于一些音视频和好玩的！

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
