### ISSUE TITLE
多米诺的blog

### ISSUE THREAD

**Issue by DomeenoH** [travellings-link/travellings#938]
### 网站名称

多米诺的blog

### 网站网址

https://blog.dominoh.com

### 徽标位置

顶部导航栏

### 内容方向

知识分享，生活思考，跑团记录

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
