### ISSUE TITLE
欧阳淇淇の小屋

### ISSUE THREAD

**Issue by hyb-oyqq** [travellings-link/travellings#940]
### 网站名称

欧阳淇淇の小屋

### 网站网址

https://ouyangqiqi.cn

### 徽标位置

网页底部
右侧菜单栏
首页友链置顶首位

### 内容方向

分享一些个人生活&偶尔突发奇想的干活

**Comment by HAHH9527** [comment]
可以的话再多更新几篇文章，目前建议20篇以上
