### ISSUE TITLE
芸熙の小屋

### ISSUE THREAD

**Issue by yunxixiaowu** [travellings-link/travellings#943]
### 网站名称

芸熙の小屋

### 网站网址

https://stvue.com

### 徽标位置

侧栏

### 内容方向

个人生活记录，网络内容学习与分享

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
