### ISSUE TITLE
老邓的博客

### ISSUE THREAD

**Issue by dengqinzhi** [travellings-link/travellings#946]
### 网站名称

老邓的博客

### 网站网址

https://www.qinzhi.cc

### 徽标位置

网页底部

### 内容方向

个人的日常生活旅游随拍分享

**Comment by HAHH9527** [comment]
没有发现开往徽标，请确认是否已添加

**Comment by dengqinzhi** [comment]
网页底部已经添加了啊，请看下图片截图，谢谢










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 老邓的博客 (Issue #946)





 
没有发现开往徽标，请确认是否已添加

**Comment by HAHH9527** [comment]
![image](https://user-images.githubusercontent.com/27153191/163753581-3a062d35-c482-456d-9e0f-c4ae5e7a1b61.png)

**Comment by HAHH9527** [comment]
另外可否在顶栏放置开往徽标 底部的是可选的

**Comment by dengqinzhi** [comment]
&nbsp;稍等半分钟，你再刷新一下，我刷下缓存，谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午12:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 老邓的博客 (Issue #946)

**Comment by dengqinzhi** [comment]
我有空重挑个主题再放上面，暂时先放在底部，你再刷新一下，确认下是否可以看到LOGO&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 老邓的博客 (Issue #946)





 
另外可否在顶栏放置开往徽标 底部的是可选的

**Comment by HAHH9527** [comment]
底部开往徽标已可见

**Comment by linlinzzo** [comment]
网站空白？出问题了？

**Comment by Jiaocz** [comment]
我这里看是可以正常打开的 @linlinzzo

**Comment by HAHH9527** [comment]
我这也显示正常

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by dengqinzhi** [comment]
OK,已收到。


该小站已变更以上信息




24427467
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "travellings-link/travellings"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 下午2:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [travellings-link/travellings] 老邓的博客 (Issue #946)





 
您好，开往的地址已更换为 travellings.cn/go.html ，相关LOGO图片新地址如下：
 
gif动图：travellings.cn/assets/logo.gif
 svg：travellings.cn/assets/logo.svg
 
请您及时更换相关地址，谢谢配合。
