### ISSUE TITLE
百乐的编程学习

### ISSUE THREAD

**Issue by leyouBaloy** [travellings-link/travellings#949]
### 网站名称

百乐的编程学习

### 网站网址

https://www.leyoubaloy.xyz/

### 徽标位置

网页底部

### 内容方向

编程题解，一些编程技能分享（比如博客搭建，使用代理，前端，后端），读书分享，生活趣事的分享。

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/1d9581e6-072e-4898-9927-8356f50006e2)


我一开始以为是站点信息未成功修改

![Image](https://github.com/user-attachments/assets/a8fc0f57-1b54-4d20-ae76-7f22fa055c68)

改了之后发现是站长您申请了两遍。

保留较早的原则下，我们将会移除 id=1264，保留 id=448 的站点，另外根据最新状态，将 id=448 的站点名改为 `Bailey's Blog` 站点链接改为 `https://www.imbailey.cn/`

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/34b9de3b-e27a-4c68-b9b9-eb059b921c71)
这是修改后的状态
