### ISSUE TITLE
单项式的笔记本

### ISSUE THREAD

**Issue by BCMonomial** [travellings-link/travellings#951]
### 网站名称

单项式的笔记本

### 网站网址

https://www.bcmonomial.xyz

### 徽标位置

侧栏

### 内容方向

比较个人化，自己的想法、心得、所见所闻

**Comment by linlinzzo** [comment]
文章有点少，再更新一点吧。

**Comment by BCMonomial** [comment]
明白了，谢谢，日后再看看吧（
