### ISSUE TITLE
MORA博客

### ISSUE THREAD

**Issue by mengmeng33** [travellings-link/travellings#953]
### 网站名称

MORA博客

### 网站网址

https://www.moraex.cn/

### 徽标位置

侧栏

### 内容方向

这里是一个大学生用来在互联网上留下痕迹的网站

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
