### ISSUE TITLE
Gugu's Blog

### ISSUE THREAD

**Issue by imgugu233** [travellings-link/travellings#957]
### 网站名称

Gugu's Blog

### 网站网址

https://blog.imgugu.ink

### 徽标位置

网页底部

### 内容方向

分享一些技术向的东西以及个人的一些小看法

**Comment by HAHH9527** [comment]
请再多更新一些文章吧，要求如下
[https://github.com/travellings-link/travellings#1-您的网页应满足](https://github.com/travellings-link/travellings#1-%E6%82%A8%E7%9A%84%E7%BD%91%E9%A1%B5%E5%BA%94%E6%BB%A1%E8%B6%B3)

**Comment by imgugu233** [comment]
了解

**Comment by linlinzzo** [comment]
建议博客不要这么“水”，国际歌网上随便都找得到。
