### ISSUE TITLE
南星の博客

### ISSUE THREAD

**Issue by fuzhibin** [travellings-link/travellings#958]
### 网站名称

南星の博客

### 网站网址

https://nanxing.ltd

### 徽标位置

顶栏+底部bedge

### 内容方向

技术分享、博客美化，生活记录

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
