### ISSUE TITLE
广然笔记

### ISSUE THREAD

**Issue by rsecc** [travellings-link/travellings#961]
### 网站名称

广然笔记

### 网站网址

https://www.rsecc.cn/

之前提交了一次，回复说收录了，但是没有看到收录

### 徽标位置

导航栏

### 内容方向

用文字记录工作和学习生活

**Comment by HAHH9527** [comment]
#695

**Comment by rsecc** [comment]
成员列表没有看到收录啊

**Comment by HAHH9527** [comment]
还没收录呢。。。要是close了之后你检查了还是没有可以再反馈一下

**Comment by linlinzzo** [comment]
@HAHH9527 现在是要重新添加吗？

**Comment by HAHH9527** [comment]
@linlinzzo 对 要重新添加一下
