### ISSUE TITLE
一刀斩の小窝

### ISSUE THREAD

**Issue by YidaozhanYa** [travellings-link/travellings#965]
### 网站名称

一刀斩の小窝

### 网站网址

https://blog.yidaozhan.ga

### 徽标位置

网页底部

### 内容方向

网络技术、GNU/Linux 及个人杂谈等

**Comment by YidaozhanYa** [comment]
链接更改: blog.yidaozhan.top

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by YidaozhanYa** [comment]
更换完成 （https://github.com/YidaozhanYa/blog/commit/3bbefb302bbc4d08e2493f07f4b10a8058c933e2）

**Comment by YidaozhanYa** [comment]
![图片](https://user-images.githubusercontent.com/73830635/210677994-9b142af4-d14f-44b6-84f7-c8f74f7ccd67.png)
您好，我已经更换完成了
