### ISSUE TITLE
wututuのblog

### ISSUE THREAD

**Issue by wututua** [travellings-link/travellings#967]
### 网站名称

wututuのblog

### 网站网址

https://blog.wututu.cn/

### 徽标位置

顶部导航栏

### 内容方向

分享一些个人的学习与生活，还有一些技术方面的东西

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。
