### ISSUE TITLE
Wonder Space

### ISSUE THREAD

**Issue by LeonWong0609** [travellings-link/travellings#968]
### 网站名称

Wonder Space

### 网站网址

<https://www.l3on.site/>

### 徽标位置

顶栏

### 内容方向

记录学习笔记，写读书、观影、看剧笔记，写写感悟随笔，分享日常生活。一起用写作记录来对抗虚无。
(域名已续费三年，希望能长期坚持写下去）

**Comment by HAHH9527** [comment]
可以再多更新一些文章，目前建议20篇以上

**Comment by LeonWong0609** [comment]
好的，那我晚些时候再来申请。

多谢回复！
