### ISSUE TITLE
公爵书房 | 技术分享

### ISSUE THREAD

**Issue by gongjuecloak** [travellings-link/travellings#972]
### 网站名称

公爵书房 | 技术分享

### 网站网址

https://www.gjcloak.top

### 徽标位置

顶栏

### 内容方向

技术分享、个人的见闻随笔和B站专栏与视频

**Comment by linlinzzo** [comment]
文章有点少，再发一点吧。

**Comment by gongjuecloak** [comment]
好，因为近期做了迁移少了些文章

**Comment by gongjuecloak** [comment]
大概多少文章才行呀

**Comment by linlinzzo** [comment]
> 大概多少文章才行呀

满 20 篇后回复一下 issue。

**Comment by gongjuecloak** [comment]
目前已经够了

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博友。

**Comment by essesoul** [comment]
未找到开往图标或链接
![image](https://user-images.githubusercontent.com/58624474/179334477-4bdbda8b-ca06-406e-baf6-6c62a4cc73b2.png)
![image](https://user-images.githubusercontent.com/58624474/179334497-ad04f783-5644-4cbf-a72c-2148420b6ca7.png)

**Comment by gongjuecloak** [comment]
博客地址更换为 https://blog.gjcloak.top
