### ISSUE TITLE
QAIU's blog

### ISSUE THREAD

**Issue by qaiu** [travellings-link/travellings#977]
### 网站名称

QAIU's blog

### 网站网址

https://blog.qaiu.top

### 徽标位置

顶部

### 内容方向

手机编程, 开发教程分享

**Comment by Cubik65536** [comment]
您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：

gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)

请您及时更换相关地址，谢谢配合。

**Comment by qaiu** [comment]
> 您好，开往的地址已更换为 [travellings.cn/go.html](https://www.travellings.cn/go.html) ，相关LOGO图片新地址如下：
> 
> gif动图：[travellings.cn/assets/logo.gif](https://www.travellings.cn/assets/logo.gif)
> svg：[travellings.cn/assets/logo.svg](https://www.travellings.cn/assets/logo.svg)
> 
> 请您及时更换相关地址，谢谢配合。

已更换
