### ISSUE TITLE
无聊の人博客

### ISSUE THREAD

**Issue by wuliaopeople** [travellings-link/travellings#978]
### 网站名称

无聊の人博客

### 网站网址

https://blog.wlr.lol/

### 徽标位置

侧栏

### 内容方向

极速分享，源码分享，网站分享，以及生活日记~

**Comment by linlinzzo** [comment]
文章有点少，到20篇提醒我们一下。你可以在 https://zhblogs.ohyee.cc/ 发现更多博友。

**Comment by wuliaopeople** [comment]
> 

到20了个辽~

**Comment by linlinzzo** [comment]
刚好20

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博友。
