### ISSUE TITLE
rickblog

### ISSUE THREAD

**Issue by rickhqh** [travellings-link/travellings#983]
### 网站名称

rickのblog

### 网站网址

https://blog.rick.icu

### 徽标位置

网站顶部菜单

### 内容方向

个人随想,技术文章,学习笔记,生活日常

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by HowieHz** [comment]
![Image](https://github.com/user-attachments/assets/66e9972f-cd4f-4fbe-b55e-db93d1fce587)

![Image](https://github.com/user-attachments/assets/0323a395-61e2-43cd-b0d1-7d3ea7a783fb)
站长您好
您的站点根据我们的核查，已大致确定您的域名已出现无法访问的情况。
请您在 15 天内对本Issue进行回复或提交链接更新，否则我们将删除您的开往成员信息
