### ISSUE TITLE
Saiodgm の 博客儿

### ISSUE THREAD

**Issue by cqbzljt** [travellings-link/travellings#984]
### 网站名称

Saiodgm の 博客儿

### 网站网址

https://oi.saiodgm.gq/

### 徽标位置

顶栏

### 内容方向

一个 OIer 关于 OI 的学习笔记

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博友。

**Comment by yzwsl** [comment]
### 网站名称
天之文博客

### 网站网址
https://blog.qqder.com/

### 徽标位置
顶栏

### 内容方向
平行宇宙的一个宁静角落

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
