### ISSUE TITLE
shunhang

### ISSUE THREAD

**Issue by ShimmerLS** [travellings-link/travellings#986]
### 网站名称

shunhang

### 网站网址

https://www.shimmerl.top/

### 徽标位置

顶栏

### 内容方向

生活，日记，网站分享。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博友。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
