### ISSUE TITLE
一个小站

### ISSUE THREAD

**Issue by ding113** [travellings-link/travellings#990]
### 网站名称

一个小站

### 网站网址

https://www.ygxz.in

### 徽标位置

左侧栏下方“links”位置

### 内容方向

我站主要分享泛互联网内容，兼有一点对当下互联网和生活的思考。

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 中发现更多博客网站。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
