### ISSUE TITLE
Seraphineの小窝

### ISSUE THREAD

**Issue by L-Seraphine** [travellings-link/travellings#992]
### 网站名称

Seraphineの小窝

### 网站网址

https://helloseraphine.top/

### 徽标位置

侧栏（公告栏旁）

### 内容方向

C#,R,C,游戏开发,想要开摆的林学人

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 中发现更多博客网站。

**Comment by essesoul** [comment]
网址https://www.helloseraphine.top/ 中未找到开往图标或链接
![image](https://user-images.githubusercontent.com/58624474/179334425-5c1b4868-7abf-496d-ab77-ec23dc2cd4c1.png)
