### ISSUE TITLE
mes ames

### ISSUE THREAD

**Issue by moi-mo** [travellings-link/travellings#994]
### 网站名称

mes ames

### 网站网址

https://moi-mo.github.io/

### 徽标位置

底栏

### 内容方向

文学、随笔、写作

另本站为原MES（已在本项目记录），烦请将MES的信息更换如上
感谢！

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博友。

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
