### ISSUE TITLE
DaPeng's Blog

### ISSUE THREAD

**Issue by li14300** [travellings-link/travellings#996]
### 网站名称

DaPeng's Blog

### 网站网址

https://www.imut.xyz/

### 徽标位置

自适应PC顶栏/移动端侧栏，页脚

### 内容方向

技术分享，德语资料分享

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
https://github.com/travellings-link/travellings/pull/1034

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。
