### ISSUE TITLE
张洪Heo - 产品设计博客

### ISSUE THREAD

**Issue by zhheo** [travellings-link/travellings#998]
### 网站名称

张洪Heo

### 网站网址

https://blog.zhheo.com/

### 徽标位置

导航栏

### 内容方向

日常生活、设计、数码

**Comment by linlinzzo** [comment]
您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：

gif动图：https://www.travellings.cn/assets/logo.gif
svg：https://www.travellings.cn/assets/logo.svg

请您及时更换相关地址，谢谢配合。

**Comment by zhheo** [comment]
> 您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
> 
> gif动图：https://www.travellings.cn/assets/logo.gif svg：https://www.travellings.cn/assets/logo.svg
> 
> 请您及时更换相关地址，谢谢配合。

已更换，受cdn影响，3日内完成更新
