### ISSUE TITLE
摸鱼中...

### ISSUE THREAD

**Issue by kifuan** [travellings-link/travellings#999]
### 网站名称

摸鱼中...

### 网站网址

https://kifuan.top/

### 徽标位置

顶部

### 内容方向

学习/开发前后端过程中遇到的一些bug, 一些坑的记录

**Comment by HAHH9527** [comment]
或许再努力一点更新三四篇文章？
>（建议20篇以上，已持续更新一段时间）

**Comment by kifuan** [comment]
> 或许再努力一点更新三四篇文章？
> 
> > （建议20篇以上，已持续更新一段时间）

已更新到20篇了, 以后会继续写的

**Comment by linlinzzo** [comment]
审核通过，等待添加。你可以在 https://zhblogs.ohyee.cc/ 发现更多博客。

**Comment by linlinzzo** [comment]
https://github.com/travellings-link/travellings/pull/1034

**Comment by kifuan** [comment]
已更改
